---
title: "Emissions trends and drivers"
output: html_document
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(gganimate)
library(xlsx)


######### load basic development and emissions data ######### 

# load('Data/basic.RData')
# 
# ## bring in more regional codes
# codes <- read.xlsx('C:/Users/lamw/Documents/SpiderOak Hive/Work/Code/R/.Place names and codes/output/ISOcodes.xlsx',sheetName = 'ISO_master')
# 
# basic <- left_join(basic,codes %>% select(Code,WB.income),by=c("ISO"="Code")) %>% 
#   select(Country,ISO,Year,UN6,RCP5,IAM10,WB.income,pop_UN,everything())
# 
# basic$WB.income <- factor(basic$WB.income,levels(basic$WB.income)[c(1,4,3,2)])
# 
# # any other adjustments here
# basic$UN6 <- gsub("LATIN AMERICA AND THE CARIBBEAN","LATIN AMERICA",basic$UN6)
# 
# basic <- basic %>% 
#   mutate(gdp_ppp_pc = gdp_ppp_WB/pop_UN)
# 
# basic$income_category  <- cut(basic$gdp_ppp_pc,breaks = c(1700,4300,8600,15000,29000,150000),dig.lab=10,include.lowest=TRUE)


```


### GHG emissions by gas (Figure 1)

```{r Fig1_trend, echo=FALSE,warning=FALSE,fig.width=8,fig.path="Plots/",dev=c('png','pdf')}

######### load Jan data ######### 

data <- read.xlsx('Data/data from Jan.xlsx',sheetIndex = "EDGAR gas - Figure 1",startRow = 10,endRow = 16,check.names=FALSE)

data <- gather(data,Year,value,-source,-gas) %>% 
  mutate(Year=as.numeric(Year)) %>% 
  filter(!is.na(value))

data %>% 
  filter(gas!="Total") %>% 
  ggplot(.,aes(x=Year,y=value,fill=gas)) +
  geom_area() +
  ylab('GHG Emissions (GtCO2eq/yr)') +
  theme_bw() +
  theme(axis.title.x = element_blank(),
          legend.position = c(0.12,0.8),
        legend.title=element_blank(),
        legend.background = element_blank())

```

### Long term CO2 emissions sources and sinks (Figure 2)


```{r Fig2_budget, echo=FALSE,warning=FALSE,fig.width=10,fig.height=6,fig.path="Plots/",dev=c('png','pdf')}

######### load the global carbon budget ######### 

gcb <- read.xlsx('Data/data from Jan.xlsx',sheetIndex = "CDIAC CO2 - Figure 2",startRow = 3,endRow = 270,colIndex=1:9)
names(gcb) <- c("Year","Total","Gas","Oil","Coal","Cement","Flaring","Net land-use","Total CO2")

# fft <- read.xlsx('Data/Global_Carbon_Budget_2018v1.0.xlsx',sheetIndex = 'Fossil Emissions by Fuel Type',startRow = 13,endRow = 2017,colIndex = 1:8)

budget_data <- gather(gcb,key,value,-Year) %>% 
  filter(key!="Total CO2",key!="Total") %>% 
  filter(Year>=1850) 

budget_data$key <- as.factor(budget_data$key)
budget_data$key <- factor(budget_data$key,levels(budget_data$key)[c(1,2,3,4,6,5)])

p1 <- budget_data %>% 
  ggplot(.,aes(x=Year,y=value,fill=key)) + 
  geom_area() +
  ylab("Carbon emissions (GtCO2/yr)") +
  theme_bw() +
  theme(legend.position = c(0.15,0.7),
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        legend.background = element_blank())

##### future budget code

# future_budget <- data.frame(target=c("1.5oC target","2oC target"),budget=c(500,1000)) %>% 
#   mutate(years=ceiling(budget/as.vector(plot_data %>% filter(Year==2017) %>% summarise(total=sum(value)))[[1]]))
# 
# p2 <- future_budget %>% 
#   ggplot(.,aes(x=target,y=budget)) +
#   geom_bar(stat='identity') +
#   geom_text(aes(x=target,y=budget+50,label=paste("Years: ",years))) +
#   theme(axis.title.x = element_blank()) +
#   ylab("Total carbon budget relative to climate targets (GtCO2)")

date_data <- gcb %>% 
  select(Year,value=Total) %>% 
  filter(Year>=1850) %>% 
  mutate(key=ifelse(Year>=1850 & Year < 1890,'1850-1889',NA)) %>% 
  mutate(key=ifelse(Year>=1890 & Year < 1930,'1890-1930',key)) %>% 
  mutate(key=ifelse(Year>=1930 & Year < 1970,'1930-1970',key)) %>% 
  mutate(key=ifelse(Year>=1970 & Year < 2010,'1970-2010',key)) %>% 
  mutate(key=ifelse(Year>=2010,'2010-2017',key)) %>% 
  filter(!is.na(key))

date_data <- date_data %>% 
  mutate(key=as.factor(key)) %>% 
  group_by(key) %>% 
  summarise(value=sum(value)) %>% 
  add_row(key="1.5",value=420) %>% 
  add_row(key="2.0",value=1120)


date_data$key <- factor(date_data$key,levels(date_data$key)[c(7,6,5,4,3,2,1)])

p2 <- date_data %>% 
  ggplot(.,aes(x='x',y=value,fill=key)) +
  geom_bar(stat='identity') +
  ylab('GHG emissions, cumulative (GtCO2eq)') +
  theme_bw() +
  theme(legend.position= c(0.5,0.5),
        legend.background = element_blank(),
        axis.title.x = element_blank())


time_data <- data.frame(target=c("1.5oC target","2oC target"),budget=c(500,1000)) %>% 
  group_by(budget) %>% 
  mutate(current_emissions=budget/as.vector(budget_data %>% filter(Year==2017) %>% summarise(total=sum(value)))[[1]]) %>% 
  mutate(fake_1 = 1.5*(budget/as.vector(budget_data %>% filter(Year==2017) %>% summarise(total=sum(value)))[[1]]))%>% 
  mutate(fake_2 = 2*(budget/as.vector(budget_data %>% filter(Year==2017) %>% summarise(total=sum(value)))[[1]]))

time_data <- gather(time_data,key,value,-budget,-target) %>% 
  mutate(key=as.factor(key))

time_data$key <- factor(time_data$key,levels(time_data$key)[c(3,2,1)])

p3 <- time_data %>% 
  ggplot(.,aes(x=key,y=value,fill=target)) + 
  geom_bar(stat='identity') +
  coord_flip() +
  facet_grid(target~.) +
  theme_bw() +
  theme(legend.position='none',
        axis.title.y=element_blank()) +
  ylab('Years until budget exceeded')

p4<- ggarrange(p2,p3,ncol=2,widths=c(1,2))

p <- ggarrange(p1,p4,nrow=2)
p

```



```{r edgar_prep,include=FALSE}

sector=7
gas="GHG"
time_start=2010
category="IPCC_AR5_chapter"
rate_or_abs="rate"

library(openxlsx)

######### load edgar data ######### 

load('Data/edgar.RData')

codes <- read.xlsx('C:/Users/lamw/Documents/SpiderOak Hive/Work/Code/R/.Place names and codes/output/ISOcodes.xlsx',sheet = 'ISO_master')
edgar_GHG <- left_join(edgar_GHG,codes %>% select(Country,Code,WB.income),by=c("ISO"="Code"))
edgar_GHG$WB.income <- as.factor(edgar_GHG$WB.income)
edgar_GHG$WB.income <- factor(edgar_GHG$WB.income,levels(edgar_GHG$WB.income)[c(1,4,3,2)])
rm(codes)

chapters <- read.xlsx('Data/IPCC_master_categories_JM.xlsx',sheet='code_comparisons',cols = 1:6) %>% 
  select(code,IPCC_AR5_chapter,IPCC_AR5_sector)

edgar_GHG <- left_join(edgar_GHG,chapters,by=c("sector_code"="code"))



edgar_emissions_plot <- function(time_start,category,sector,gas,rate_or_abs) {
  
  ##############  calculate growth rates in given time period ############## 
  
  sector_code <- edgar_GHG %>%
    filter_at(vars(category),all_vars(.==sector))
  sector_code <- substr(sector_code$sector_code[[1]],1,as.numeric(str_sub(category,-1)))
  
  rates <- edgar_GHG %>% 
    filter_at(vars(category),all_vars(.==sector)) %>% 
    filter(!is.na(WB.income)) %>% 
    filter(Year>=time_start & Year<2018) %>% 
    group_by(Country,Year,WB.income) %>% 
    summarise_at(gas,sum,na.rm=TRUE) %>% 
    ungroup() %>% 
    rename_at(gas,funs(sprintf('value')))
  
  ####### CHECK DATA HERE FOR ZEROS AND NANS ####### 
  
  
  # what is 80% of the emissions?
  blarg <- rates %>%
    filter(Year==2017)
  threshold <- sum(blarg$value,na.rm=T)*0.8
  
  ## remove countries below absolute emissions threshold
  
  rates <- rates %>% 
    group_by(Country) %>% 
    mutate(rate=(last(value)/first(value))^(1/(last(Year)-time_start+1))-1) %>% 
    mutate(abs_growth=last(value)-first(value)) %>%
    filter(Year==2017) %>% 
    na.omit() %>% 
    arrange(desc(value))
  
  
  rates$cutoff <- 0
  z <- 0
  for (i in 1:length(rates$Country)){
    z <- z + rates$value[i]
    if (z > threshold) {
      break
    }
    rates$cutoff[i] <- 1
  }
  
  country_list <- rates %>% select(Country,cutoff)
  
  #### calculate growth rates for countries below threshold, grouped by region ####
  
  blarg <- edgar_GHG %>% 
    filter_at(vars(category),all_vars(.==sector)) %>% 
    filter(!is.na(WB.income)) %>% 
    filter(Year>=time_start & Year<2018) %>% 
    group_by(Country,Year,WB.income) %>% 
    summarise_at(gas,sum,na.rm=TRUE) %>% 
    ungroup() %>% 
    rename_at(gas,funs(sprintf('value')))
  
  blarg <- left_join(blarg,country_list,by=c("Country"="Country")) %>% 
    filter(cutoff==0) %>% 
    filter(!is.na(WB.income)) %>% 
    filter(Year>=time_start & Year<2018) %>% 
    group_by(WB.income,Year) %>% 
    summarise_at('value',sum,na.rm=TRUE)
  
  blarg <- blarg %>% 
    group_by(WB.income) %>% 
    mutate(rate=(last(value)/first(value))^(1/(last(Year)-time_start+1))-1) %>% 
    mutate(abs_growth=last(value)-first(value)) %>%
    filter(Year==2017) %>% 
    na.omit() %>% 
    mutate(Country=paste(WB.income,"(rest)"))
  
  
  ### join and plot
  rates <- rbind(rates %>% filter(cutoff==1) %>% select(-cutoff),blarg)
  
    rates <- gather(rates %>% mutate(rate=rate*100),var,value,rate:abs_growth)
  
  p2 <- rates %>% 
    filter(var==rate_or_abs) %>% 
    ggplot(.,aes(x = reorder(Country,value),y = value, fill=WB.income)) +
    geom_bar(stat='identity') + 
    ylab(paste(ifelse(rate_or_abs=="rate","Rate of","Absolute")," change in ",gas," emissions (Sector ",sector,") ",time_start,"-2017\n (Countries responsible for 80% of sector emissions are shown)",sep="")) +
    coord_flip() +
    theme_bw() +
    theme(legend.position="none",
          axis.title.y = element_blank()) 

  regions <- left_join(edgar_GHG,country_list,by=c("Country"="Country")) %>%
    filter_at(vars(category),all_vars(.==sector)) %>% 
    filter(!is.na(WB.income)) %>% 
    filter(Country!="World") %>% 
    filter(Year>1979 & Year<2018) %>% 
    filter(cutoff==0) %>% 
    group_by(WB.income,Year) %>% 
    summarise_at(gas,sum,na.rm=TRUE) %>% 
    mutate(Country=paste(WB.income,"(rest)")) %>% 
    ungroup() %>% 
    rename_at(gas,funs(sprintf('value')))
  
  rect <- data.frame(xmin=time_start, xmax=2017, ymin=-Inf, ymax=Inf)
  
  p1 <-regions %>%
    ggplot(.,aes(x=Year,y=value,fill=WB.income)) +
    geom_area() +
    geom_rect(data=rect, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),
              fill="grey20",
              alpha=0.35,
              inherit.aes = FALSE) +
    theme_bw() +
    theme(legend.position='bottom',
          legend.title=element_blank(),
          axis.title.x = element_blank()) +
    ylab(paste(gas,"Emissions, Gg CO2eq")) +
    ggtitle(paste("IPCC Sector ",sector,", ",gas," Emissions",sep=""))
  
  
  ############## plot absolute values ############## 
  
  countries <- left_join(edgar_GHG,country_list,by=c("Country"="Country")) %>%
    filter_at(vars(category),all_vars(.==sector)) %>% 
    filter(!is.na(WB.income)) %>% 
    filter(Country!="World") %>% 
    filter(Year>1979 & Year<2018) %>% 
    filter(cutoff==1) %>% 
    group_by(Country,Year,WB.income) %>% 
    summarise_at(gas,sum,na.rm=TRUE) %>% 
    ungroup() %>% 
    rename_at(gas,funs(sprintf('value')))
  
  
  p4 <- ggarrange(p1,p2,ncol=1,nrow=2)
  return(list("plot"=p4,"data"=rates))
}


```


### Regional trends & rates of change by IPCC sector


```{r edgar_plots_rates,echo=FALSE,warning=FALSE,fig.width=8,fig.height=10,fig.path="Plots/",dev=c('png','pdf')}


########### rates of change: sectors 7-11
c=1
data = data.frame()
plot_list = list()
time_start = 2010
category = 'IPCC_AR5_chapter'
gas = 'GHG'

for (i in 7:11) {
  
  p <- edgar_emissions_plot(time_start,category,i,gas,'rate')
  
  plot_list[[c]] <- p$plot
  
  if (c==1) {
    data <- p$data %>% 
      mutate(run=paste(category,i,gas,time_start,sep="_"))
  } else {
    data <- rbind(data,p$data %>% mutate(run=paste(category,i,gas,time_start,sep="_")))
  }
  
  c=c+1
  
}
plot_list

write.xlsx(data %>% select(-Year),file="Results/results.xlsx",sheetName=paste(category,gas,time_start,sep="_"),overwrite=T)

```

### Regional trends & absolute change by IPCC sector


```{r edgar_plots_abs,echo=FALSE,warning=FALSE,fig.width=8,fig.height=10,fig.path="Plots/",dev=c('png','pdf')}

########### absolute growth: sectors 7-11
c=1
data = data.frame()
plot_list = list()
time_start = 2010
category = 'IPCC_AR5_chapter'
gas = 'GHG'

for (i in 7:11) {
  
  p <- edgar_emissions_plot(time_start,category,i,gas,'abs_growth')
  
  plot_list[[c]] <- p$plot
  
  if (c==1) {
    data <- p$data %>% 
      mutate(run=paste(category,i,gas,time_start,sep="_"))
  } else {
    data <- rbind(data,p$data %>% mutate(run=paste(category,i,gas,time_start,sep="_")))
  }
  
  c=c+1
  
}
plot_list



```

### Regional per capita trends

```{r percapita_trends, echo=FALSE,warning=FALSE,fig.width=10,fig.height=5}

######
load('Data/edgar.RData')

codes <- openxlsx::read.xlsx('C:/Users/lamw/Documents/SpiderOak Hive/Work/Code/R/.Place names and codes/output/ISOcodes.xlsx',sheet = 'ISO_master')
edgar_GHG <- left_join(edgar_GHG,codes %>% select(Country,Code,WB.income),by=c("ISO"="Code"))
edgar_GHG$WB.income <- as.factor(edgar_GHG$WB.income)
edgar_GHG$WB.income <- factor(edgar_GHG$WB.income,levels(edgar_GHG$WB.income)[c(1,4,3,2)])
rm(codes)

chapters <- openxlsx::read.xlsx('Data/IPCC_master_categories_JM.xlsx',sheet='code_comparisons',cols = 1:6) %>% 
  select(code,IPCC_AR5_chapter,IPCC_AR5_sector)

edgar_GHG <- left_join(edgar_GHG,chapters,by=c("sector_code"="code"))

load('Data/basic.RData')

edgar_GHG <- left_join(edgar_GHG,basic %>% select(ISO,pop_UN,Year,gdp_real_WB),by=c("ISO"="ISO","Year"="Year"))

######
region <- edgar_GHG %>% 
  filter(Year>1969 & Year<2018) %>% 
  #filter(!is.na(WB.income)) %>% 
  group_by(WB.income,Year) %>% 
  summarise(ghg_total = sum(GHG,na.rm=T),pop=sum(pop_UN,na.rm=T),gdp=sum(gdp_real_WB,na.rm=T)) %>% 
  mutate(ghg_pc = ghg_total/pop,ghg_gdp = ghg_total/gdp)

## cumulative emissions total (horizontal bar chart)
p1 <- region %>% 
  group_by(WB.income) %>% 
  summarise(cumulative_ghg = sum(ghg_total)) %>% 
  ggplot(.,aes(y=cumulative_ghg,x=WB.income,fill=WB.income)) +
  geom_bar(stat='identity') +
  coord_flip() +
  theme(legend.title = element_blank(), legend.position = "none") +
  theme(axis.title.y = element_blank()) 

## total ghg emissions (stacked area)
p2 <- region %>% ggplot(.,aes(x=Year,y=ghg_total,fill=WB.income)) +
  geom_area() +
  theme(legend.title = element_blank(),legend.position = "none")

## per capita ghg emissions (line chart)
p3 <- region %>% 
  filter(!is.na(WB.income)) %>% 
  ggplot(.,aes(x=Year,y=ghg_pc,colour=WB.income)) +
  geom_path(size=1) +
  theme(legend.title = element_blank(), legend.position = "none")

## ghg emissions per gdp (line chart)
p4 <- region %>% 
  filter(!is.na(WB.income)) %>% 
  ggplot(.,aes(x=Year,y=ghg_gdp,colour=WB.income)) +
  geom_path(size=1) +
  theme(legend.title = element_blank(), legend.position = "none")


ggarrange(p1, p2, p3, p4, nrow=2,ncol=2)

```