---
title: "build_kaya_data"
output: word_document
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(openxlsx)
library(ggplot2); theme_set(theme_bw())
library(data.table)
library(janitor)

wb <- openxlsx::createWorkbook(title = "sector_kaya_data")

##### data for the ERL version of the sector emissions analysis https://iopscience.iop.org/article/10.1088/1748-9326/abee4e

#load('../../Data/Not public/IPCC data versions/edgar_data_gwp_ar6_late_2020.RData')
#edgar_ghg <- edgar_GHG_ar6_late_2020

#####

load('../../Data/data_edgar_ghg.RData')
load('../../Data/data_land_co2.RData')
load('../../Data/data_WDI_gdp_pop.RData')

land <- land %>%
  filter(year>1969) %>% 
  mutate(sector_title="AFOLU",
         subsector_title="Land-use CO2",
         CO2=mean,
         CH4=NA,N2O=NA,Fgas=NA,GHG=mean) %>% 
  select(-blue,-houghton,-mean)

load('../../Data/basic.RData')
load("../../Data/ipcc_regions.RData")

codes <- openxlsx::read.xlsx('C:/Users/lamw/ownCloud/Projects/Code/R/.Place names and codes/output/ISOcodes.xlsx',sheet = 'alternative_names')

```

```{r load_robbie_data }

# IEA data prepared by Robbie Andrew (CICERO)

kaya_data <- read.csv('../../Data/Not public/kaya_data_flat_210924.csv')
names(kaya_data) <- tolower(names(kaya_data))
kaya_data <- kaya_data %>% select(ISO=iso,everything())

pop_gdp <- kaya_data %>% 
  filter(sector=="---") %>%
  filter(variable=="POP" | variable=="GCP") %>% 
  select(-sector)
pop_gdp <- spread(pop_gdp,variable,value)
pop_gdp <- pop_gdp %>% 
  select(ISO,year,GDP=GCP,POP)

kaya_data <- left_join(kaya_data %>% filter(sector!="---"),
                       pop_gdp,by = c("ISO", "year"))

kaya_data <- kaya_data %>% 
  mutate(sector=ifelse(grepl("EGY",sector),"Energy systems",sector)) %>% 
  mutate(sector=ifelse(grepl("BLD",sector),"Buildings",sector)) %>% 
  mutate(sector=ifelse(grepl("IND",sector),"Industry",sector)) %>% 
  mutate(sector=ifelse(grepl("LUC",sector),"AFOLU",sector)) %>% 
  mutate(sector=ifelse(grepl("TOT",sector),"Total",sector)) %>% 
  mutate(sector=ifelse(grepl("TRA",sector),"Transport",sector)) %>% 
  mutate(variable=ifelse(grepl("EGY",variable),"energy",variable)) %>% 
  mutate(variable=ifelse(grepl("CO2",variable),"CO2",variable))

kaya_data <- spread(kaya_data,variable,value)
kaya_data <- kaya_data %>% 
  filter(year<2020) %>% 
  filter(year>1989)

# join IPCC regions
kaya_data <- left_join(kaya_data,ipcc_regions %>% select(ISO,name,region_ar6_6,region_ar6_6_short,region_ar6_10),by=c("ISO"="ISO"))

uhoh <- anti_join(kaya_data,ipcc_regions %>% select(ISO,name,region_ar6_6,region_ar6_6_short,region_ar6_10),by=c("ISO"="ISO"))

kaya_data <- kaya_data %>% 
  select(ISO,name,region_ar6_6,region_ar6_6_short,region_ar6_10,sector_title=sector,year,everything()) %>% 
  mutate(year=as.numeric(year))

# edit units
kaya_data <- kaya_data %>% 
  mutate(GDP = as.numeric(GDP)) %>% 
  mutate(POP = as.numeric(POP)) %>% 
  mutate(CO2 = as.numeric(CO2)) %>% 
  mutate(energy = as.numeric(energy))
kaya_data <- kaya_data %>% 
  mutate(GDP = GDP*1e9) %>% 
  mutate(POP = POP*1000) %>% 
  mutate(CO2 = CO2*1000) %>% 
  mutate(energy = energy*1000)

country_kaya_data <- kaya_data

world_pop <- kaya_data %>% 
  filter(sector_title=="Total") %>% 
  filter(ISO!="WLD") %>% 
  group_by(year) %>% 
  summarise(POP=sum(POP,na.rm=TRUE)/1e6)

```

```{r decomposition, include=FALSE}

# change World into a region
kaya_data <- kaya_data %>% 
  mutate(region_ar6_10=as.character(region_ar6_10)) %>% 
  mutate(name=ifelse(ISO=="WLD","World",name)) %>% 
  mutate(region_ar6_6=ifelse(ISO=="WLD","World",region_ar6_6)) %>% 
  mutate(region_ar6_6_short=ifelse(ISO=="WLD","World",region_ar6_6_short)) %>% 
  mutate(region_ar6_10=ifelse(ISO=="WLD","World",region_ar6_10))

kaya_data$region_ar6_10 <- as.factor(kaya_data$region_ar6_10)

# sum all variables to regions - first check for nan countries

missing_countries <- kaya_data[!complete.cases(kaya_data),]
missing_countries <- missing_countries %>% 
  filter(sector_title!="AFOLU") %>% 
  filter(sector_title!="OTH") %>% 
  filter(sector_title!="NON") %>% 
  filter(sector_title!="STT")
missing_countries <- missing_countries %>% 
  select(name) %>% distinct() %>% 
  mutate(missing=1)

#kaya_data <- kaya_data %>% 
#  na.omit()
kaya_data <- left_join(kaya_data,missing_countries,by = "name")
kaya_data <- kaya_data %>% 
  filter(is.na(missing)) %>% 
  select(-missing)

kaya_data <- kaya_data %>% 
  group_by(region_ar6_10,sector_title,year) %>% 
  summarise_at(vars(CO2,energy,GDP,POP),sum,na.rm=TRUE)

# calculate kaya components
kaya_data <- kaya_data %>% 
  mutate(CO2_energy=CO2/energy) %>%
  mutate(energy_GDP=energy/GDP) %>%
  mutate(GDP_POP=GDP/POP)

```

```{r data_decomposition_afolu_fgd}

# for AFOLU use the Hong et al decomposition
# data source here: https://www.ess.uci.edu/~sustsys/CALUE/index.html

## updated Hong dataset for final government draft

## load and join data for agricultural production and land area

hong_a <- openxlsx::read.xlsx('../../Data/Not public/LUE_Data_2019_CH.xlsx',sheet='8.1.AgProd')
names(hong_a) <- c("country",1961:2019)
hong_a <- gather(hong_a,year,ag_production_kcal,`1961`:`2019`)

hong_b <- openxlsx::read.xlsx('../../Data/Not public/LUE_Data_2019_CH.xlsx',sheet='9.1.AgLand')
names(hong_b) <- c("country",1961:2019)
hong_b <- gather(hong_b,year,land_area_hectares,`1961`:`2019`)

kaya_data_afolu <- left_join(hong_a,hong_b,by = c("year", "country"))


## join ISO codes

kaya_data_afolu <- left_join(kaya_data_afolu %>% mutate(country=tolower(country)),codes,by=c("country"="alternative.name"))

missing_countries <- kaya_data_afolu %>%
  filter(is.na(alpha.3)) %>%
  select(country) %>%
  distinct()

kaya_data_afolu <- kaya_data_afolu %>%
  mutate(alpha.3=ifelse(grepl("china- taiwan province of",country),"TWN",alpha.3)) %>%
  mutate(alpha.3=ifelse(grepl("china- hong kong sar",country),"HKG",alpha.3)) %>%
  mutate(alpha.3=ifelse(grepl("china- macao sar",country),"MAC",alpha.3)) %>%
  mutate(alpha.3=ifelse(grepl("china- mainland",country),"CHN",alpha.3)) %>%
  mutate(alpha.3=ifelse(grepl("saint helena- ascension and tristan da cunha",country),"SHN",alpha.3)) %>%
  ungroup() %>%
  mutate(year=as.numeric(year)) %>%
  filter(year>=1970)


## join AFOLU GHG emissions from the EDGAR dataset (not LULUCF)

afolu_GHG <- edgar_ghg %>%
  filter(sector_title=="AFOLU") %>%
  group_by(ISO,year,region_ar6_10) %>%
  summarise(GHG=sum(GHG,na.rm = TRUE))

kaya_data_afolu <- left_join(kaya_data_afolu,afolu_GHG,by=c("alpha.3"="ISO","year"="year"))

missing_countries <- anti_join(afolu_GHG,kaya_data_afolu,by=c("ISO"="alpha.3","year"))


## constrain to 1990 onwards and IPCC regions only

kaya_data_afolu <- kaya_data_afolu %>%
  filter(year>1989) %>%
  filter(!is.na(region_ar6_10)) %>%
  select(ISO=alpha.3,country,region_ar6_10,year,everything())


## join population data

kaya_data_afolu <- left_join(kaya_data_afolu,wdi_data_gdp_pop %>% select(ISO=iso3c,year,population),by=c("ISO","year"))


## create a world region

wld <- kaya_data_afolu %>%
  group_by(year) %>%
  summarise_at(vars(population,GHG,ag_production_kcal,land_area_hectares),sum,na.rm=TRUE) %>%
  mutate(region_ar6_10="World") %>%
  mutate(sector_title="AFOLU")


## sum to regions and join world

kaya_data_afolu <- kaya_data_afolu %>%
  mutate(sector_title="AFOLU") %>%
  group_by(region_ar6_10,sector_title,year) %>%
  summarise(ag_production_kcal=sum(ag_production_kcal,na.rm=TRUE),
            land_area_hectares=sum(land_area_hectares,na.rm=TRUE),
            GHG=sum(GHG,na.rm=TRUE),
            population=sum(population,na.rm=TRUE))

kaya_data_afolu <- kaya_data_afolu %>%
  bind_rows(wld) %>%
  rename(POP=population)


```




```{r data_decomposition_afolu_erl}

## this is for the published ERL version of the kaya analysis

## load datasets and join

# hong_a <- openxlsx::read.xlsx('../../Data/Not public/DataPortal_LUE_28Jun20.xlsx',sheet='Ag_production_kcal')
# names(hong_a) <- c("country","product",1961:2017)
# hong_a <- gather(hong_a,year,ag_production_kcal,`1961`:`2017`)
# hong_a <- hong_a %>%
#   group_by(year,country) %>%
#   summarise(ag_production_kcal=sum(ag_production_kcal,na.rm=TRUE))
# 
# hong_b <- openxlsx::read.xlsx('../../Data/Not public/DataPortal_LUE_28Jun20.xlsx',sheet='Land_area_hectares')
# names(hong_b) <- c("country","product",1961:2017)
# hong_b <- gather(hong_b,year,land_area_hectares,`1961`:`2017`)
# hong_b <- hong_b %>%
#   group_by(year,country) %>%
#   summarise(land_area_hectares=sum(land_area_hectares,na.rm=TRUE))
# 
# kaya_data_afolu <- left_join(hong_a,hong_b,by = c("year", "country"))
# 
# 
# ## join ISO codes
# 
# kaya_data_afolu <- left_join(kaya_data_afolu %>% mutate(country=tolower(country)),codes,by=c("country"="alternative.name"))
# 
# kaya_data_afolu <- kaya_data_afolu %>%
#   mutate(alpha.3=ifelse(grepl("d ivoire",country),"CIV",alpha.3)) %>%
#   mutate(alpha.3=ifelse(grepl("china, taiwan province of",country),"TWN",alpha.3)) %>%
#   mutate(alpha.3=ifelse(grepl("union",country),"REU",alpha.3))  %>%
#   mutate(alpha.3=ifelse(grepl("pacific islands trust territory",country),"PCI",alpha.3)) %>%
#   ungroup() %>%
#   mutate(year=as.numeric(year))
# 
# 
# ## join GHG emissions
# 
# afolu_GHG <- edgar_ghg %>%
#   filter(sector_title=="AFOLU") %>%
#   group_by(ISO,year,region_ar6_10) %>%
#   summarise(GHG=sum(GHG,na.rm = TRUE))
# 
# kaya_data_afolu <- left_join(kaya_data_afolu,afolu_GHG,by=c("alpha.3"="ISO","year"="year"))
# 
# 
# ## constrain to 1990-
# 
# kaya_data_afolu <- kaya_data_afolu %>%
#   filter(year>1989) %>%
#   filter(!is.na(region_ar6_10)) %>%
#   select(ISO=alpha.3,country,region_ar6_10,year,everything())
# 
# 
# ## join population (prior dataset for the ERL version)
# 
# kaya_data_afolu <- left_join(kaya_data_afolu,basic %>% select(ISO,year=Year,population=pop_UN),by = c("ISO", "year"))
# 
# 
# ## gather world region
# 
# wld <- kaya_data_afolu %>%
#   group_by(year) %>%
#   summarise_at(vars(population,GHG,ag_production_kcal,land_area_hectares),sum,na.rm=TRUE) %>% 
#   mutate(region_ar6_10="World") %>%
#   select(year,region_ar6_10,population,GHG,ag_production_kcal,land_area_hectares)
# 
# 
# ## join land use co2 data
# 
# wld_land <- land %>%
#   group_by(year) %>%
#   summarise(CO2_land=sum(CO2))
# wld <- left_join(wld,wld_land, by = "year")
# wld <- wld %>%
#   mutate(GHG_total=GHG+CO2_land)
# 
# 
# ## sum data to regions
# 
# kaya_data_afolu <- kaya_data_afolu %>%
#   group_by(year,region_ar6_10) %>%
#   summarise_at(vars(population,GHG,ag_production_kcal,land_area_hectares),sum,na.rm=TRUE)
# 
# 
# ## join land use CO2
# 
# kaya_data_afolu <- left_join(kaya_data_afolu,land %>% select(year,region_ar6_10,CO2_land=CO2),by = c("year", "region_ar6_10"))
# 
# kaya_data_afolu <- kaya_data_afolu %>%
#   mutate(GHG_total = GHG+CO2_land)
# 
# 
# ## join world
# 
# kaya_data_afolu <- kaya_data_afolu %>%
#   bind_rows(wld) %>% 
#   rename(POP=population)

```



```{r save, include=FALSE}


save(file='../../Data/data_kaya.RData',kaya_data,kaya_data_afolu)


# meta <- data.frame("Variable" = c("CO2","energy","GDP","POP","ag_production_kcal","land_area_hectares","GHG"),
#                    "Description" = c("Carbon emissions","Energy","Gross Domestic Product","Population","Agricultural production","Land area","Greenhouse gas emissions"),
#                    "Units" = c("tCO2","GJ","$ (PPP 2010 USD)","persons","kcals","hectares","tCO2eq"),
#                    "Source" = c("IEA World Energy Balances","IEA World Energy Balances","World Bank, IMF","UN Population division","Hong et al. 2020","Hong et al. 2020","EDGAR & BLUE"))
# 
# 
# wb <- openxlsx::createWorkbook(title = "kaya_data")
# openxlsx::addWorksheet(wb,"metadata")
# openxlsx::addWorksheet(wb,"data")
# openxlsx::writeData(wb, sheet = "metadata",meta, colNames = T, rowNames = F)
# openxlsx::writeData(wb, sheet = "data",country_kaya_data %>% filter(sector_title!="AFOLU"), colNames = T, rowNames = F)
# 

```
