---
title: "build_summary_sheets"
output: word_document
---

```{r setup, include=FALSE}

## This is for summarising the current version of our data including:
## - Global totals by gas
## - Sector totals by gas
## - Regional totals by sector

## It also generates a summary sheet with the IPCC sectors, regions, and GWPs

## This script should be run after compiling the data (import_edgar6_data.R)

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(openxlsx)
library(patchwork)
library(zoo)

knitr::opts_chunk$set(echo = FALSE,warning=FALSE)
options(dplyr.summarise.inform = FALSE)

load('../../Data/edgar6_v2_data_raw.RData')
load('../../Data/edgar6_v2_data_ghg_gwp_ar6.RData')
load('../../Data/land.RData')


```




```{r table_of_contents}


wb <- openxlsx::createWorkbook(title = "ipcc_ar6_edgar_summary")
addWorksheet(wb,"info")
info = data.frame(x=c("Author","Units","Last update","Code","","",
                      "Contents","gases sheets","sectors sheets","regions sheets","CO2, CH4, etc. sheets"),
                  y=c("William F. Lamb",
                      "Gt of gas (or GtCO2eq in GWP tabs)",
                      as.character(Sys.Date()),
                      "https://github.com/mcc-apsis/AR6-Emissions-trends-and-drivers/blob/master/R/Data%20preparation/build_summary_sheets.Rmd",
                  "","","",
                  "Emissions by gas in all years, with and without gwps applied",
                  "Emissions by sectors and gases in 2018, with and without gwps applied",
                  "Emissions by regions and gases in 2018, with and without gwps applied",
                  "Emissions by gas and sector in all years, no gwps applied"))
writeData(wb, sheet = "info",info, colNames = F, rowNames = F)





```



```{r gas_sheets}


gases <- edgar_raw %>% 
  group_by(year,gas,gwp100_ar6,gwp100_ar5) %>% 
  summarise(value=sum(value,na.rm=TRUE)/1e9) %>% 
  ungroup()

gases_land <- land %>% 
  filter(year>1969) %>% 
  group_by(year) %>% 
  summarise(value=sum(mean,na.rm=TRUE)/1e9) %>% 
  mutate(gas="CO2 (Land-use)") %>% 
  mutate(gwp100_ar6=1) %>% 
  mutate(gwp100_ar5=1) %>% 
  ungroup()

gases <- rbind(gases,gases_land)
gases$gas <- fct_relevel(gases$gas,c("CO2","CO2 (Land-use)","CH4","N2O"))
gases <- spread(gases,year,value)

gases_gwps_ar6 <- gather(gases,year,value,`1970`:`2019`) 
gases_gwps_ar6 <- gases_gwps_ar6 %>% 
  mutate(value=value*gwp100_ar6)
gases_gwps_ar6 <- spread(gases_gwps_ar6,year,value) 


addWorksheet(wb,"gases")
addWorksheet(wb,"gases_gwp_ar6")

writeData(wb, sheet = "gases", gases, colNames = T)
writeData(wb, sheet = "gases_gwp_ar6", gases_gwps_ar6 %>% select(-gwp100_ar5), colNames = T)


```

```{r sector_sheets}

sectors <- edgar_raw %>% 
  filter(year==2019) %>% 
  group_by(sector_code,fossil_bio,description,chapter_title,subsector_title,gas) %>% 
  summarise(value=sum(value,na.rm=TRUE)/1e9) %>% 
  ungroup()

sectors <- spread(sectors,gas,value)


sector_gwps_ar6 <- edgar_ghg %>% 
  filter(year==2019) %>% 
  group_by(sector_code,fossil_bio,description,chapter_title,subsector_title) %>% 
  summarise_at(vars(CO2,CH4,N2O,Fgas),sum,na.rm=TRUE) %>%
  ungroup()

sector_gwps_ar6 <- gather(sector_gwps_ar6,gas,value,CO2:Fgas) %>% 
  mutate(value=value/1e9)
sector_gwps_ar6$gas <- as.factor(sector_gwps_ar6$gas)
sector_gwps_ar6$gas <- fct_relevel(sector_gwps_ar6$gas,"CO2","CH4","N2O")
sector_gwps_ar6 <- spread(sector_gwps_ar6,gas,value)

addWorksheet(wb,"sectors_2019")
addWorksheet(wb,"sectors_2019_gwp_ar6")


writeData(wb, sheet = "sectors_2019", sectors, colNames = T)
writeData(wb, sheet = "sectors_2019_gwp_ar6", sector_gwps_ar6, colNames = T)


```

```{r region_sheets}

regions_ar6 <- edgar_ghg %>% 
  filter(year==2019) %>% 
  group_by(region_ar6_6,chapter_title) %>% 
  summarise_at(vars(CO2,CH4,N2O,Fgas),sum,na.rm=TRUE) %>%
  ungroup()

regions_ar6 <- gather(regions_ar6,gas,value,CO2:Fgas) %>% 
  mutate(value=value/1e9)
regions_ar6$gas <- as.factor(regions_ar6$gas)
regions_ar6$gas <- fct_relevel(regions_ar6$gas,"CO2","CH4","N2O")
regions_ar6 <- spread(regions_ar6,gas,value)

addWorksheet(wb,"regions_2019_gwp_ar6")

writeData(wb, sheet = "regions_2019_gwp_ar6", regions_ar6, colNames = T)

```

```{r sheet_for_each_gas}

each_gas <- edgar_raw %>% 
  group_by(sector_code,fossil_bio,description,subsector,subsector_title,chapter,chapter_title,year,gas,gwp100_ar5,gwp100_ar6) %>% 
  summarise(value=sum(value)/1e9) %>% 
  arrange(gas)

gas_names <- as.character(unique(each_gas$gas))


for (i in 1:length(gas_names)) {
  
  addWorksheet(wb,gas_names[i])
  data <- each_gas %>% 
    filter(gas==gas_names[i])
  
  data <- spread(data,year,value)
  
  data <- data %>% 
    filter_at(vars(-sector_code,-fossil_bio,-description,-subsector,-subsector_title,-chapter,-chapter_title,-gas,-gwp100_ar5,gwp100_ar6),
              any_vars(.!=0))
  
  writeData(wb, sheet = gas_names[i], data, colNames = T)
  
}


```





```{r classifications}

wb2 <- openxlsx::createWorkbook(title = "ipcc_ar6_data_metadata")

load('../../Data/ipcc_regions.RData')
load('../../Data/ipcc_sectors.RData')
load('../../Data/gwps.RData')

info = data.frame(x=c("Author","Last update","Code"),
                  y=c("William F. Lamb",
                      as.character(Sys.Date()),
                      "https://github.com/mcc-apsis/AR6-Emissions-trends-and-drivers/blob/master/R/Data%20preparation/build_summary_sheets.Rmd"))


addWorksheet(wb2,"info")
addWorksheet(wb2,"ipcc_sectors")
addWorksheet(wb2,"ipcc_regions")
addWorksheet(wb2,"ipcc_gwps")
addWorksheet(wb2,"ipcc_gwps_ch4")

writeData(wb2, sheet = "info",info, colNames = F, rowNames = F)
writeData(wb2, sheet = "ipcc_sectors", ipcc_sectors, colNames = T)
writeData(wb2, sheet = "ipcc_regions", ipcc_regions, colNames = T)
writeData(wb2, sheet = "ipcc_gwps", gwps, colNames = T)
writeData(wb2, sheet = "ipcc_gwps_ch4", gwps_ch4, colNames = T)



```

```{r sectors_gases}


ipcc_codes <- read.xlsx('../../Data/Codes and classifications/EDGAR_IPCC1996_to_IPCC2006.xlsx',sheet=3)

# summary of sectors and their gases

sectors_gases <- edgar_raw %>% 
  group_by(chapter_title,subsector_title,sector_code,fossil_bio,gas) %>% 
  summarise(value=sum(value,na.rm=TRUE))

# join dodgy IPCC 2006 correspondence

sectors_gases <- left_join(sectors_gases,ipcc_codes %>% select(-description,-ipcc_1996),by="sector_code")

sectors_gases <- sectors_gases %>% 
  ungroup() %>% 
  mutate(sector_code = paste0(sector_code," (",fossil_bio,")")) %>% 
  mutate(ipcc_2006 = paste0(ipcc_2006," (",fossil_bio,")")) %>% 
  select(-fossil_bio)

sectors_gases <- sectors_gases %>% 
  mutate(gas=as.character(gas)) %>% 
  mutate(gas=ifelse(value==0,NA,gas)) %>% 
  filter(!is.na(gas)) %>% 
  select(-value)

only_sectors <- sectors_gases %>% 
  ungroup() %>% 
  select(-gas,-sector_code) %>% 
  distinct() %>% 
  group_by(chapter_title,subsector_title) %>% 
  summarise(ipcc_2006=paste0(ipcc_2006,collapse=", "))


only_gases <- sectors_gases %>% 
  ungroup() %>% 
  select(-sector_code,-ipcc_2006) %>% 
  distinct() %>% 
  group_by(chapter_title,subsector_title) %>% 
  summarise(gases=paste0(gas,collapse=", "))


sectors_gases <- left_join(only_sectors,only_gases,by = c("chapter_title", "subsector_title"))


addWorksheet(wb2,"sectors_gases")
writeData(wb2, sheet = "sectors_gases",sectors_gases, colNames = T, rowNames = F)

```

```{r annex_b_table}


ipcc_codes <- read.xlsx('../../Data/Codes and classifications/EDGAR_IPCC1996_to_IPCC2006.xlsx',sheet=3)

# summary of sectors and their gases

annex <- edgar_raw %>% 
  group_by(sector_code,description,gas) %>% 
  summarise(value=sum(value,na.rm=TRUE))

annex <- annex %>% 
  group_by(sector_code,description) %>% 
  summarise(gases = paste0(gas,collapse=", "))

annex <- left_join(annex,ipcc_codes %>% select(-description,-ipcc_1996),by="sector_code")

annex <- annex %>% 
  group_by(sector_code,description) %>% 
  summarise(ipcc_2006=paste0(ipcc_2006,collapse=", "))
  

sectors_gases <- edgar_raw %>% 
  group_by(chapter_title,subsector_title,sector_code,fossil_bio,gas) %>% 
  summarise(value=sum(value,na.rm=TRUE))

# join dodgy IPCC 2006 correspondence

sectors_gases <- left_join(sectors_gases,ipcc_codes %>% select(-description,-ipcc_1996),by="sector_code")

sectors_gases <- sectors_gases %>% 
  ungroup() %>% 
  mutate(sector_code = paste0(sector_code," (",fossil_bio,")")) %>% 
  mutate(ipcc_2006 = paste0(ipcc_2006," (",fossil_bio,")")) %>% 
  select(-fossil_bio)

sectors_gases <- sectors_gases %>% 
  mutate(gas=as.character(gas)) %>% 
  mutate(gas=ifelse(value==0,NA,gas)) %>% 
  filter(!is.na(gas)) %>% 
  select(-value)

only_sectors <- sectors_gases %>% 
  ungroup() %>% 
  select(-gas,-sector_code) %>% 
  distinct() %>% 
  group_by(chapter_title,subsector_title) %>% 
  summarise(ipcc_2006=paste0(ipcc_2006,collapse=", "))


only_gases <- sectors_gases %>% 
  ungroup() %>% 
  select(-sector_code,-ipcc_2006) %>% 
  distinct() %>% 
  group_by(chapter_title,subsector_title) %>% 
  summarise(gases=paste0(gas,collapse=", "))


sectors_gases <- left_join(only_sectors,only_gases,by = c("chapter_title", "subsector_title"))


addWorksheet(wb2,"sectors_gases")
writeData(wb2, sheet = "sectors_gases",sectors_gases, colNames = T, rowNames = F)

```


```{r save}

saveWorkbook(wb,"../../Results/Data/ipcc_ar6_data_summary.xlsx",overwrite = T)
saveWorkbook(wb2,"../../Results/Data/ipcc_ar6_data_metadata.xlsx",overwrite = T)


```

```{r n20}

# load('../../Data/edgar5_data_raw.RData')
# n2o_5 <- edgar_raw %>%
#   filter(sector_code!="4E") %>% 
#   filter(gas=="N2O") %>% 
#   group_by(year) %>% 
#   summarise(N2O_5=sum(value,na.rm=TRUE))
# 
# load('../../Data/edgar6_data_raw.RData')
# n2o_6 <- edgar_raw %>%
#   filter(gas=="N2O") %>% 
#   group_by(year) %>% 
#   summarise(N2O_6=sum(value,na.rm=TRUE))
# 
# n2o <- left_join(n2o_5,n2o_6)
# n2o <- n2o %>% 
#   mutate(difference=((N2O_6/N2O_5)-1)*100)
# 
# 
