---
title: "data_checking"
author: "William F. Lamb"
output: 
  word_document:
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../Results") })
  
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,warning=FALSE)

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(openxlsx)
library(patchwork)
theme_set(theme_bw())

load('../../Data/edgar_data_all.RData')
#load('../../Data/edgar_data_gwp_ar6.RData')
#load('../../Data/basic.RData')

load('../../Data/dump/edgar_data_all_late_2020.RData')
#load('../../Data/dump/edgar_data_gwp_ar6_late_2020.RData')





```


```{r edgar_public,fig.width=10,fig.height=4}

edgar_public_co2 <- read.xlsx('../../Data/EDGAR/public version/v50_CO2_excl_short-cycle_org_C_1970_2018.xlsx',sheet=1,startRow = 9)
edgar_public_co2 <- gather(edgar_public_co2,year,CO2,`1970`:`2018`)
edgar_public_co2 <- edgar_public_co2 %>% 
  mutate(CO2=as.numeric(CO2)*1000) %>% 
  mutate(year=as.numeric(year))

edgar_public_ch4 <- read.xlsx('../../Data/EDGAR/public version/v50_CH4_1970_2015.xlsx',sheet=1,startRow = 9)
edgar_public_ch4 <- gather(edgar_public_ch4,year,CH4,`1970`:`2015`)
edgar_public_ch4 <- edgar_public_ch4 %>% 
  mutate(CH4=as.numeric(CH4)*1000) %>% 
  mutate(year=as.numeric(year))

edgar_public_n2o <- read.xlsx('../../Data/EDGAR/public version/v50_N2O_1970_2015.xlsx',sheet=1,startRow = 9)
edgar_public_n2o <- gather(edgar_public_n2o,year,N2O,`1970`:`2015`)
edgar_public_n2o <- edgar_public_n2o %>% 
  mutate(N2O=as.numeric(N2O)*1000) %>% 
  mutate(year=as.numeric(year))

edgar_public <- left_join(edgar_public_co2,edgar_public_ch4,by = c("IPCC-Annex", "World.Region", "ISO_A3", "Name", "IPCC", "IPCC_description", "year"))
edgar_public <- left_join(edgar_public,edgar_public_n2o,by = c("IPCC-Annex", "World.Region", "ISO_A3", "Name", "IPCC", "IPCC_description", "year"))

edgar_public <- edgar_public %>% 
  select(ISO=ISO_A3,sector_code=IPCC,everything())

rm(edgar_public_co2,edgar_public_ch4,edgar_public_n2o)

```


```{r ghg_compare,fig.width=10,fig.height=4}


# compare my processed edgar data, published edgar data and previous database

gas <- names(edgar_GHG %>% select(-ISO,-country,-region_ar6_5,-region_ar6_5_short,-region_ar6_10,-region_ar6_22,-region_ar6_dev,-year,-chapter,-chapter_title,-sector_code,-description,-subsector,-subsector_title))


edgar_ipcc_old <- edgar_GHG_late_2020 %>% 
  group_by(year) %>% 
  summarise_at(vars(all_of(gas)),sum,na.rm=TRUE)
edgar_ipcc_old <- gather(edgar_ipcc_old,gas,edgar_ipcc_old,-year)

edgar_ipcc_new <- edgar_GHG %>% 
  group_by(year) %>% 
  summarise_at(vars(all_of(gas)),sum,na.rm=TRUE)
edgar_ipcc_new <- gather(edgar_ipcc_new,gas,edgar_ipcc_new,-year)

edgar_public_ghgs <- edgar_public %>% 
  group_by(year) %>% 
  summarise_at(vars(all_of(c("CO2","CH4","N2O"))),sum,na.rm=TRUE)
edgar_public_ghgs <- gather(edgar_public_ghgs,gas,edgar_public,-year)

comparison <- left_join(edgar_ipcc_new,edgar_ipcc_old,by=c("year","gas"))
comparison <- left_join(comparison,edgar_public_ghgs,by=c("year","gas"))

comparison <- comparison %>% 
  mutate(difference=((edgar_ipcc_old/edgar_ipcc_new)))


comparison <- gather(comparison,var,value,-year,-gas,-difference)

comparison %>% 
  filter(gas %in% c("CO2","CH4","N2O")) %>% 
  ggplot(.,aes(x=year,y=value,color=var)) +
  geom_path() +
  geom_text(data=comparison %>% 
              filter(gas %in% c("CO2","CH4","N2O")) %>% 
              filter(year==2018),
            aes.inherit=FALSE,aes(x=1970,y=Inf,vjust=1.1,hjust=0,label=paste0("2018 difference (old/new): ",round(difference,3)))) +
  facet_wrap(.~gas,scales="free") +
  theme(legend.position="bottom",
        axis.title = element_blank(),
        legend.title=element_blank())



```

```{r fgas_compare,fig.width=10,fig.height=10}


fgas <- names(edgar_GHG %>% select(-ISO,-country,-region_ar6_5,-region_ar6_5_short,-region_ar6_10,-region_ar6_22,-region_ar6_dev,-year,-chapter,-chapter_title,-sector_code,-description,-subsector,-subsector_title,-CO2,-CH4,-N2O))

comparison %>% 
  filter(gas %in% fgas) %>% 
  ggplot(.,aes(x=year,y=value,color=var)) +
  geom_path() +
  facet_wrap(.~gas,scales="free") +
  theme(legend.position="bottom",
        axis.title = element_blank(),
        legend.title=element_blank())

```

## countries


```{r country_compare,fig.width=10,fig.height=8}



edgar_ipcc_old <- edgar_GHG_late_2020 %>% 
  group_by(year,ISO) %>% 
  summarise_at(vars(all_of(gas)),sum,na.rm=TRUE)
edgar_ipcc_old <- gather(edgar_ipcc_old,gas,edgar_ipcc_old,-year,-ISO)

edgar_ipcc_new <- edgar_GHG %>% 
  group_by(year,ISO) %>% 
  summarise_at(vars(all_of(gas)),sum,na.rm=TRUE)
edgar_ipcc_new <- gather(edgar_ipcc_new,gas,edgar_ipcc_new,-year,-ISO)

edgar_public_ghgs <- edgar_public %>% 
  group_by(year,ISO) %>% 
  summarise_at(vars(all_of(c("CO2","CH4","N2O"))),sum,na.rm=TRUE)
edgar_public_ghgs <- gather(edgar_public_ghgs,gas,edgar_public,-year,-ISO)

comparison <- left_join(edgar_ipcc_new,edgar_ipcc_old,by=c("year","gas","ISO"))
comparison <- left_join(comparison,edgar_public_ghgs,by=c("year","gas","ISO"))


load('../../Data/gwps.RData')

comparison <- left_join(comparison,gwps %>% select(gas,gwp_ar6),by="gas")
comparison <- comparison %>% 
  mutate(gwp_ar6=ifelse(gas=="CH4",28,gwp_ar6)) ###### just use a single GWP from AR5 for CH4

comparison <- comparison %>% 
  mutate(edgar_ipcc_new_gwp = edgar_ipcc_new*gwp_ar6) %>% 
  mutate(edgar_ipcc_old_gwp = edgar_ipcc_old*gwp_ar6) %>% 
  mutate(edgar_public_gwp = edgar_public*gwp_ar6)

comparison_ghgs <- comparison %>% 
  select(year,ISO,gas,edgar_ipcc_new_gwp,edgar_ipcc_old_gwp,edgar_public_gwp)
comparison_ghgs <- gather(comparison_ghgs,var,value,-year,-ISO,-gas)
comparison_ghgs <- comparison_ghgs %>% 
  group_by(year,ISO,var) %>% 
  summarise(value=sum(value,na.rm=TRUE))

top_countries <- comparison_ghgs %>% 
  ungroup() %>% 
  filter(year==2018) %>% 
  filter(var=="edgar_ipcc_new_gwp") %>% 
  mutate(rank=dense_rank(desc(value))) %>% 
  select(ISO,rank) %>% 
  distinct()

comparison_ghgs <- left_join(comparison_ghgs,top_countries,by = "ISO")

comparison_ghgs %>% filter(rank<13) %>% 
  ggplot(.,aes(x=year,y=value,colour=var)) +
  geom_path() +
  facet_wrap(.~ISO,scales="free") +
  theme(legend.position="bottom")

```

```{r code_comparison,fig.width=10,fig.height=10}



edgar_ipcc_old <- edgar_GHG_late_2020 %>% 
  group_by(year,sector_code,description) %>% 
  summarise_at(vars(all_of(gas)),sum,na.rm=TRUE)
edgar_ipcc_old <- gather(edgar_ipcc_old,gas,edgar_ipcc_old,-year,-sector_code,-description)

edgar_ipcc_new <- edgar_GHG %>% 
  group_by(year,sector_code,description) %>% 
  summarise_at(vars(all_of(gas)),sum,na.rm=TRUE)
edgar_ipcc_new <- gather(edgar_ipcc_new,gas,edgar_ipcc_new,-year,-sector_code,-description)

comparison <- left_join(edgar_ipcc_new,edgar_ipcc_old,by=c("year","gas","sector_code","description"))

load('../../Data/gwps.RData')

comparison <- left_join(comparison,gwps %>% select(gas,gwp_ar6),by="gas")
comparison <- comparison %>% 
  mutate(gwp_ar6=ifelse(gas=="CH4",28,gwp_ar6)) ###### just use a single GWP from AR5 for CH4

comparison <- comparison %>% 
  mutate(edgar_ipcc_new_gwp = edgar_ipcc_new*gwp_ar6) %>% 
  mutate(edgar_ipcc_old_gwp = edgar_ipcc_old*gwp_ar6)

comparison_ghgs <- comparison %>% 
  select(year,sector_code,description,gas,edgar_ipcc_new_gwp,edgar_ipcc_old_gwp)
comparison_ghgs <- gather(comparison_ghgs,var,value,-year,-sector_code,-description,-gas)
comparison_ghgs <- comparison_ghgs %>% 
  group_by(year,sector_code,description,var) %>% 
  summarise(value=sum(value,na.rm=TRUE))

different_codes <- spread(comparison_ghgs,var,value) %>% 
  ungroup() %>% 
  filter(year!=2019) %>% 
  mutate(difference=edgar_ipcc_new_gwp-edgar_ipcc_old_gwp) %>%
  group_by(sector_code) %>% 
  mutate(max_difference=max(abs(difference)),ratio=edgar_ipcc_new_gwp/edgar_ipcc_old_gwp)
different_codes <- different_codes %>% 
  ungroup() %>% 
  select(sector_code,max_difference) %>% 
  distinct() %>% 
  mutate(rank=dense_rank(desc(max_difference)))

comparison_ghgs <- left_join(comparison_ghgs,different_codes,by = "sector_code")


comparison_ghgs %>% filter(rank<17) %>% 
  filter(year!=2019) %>% 
  ggplot(.,aes(x=year,y=value,colour=var)) +
  geom_path() +
  facet_wrap(.~description,scales="free") +
  theme(legend.position="bottom")


```

```{r check_gwps}

totals <- rbind(compare_ch4 %>% mutate(gas="CH4"),compare_n2o %>% mutate(gas="N2O"),compare_co2 %>% mutate(gas="CO2")) %>% 
  filter(year==2015)

edgar_ipcc_gwps <- edgar_GHG_ar6 %>% 
  group_by(year) %>% 
  summarise_at(vars(CO2,CH4,N2O),sum,na.rm=T)

edgar_ipcc_gwps <- gather(edgar_ipcc_gwps,gas,ipcc_gwp,CO2:N2O)

totals <- left_join(totals,edgar_ipcc_gwps,by = c("year", "gas"))

load('../../Data/gwps.RData')

totals <- totals %>% 
  mutate(ipcc_gwp = ifelse(gas=="N2O",ipcc_gwp/261,ipcc_gwp))

```


## Single out countries with high emissions contributions from individual sectors

```{r crazy_countries,fig.width=8,fig.height=20,fig.path="../Results/Plots/Checks/",dev=c('png','pdf')}

##

data <- edgar_GHG_ar6 %>% 
  group_by(country,year) %>% 
  mutate(country_GHG=sum(GHG,na.rm=TRUE)) %>% 
  ungroup()

blarg <- edgar_GHG_ar6 %>% 
  group_by(country,ISO,year) %>% 
  summarise(GHG=sum(GHG,na.rm=T))

blarg <- left_join(blarg,basic %>% select(ISO,year=Year,pop_UN))

blarg <- blarg %>% 
  mutate(ghgpc = GHG/pop_UN) %>% 
  filter(year==2018) %>% 
  arrange(desc(ghgpc))

data <- data %>% 
  mutate(sector_fraction=(GHG/country_GHG)*100)

data <- data %>% 
  filter(region_ar6_5_short!="AIR") %>% 
  filter(region_ar6_5_short!="SEA") 

data <- data %>% 
  filter(year==2018) %>% 
  group_by(country) %>% 
  arrange(desc(sector_fraction)) %>% 
  mutate(include=ifelse(first(sector_fraction)>50,1,0)) %>% 
  ungroup()


data <- data %>% 
  filter(country_GHG>1e6) %>% ## exclude countries with less than 1Mt CO2
  filter(include==1) %>% 
  group_by(country) %>% 
  top_n(10,wt = GHG) %>% 
  ungroup()




data <- gather(data,gas,value,CO2:Fgas)


data %>% ggplot(.,aes(x=reorder(description,desc(value)),y=value,fill=gas)) +
  geom_bar(stat='identity') +
  coord_flip() +
  facet_wrap(.~country,scales='free',ncol=1) +
  theme_bw() +
  theme(legend.position="top",
        legend.title=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())




```

```{r cement,fig.width=8,fig.height=10,fig.path="../Results/Plots/Checks/",dev=c('png','pdf')}

data <- edgar_GHG_ar6 %>% 
  filter(chapter_title=="Industry") %>%
  filter(year>1989) %>% 
  group_by(year,sector_code,description) %>% 
  summarise(value=sum(GHG,na.rm=T))

data %>%
  filter(value>1e8) %>% 
  ggplot(.,aes(x=year,y=value,colour=description)) +
  geom_path() +
  facet_wrap(~description,ncol=4,scales='free',labeller = label_wrap_gen(width=15)) +
  theme(legend.position = "none")


```

```{r industry_check,fig.width=8,fig.height=6,fig.path="../Results/Plots/Checks/",dev=c('png','pdf')}

data <- edgar_GHG_ar6 %>% 
  filter(chapter_title=="Industry") %>%
  filter(year>1989) %>% 
  group_by(year,sector_code,description) %>% 
  summarise(value=sum(GHG,na.rm=T))


data %>%
  filter(str_detect(sector_code, "^2F") | str_detect(sector_code, "^2E")) %>% 
  #  filter(sector_code=="2F1-4" | sector_code=="2F9" | sector_code=="2E1") %>% 
  ggplot(.,aes(x=year,y=value,colour=sector_code)) +
  geom_path() +
  facet_wrap(~sector_code,ncol=4,scales='free',labeller = label_wrap_gen(width=15)) +
  theme(legend.position = "none")


```

```{r building_check,fig.width=8,fig.height=6,fig.path="../Results/Plots/Checks/",dev=c('png','pdf')}

data <- edgar_GHG_ar6 %>% 
  filter(chapter_title=="Buildings")

library(openxlsx)
wb <- openxlsx::createWorkbook(title = "ipcc_ar6_edgar_buildings")
addWorksheet(wb,'all_data')
writeData(wb, sheet = "all_data", data, colNames = T)

sector_aggregation <- data %>% 
  group_by(year,sector_code,description) %>% 
  summarise_at(vars(CO2:GHG),sum,na.rm=T)

addWorksheet(wb,'sector_aggregation')
writeData(wb, sheet = "sector_aggregation", sector_aggregation, colNames = T)

unique_codes <- data %>% 
  select(sector_code,description) %>% 
  unique()

addWorksheet(wb,'codes_in_data')
writeData(wb, sheet = "codes_in_data", unique_codes, colNames = T)


global_totals <- edgar_GHG_ar6 %>% 
  filter(year==2018) %>% 
  summarise_at(vars(CO2:GHG),sum,na.rm=T) %>% 
  mutate(chapter_title='Total')

totals_data <- edgar_GHG_ar6 %>% 
  filter(year==2018) %>% 
  group_by(chapter_title) %>% 
  summarise_at(vars(CO2:GHG),sum,na.rm=T)

totals_data <- rbind(totals_data,global_totals)

addWorksheet(wb,'totals_by_chapter_2018')
writeData(wb, sheet = "totals_by_chapter_2018",totals_data, colNames = T)

fgas_totals <- edgar_GHG_ar6 %>% 
  filter(year==2018) %>% 
  group_by(sector_code,description,chapter,chapter_title) %>% 
  summarise_at(vars(CO2:GHG),sum,na.rm=T)

addWorksheet(wb,'totals_by_code_2018')
writeData(wb, sheet = "totals_by_code_2018",fgas_totals, colNames = T)



saveWorkbook(wb,"../Results/Data/ipcc_ar6_edgar_buildings.xlsx",overwrite = T)



```

```{r worksheet_check,fig.width=8,fig.height=6,fig.path="../Results/Plots/testing/",dev=c('png','pdf')}



worksheet <- read.xlsx('../Results/Data/ipcc_ar6_edgar_data_gwp100_v3.xlsx','emissions_data')

plot_data <- worksheet %>% 
  filter(year>1989) %>% 
  filter(year<2019) %>% 
  group_by(year) %>% 
  summarise(CO2=sum(CO2,na.rm=T)/1e9,CH4=sum(CH4,na.rm=T)/1e9,N2O=sum(N2O,na.rm=T)/1e9,Fgas=sum(Fgas,na.rm=T)/1e9)


```

```{r double_counting,fig.width=8,fig.height=6,fig.path="../Results/Plots/testing/",dev=c('png','pdf')}

data <- edgar_GHG_ar5 %>% 
  filter(year==2018) %>% 
  #filter(str_detect(sector_code, "^1A")) %>% 
  group_by(year,sector_code,description) %>% 
  summarise(value=sum(GHG,na.rm=T))


data %>%
  filter(str_detect(sector_code, "^2F") | str_detect(sector_code, "^2E")) %>% 
  ggplot(.,aes(x=year,y=value,colour=sector_code)) +
  geom_path() +
  facet_wrap(~sector_code,ncol=4,scales='free',labeller = label_wrap_gen(width=15)) +
  theme(legend.position = "none")


```


```{r waste,fig.width=8,fig.height=6,fig.path="../Results/Plots/testing/",dev=c('png','pdf')}

data <- edgar_GHG_ar5 %>% 
  filter(year>1989) %>% 
  filter(str_detect(description, "Managed waste")) %>% 
  group_by(year,sector_code,description) %>% 
  summarise(value_new=sum(GHG,na.rm=T))


data2 <- edgar_GHG %>% 
  filter(year>1989) %>% 
  filter(str_detect(description, "Managed waste")) %>% 
  group_by(year,sector_code,description) %>% 
  summarise(value_old=sum(GHG,na.rm=T))  

data <- left_join(data,data2)

data <- data %>% 
  mutate(difference=value_new-value_old)

data <- gather(data,key,value,value_new:value_old)

data %>% ggplot(.,aes(x=year,y=value,colour=key)) +
  geom_line() +
  ggtitle(data$description[1])


```


## differences by gas


```{r total_gas_checks,fig.width=8,fig.height=6}

divide.by <- function(x, na.rm=FALSE) (x/1e9)

totals_new <- edgar_GHG_ar5 %>% 
  group_by(year) %>% 
  mutate_at(vars(CO2:GHG),divide.by) %>% 
  summarise_at(vars(CO2:GHG),sum,na.rm=T)

totals_old <- edgar_GHG %>% 
  group_by(year) %>% 
  mutate_at(vars(CO2:GHG),divide.by) %>% 
  summarise_at(vars(CO2:GHG),sum,na.rm=T) %>% 
  ungroup()

totals_new <- gather(totals_new,key,value_new,CO2:GHG)
totals_old <- gather(totals_old,key,value_old,CO2:GHG)

totals <- left_join(totals_new,totals_old)

totals$key=as.factor(totals$key)
totals$key <- factor(totals$key,levels(totals$key)[c(2,1,5,3,4)])


totals <- totals %>% 
  mutate(difference=(value_new-value_old)/value_new) %>% 
  filter(year!=2018)

totals %>% ggplot(.,aes(x=year,y=difference,fill=key)) +
  geom_bar(stat='identity') +
  facet_wrap(~key,scales='free',nrow = 2) +
  ylab("Difference in emissions (as % of the new data in that year)") +
  theme(legend.position="bottom",
        axis.title.x=element_blank(),
        legend.title=element_blank())


```

## differences by chapter


```{r total_chapter_checks,fig.width=8,fig.height=12}

divide.by <- function(x, na.rm=FALSE) (x/1e9)

totals_new <- edgar_GHG_ar5 %>% 
  group_by(year,chapter) %>% 
  mutate_at(vars(CO2:GHG),divide.by) %>% 
  summarise_at(vars(CO2:GHG),sum,na.rm=T)

totals_old <- edgar_GHG %>% 
  group_by(year,chapter) %>% 
  mutate_at(vars(CO2:GHG),divide.by) %>% 
  summarise_at(vars(CO2:GHG),sum,na.rm=T) %>% 
  ungroup()

totals_new <- gather(totals_new,key,value_new,CO2:GHG)
totals_old <- gather(totals_old,key,value_old,CO2:GHG)

totals <- left_join(totals_new,totals_old)

totals$key=as.factor(totals$key)
totals$key <- factor(totals$key,levels(totals$key)[c(2,1,5,3,4)])


totals <- totals %>% 
  mutate(difference=value_new-value_old) %>% 
  filter(year!=2018) %>% 
  filter(year>1989)

#totals <- totals %>% 
# group_by(chapter,key) %>% 
#filter(any(difference!=0))


totals %>% ggplot(.,aes(x=year,y=difference,fill=key)) +
  geom_bar(stat='identity') +
  facet_grid(chapter~key,scales='free') +
  ylab("Difference in emissions (GtCO2eq)") +
  theme(legend.position="bottom",
        axis.title.x=element_blank(),
        legend.title=element_blank())

```


## differences by individual sector


```{r total_sector_checks,fig.width=8,fig.height=12}

divide.by <- function(x, na.rm=FALSE) (x/1e9)

totals_new <- edgar_GHG_ar5 %>% 
  group_by(year,sector_code,description) %>% 
  mutate_at(vars(CO2:GHG),divide.by) %>% 
  summarise_at(vars(CO2:GHG),sum,na.rm=T)

totals_old <- edgar_GHG %>% 
  group_by(year,sector_code,description) %>% 
  mutate_at(vars(CO2:GHG),divide.by) %>% 
  summarise_at(vars(CO2:GHG),sum,na.rm=T) %>% 
  ungroup()

totals_new <- gather(totals_new,key,value_new,CO2:GHG)
totals_old <- gather(totals_old,key,value_old,CO2:GHG)

totals <- left_join(totals_new,totals_old)

totals$key=as.factor(totals$key)
totals$key <- factor(totals$key,levels(totals$key)[c(2,1,5,3,4)])

totals <- totals %>% 
  filter(year>1989) %>% 
  filter(key!="GHG") %>% 
  group_by(sector_code,description,key) %>% 
  summarise_at(vars(value_new:value_old),sum,na.rm=T) %>% 
  mutate(difference=(value_new-value_old)/value_new)

totals <- totals %>% 
  filter(!is.na(difference)) %>% 
  filter(difference!=0) %>% 
  filter(difference>0.09 | difference< -0.09) %>% 
  arrange(desc(difference))

totals %>% 
  ggplot(.,aes(x=reorder(description,difference),y=difference,fill=key)) +
  geom_bar(stat='identity') +
  coord_flip() +
  facet_wrap(~key,scales='free',ncol=1) +
  ylab("Relative increase (%) in emissions of new data, averaged 1990-2017") +
  theme(legend.position="bottom",
        axis.title.x=element_blank(),
        legend.title=element_blank())

```












## new data - sector trends


```{r sector_checks,fig.width=8,fig.height=6}

totals <- edgar_GHG_ar5 %>% 
  group_by(year,chapter_title) %>% 
  summarise_at(vars(CO2:Fgas),sum,na.rm=T)

totals <- gather(totals,key,value,CO2:Fgas)

totals <- totals %>% 
  group_by(chapter_title) %>% 
  mutate(nor=value/max(value)) %>% 
  arrange(year) %>% 
  group_by(chapter_title,key) %>% 
  mutate(nor_x=nor+(1-nth(nor,n=1)))


totals %>% ggplot(.,aes(x=year,y=nor_x,color=key)) +
  geom_line() +
  facet_wrap(~chapter_title,scales='free',nrow = 2) +
  theme(legend.position="bottom",
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.title=element_blank())



```

## new data - region trends  

```{r region_checks,fig.width=8,fig.height=6}

totals <- edgar_GHG_ar5 %>% 
  group_by(year,region_ar6_5) %>% 
  summarise_at(vars(CO2:Fgas),sum,na.rm=T)

totals <- gather(totals,key,value,CO2:Fgas)

totals <- totals %>% 
  group_by(region_ar6_5) %>% 
  mutate(nor=value/max(value)) %>% 
  arrange(year) %>% 
  group_by(region_ar6_5,key) %>% 
  mutate(nor_x=nor+(1-nth(nor,n=1)))


totals %>% ggplot(.,aes(x=year,y=nor_x,color=key)) +
  geom_line() +
  facet_wrap(~region_ar6_5,scales='free',ncol=4,labeller = label_wrap_gen(width=18)) +
  theme(legend.position="bottom",
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.title=element_blank())


```


## new data - high emitting country trends

```{r country_checks,fig.width=8,fig.height=6}

totals <- edgar_GHG_ar5 %>% 
  group_by(year,country) %>% 
  summarise_at(vars(CO2:GHG),sum,na.rm=T)

countries <- totals %>%
  ungroup() %>% 
  filter(year==2018) %>% 
  arrange(desc(GHG)) %>% 
  mutate(include=0)
countries$include[1:10] <- 1
countries <- countries %>% 
  select(country,include)

totals <- left_join(totals,countries,by=c("country"="country"))

totals <- gather(totals,key,value,CO2:Fgas)
totals <- totals %>% 
  filter(include==1) %>% 
  group_by(country,year) %>% 
  arrange(desc(value))

totals <- totals %>% 
  group_by(country) %>% 
  mutate(nor=value/max(value)) %>% 
  arrange(year) %>% 
  group_by(country,key) %>% 
  mutate(nor_x=nor+(1-nth(nor,n=1)))


totals %>% ggplot(.,aes(x=year,y=nor_x,color=key)) +
  geom_line() +
  facet_wrap(~country,scales='free',ncol=4,labeller = label_wrap_gen(width=18)) +
  theme(legend.position="bottom",
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.title=element_blank())


```