---
title: "Cumulative historical emissions (1750 & 1850-)"
author: "Niklas Döbbeling"
date: "12 10 2021"
output: 
  word_document:
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results/knitr/") })

---

```{r setup, include=FALSE}
library(tidyverse)
library(RColorBrewer)
library(ggrepel)
colors = colorRampPalette(brewer.pal(8, "Set2"))(11)
ggplot <- function(...) ggplot2::ggplot(...) + scale_color_manual(values=colors) + scale_fill_manual(values=colors)

load("../../Data/data_land_co2.RData")

gcb_hist<-read_csv('../../Data/Supplementary datasets/GCB2020v18_MtCO2_flat.csv') %>%
  filter(Country!="Global")

load("../../Data/ipcc_regions.RData")

gcb_hist<-gcb_hist %>%
  mutate(`ISO 3166-1 alpha-3`=ifelse(Country=="Panama Canal Zone","PAN",`ISO 3166-1 alpha-3`))%>%
  mutate(`ISO 3166-1 alpha-3`=ifelse(Country=="French Equatorial Africa","TCD",`ISO 3166-1 alpha-3`))%>%
  mutate(`ISO 3166-1 alpha-3`=ifelse(Country=="French West Africa","NER",`ISO 3166-1 alpha-3`))%>%
  mutate(`ISO 3166-1 alpha-3`=ifelse(Country=="Kosovo","MNE",`ISO 3166-1 alpha-3`))%>%
  mutate(`ISO 3166-1 alpha-3`=ifelse(Country=="Kuwaiti Oil Fires","KWT",`ISO 3166-1 alpha-3`))%>%
  mutate(`ISO 3166-1 alpha-3`=ifelse(Country=="Leeward Islands","GLP",`ISO 3166-1 alpha-3`))%>%
  mutate(`ISO 3166-1 alpha-3`=ifelse(Country=="Pacific Islands (Palau)","PLW",`ISO 3166-1 alpha-3`))%>%
  mutate(`ISO 3166-1 alpha-3`=ifelse(Country=="Ryukyu Islands","JPN",`ISO 3166-1 alpha-3`))

gcb_hist<-left_join(gcb_hist,ipcc_regions,by=c("ISO 3166-1 alpha-3"="ISO")) %>%
  mutate(region_ar6_6=ifelse(Country=="International Transport","Int. Aviation and Shipping",region_ar6_6)) %>%
  mutate(region_ar6_10=ifelse(Country=="International Transport","Int. Aviation and Shipping",region_ar6_10)) %>%
  mutate(region_ar6_dev=ifelse(Country=="International Transport","Int. Aviation and Shipping",region_ar6_dev)) %>%
  filter(!is.na(region_ar6_10))

hist_countries <- gcb_hist %>% 
  select(year=Year,ISO=`ISO 3166-1 alpha-3`,co2_cum=Total) %>% 
  mutate(co2_cum=co2_cum/1000)

gcb_hist<-gcb_hist %>%
  #filter(Year>=1850) %>%
  group_by(Year,region_ar6_10,region_ar6_6,region_ar6_dev) %>%
  summarise(co2_cum=sum(Total,na.rm=TRUE)/1000) %>%
  mutate(source="CO2-FFI") %>%
  rename("year"="Year")

# hist_emissions_1750<-gcb_hist %>%
#   group_by(region_ar6_10,region_ar6_6) %>%
#   summarise(co2_cum=sum(Total,na.rm=TRUE)/1000) %>%
#   mutate(source="CO2-FFI") %>%
#   ungroup() %>%
#   mutate(share=co2_cum/sum(co2_cum)*100)

### land
land_1850<-land %>%
  group_by(year,region_ar6_10,region_ar6_6) %>%
  summarise(co2_cum=sum(mean,na.rm=TRUE)/1e9) %>%
  mutate(source="CO2-LULUCF")
  
hist_emissions<-rbind(gcb_hist,land_1850)

hist_1850_10<-hist_emissions %>%
  filter(year>=1850) %>%
  group_by(region_ar6_10,source) %>%
  summarise(co2_cum=sum(co2_cum,na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(share=co2_cum/sum(co2_cum)*100)

hist_1850_6<-hist_emissions %>%
  filter(year>=1850) %>%
  group_by(region_ar6_6,source) %>%
  summarise(co2_cum=sum(co2_cum,na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(share=co2_cum/sum(co2_cum)*100)

hist_1850_dev<-hist_emissions %>%
  filter(year>=1850) %>%
  filter(source=="CO2-FFI") %>%
  group_by(region_ar6_dev,source) %>%
  summarise(co2_cum=sum(co2_cum,na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(share=co2_cum/sum(co2_cum)*100)

hist_1750_10<-hist_emissions %>%
  filter(source=="CO2-FFI") %>%
  group_by(region_ar6_10,source) %>%
  summarise(co2_cum=sum(co2_cum,na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(share=co2_cum/sum(co2_cum)*100)

hist_1750_6<-hist_emissions %>%
  filter(source=="CO2-FFI") %>%
  group_by(region_ar6_6,source) %>%
  summarise(co2_cum=sum(co2_cum,na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(share=co2_cum/sum(co2_cum)*100)

hist_1750_dev<-hist_emissions %>%
  filter(source=="CO2-FFI") %>%
  group_by(region_ar6_dev,source) %>%
  summarise(co2_cum=sum(co2_cum,na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(share=co2_cum/sum(co2_cum)*100)

```

```{r save,echo=FALSE}

save(hist_1750_10,hist_1750_6,hist_1750_dev,hist_1850_10,hist_1850_6,hist_1850_dev,hist_emissions,hist_countries,file="../../Data/data_cumulative_co2.RData")

wb <- openxlsx::createWorkbook(title = paste("ipcc_ar6_figure_spm_cumulative_co2"))

openxlsx::addWorksheet(wb,"emissions 1850-2019 10 regions")
openxlsx::addWorksheet(wb,"emissions 1750-2019 10 regions")

openxlsx::addWorksheet(wb,"emissions 1850-2019 6 regions")
openxlsx::addWorksheet(wb,"emissions 1750-2019 6 regions")

openxlsx::addWorksheet(wb,"emissions 1850-2019 dev regions")
openxlsx::addWorksheet(wb,"emissions 1750-2019 dev regions")

openxlsx::addWorksheet(wb,"info")

openxlsx::writeData(wb,"emissions 1850-2019 10 regions",hist_1850_10, colNames = T, rowNames = F)
openxlsx::writeData(wb,"emissions 1750-2019 10 regions",hist_1750_10, colNames = T, rowNames = F)

openxlsx::writeData(wb,"emissions 1850-2019 6 regions",hist_1850_6, colNames = T, rowNames = F)
openxlsx::writeData(wb,"emissions 1750-2019 6 regions",hist_1750_6, colNames = T, rowNames = F)

openxlsx::writeData(wb,"emissions 1850-2019 dev regions",hist_1850_dev, colNames = T, rowNames = F)
openxlsx::writeData(wb,"emissions 1750-2019 dev regions",hist_1750_dev, colNames = T, rowNames = F)

openxlsx::writeData(wb,"info","Please note that the data presented here does not include cement carbonation. It deviates in this respect from the aggregated emissions presented by WG1.", colNames = T, rowNames = F)

openxlsx::saveWorkbook(wb,"../../Results/Plot data/ipcc_ar6_figure_spm_cumulative_co2.xlsx",overwrite=T)

```

```{r plot_region_10,echo=FALSE}
hist_1850_10 %>%
  ggplot(aes(x=source,y=co2_cum,fill=region_ar6_10))+
  geom_bar(stat="identity",position = "stack")+
  ylab('CO2 Emissions (Gt)') +
  xlab('') +
  ggtitle("Cumulative CO2 emissions 1850-2019")+
  theme(legend.title = element_blank())

blarg <- hist_1850_10 %>% 
  group_by(region_ar6_10) %>%
  summarise_at(vars(co2_cum,share),sum,na.rm=TRUE) %>%
  ungroup() %>%
  arrange(desc(region_ar6_10)) %>% 
  mutate(label=paste0(region_ar6_10," (",round(share,1),"%)")) %>%
  #arrange(desc(chapter_title),GHG) %>% 
  ungroup() %>% 
  mutate(label_position = cumsum(co2_cum) - co2_cum/2)

hist_1850_10 %>%
  ggplot(aes(x=01,y=co2_cum,fill=region_ar6_10))+
  geom_bar(stat="identity",position = "stack")+
  geom_text_repel(inherit.aes = FALSE,data=blarg,aes(x=1.6,y=label_position,label=label,color=region_ar6_10),
    nudge_x      = 1,
    direction    = "y",
    hjust        = 0,
    segment.size = 0.02#,
    #ylim = c(-1,100)
  )+
  xlim(0,9) +
  ylab('CO2 Emissions (Gt)') +
  xlab('') +
  ggtitle("Cumulative CO2 emissions (FFI and LULUCF) 1850-2019")+
    theme(legend.position = "none",
           plot.background = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
        panel.background = element_blank())

blarg <- hist_1850_10 %>% 
  group_by(region_ar6_10) %>%
  summarise(share=sum(share)) %>%
  ungroup() %>%
  arrange(desc(region_ar6_10)) %>% 
  mutate(label=paste0(region_ar6_10," (",round(share,1),"%)")) %>%
  #arrange(desc(chapter_title),GHG) %>% 
  ungroup() %>% 
  mutate(label_position = cumsum(share) - share/2)

hist_1850_10 %>%
  group_by(region_ar6_10) %>%
  summarise(share=sum(share)) %>%
  ggplot(aes(x=1,y=share,fill=region_ar6_10))+
  geom_bar(stat="identity",position = "stack")+
   geom_text_repel(inherit.aes = FALSE,data=blarg,aes(x=1.6,y=label_position,label=label,color=region_ar6_10),
    nudge_x      = 1,
    direction    = "y",
    hjust        = 0,
    segment.size = 0.02,
    ylim = c(-1,100)
  )+
  xlim(0,8) +
  ylab('%-Share of CO2 Emissions') +
  xlab('') +
  ggtitle("Regional shares of cumulative CO2 emissions 1850-2019")+
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank())

hist_1750_10 %>%
  ggplot(aes(x=source,y=co2_cum,fill=region_ar6_10))+
  geom_bar(stat="identity",position = "stack")+
  ylab('CO2 Emissions (Gt)') +
  xlab('') +
  ggtitle("Cumulative CO2 emissions 1750-2019")+
  theme(legend.title = element_blank())
```

```{r plot_6_regions,echo=FALSE}
hist_1850_6 %>%
  ggplot(aes(x=source,y=co2_cum,fill=region_ar6_6))+
  geom_bar(stat="identity",position = "stack")+
  ylab('CO2 Emissions (Gt)') +
  xlab('') +
  ggtitle("Cumulative CO2 emissions 1850-2019")+
  theme(legend.title = element_blank())

blarg <- hist_1850_6 %>%
  group_by(region_ar6_6) %>%
  summarise_at(vars(co2_cum,share),sum,na.rm=TRUE) %>%
  ungroup() %>%
  arrange(desc(region_ar6_6)) %>%
  mutate(label=paste0(region_ar6_6," (",round(share,1),"%)")) %>%
  #arrange(desc(chapter_title),GHG) %>%
  ungroup() %>%
  mutate(label_position = cumsum(co2_cum) - co2_cum/2)

hist_1850_6 %>%
  ggplot(aes(x=1,y=co2_cum,fill=region_ar6_6))+
  geom_bar(stat="identity",position = "stack")+
  geom_text_repel(inherit.aes = FALSE,data=blarg,aes(x=1.6,y=label_position,label=label,color=region_ar6_6),
    nudge_x      = 1,
    direction    = "y",
    hjust        = 0,
    segment.size = 0.02#,
    #ylim = c(-1,100)
  )+
  xlim(0,9) +
  ylab('CO2 Emissions (Gt)') +
  xlab('') +
  ggtitle("Cumulative CO2 emissions (FFI and LULUCF) 1850-2019")+
  theme(legend.position = "none",
           plot.background = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
        panel.background = element_blank())

blarg <- hist_1850_6 %>%
  group_by(region_ar6_6) %>%
  summarise(share=sum(share)) %>%
  ungroup() %>%
  arrange(desc(region_ar6_6)) %>%
  mutate(label=paste0(region_ar6_6," (",round(share,1),"%)")) %>%
  #arrange(desc(chapter_title),GHG) %>%
  ungroup() %>%
  mutate(label_position = cumsum(share) - share/2)

hist_1850_6 %>%
  group_by(region_ar6_6) %>%
  summarise(share=sum(share)) %>%
  ggplot(aes(x=1,y=share,fill=region_ar6_6))+
  geom_bar(stat="identity",position = "stack")+
   geom_text_repel(inherit.aes = FALSE,data=blarg,aes(x=1.6,y=label_position,label=label,color=region_ar6_6),
    nudge_x      = 1,
    direction    = "y",
    hjust        = 0,
    segment.size = 0.02,
    ylim = c(-1,100)
  )+
  xlim(0,8) +
  ylab('%-Share of CO2 Emissions') +
  xlab('') +
  ggtitle("Regional shares of cumulative CO2 emissions 1850-2019")+
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank())


hist_1750_6 %>%
  ggplot(aes(x=source,y=co2_cum,fill=region_ar6_6))+
  geom_bar(stat="identity",position = "stack")+
  ylab('CO2 Emissions (Gt)') +
  xlab('') +
  ggtitle("Cumulative CO2 emissions 1750-2019")+
  theme(legend.title = element_blank())
```

