---
title: "emissions_maps"
output: word_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "Results") })
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(patchwork)
library(ggmap)
library(maps)
library(ggplot2); theme_set(theme_bw())
library(scales)

source("../Analysis and figures/small_figures.R")


#load('../../Data/edgar6_data_ghg_gwp_ar5.RData')
#load('../../Data/edgar_essd_data_ghg_gwp_ar5.RData')
load('../../Data/edgar6_v4_data_ghg_gwp_ar6.RData')
load('../../Data/gwps.RData')
load("../../Data/land.RData")
load('../../Data/WDI_gdp_pop.RData')


#isos <- openxlsx::read.xlsx("C:/Users/lamw/Documents/SpiderOak Hive/Work/Code/R/.Place names and codes/output/ISOcodes.xlsx","alternative_names")
isos <- openxlsx::read.xlsx("../../Data/Codes and classifications/ISOcodes.xlsx","alternative_names")

# set palette
ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2")

wb <- openxlsx::createWorkbook(title = paste("ipcc_ar6_map_data_",Sys.Date()))

```




```{r data, include=FALSE,echo=FALSE}


mapdata <- edgar_ghg %>% 
  filter(year>1969) %>% 
  filter(year<=2019) %>%
  group_by(country,ISO,year) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE))

mapdata <- left_join(mapdata,wdi_data_gdp_pop,by=c("ISO"="iso3c","year"="year"))


mapdata <- mapdata %>% 
  mutate(GHGpc=GHG/population) %>% 
  filter(population>1e6)



## calculate average annual and absolute growth

time_start=1990
mapdata_1990 <- mapdata %>% 
  filter(year %in% c(time_start,2018)) %>% 
  group_by(country,ISO) %>% 
  mutate(avg_growth_1990=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
  filter(year==2018) %>% 
  mutate(avg_growth_1990=avg_growth_1990*100) %>% 
  select(country,ISO,avg_growth_1990)

time_start=2009
mapdata_2009 <- mapdata %>% 
  filter(year %in% c(time_start,2018)) %>% 
  group_by(country,ISO) %>% 
  mutate(avg_growth_2009=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
  filter(year==2018) %>% 
  mutate(avg_growth_2009=avg_growth_2009*100) %>% 
  select(country,ISO,avg_growth_2009)

time_start=1970
mapdata_1970 <- mapdata %>% 
  filter(year %in% c(time_start,2018)) %>% 
  group_by(country,ISO) %>% 
  mutate(avg_growth_1970=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
  filter(year==2018) %>% 
  mutate(avg_growth_1970=avg_growth_1970*100) %>% 
  select(country,ISO,avg_growth_1970)

mapdata <- mapdata %>% filter(year==2018)
mapdata <- left_join(mapdata,mapdata_1990,by = c("country", "ISO"))
mapdata <- left_join(mapdata,mapdata_2009,by = c("country", "ISO"))
mapdata <- left_join(mapdata,mapdata_1970,by = c("country", "ISO"))

world <- map_data("world") %>% 
  filter(region!="Antarctica")
world <- left_join(world %>% mutate(region=tolower(region)),isos,by=c("region"="alternative.name"))
world <- left_join(world,mapdata,by=c("alpha.3"="ISO"))

##save data
openxlsx::addWorksheet(wb,"growth_rates")
openxlsx::writeData(wb, sheet = "growth_rates", mapdata, colNames = T, rowNames = F)

openxlsx::saveWorkbook(wb,paste0("Results/Data/ipcc_ar6_map_data_",Sys.Date(),".xlsx"),overwrite=T)

```

```{r map_subplots,include=FALSE,echo=FALSE,fig.width=6,fig.height=3}



## per capita
p1 <- ggplot() + 
  geom_polygon(data = world, aes(x=long, y = lat, group=group, fill=GHGpc),color="grey",size=0.25,na.rm=T) + 
  #scale_fill_viridis_c(limits = c(0,35)) +
  scale_fill_steps(low = 'lightyellow',high = "darkred", na.value="lightgrey", limits = c(0,35), breaks=c(5,10,15,20,25,30), oob=squish) +
  #check again with new data the limit to 35 tCO2eq per capita
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.5,0),
        legend.direction = "horizontal",
        legend.key.width = unit(2,"cm"),
        legend.key.height = unit(.2,"cm"),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0.5,0),units="cm"),
        plot.title = element_text(size=12),
        panel.grid=element_blank()) +
  ggtitle("a. GHG emissions per capita in 2018 in tCO2eq")
p1

p2 <- ggplot() + 
  geom_polygon(data = world, aes(x=long, y = lat, group=group, fill=avg_growth_2009),color="grey",size=0.25,na.rm=T) + 
  #scale_fill_viridis_c() +
  scale_fill_steps2(low = "midnightblue",mid = "lightyellow",high = "darkred", na.value="lightgrey", midpoint=0, breaks=c(-8,-6,-4,-2,0,2,4,6,8), limits=c(-10,10), oob=squish) +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.5,0),
        legend.direction = "horizontal",
        legend.key.width = unit(2,"cm"),
        legend.key.height = unit(.2,"cm"),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0.5,0),units="cm"),
        plot.title = element_text(size=12),
        panel.grid=element_blank()) +
  # theme(panel.border = element_rect(colour = "black",fill=NA),
  #       legend.position = c(0.05,0.3),
  #       legend.title = element_blank(),
  #       legend.background = element_blank(),
  #       axis.title = element_blank(),
  #       axis.ticks = element_blank(),
  #       axis.text = element_blank(),
  #       plot.margin = unit(c(0,0,0,0),units="cm"),
  #       plot.title = element_text(size=12)) +
  ggtitle("b. Average annual GHG emissions growth in percent (2009-2018)")
p2

## growth 1990-2018
# p3 <- ggplot() + 
#   geom_polygon(data = world, aes(x=long, y = lat, group=group, fill=avg_growth_1990),color="grey",size=0.25,na.rm=T) + 
#   #scale_fill_viridis_c() +
#   scale_fill_steps2(low = "midnightblue",mid = "lightyellow",high = "darkred", na.value="lightgrey", midpoint=0, breaks=c(-8,-6,-4,-2,0,2,4,6,8), limits=c(-10,10),oob=squish) +
#   theme(panel.border = element_rect(colour = "black",fill=NA),
#         legend.position = c(0.5,0),
#         legend.direction = "horizontal",
#         legend.key.width = unit(2,"cm"),
#         legend.key.height = unit(.2,"cm"),
#         legend.background = element_blank(),
#         legend.title = element_blank(),
#         axis.title = element_blank(),
#         axis.ticks = element_blank(),
#         axis.text = element_blank(),
#         plot.margin = unit(c(0,0,0.5,0),units="cm"),
#         plot.title = element_text(size=12),
#         panel.grid=element_blank()) +
#   ggtitle("c. Average annual GHG emissions growth in percent (1990-2018)")
# p3

## growth 1970-2018
p4 <- ggplot() + 
  geom_polygon(data = world, aes(x=long, y = lat, group=group, fill=avg_growth_1970),color="grey",size=0.25,na.rm=T) + 
  #scale_fill_viridis_c() +
  scale_fill_steps2(low = "midnightblue",mid = "lightyellow",high = "darkred", na.value="lightgrey", midpoint=0, breaks=c(-8,-6,-4,-2,0,2,4,6,8), limits=c(-10,10),oob=squish) +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.5,0),
        legend.direction = "horizontal",
        legend.key.width = unit(2,"cm"),
        legend.key.height = unit(.2,"cm"),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0.5,0),units="cm"),
        plot.title = element_text(size=12),
        panel.grid=element_blank()) +
  ggtitle("c. Average annual GHG emissions growth in percent (1970-2018)")

```

```{r maps,echo=FALSE,fig.width=5,fig.height=9,results='asis',fig.path="Results/Plots/",dev=c('png','pdf')}

p1/p2/p4

```
