---
title: "emissions_by_sector"
output: word_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "Results") })
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(ggplot2); theme_set(theme_bw())
library(RColorBrewer)
library(ggrepel)
library(patchwork)
library(zoo)
library(lubridate)

source("../../R/Analysis and figures/small_figures.R")

#load('../../Data/edgar6_data_ghg_gwp_ar5.RData')
load('../../Data/edgar_essd_data_ghg_gwp_ar5.RData')
load('../../Data/gwps.RData')
load('../../Data/land.RData')

options(dplyr.summarise.inform = FALSE)


########## add land CO2 data

land <- land %>%
  filter(year>1969) %>% 
  filter(year<=2019) %>% 
  mutate(chapter=7) %>% 
  mutate(chapter_title="AFOLU") %>% 
  mutate(subsector=7.7) %>% 
  mutate(subsector_title="Land-use (CO2)") %>% 
  select(region_ar6_10,year,chapter,chapter_title,subsector,subsector_title,value=mean)

########## summary sheet

wb <- openxlsx::createWorkbook(title = paste("ipcc_sector_data",Sys.Date()))

info <- data.frame(x=c("Author","Date","Units","Contact","Code"),y=c("William F. Lamb",as.character(Sys.Date()),"tCO2eq","Lamb@mcc-berlin.net","https://github.com/mcc-apsis/AR6-Emissions-trends-and-drivers/blob/master/R/Analysis%20and%20figures/emissions_by_sector.Rmd"))

openxlsx::addWorksheet(wb,sheetName="info")
openxlsx::writeData(wb,sheet="info",info,colNames=F,rowNames=F)

growth_rate <- function(years,y){
  
  # if(all(is.na(y))){
  #    return(NA)
  # } else {
  
  data <- data.frame(years,y)
  
  data <- data %>%
    mutate(leap_years = leap_year(years)) %>%
    mutate(y = ifelse(leap_years==TRUE,y*365/366,y)) #%>%
    #filter(!is.na(y))
  
  # if (nrow(data<3)) {
  #   return(NA)
  #   } else {
      
  fit <- lm(log(y) ~ years,data = data)
  
  # data <- data %>% 
  #   mutate(rate=fit$coefficients[2]) %>% 
  #   mutate(predicted_x = exp(predict(fit,data %>% select(years)))) %>% 
  #   mutate(st_error = sqrt(diag(vcov(fit)))[2])
  # 
  # return(list("rate"=fit$coefficients[2],"data"=data))
  
  return(fit$coefficients[2])
  # }
}


```

```{r sector_data,echo=FALSE,warning=FALSE}

######### data preparation

## sum emissions for the sector
sector_data <- edgar_ghg %>%
  filter(year>1969) %>%
  group_by(year,chapter,chapter_title) %>%
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE) %>% 
  mutate_at(vars(CO2,CH4,N2O,Fgas,GHG),list(~./1e9)) %>%
  mutate(CO2_land=NA,CO2_indirect=NA) %>% 
  ungroup()

# PREPARE LAND DATA
land_totals <- land %>%
  group_by(year,chapter,chapter_title) %>%
  summarise(GHG=sum(value,na.rm=TRUE)) %>%
  mutate(GHG=GHG/1e9)

land_totals <- land_totals %>%
  ungroup() %>% 
  mutate(CO2_land=GHG) %>% 
  mutate(CO2=NA,CH4=NA,N2O=NA,Fgas=NA,CO2_indirect=NA) %>% 
  select(year,chapter,chapter_title,CO2,CH4,N2O,Fgas,GHG,CO2_land,CO2_indirect)

sector_data <- rbind(sector_data,land_totals)
sector_data <- sector_data %>%
  group_by(year,chapter,chapter_title) %>%
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG,CO2_land,CO2_indirect),sum,na.rm=TRUE)

trend_ghg_data <- sector_data
sector_data <- sector_data %>% 
  select(year,chapter,chapter_title,value=GHG)

openxlsx::addWorksheet(wb,"sector_trends")
openxlsx::writeData(wb, sheet = "sector_trends", spread(sector_data,year,value), colNames = T, rowNames = F)

######### label preparation


## align factors and labels
sector_data$chapter_title <- as.factor(sector_data$chapter_title)
sector_data$chapter_title <- factor(sector_data$chapter_title,levels=levels(sector_data$chapter_title)[c(3,4,1,5,2)])



labels <- sector_data %>%
  filter(year==2019) %>% 
  arrange(desc(chapter_title))

labels <- labels %>% 
  mutate(fractions=(value/sum(labels$value))*100)

labels$cum <- cumsum(labels$value)

for (j in 1:length(labels$year)) {
  labels$location[j] = labels$value[j]*0.5
}
for (j in 2:length(labels$year)) {
  labels$location[j] = labels$location[j] + labels$cum[j-1]
}

## calculate shares
shares <- sector_data %>%
  filter(year %in% c(1970,1980,1990,2000,2010,2019)) %>%
  group_by(year) %>%
  mutate(totals=sum(value)) %>%
  ungroup() %>%
  group_by(year,chapter) %>%
  mutate(fractions=(value/totals)*100) %>%
  ungroup()

shares <- locate_shares(shares,"chapter",6)

# # calculate overall growth between years (time 1 time 2)
growth_data <- sector_data %>%
  group_by(year) %>%
  summarise(value=sum(value)) %>%
  mutate(decade=ifelse((year>1969 & year<1980),"1970-1979",NA)) %>%
  mutate(decade=ifelse((year>1979 & year<1990),"1980-1989",decade)) %>%
  mutate(decade=ifelse((year>1989 & year<2000),"1990-1999",decade)) %>%
  mutate(decade=ifelse((year>1999 & year<2010),"2000-2009",decade)) %>%
  mutate(decade=ifelse((year>2009 & year<2020),"2010-2019",decade)) %>%
  group_by(decade) %>%
  mutate(avg_annual_growth=growth_rate(years = year,y=value)*100) %>%
  filter(year %in% c(1970,1980,1990,2000,2010,2019))

# growth_data <- sector_data %>%
#   filter(year %in% c(1970,1980,1990,2000,2010,2019)) %>%
#   group_by(year) %>%
#   summarise(value=sum(value)) %>%
#   mutate(total_rate = NA)
# 
# for (j in 1:length(growth_data$year)-1) {
#   rate = (((growth_data$value[j+1]/growth_data$value[j])^(1/(growth_data$year[j+1]-growth_data$year[j])))-1)*100
#   growth_data$total_rate[j] <- rate
# }

shares <- left_join(shares,growth_data %>% select(-value) %>% filter(year %in% c(1970,1980,1990,2000,2010)),by="year")

```

```{r sector_trend_plot,echo=FALSE,warning=FALSE,include=FALSE}



p1 <- sector_data %>%
  ggplot(.,aes(x=year,y=value,fill=chapter_title)) +
  geom_area(color='#737373') +
  
  geom_vline(xintercept=c(1970,1980,1990,2000,2010,2019),alpha=0.3,linetype="dashed") +
  geom_text(data=shares %>% filter(chapter_title==shares$chapter_title[1]),aes(x=year,y=1.2*max(shares$totals),label=paste(round(totals,1),  "Gt")),size=3.5,colour="#252525") +
  
  geom_text(inherit.aes=FALSE,data=labels,aes(x=year+0.5,y=location,label=paste0(round(fractions,0),"%"),color=chapter_title),size=3.5,show.legend = FALSE,hjust=0) +
  
  geom_text(data=shares %>% filter(chapter_title==shares$chapter_title[1]) %>% filter(year<=2019),aes(x=year+5,y=1.15*max(shares$totals),label=paste0(ifelse(avg_annual_growth>0,"+","-"),round(abs(avg_annual_growth),1),"%/yr")),size=3.5,colour="#252525") +
  
  scale_x_continuous(breaks=c(1970,1980,1990,2000,2010,2019),limits = c(1970,2020)) +
  scale_y_continuous() +
  expand_limits(y=c(0,max(shares$totals)*1.2)) +
  scale_fill_brewer(type = "qual",palette="Set2") +
  scale_color_brewer(type = "qual",palette="Set2") +
  
  big_trend_theme +
  ggtitle("a. GHG emissions trends by sector") +
  theme(legend.position="right",
        axis.title.x = element_blank(),
        legend.title=element_blank(),
        legend.spacing.x= unit(0.25, 'cm')) +
  ylab(bquote("GHG Emissions (Gt" ~CO[2]* "eq/yr)"))

p1

```

```{r subsector_data,echo=FALSE,warning=FALSE}



## sum emissions for the sector
subsector_data <- edgar_ghg %>%
  filter(year>1969) %>%
  group_by(year,chapter,chapter_title,subsector,subsector_title) %>%
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE) %>% 
  mutate_at(vars(CO2,CH4,N2O,Fgas,GHG),list(~./1e9)) %>%
  mutate(CO2_land=NA,CO2_indirect=NA) %>% 
  ungroup()

# PREPARE LAND DATA
land_totals <- land %>%
  group_by(year,chapter,chapter_title,subsector,subsector_title) %>%
  summarise(GHG=sum(value,na.rm=TRUE)) %>%
  mutate(GHG=GHG/1e9)

land_totals <- land_totals %>%
  ungroup() %>% 
  mutate(CO2_land=GHG) %>% 
  mutate(CO2=NA,CH4=NA,N2O=NA,Fgas=NA,CO2_indirect=NA) %>% 
  select(year,chapter,chapter_title,subsector,subsector_title,CO2,CH4,N2O,Fgas,GHG,CO2_land,CO2_indirect)

subsector_data <- rbind(subsector_data,land_totals)
subsector_data <- subsector_data %>%
  group_by(year,chapter,chapter_title,subsector,subsector_title) %>%
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG,CO2_land,CO2_indirect),sum,na.rm=TRUE)

subsector_ghg_data <- subsector_data
subsector_data <- subsector_data %>% 
  select(year,chapter,chapter_title,subsector,subsector_title,GHG)


## align factors and labels
subsector_data$chapter_title <- as.factor(subsector_data$chapter_title)
subsector_data$chapter_title <- factor(subsector_data$chapter_title,levels=levels(subsector_data$chapter_title)[c(3,4,1,5,2)])

time_start=1990

# what is 90% of the emissions?
threshold <- subsector_data %>%
  filter(year==2019)
threshold <- sum(threshold$GHG,na.rm=T)*0.9


## calculate average annual and absolute growth

subsector_data <- subsector_data %>% 
  filter(year>=1990) %>% 
  group_by(subsector,subsector_title) %>% 
  mutate(avg_growth_1990=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
  mutate(abs_growth_1990=last(GHG)-first(GHG)) %>%
  filter(year>=2010) %>% 
  group_by(subsector,subsector_title) %>% 
  mutate(avg_growth_2010=(last(GHG)/first(GHG))^(1/(last(year)-2010))-1) %>% 
  mutate(abs_growth_2010=last(GHG)-first(GHG)) %>%
  filter(year==2019) %>% 
  mutate(avg_growth_1990=avg_growth_1990*100) %>% 
  mutate(avg_growth_2010=avg_growth_2010*100)

## remove subsectors below absolute emissions threshold

subsector_data <- subsector_data %>% 
  ungroup() %>% 
  arrange(desc(GHG)) %>% 
  mutate(cumulative_GHG=cumsum(GHG)) %>% 
  mutate(cutoff = ifelse(cumulative_GHG<threshold,1,0)) %>% 
  select(-cumulative_GHG)

subsector_data <- gather(subsector_data,var,value,avg_growth_1990,abs_growth_1990,avg_growth_2010,abs_growth_2010)


plot_theme <- theme_bw() +
  theme(axis.title.y = element_blank(),
        plot.title = element_text(size = 11,color="#252525"),
        axis.title = element_text(color="#525252"),
        panel.grid.minor.x = element_blank(),
        legend.position="none",
        text = element_text(size=11),
        plot.background = element_blank())


#rate
p2 <- subsector_data %>% 
  filter(cutoff==1) %>% 
  filter(var=="avg_growth_1990") %>% 
  ggplot(.,aes(x = reorder(subsector_title,value),y = value, fill=chapter_title)) +
  geom_bar(stat='identity',colour="#525252") + 
  coord_flip() +
  plot_theme +
  scale_fill_brewer(type = "qual",palette="Set2") +
  ylab("%") +
  ggtitle(str_wrap("b. Avg. annual GHG emissions growth",width=38)) +
  annotate(geom = 'text', label = 'Years: 1990-2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.4,size=3.5,color="#525252")

#absolute
p3 <- subsector_data %>% 
  filter(cutoff==1) %>% 
  filter(var=="abs_growth_1990") %>% 
  ggplot(.,aes(x = reorder(subsector_title,value),y = value, fill=chapter_title)) +
  geom_bar(stat='identity',colour="#737373") + 
  coord_flip() +
  plot_theme +
  scale_fill_brewer(type = "qual",palette="Set2") +
  ylab("Gt CO2eq") +
  ggtitle(str_wrap("c. Absolute GHG emissions growth",width=35)) +
    annotate(geom = 'text', label = 'Years: 1990-2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#525252")

#rate
p4 <- subsector_data %>% 
  filter(cutoff==1) %>% 
  filter(var=="avg_growth_2010") %>% 
  ggplot(.,aes(x = reorder(subsector_title,value),y = value, fill=chapter_title)) +
  geom_bar(stat='identity',colour="#525252") + 
  coord_flip() +
  plot_theme +
  scale_fill_brewer(type = "qual",palette="Set2") +
  ylab("%") +
  ggtitle(str_wrap("d. Avg. annual GHG emissions growth",width=38)) +
  annotate(geom = 'text', label = 'Years: 2010-2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.4,size=3.5,color="#525252")

#absolute
p5 <- subsector_data %>% 
  filter(cutoff==1) %>% 
  filter(var=="abs_growth_2010") %>% 
  ggplot(.,aes(x = reorder(subsector_title,value),y = value, fill=chapter_title)) +
  geom_bar(stat='identity',colour="#737373") + 
  coord_flip() +
  plot_theme +
  scale_fill_brewer(type = "qual",palette="Set2") +
  ylab("Gt CO2eq") +
  ggtitle(str_wrap("e. Absolute GHG emissions growth",width=35)) +
    annotate(geom = 'text', label = 'Years: 2010-2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#525252")

##save data
openxlsx::addWorksheet(wb,"Emissions by subsector")
openxlsx::writeData(wb, sheet = "Emissions by subsector", subsector_data, colNames = T, rowNames = F)

openxlsx::saveWorkbook(wb,paste0("Results/Data/ipcc_ar6_sector_data_",Sys.Date(),".xlsx"),overwrite=T)

```

```{r sector_emissions,echo=FALSE,warning=FALSE,results='asis',fig.width=10,fig.height=12,fig.path="Results/Plots/",dev=c('png','pdf')}


#p1 / (p2 + p3)

p <- ggarrange(p2,p3,ncol=2,align = "v")
pp <- ggarrange(p4,p5,ncol=2,align = "v")
p <- ggarrange(p1,p,pp,nrow=3,align = "h",heights=c(1/3,1/3,1/3))
p

```