---
title: "Global emissions trends by gas"
author: "William F. Lamb"
date: "30 10 2020"
output: word_document
#knit: (function(inputFile, encoding) {
#  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results") })
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "Results") })
---


```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(patchwork)
library(ggplot2); theme_set(theme_bw())

source("../Analysis and figures/small_figures.R")


# load('../../Data/edgar_data_gwp_ar6.RData')
# load("../../Data/edgar_data_all.RData")
#load('../../Data/edgar6_data_ghg_gwp_ar5.RData')
load('../../Data/edgar_essd_data_ghg_gwp_ar5.RData')
#load("../../Data/edgar6_data_raw_gwp_ar5.RData") #if changed to ar6 change line 432 and 440
#load("../../Data/edgar6_data_raw.RData")
load("../../Data/edgar_essd_data_raw.RData")
load('../../Data/gwps.RData')
load("../../Data/land.RData")


# set palette
ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2")

uncertainties <- data.frame(gas=c('CO2 FFI','CO2 Land use','CH4','N2O','Fgas','GHG'),
                            uncertainty=c(0.08,0.5,0.2,0.6,0.2,0.1))


wb <- openxlsx::createWorkbook(title = paste("ipcc_ar6_gas_data_",Sys.Date()))

```


```{r waterfall, echo=FALSE,warning=FALSE,include=FALSE}

####### calculate total emissions for different gases using different GWPs

waterfall_data <- edgar_raw %>% 
  # group_by(year) %>% 
  # summarise_at(vars(CO2:SF6),sum,na.rm=TRUE) %>% 
  # mutate_at(vars(CO2:SF6),list(~./1e9))
  group_by(year,gas,gwp100_ar2,gwp100_ar5) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(value=value/1e9) %>%
  ungroup()

#waterfall_data <- gather(waterfall_data,gas,value,CO2:SF6)
#waterfall_data <- left_join(waterfall_data,gwps,by = "gas")
waterfall_data <- waterfall_data %>% 
  mutate(gwp_ar2=gwp100_ar2*value) %>% 
  #mutate(gwp_ar4=gwp100_ar4*value) %>% 
  mutate(gwp_ar5=gwp100_ar5*value) %>% 
  #mutate(gwp_ar6=gwp_ar6*value) %>% 
  group_by(year,gas) %>% 
  summarise_at(vars(gwp_ar2:gwp_ar5),sum,na.rm=TRUE) #%>% 
  #select(-value,-gwp100_ar2,-gwp100_ar5)#,-gwp_ar6_sod)


#### recalculate methane in AR6 using biogenic / non-biogenic methane GWPs

# methane <- edgar_raw %>% 
#   #filter(!is.na(CH4)) %>% 
#   filter(gas=="CH4") %>%
#   group_by(sector_code,description,year) %>% 
#   #summarise(CH4=sum(CH4,na.rm=TRUE))
#   summarise(value=sum(value,na.rm=TRUE))
# 
# methane <- left_join(methane,gwps_ch4,by = "sector_code")
# 
# methane <- methane %>% 
#   mutate(CH4_adjusted=value*gwp_ar6) %>% 
#   mutate(CH4_base=value*32)
# 
# ## which methane sectors explain the difference?
# 
# # methane <- methane %>% 
# #   filter(year==2019) %>% 
# #   mutate(difference=(CH4_adjusted-CH4_base)/1e9) %>% 
# #   arrange(desc(difference))
# 
# methane <- methane %>% 
#   group_by(year) %>% 
#   summarise(CH4_base=sum(CH4_base)/1e9,CH4_adjusted=sum(CH4_adjusted,na.rm = TRUE)/1e9) %>% 
#   mutate(difference=(CH4_adjusted-CH4_base)) %>% 
#   mutate(gas="CH4")
# 
# waterfall_data <- left_join(waterfall_data,methane,by = c("year", "gas"))
# 
# waterfall_data <- waterfall_data %>% 
#   mutate(gwp_ar6=ifelse(!is.na(CH4_adjusted),CH4_adjusted,gwp_ar6)) %>% 
#   select(-CH4_base,-CH4_adjusted,-difference)

#### calculate fgas and land emissions

fgas <- waterfall_data %>% 
  filter(!gas %in% c("CO2","CH4","N2O")) %>% 
  group_by(year) %>% 
  #summarise_at(vars(gwp_ar2:gwp_ar6),sum,na.rm=TRUE) %>% 
  summarise_at(vars(gwp_ar2:gwp_ar5),sum,na.rm=TRUE) %>% 
  mutate(gas="Fgas") %>% 
  select(year,gas,everything())

land_totals <- land %>% 
  filter(year>1969) %>% 
  filter(year<2020) %>% 
  group_by(year) %>% 
  summarise(CO2_landuse=sum(mean)/1e9)

waterfall_land <- land_totals %>% 
  mutate(gas="CO2 Land use") %>% 
  mutate(gwp_ar2=CO2_landuse) %>% 
  #mutate(gwp_ar4=CO2_landuse) %>% 
  mutate(gwp_ar5=CO2_landuse) %>% 
  #mutate(gwp_ar6=CO2_landuse) %>% 
  select(-CO2_landuse)

waterfall_data <- waterfall_data %>% 
  filter(gas %in% c("CO2","CH4","N2O"))
waterfall_data <- rbind(waterfall_data,fgas)
waterfall_data <- rbind(waterfall_data,waterfall_land) %>% 
  mutate(gas=as.character(gas)) %>%
  mutate(gas=ifelse(gas=="CO2","CO2 FFI",gas))

waterfall_data <- waterfall_data %>% 
  filter(year==2019) %>% 
  select(-year)

######### save data ######### 

openxlsx::addWorksheet(wb,"gwp_waterfall")
openxlsx::writeData(wb, sheet = "gwp_waterfall", waterfall_data, colNames = T, rowNames = F)

######### plot different gwp totals in a waterfall

waterfall_data$gas <- as.factor(waterfall_data$gas)
waterfall_data$gas <-  factor(waterfall_data$gas,levels(waterfall_data$gas)[c(2,3,1,5,4)])

waterfall_data <- waterfall_data %>% 
  arrange(gas)

# waterfall_data <- gather(waterfall_data,gwp,value,gwp_ar2:gwp_ar6)
waterfall_data <- gather(waterfall_data,gwp,value,gwp_ar2:gwp_ar5)

waterfall_data <- waterfall_data %>% 
  group_by(gwp) %>% 
  mutate(end = cumsum(value)) %>% 
  mutate(start = c(0, head(end, -1))) %>% 
  mutate(id = c(5,4,3,2,1))

### add uncertainties

waterfall_data <- left_join(waterfall_data,uncertainties,by=c("gas"="gas"))
waterfall_data <- waterfall_data %>% 
  group_by(gwp) %>% 
  mutate(abs_uncertainty=value*uncertainty) %>% 
  mutate(uncertainty_start=end-abs_uncertainty) %>% 
  mutate(uncertainty_end=end+abs_uncertainty) %>% 
  group_by(gwp) %>% 
  mutate(total=sum(value))


waterfall_data$gas <- as.factor(waterfall_data$gas)
waterfall_data$gas <-  factor(waterfall_data$gas,levels(waterfall_data$gas)[c(4,5,1,3,2)])
colours = c("#e78ac3","#fc8d62","#8da0cb","#66c2a5","#a6d854")

### plot

p_waterfall <- waterfall_data %>%
  filter(gwp!="gwp_ar4") %>% 
  ggplot(., aes(fill = gas)) +
  scale_fill_manual(values=colours) +
  geom_rect(aes(
    x = gas,
    xmin = id - 0.48,
    xmax = id + 0.48,
    ymin = start,
    ymax = end
  ),colour = "#737373") +
  
  geom_rect(aes(
    xmin = id,
    xmax = id,
    ymin = uncertainty_start,
    ymax = uncertainty_end
  ),colour = "#252525") +

  geom_rect(aes(
    xmin = id - 0.2,
    xmax = id + 0.2,
    ymin = uncertainty_start,
    ymax = uncertainty_start
  ),colour = "#252525") +

  geom_rect(aes(
    xmin = id - 0.2,
    xmax = id + 0.2,
    ymin = uncertainty_end,
    ymax = uncertainty_end
  ),colour = "#252525") +

   facet_grid(~gwp,switch="both") +
   
   geom_text(data=waterfall_data %>% filter(gwp!="gwp_ar4") %>%  filter(gas=="CO2 Land use"),aes(x=gas,y=62,label=paste(round(total,1),  "Gt")),size=3.5,colour="#252525") +
  
  #geom_text(data=waterfall_data %>% filter(gwp!="gwp_ar4") %>%  filter(gas=="CH4"),aes(x=gas,xlab(c("AR2 GWP","AR5 GWP","AR6 GWP"))),size=3.5,colour="#252525") +
   
   theme_bw() +
   scale_y_continuous(breaks=c(0,10,20,30,40,50,60),limits=c(0,62)) +
   scale_x_discrete(labels=c("","","","","")) +
   #xlab("GWP AR2, AR5, AR6") +
   theme(
     legend.position = "none",
     title = element_blank(),
     axis.title.y = element_blank(),
     axis.ticks.y = element_blank(),
     axis.text.y = element_blank(),
     #axis.title.x = element_blank(),
     #axis.text.x = element_blank(),
     axis.ticks.x = element_blank(),
     panel.grid.minor.x = element_blank(),
     panel.grid.minor.y = element_blank(),
     panel.grid.major.x = element_blank(),
     panel.spacing = unit(0, "mm"),
     strip.background = element_blank())
     #strip.text = c("AR2 GWP","AR5 GWP","AR6 GWP"))

p_waterfall

```

```{r gas_trend, echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=4}

plot_data <- edgar_ghg %>% 
  filter(year>1969) %>% 
  filter(year<2020) %>% 
  group_by(year) %>% 
  summarise(CO2=sum(CO2,na.rm=T)/1e9,CH4=sum(CH4,na.rm=T)/1e9,N2O=sum(N2O,na.rm=T)/1e9,Fgas=sum(Fgas,na.rm=T)/1e9)

### join land use data

plot_data <- left_join(plot_data,land_totals,by=c("year"="year"))
plot_data<- gather(plot_data,gas,value,-year) 
plot_data <- plot_data %>% 
  mutate(gas=ifelse(gas=="CO2","CO2 FFI",gas)) %>% 
  mutate(gas=ifelse(gas=="CO2_landuse","CO2 Land use",gas))

plot_data$gas <- as.factor(plot_data$gas)
plot_data$gas <-  factor(plot_data$gas,levels(plot_data$gas)[c(4,5,1,3,2)])

shares <- plot_data %>% 
  filter(year %in% c(1970,1980,1990,2000,2010,2019)) %>%              #change
  group_by(year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,gas) %>% 
  mutate(fractions=(value/totals)*100)

shares <- locate_shares(shares,"gas",6)           #change, 4 to 6
shares <- shares %>%
  mutate(location=ifelse(gas=="Fgas",location+1.5,location))

line_data <- data.frame(x=c(1970,1970,1980,1980,1990,1990,2000,2000,2010,2010,2019,2019),y=c(0,60))       #change

# # calculate overall growth between years (time 1 time 2)
growth_data <- plot_data %>%
  filter(year %in% c(1970,1980,1990,2000,2010,2019)) %>%
  group_by(year) %>%
  summarise(value=sum(value)) %>%
  mutate(total_rate = NA)

for (j in 1:length(growth_data$year)-1) {
  rate = (((growth_data$value[j+1]/growth_data$value[j])^(1/(growth_data$year[j+1]-growth_data$year[j])))-1)*100
  growth_data$total_rate[j] <- rate
}

shares <- left_join(shares,growth_data %>% select(-value) %>% filter(year %in% c(1970,1980,1990,2000,2010)),by="year")


p_gas_totals <- plot_data %>% 
  ggplot(.,aes(x=year,y=value,fill=gas)) +
  scale_fill_manual(values=colours) +
  geom_area(colour="#737373") +
  
  geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  
  #geom_vline(xintercept=c(1990,2000,2010,2019),alpha=0.3,linetype="dashed") +
  
  #### text with the shares
  geom_text(data=shares,aes(x=year+1.5,y=location,label=paste(round(fractions,0),"%",sep="")),size=3.5,colour="#252525")+
  
  #### text with the totals
  geom_text(data=shares %>% filter(gas=="Fgas"),aes(x=year,y=62,label=paste(round(totals,0),  "Gt")),size=3.5,colour="#252525")+
  
  geom_text(data=shares %>% filter(gas=="Fgas") %>%
    filter(year<2019),aes(x=year+5,y=1.15*max(shares$totals,na.rm = TRUE),label=paste0(ifelse(total_rate>0,"+","-"),
    round(abs(total_rate),1),"%/yr")),size=3.5,colour="#252525") +
  
  ylab('GHG Emissions \n(GtCO2eq/yr)') +
  labs(fill="Gas") +
  scale_y_continuous(breaks=c(0,10,20,30,40,50,60)) +
  scale_x_continuous(breaks=c(1970,1980,1990,2000,2010,2019)) +             #change
  big_trend_theme +
  theme(
    #legend.position = c(0.225,0.85),
    legend.position="none",    
    legend.background = element_rect(linetype = 1, size = 0.5, colour = "#525252"),
    legend.margin = margin(l=5,t=5,b=5,r=10,unit="pt"),
    legend.text = element_text(size=8),
    legend.title = element_text(size=8)) +
  guides(fill=guide_legend(nrow=1,byrow=TRUE),
    shape = guide_legend(override.aes = list(size = 0.5)),
    color = guide_legend(override.aes = list(size = 0.5)))

p_gas_totals

```

```{r ghgs_no_gwp, echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=2}
# 
# 
# 
# plot_data_nogwp <- edgar_raw %>% 
#   group_by(year) %>% 
#   summarise_at(vars(CO2:N2O),sum,na.rm=TRUE) %>% 
#   mutate_at(vars(CO2:N2O),list(~./1e9))
# 
# plot_data_nogwp <- left_join(plot_data_nogwp,land_totals,by = "year")
# 
# plot_data_nogwp <- gather(plot_data_nogwp,gas,value,CO2:CO2_landuse)
# plot_data_nogwp <- plot_data_nogwp %>% 
#   mutate(gas=ifelse(gas=="CO2","CO2 FFI",gas)) %>% 
#   mutate(gas=ifelse(gas=="CO2_landuse","CO2 Land use",gas))
# 
# 
# 
# # Normalise to 1990?
# plot_data_nogwp <- plot_data_nogwp %>%
#   filter(year>1969) %>% 
#   group_by(gas) %>%
#   mutate(value=value/(value[year==1990]))
# 
# # calculate error range
# plot_data_nogwp <- left_join(plot_data_nogwp,uncertainties,by = "gas")
# 
# plot_data_nogwp <- plot_data_nogwp %>% 
#   mutate(high = value+((uncertainty*value))) %>% 
#   mutate(low = value-((uncertainty*value))) %>% 
#   select(-uncertainty)
# 
# #manually map colours
# plot_data_nogwp$gas <- as.factor(plot_data_nogwp$gas)
# plot_data_nogwp$gas <- factor(plot_data_nogwp$gas,levels=levels(plot_data_nogwp$gas)[c(2,3,1,4)])
# colours = c("#a6d854","#e78ac3","#8da0cb","#fc8d62")
# 
# 
# p_gas_trends <- plot_data_nogwp %>%
#   ggplot(.,aes(x=year,y=value)) +
#   geom_line(aes(color=gas)) +
#   geom_ribbon(data=plot_data_nogwp,aes(ymin=low,ymax=high,fill=gas),alpha=0.3)+
#   scale_x_continuous(breaks=c(1980,1995,2010)) +
#   scale_fill_manual(values=colours) +
#   scale_color_manual(values=colours) +
#   theme_bw() +
#   ylab(str_wrap('Emissions (original units, noramlised to 1990)',width=26)) +
#   facet_wrap(.~gas,nrow=1) +
#   theme(legend.position = "none",
#         axis.title.x = element_blank(),
#         axis.title.y = element_text(margin=margin(0,10,0,0)),
#         text = element_text(size=11),
#         panel.grid.minor.x = element_blank(),
#         panel.grid.minor.y = element_blank())
# 
# p_gas_trends
# 
# 
# openxlsx::addWorksheet(wb,"gas_trend_normalised")
# openxlsx::writeData(wb, sheet = "gas_trend_normalised", plot_data_nogwp, colNames = T, rowNames = F)

```

```{r country_changes,echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=6}

## CRF data
crf_data<-read_csv("../../Data/supplemetary data/Guetschow-et-al-2021-PRIMAP-crf96_2021-v1.csv")

crf_total_sector<-crf_data %>%
  filter(`category (IPCC1996)`=="M.0.EL") %>%  #excludes LULUCF
  mutate(unit1=substring(unit,1,1))

crf_methane_adjustment<-crf_data %>%
  filter(entity=="CH4") %>%
  filter(`category (IPCC1996)` %in% c("1.B.2","2.C.2","2.B.5"))

match<-openxlsx::read.xlsx("C:/Users/doen/Documents/IPCC data/PRIMAP_gases_matching.xlsx") %>%
  select(-Description.PRIMAP)

match$Code.PRIMAP<-gsub(" ","",match$Code.PRIMAP)

gwps<-left_join(match,gwps,by=c("Code.gwps"="gas")) %>%
  select(Code.PRIMAP,Code.gwps,gwp_ar5,gwp_ar6)

gwps[1,4]<-27.2 #we first use the factor 27.2 for all CH4 and adjust in a second step

crf_total_sector<-left_join(crf_total_sector,gwps,by=c("entity"="Code.PRIMAP"))

crf_total_sector<-crf_total_sector %>%
  filter(`area (ISO3)`!="EU27BX") %>%
  filter(`area (ISO3)`!="EU28") %>%
  filter(!is.na(gwp_ar6))

crf_total_sector<-gather(crf_total_sector,key = "year", value = "value", "1986":"2019") %>%
  mutate(value=ifelse(unit1=="k",value/1e6,value/1e9)) %>%   #transforming kt to Gt
  mutate(unit="Gt") %>%
  select(-unit1) %>%
  mutate(year=as.numeric(year))

crf_total_sector<-crf_total_sector %>% 
  #mutate(GHG_crf=value*gwp_ar6) %>%
  mutate(GHG_crf=value*gwp_ar5) %>%
  select(-gwp_ar5,-gwp_ar6,-Code.gwps)

##adjusting for fugitive methane
crf_methane_adjustment<-gather(crf_methane_adjustment,key = "year", value = "value", "1986":"2019") %>%
  mutate(value=value/1e6) %>%   #transforming kt to Gt
  mutate(unit="Gt") %>%
  mutate(year=as.numeric(year)) %>%
  #mutate(GHG_crf=value*(29.8-27.2))          #in the first step all methane emissions were factored by 27.2; for those sectors, where the higher factor of 29.8 should be used, this is added
  mutate(GHG_crf=value*(30-28))
  
crf_total_sector<-rbind(crf_total_sector,crf_methane_adjustment)

crf_total_sector<-crf_total_sector %>%
  group_by(`area (ISO3)`,year) %>%
  summarise(GHG_crf=sum(GHG_crf,na.rm = TRUE))

## get country level data

time_start=2010

countries <- edgar_ghg %>% 
  filter(region_ar6_6_short!="AIR") %>% 
  filter(region_ar6_6_short!="SEA") %>% 
  filter(year>=time_start & year<=2019) %>% 
  group_by(country,ISO,year,region_ar6_6_short) %>% 
  summarise_at(vars(CH4:GHG),sum,na.rm=TRUE) %>% 
  mutate_at(vars(CH4:GHG),list(~./1e9)) %>%
  ungroup() %>%
  mutate(region_ar6_6_short=as.character(region_ar6_6_short))

# what is 75% of the emissions?
threshold <- countries %>%
  filter(year==2019)
threshold <- sum(threshold$GHG,na.rm=T)*0.75
large_emitters<- countries %>% 
  ungroup() %>% 
  filter(year==2019) %>%
  arrange(desc(GHG)) %>% 
  mutate(cumulative_GHG=cumsum(GHG)) %>% 
  filter(cumulative_GHG<threshold) %>%
  select(country)

countries<-gather(countries,value = value,key = gas,CH4:Fgas)

countries<-left_join(countries,crf_total_sector,by=c("ISO"="area (ISO3)","year"="year"))

countries <- countries %>% 
  filter(year %in% c(time_start,2019)) %>% 
  group_by(country,gas) %>% 
  mutate(avg_growth=(last(value)/first(value))^(1/(last(year)-time_start))-1) %>% 
  mutate(abs_growth=last(value)-first(value)) %>%
  mutate(avg_ghg_growth=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
  mutate(abs_ghg_growth=last(GHG)-first(GHG)) %>%
  mutate(avg_ghg_growth_crf=(last(GHG_crf)/first(GHG_crf))^(1/(last(year)-time_start))-1) %>% 
  mutate(abs_ghg_growth_crf=last(GHG_crf)-first(GHG_crf)) %>%
  filter(year==2019) %>% 
  mutate(avg_growth=avg_growth*100)%>% 
  mutate(avg_ghg_growth=avg_ghg_growth*100)%>%
  mutate(avg_ghg_growth_crf=avg_ghg_growth_crf*100)


countries$gas <- as.factor(countries$gas)
countries$gas<-factor(countries$gas,levels(countries$gas)[c(2,1,4,3)])
colours = c("#a6d854","#8da0cb","#fc8d62","#e78ac3")


plot_theme <- theme_bw() +
  theme(axis.title.y = element_blank(),
        plot.title = element_text(size = 11,color="#252525"),
        axis.title = element_text(color="#525252"),
        panel.grid.minor.x = element_blank(),
        legend.position="none",
        text = element_text(size=11),
        plot.background = element_blank())

#rate
p_countries_rate <- countries %>%
  filter(country %in% large_emitters$country) %>% 
  filter(gas=="CO2") %>%
  ggplot(.,aes(x = reorder(country,avg_ghg_growth)))+
  geom_bar(aes(y = avg_ghg_growth),stat='identity',colour="#525252")+
  geom_point(aes(y = avg_ghg_growth_crf),stat='identity',colour="#525252",fill="yellow",size=2,shape=21)+
  coord_flip() +
  plot_theme +
  ylab("%") +
  ggtitle(str_wrap("b. Avg. annual GHG emissions growth",width=38)) +
  annotate(geom = 'text', label = 'Years: 2010-2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.4,size=3.5,color="#525252")

#absolute
p_countries_abs <- countries %>% 
  filter(country %in% large_emitters$country) %>% 
  ggplot(.,aes(x = reorder(country,abs_ghg_growth),y = abs_growth))+
  geom_bar(aes(fill=gas),position='stack',stat='identity',colour="#525252")+
  scale_fill_manual(values=colours) +
  geom_point(aes(y = abs_ghg_growth_crf),stat='identity',colour="#525252",fill="yellow",size=2,shape=21)+
  coord_flip() +
  plot_theme +
  ylab("Gt CO2eq") +
  ggtitle(str_wrap("c. Absolute GHG emissions growth",width=35)) +
    annotate(geom = 'text', label = 'Years: 2010-2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#525252")


openxlsx::addWorksheet(wb,"countries_2019")
openxlsx::writeData(wb, sheet = "countries_2019", countries, colNames = T, rowNames = F)


```

```{r sector_changes,echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=6}

time_start=2010

## get country level data

sectors <- edgar_ghg %>% 
 # filter(region_ar6_6_short!="AIR") %>% 
#  filter(region_ar6_6_short!="SEA") %>% 
  filter(year>=time_start & year<=2019) %>% 
  group_by(year,chapter,chapter_title,subsector,subsector_title) %>% 
  summarise_at(vars(CH4:GHG),sum,na.rm=TRUE) %>% 
  mutate_at(vars(CH4:GHG),list(~./1e9)) %>%
  mutate(CO2_land=NA,CO2_indirect=NA) %>% 
  ungroup()

land <- land %>%
  filter(year>=time_start) %>% 
  filter(year<=2019) %>% 
  mutate(chapter=7) %>% 
  mutate(chapter_title="AFOLU") %>% 
  mutate(subsector=7.7) %>% 
  mutate(subsector_title="Land-use (CO2)") %>% 
  select(region_ar6_10,year,chapter,chapter_title,subsector,subsector_title,value=mean)

land_totals <- land %>%
  group_by(year,chapter,chapter_title,subsector,subsector_title) %>%
  summarise(GHG=sum(value,na.rm=TRUE)) %>%
  mutate(GHG=GHG/1e9)

land_totals <- land_totals %>%
  ungroup() %>% 
  mutate(CO2_land=GHG) %>% 
  mutate(CO2=NA,CH4=NA,N2O=NA,Fgas=NA,CO2_indirect=NA) %>% 
  select(year,chapter,chapter_title,subsector,subsector_title,CH4,CO2,N2O,Fgas,GHG,CO2_land,CO2_indirect)

sectors <- rbind(sectors,land_totals)
sectors <- sectors %>%
  group_by(year,chapter,chapter_title,subsector,subsector_title) %>%
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG,CO2_land,CO2_indirect),sum,na.rm=TRUE)

# subsector_ghg_data <- subsector_data
# subsector_data <- subsector_data %>% 
#   select(year,chapter,chapter_title,subsector,subsector_title,GHG)

# what is 90% of the emissions?
threshold <- sectors %>%
  filter(year==2019)
threshold <- sum(threshold$GHG,na.rm=T)*0.9
large_emitters<- sectors %>% 
  ungroup() %>% 
  filter(year==2019) %>%
  arrange(desc(GHG)) %>% 
  mutate(cumulative_GHG=cumsum(GHG)) %>% 
  filter(cumulative_GHG<threshold) %>%
  select(subsector)

sectors<-gather(sectors,value = value,key = gas,c(CO2,CH4,N2O,Fgas,CO2_land,CO2_indirect))

sectors <- sectors %>% 
  filter(year %in% c(time_start,2019)) %>% 
  group_by(subsector,subsector_title,gas) %>% 
  mutate(avg_growth=(last(value)/first(value))^(1/(last(year)-time_start))-1) %>% 
  mutate(abs_growth=last(value)-first(value)) %>%
  mutate(avg_ghg_growth=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
  mutate(abs_ghg_growth=last(GHG)-first(GHG)) %>%
  filter(year==2019) %>% 
  mutate(avg_growth=avg_growth*100) %>% 
  mutate(avg_ghg_growth=avg_ghg_growth*100)


sectors$gas <- as.factor(sectors$gas)
sectors$gas<-factor(sectors$gas,levels(sectors$gas)[c(2,4,1,6,5)])
# colours = c("#a6d854","#e78ac3","#8da0cb","#fc8d62","#66c2a5")
colours = c("#a6d854","#66c2a5","#8da0cb","#fc8d62","#e78ac3")

plot_theme <- theme_bw() +
  theme(axis.title.y = element_blank(),
        plot.title = element_text(size = 11,color="#252525"),
        axis.title = element_text(color="#525252"),
        panel.grid.minor.x = element_blank(),
        legend.position="none",
        text = element_text(size=11),
        plot.background = element_blank())

#rate
p_sectors_rate <- sectors %>%
  filter(subsector %in% large_emitters$subsector) %>% 
  filter(gas=="CO2") %>%
  ggplot(.,aes(x = reorder(subsector_title,avg_ghg_growth)))+
  geom_bar(aes(y = avg_ghg_growth),stat='identity',colour="#525252")+
  coord_flip() +
  plot_theme +
  ylab("%") +
  ggtitle(str_wrap("d. Avg. annual GHG emissions growth",width=38)) +
  annotate(geom = 'text', label = 'Years: 2010-2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.4,size=3.5,color="#525252")

#absolute
p_sectors_abs <- sectors %>% 
  filter(subsector %in% large_emitters$subsector) %>% 
  ggplot(.,aes(x = reorder(subsector_title,abs_ghg_growth),y = abs_growth))+
  geom_bar(aes(fill=gas),position='stack',stat='identity',colour="#525252")+
  scale_fill_manual(values=colours) +
  coord_flip() +
  plot_theme +
  ylab("Gt CO2eq") +
  ggtitle(str_wrap("e. Absolute GHG emissions growth",width=35)) +
    annotate(geom = 'text', label = 'Years: 2010-2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#525252")

#sectors<- sectors %>%
#  pivot_wider(key=year,values_from)

openxlsx::addWorksheet(wb,"sectors_2019")
openxlsx::writeData(wb, sheet = "sectors_2019", sectors, colNames = T, rowNames = F)


```

```{r gas_trends_spm, echo=FALSE,warning=FALSE,fig.width=10,fig.height=12,fig.path="Results/Plots/",dev=c('png','pdf')}


#########

# p_countries<-ggarrange(p_countries_rate, p_countries_abs,ncol=2,align = "v")
# p_sectors<-ggarrange(p_sectors_rate, p_sectors_abs,ncol=2,align = "v")
# p_contibutors<-ggarrange(p_countries,p_sectors,nrow=2,align = "h")

p_rate<-ggarrange(p_countries_rate, p_sectors_rate,ncol=1,align = "v")
p_abs<-ggarrange(p_countries_abs, p_sectors_abs,ncol=1,align = "v")

#(p_gas_totals + p_waterfall + plot_layout(width = c(3, 1))) / p_gas_trends + plot_layout(height = c(3,1))
#(p_gas_totals + p_waterfall + plot_layout(width = c(3, 1))) / (p_countries_rate + p_countries_abs) /(p_sectors_rate + p_sectors_abs) /p_gas_trends + plot_layout(height = c(3,2,2,1))
#(p_gas_totals + p_waterfall + plot_layout(width = c(3, 1))) / p_contibutors /p_gas_trends + plot_layout(height = c(3,4,1))
(p_gas_totals + p_waterfall + plot_layout(width = c(3, 1))) / (p_rate + p_abs) + plot_layout(height = c(3,5))

##### write data

#Sys.Date()))

openxlsx::addWorksheet(wb,"gas_trend")
openxlsx::writeData(wb, sheet = "gas_trend", spread(plot_data,year,value), colNames = T, rowNames = F)

openxlsx::saveWorkbook(wb,paste0("Results/Data/ipcc_ar6_gas_data_",Sys.Date(),".xlsx"),overwrite=T)

```

```{r ghg_growth, echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=0.1}

## calculate average annual and absolute growth

time_start <- 1990

growth_data <- plot_data %>%                                                                         #plot_data reused from gas_trend chart
  filter(year %in% c(time_start,2019)) %>% 
  group_by(gas) %>% 
  mutate(avg_growth=(last(value)/first(value))^(1/(last(year)-time_start))-1) %>% 
  mutate(abs_growth=last(value)-first(value)) %>%
  filter(year==2019) %>% 
  mutate(avg_growth=avg_growth*100)


#countries <- gather(countries,var,value,avg_growth,abs_growth,emissions_pc,emissions_pgdp)


plot_theme <- theme_bw() +
  theme(axis.title.y = element_blank(),
        plot.title = element_text(size = 11,color="#252525"),
        axis.title = element_text(color="#525252"),
        panel.grid.minor.x = element_blank(),
        legend.position="none",
        text = element_text(size=11),
        plot.background = element_blank())


#rate
p2 <- growth_data %>% 
  #filter(var=="avg_growth") %>% 
  ggplot(.,aes(x = gas,y = avg_growth, fill=gas)) +
  geom_bar(stat='identity',colour="#525252") + 
  coord_flip() +
  plot_theme +
  ylab("%") +
  ggtitle(str_wrap("b. Avg. annual GHG emissions growth",width=38)) +
  annotate(geom = 'text', label = 'Years: 1990-2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.4,size=3.5,color="#525252")

#absolute
p3 <- growth_data %>% 
  #filter(var=="abs_growth") %>% 
  ggplot(.,aes(x = gas,y = abs_growth, fill=gas)) +
  geom_bar(stat='identity',colour="#737373") + 
  coord_flip() +
  plot_theme +
  ylab("Gt CO2eq") +
  ggtitle(str_wrap("c. Absolute GHG emissions growth",width=35)) +
    annotate(geom = 'text', label = 'Years: 1990-2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#525252")
```
```{r regions_countries,echo=FALSE,warning=FALSE,fig.width=8,fig.height=10,fig.path="Results/Plots/",dev=c('png','pdf')}

(p2 + p3)# + plot_layout(nrow=1,heights = c(1/3,1/3))


```