---
title: "emissions_by_sector_maps"
output: word_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "Results") })
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(patchwork)
library(ggmap)
library(maps)
library(ggplot2); theme_set(theme_bw())
library(scales)

source("../Analysis and figures/small_figures.R")


load('../../Data/edgar6_data_ghg_gwp_ar5.RData')
load('../../Data/gwps.RData')
load("../../Data/land.RData")
load('../../Data/WDI_gdp_pop.RData')


isos <- openxlsx::read.xlsx("../../Data/Codes and classifications/ISOcodes.xlsx","alternative_names")

# set palette
ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2")

wb <- openxlsx::createWorkbook(title = paste("ipcc_ar6_sector_map_data_",Sys.Date()))

```


```{r data, include=FALSE,echo=FALSE}


mapdata <- edgar_ghg %>% 
  filter(year>1969) %>% 
  group_by(country,ISO,year,chapter_title) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE))

mapdata <- left_join(mapdata,wdi_data_gdp_pop,by=c("ISO"="iso3c","year"="year"))

mapdata <- mapdata %>% 
  mutate(GHGpc=GHG/population) %>% 
  filter(population>1e6)

## calculate average annual and absolute growth

time_start=1990
mapdata_1990 <- mapdata %>% 
  filter(year %in% c(time_start,2019)) %>% 
  group_by(country,ISO,chapter_title) %>% 
  mutate(avg_growth_1990=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
  filter(year==2019) %>% 
  mutate(avg_growth_1990=avg_growth_1990*100) %>% 
  select(country,ISO,chapter_title,avg_growth_1990)

time_start=2010
mapdata_2010 <- mapdata %>% 
  filter(year %in% c(time_start,2019)) %>% 
  group_by(country,ISO,chapter_title) %>% 
  mutate(avg_growth_2010=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
  filter(year==2019) %>% 
  mutate(avg_growth_2010=avg_growth_2010*100) %>% 
  select(country,ISO,chapter_title,avg_growth_2010)

mapdata <- mapdata %>% filter(year==2019)
mapdata <- left_join(mapdata,mapdata_1990,by = c("country", "ISO", "chapter_title"))
mapdata <- left_join(mapdata,mapdata_2010,by = c("country", "ISO", "chapter_title"))

world <- map_data("world") %>% 
  filter(region!="Antarctica")
world <- left_join(world %>% mutate(region=tolower(region)),isos,by=c("region"="alternative.name"))
world <- left_join(world,mapdata,by=c("alpha.3"="ISO"))

##save data
openxlsx::addWorksheet(wb,"secor_growth_rates")
openxlsx::writeData(wb, sheet = "secor_growth_rates", mapdata, colNames = T, rowNames = F)

openxlsx::saveWorkbook(wb,paste0("Results/Data/ipcc_ar6_sector_map_data_",Sys.Date(),".xlsx"),overwrite=T)

```

```{r map_subplots,include=FALSE,echo=FALSE,fig.width=6,fig.height=3}

#Energy systems
## per capita
p1_energy <- ggplot() + 
  geom_polygon(data = world %>% filter(chapter_title=="Energy systems"),aes(x=long, y = lat, group=group, fill=GHGpc),color="white",size=0.25,na.rm=T) + 
  #scale_fill_viridis_c(limits = c(0,15)) +
  #scale_fill_viridis_c() +
   scale_fill_gradient2(low = 'midnightblue',mid = "white",high = "darkred",midpoint=0) +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.05,0.3),
        legend.background = element_blank(),
        legend.title = element_blank(),
        legend.key.size = unit(0.5,"cm"),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0,0),units="cm"),
        plot.title = element_text(size=10)) +
  ggtitle("a. GHG emissions per capita in the Energy sector in 2019")
p1_energy

## growth 1990-2019
p2_energy <- ggplot() + 
  geom_polygon(data = world %>% filter(chapter_title=="Energy systems"), aes(x=long, y = lat, group=group, fill=avg_growth_1990),color="white",size=0.25,na.rm=T) + 
  #scale_fill_viridis_c() +
   scale_fill_gradient2(low = 'midnightblue',mid = "white",high = "darkred",midpoint=0) +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.05,0.3),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0,0),units="cm"),
        plot.title = element_text(size=10)) +
  ggtitle("b. Average annual GHG emissions growth in the Energy sector (1990-2019)")
p2_energy


#Industry
## per capita
p1_industry <- ggplot() + 
  geom_polygon(data = world %>% filter(chapter_title=="Industry"), aes(x=long, y = lat, group=group, fill=GHGpc),color="white",size=0.25,na.rm=T) + 
  #scale_fill_viridis_c(limits = c(0,15)) +
  #scale_fill_viridis_c() +
   scale_fill_gradient2(low = 'midnightblue',mid = "white",high = "darkred",midpoint=0) +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.05,0.3),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0,0),units="cm"),
        plot.title = element_text(size=10)) +
  ggtitle("c. GHG emissions per capita in the Industry in 2019")
p1_industry

## growth 1990-2019
p2_industry <- ggplot() + 
  geom_polygon(data = world %>% filter(chapter_title=="Industry"), aes(x=long, y = lat, group=group, fill=avg_growth_1990),color="white",size=0.25,na.rm=T) + 
  #scale_fill_viridis_c() +
   scale_fill_gradient2(low = 'midnightblue',mid = "white",high = "darkred",midpoint=0) +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.05,0.3),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0,0),units="cm"),
        plot.title = element_text(size=10)) +
  ggtitle("d. Average annual GHG emissions growth in the Industry (1990-2019)")
p2_industry

#Buildings
## per capita
p1_buildings <- ggplot() + 
  geom_polygon(data = world %>% filter(chapter_title=="Buildings"), aes(x=long, y = lat, group=group, fill=GHGpc),color="white",size=0.25,na.rm=T) + 
  #scale_fill_viridis_c(limits = c(0,15)) +
  #scale_fill_viridis_c() +
   scale_fill_gradient2(low = 'midnightblue',mid = "white",high = "darkred",midpoint=0) +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.05,0.3),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0,0),units="cm"),
        plot.title = element_text(size=10)) +
  ggtitle("e. GHG emissions per capita in the Buildings sector in 2019")
p1_buildings

## growth 1990-2019
p2_buildings <- ggplot() + 
  geom_polygon(data = world %>% filter(chapter_title=="Buildings"), aes(x=long, y = lat, group=group, fill=avg_growth_1990),color="white",size=0.25,na.rm=T) + 
   scale_fill_gradient2(low = 'midnightblue',mid = "white",high = "darkred",midpoint=0) +
  #scale_fill_viridis_c() +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.05,0.3),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0,0),units="cm"),
        plot.title = element_text(size=10)) +
  ggtitle("f. Average annual GHG emissions growth in the Buildings sector (1990-2019)")
p2_buildings

#Transport
## per capita
p1_transport <- ggplot() + 
  geom_polygon(data = world %>% filter(chapter_title=="Transport"), aes(x=long, y = lat, group=group, fill=GHGpc),color="white",size=0.25,na.rm=T) + 
   scale_fill_gradient2(low = 'midnightblue',mid = "white",high = "darkred",midpoint=0) +
  #scale_fill_viridis_c(limits = c(0,15)) +
  #scale_fill_viridis_c() +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.05,0.3),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0,0),units="cm"),
        plot.title = element_text(size=10)) +
  ggtitle("g. GHG emissions per capita in the Transport sector in 2019")
p1_transport

## growth 1990-2019
p2_transport <- ggplot() + 
  geom_polygon(data = world %>% filter(chapter_title=="Transport"), aes(x=long, y = lat, group=group, fill=avg_growth_1990),color="white",size=0.25,na.rm=T) + 
  scale_fill_gradient2(low = 'midnightblue',mid = "white",high = "darkred",midpoint=0) +
  #scale_fill_viridis_c() +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.05,0.3),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0,0),units="cm"),
        plot.title = element_text(size=10)) +
  ggtitle("h. Average annual GHG emissions growth in the Transport sector (1990-2019)")
p2_transport

#AFOLU
## per capita
p1_afolu <- ggplot() + 
  geom_polygon(data = world %>% filter(chapter_title=="AFOLU"), aes(x=long, y = lat, group=group, fill=GHGpc),color="white",size=0.25,na.rm=T) + 
  #scale_fill_viridis_c(limits = c(0,15)) +
  #scale_fill_viridis_c() +
  scale_fill_gradient2(low = 'midnightblue',mid = "white",high = "darkred",midpoint=0) +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.05,0.3),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0,0),units="cm"),
        plot.title = element_text(size=10)) +
  ggtitle("i. GHG emissions per capita in AFOLU in 2019")
p1_afolu

## growth 1990-2019
p2_afolu <- ggplot() + 
  geom_polygon(data = world %>% filter(chapter_title=="AFOLU"), aes(x=long, y = lat, group=group, fill=avg_growth_1990),color="white",size=0.25,na.rm=T) + 
  #scale_fill_gradient2() +
  scale_fill_gradient2(low = 'midnightblue',mid = "white",high = "darkred",midpoint=0) +
  theme(panel.border = element_rect(colour = "black",fill=NA),
        legend.position = c(0.05,0.3),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.margin = unit(c(0,0,0,0),units="cm"),
        plot.title = element_text(size=10)) +
  ggtitle("j. Average annual GHG emissions growth in AFOLU (1990-2019)")
p2_afolu

```

```{r maps,echo=FALSE,fig.width=6,fig.height=8,results='asis',fig.path="Results/Plots/",dev=c('png','pdf')}

(p1_energy+p2_energy) / (p1_industry+p2_industry) / (p1_transport+p2_transport) / (p1_buildings+p2_buildings) / (p1_afolu+p2_afolu)

```
