---
title: "calculate_uncertainties"
output: word_document
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(openxlsx)
library(patchwork)
library(zoo)

knitr::opts_chunk$set(echo = FALSE,warning=FALSE)
options(dplyr.summarise.inform = FALSE)


load('../../Data/edgar6_data_raw.RData')
load('../../Data/edgar6_data_ghg_gwp_ar5.RData')
load('../../Data/land.RData')
load('../../Data/gwps.Rdata')
land <- land %>% 
  filter(year>1969) %>%
  group_by(year) %>% 
  summarise(value=sum(mean,na.rm=TRUE)) %>% 
  mutate(gas="CO2 Land use")


uncertainties <- data.frame(gas=c('CO2 FFI','CO2 Land use','CH4','N2O','Fgas','GHG'),
                            uncertainty_gas=c(0.08,0.5,0.2,0.6,0.2,0.1))

```


```{r uncertainties}

gases <- edgar_raw %>%  
  group_by(year,gas,gwp100_ar5) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>%
  mutate(gas=as.character(gas)) %>% 
  mutate(gas=ifelse(gas=="CO2","CO2 FFI",gas))

gases <- rbind(gases,land)
gases <- gases %>% 
  mutate(gwp100_ar5=ifelse(gas=="CO2 Land use",1,gwp100_ar5)) %>% 
  mutate(value_gwp=value*gwp100_ar5)

gases <- left_join(gases,uncertainties,by="gas")

gases <- gases %>% 
  mutate(uncertainty_gas=ifelse(is.na(uncertainty_gas),0.2,uncertainty_gas))

gases <- left_join(gases,gwps %>% select(gas,lifetime),by="gas")

gases <- gases %>% 
  mutate(uncertainty_gwp=ifelse(lifetime<20,0.5,0.4)) %>% 
  mutate(uncertainty_gwp=ifelse(gas=="CO2 FFI",0,uncertainty_gwp)) %>% 
  mutate(uncertainty_gwp=ifelse(gas=="CO2 Land use",0,uncertainty_gwp))

gases <- gases %>% 
  mutate(total_uncertainty=sqrt(uncertainty_gas^2 + uncertainty_gwp^2)) %>% 
  mutate(`+/-`=total_uncertainty*value_gwp) %>% 
  filter(year==2018) %>% 
  arrange(desc(value_gwp))


write.xlsx(gases,"../../Results/Data/Analysis/aggregate_uncertainty.xlsx")

```

