---
title: "decarbonising_countries_data"
author: "William F. Lamb"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  word_document:
    toc: yes
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results") })
  
---

```{r setup,include=FALSE}

rm(list = ls())
library(tidyverse); options(dplyr.summarise.inform = FALSE)
library(ggpubr)
library(ggplot2); theme_set(theme_bw())
library(zoo)
library(cluster)
library(ggmap)
library(maps)
library(patchwork)
library(openxlsx)

load('../../Data/WDI_gdp_pop.RData')
load("../../Data/dump/edgar_data_gwp_ar5_late_2020.RData")
#load('../../Data/edgar6_v5_data_ghg_gwp_ar6.RData')
# edgar_GHG_ar6 <- edgar_ghg %>% filter(year<2020)
edgar_GHG_ar6 <- edgar_GHG_ar6 %>%
  mutate(country=ifelse(country=="Macedonia, FYR","North Macedonia",country)) %>%
  mutate(country=ifelse(country=="Slovak Republic","Slovakia",country))

source("growth_rate.R")
source("small_figures.R")


isos <- openxlsx::read.xlsx("C:/Users/lamw/ownCloud/Projects/Code/R/.Place names and codes/output/ISOcodes.xlsx","alternative_names")

colours_sectors <- c(`AFOLU` = "#66c2a5",
                     `Buildings` = "#fc8d62",
                     `Energy systems` = "#8da0cb",
                     `Industry` = "#e78ac3",
                     `Transport` = "#a6d854")

wb <- openxlsx::createWorkbook(title = paste("decarbonising_countries"))
openxlsx::addWorksheet(wb,"info")

info = data.frame(x=c("Title","Author","Date","Code"),y=c("Analysis of countries with sustained GHG emissions reductions","William F. Lamb (lamb@mcc-berlin.net)",paste(Sys.Date()),"https://github.com/mcc-apsis/AR6-Emissions-trends-and-drivers/blob/master/R/Analysis%20and%20figures/decarbonising_countries.Rmd"))

openxlsx::writeData(wb, sheet = "info", info, colNames = F, rowNames = F)

# change AFOLU to agriculture
edgar_GHG_ar6$chapter_title <- gsub("AFOLU","Agriculture",edgar_GHG_ar6$chapter_title)


```

```{r thingforMichael,echo=FALSE,warning=FALSE,include=FALSE}

# 
# data <- edgar_GHG_ar6 %>%
#   filter(region_ar6_dev=="developed") %>% 
#   filter(year %in% c(2010,2018)) %>% 
#   group_by(ISO,country,year) %>% 
#   summarise_at(vars(CO2,GHG),sum,na.rm=TRUE)
# 
# data <- data %>% 
#   group_by(country) %>% 
#   mutate(rel_CO2=(first(CO2)-last(CO2))/first(CO2)) %>% 
#   mutate(rel_GHG=(first(GHG)-last(GHG))/first(GHG))
# 
# 
# data <- data %>% 
#   filter(rel_CO2>0)
# 
# openxlsx::write.xlsx(data,"countries.xlsx")
#

```

```{r calculate_rates_2005,echo=FALSE,warning=FALSE,include=FALSE}


## gather data

# data <- edgar_GHG_ar6 %>% 
#   group_by(ISO,country,year,region_ar6_10) %>% 
#   summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE)
# 
# ## join population and GDP data
# 
# 
# data <- left_join(data,wdi_data_gdp_pop,by=c("ISO"="iso3c","year"="year"))
# 
# ## filter to countries above 1m population
# 
# data <- data %>% 
#   group_by(country) %>% 
#   mutate(include=ifelse(max(population)>1e6,1,0)) %>% 
#   ungroup() %>% 
#   filter(include==1) %>% 
#   select(-include)
# 
# ## filter to 2005-2018
# 
# data <- data %>% 
#   filter(year>=2005)
# 
# 
# ## calculate GHG growth
# 
# rates_GHG <- data %>% filter(country=="nothing") # create empty dataframe
# 
# for (i in 1:length(unique(data$country))) {
#   
#   temp_data <- data %>% 
#     filter(country==unique(data$country)[i])
#   
#   rates <- growth_rate(temp_data$year,temp_data$GHG)
#   
#   temp_data$rate_GHG_peak <- rates$rate*100
#   temp_data$fit <- rates$data$predicted_x
#   temp_data$st_error <- rates$data$st_error
#   
#   rates_GHG <- rbind(rates_GHG,temp_data)
# }
# 
# rates_GHG <- rates_GHG %>% 
#   filter(year==2018)

```

```{r calculate_rates,echo=FALSE,warning=FALSE,include=FALSE}

## gather data

data <- edgar_GHG_ar6 %>% 
  group_by(ISO,country,year,region_ar6_10) %>% 
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE)

## join population and GDP data

data <- left_join(data,wdi_data_gdp_pop,by=c("ISO"="iso3c","year"="year"))

## filter to countries above 1m population

data <- data %>% 
  group_by(country) %>% 
  mutate(include=ifelse(max(population)>1e6,1,0)) %>% 
  ungroup() %>% 
  filter(include==1) %>% 
  select(-include)


## find peak year CO2, excluding years after 2009

peak_years_CO2 <- data %>% 
  filter(year<2009) %>% 
  group_by(country) %>% 
  summarise(peak_year_CO2=year[which.max(CO2)])

## find peak year GHG, excluding years after 2009

peak_years_GHG <- data %>% 
  filter(year<2009) %>% 
  group_by(country) %>% 
  summarise(peak_year_GHG=year[which.max(GHG)])

peak_years <- left_join(peak_years_CO2,peak_years_GHG,by = "country")
peak_years <- peak_years %>% 
  select(country,peak_year=peak_year_CO2)

data <- left_join(data,peak_years,by = "country")


## calculate CO2 growth since peak year

rates_CO2 <- data %>% filter(country=="nothing") # create empty dataframe

for (i in 1:length(unique(data$country))) {
  
  temp_data <- data %>% 
    filter(country==unique(data$country)[i])
  
  temp_data <- temp_data %>% 
    filter(year>=temp_data$peak_year[1])
  
  rates <- growth_rate(temp_data$year,temp_data$CO2)
  
  temp_data$rate_CO2_peak <- rates$rate
  temp_data$fit_CO2 <- rates$data$predicted_x
  temp_data$st_error <- rates$data$st_error
  
  rates_CO2 <- rbind(rates_CO2,temp_data)
}

#rejoin with full data

data <- left_join(data,rates_CO2 %>% select(country,year,rate_CO2_peak,fit_CO2),by = c("country", "year"))

data <- data %>% 
  group_by(country) %>% 
  mutate(rate_CO2_peak=na.locf(rate_CO2_peak,fromLast=TRUE))


## now do the same for GHG emissions

rates_GHG <- data %>% 
  filter(country=="nothing") %>%  # create empty dataframe 
  select(-fit_CO2,-rate_CO2_peak)

for (i in 1:length(unique(data$country))) {
  
  temp_data <- data %>% 
    filter(country==unique(data$country)[i])
  
  temp_data <- temp_data %>% 
    filter(year>=temp_data$peak_year[1])
  
  rates <- growth_rate(temp_data$year,temp_data$GHG)
  
  temp_data$rate_GHG_peak <- rates$rate
  temp_data$fit_GHG <- rates$data$predicted_x
  temp_data$st_error <- rates$data$st_error
  
  rates_GHG <- rbind(rates_GHG,temp_data)
}


#rejoin with full data

data <- left_join(data,rates_GHG %>% select(country,year,rate_GHG_peak,fit_GHG),by = c("country", "year"))

data <- data %>% 
  group_by(country) %>% 
  mutate(rate_GHG_peak=na.locf(rate_GHG_peak,fromLast=TRUE))



```

```{r calculate_rates_2008,echo=FALSE,warning=FALSE,include=FALSE}

rates_GHG_2008 <- data %>% filter(country=="nothing") # create empty dataframe

for (i in 1:length(unique(data$country))) {
  
  temp_data <- data %>%
    filter(country==unique(data$country)[i]) %>% 
    filter(year>2007)
  
  rates <- growth_rate(temp_data$year,temp_data$GHG)
  
  temp_data$rate_GHG_2008 <- rates$rate*100
  
  rates_GHG_2008 <- rbind(rates_GHG_2008,temp_data)
}

rates_GHG_2008 <- rates_GHG_2008 %>%
  filter(year==2018) %>% 
  select(country,rate_GHG_2008)

#rejoin with full data

data <- left_join(data,rates_GHG_2008,by = c("country"))


```

```{r calculate_rates_1990,echo=FALSE,warning=FALSE,include=FALSE}

rates_GHG_1990 <- data %>% filter(country=="nothing") # create empty dataframe

for (i in 1:length(unique(data$country))) {
  
  temp_data <- data %>%
    filter(country==unique(data$country)[i]) %>% 
    filter(year>1989)
  
  rates <- growth_rate(temp_data$year,temp_data$GHG)
  
  temp_data$rate_GHG_1990 <- rates$rate*100
  
  rates_GHG_1990 <- rbind(rates_GHG_1990,temp_data)
}

rates_GHG_1990 <- rates_GHG_1990 %>%
  filter(year==2018) %>% 
  select(country,rate_GHG_1990)


```

```{r consumption_data_and_rates,echo=FALSE,warning=FALSE,include=FALSE}


cons <- openxlsx::read.xlsx('../../Data/Land and GCB/National_Carbon_Emissions_2020v1.0.xlsx',sheet=3,startRow = 1)
cons[8,1] <- "year"
names(cons) <- cons[8,]
cons <- cons[9:69,]

cons <- gather(cons,country,value,-year)
cons <- cons %>% 
  mutate(value=as.numeric(value)) %>% 
  mutate(value=value*3.664*1e6) %>% 
  mutate(country=tolower(country)) %>% 
  mutate(year=as.numeric(year))

cons <- left_join(cons,isos,by=c("country"="alternative.name"))

data <- left_join(data,cons %>% select(ISO=alpha.3,year,CO2_cons=value),by = c("ISO", "year"))

rates_cons <- data %>% 
  filter(country=="nothing") # create empty dataframe 

for (i in 1:length(unique(data$country))) {
  
  temp_data <- data %>% 
    filter(country==unique(data$country)[i])
  
  temp_data <- temp_data %>% 
    filter(year>=temp_data$peak_year[1])
  
  ### if peak year is before 1990, calculate rate from 1990 (start of cons data)
  if (temp_data$peak_year<1990) {
    
    temp_data <- temp_data %>% 
      filter(year>=1990)
    
  }
  
  ### calculate rates to 2018 only
  
  temp_data <- temp_data %>% 
    filter(year<2019)
  
  ### if there is no cons data, just fill NaNs
  if (is.na(temp_data$CO2_cons[1])==1) {
    
    temp_data$rate_CO2_cons_peak <- NA
    temp_data$fit_CO2_cons <- NA
    temp_data$st_error <- NA
    
  } else {
    
    rates <- growth_rate(temp_data$year,temp_data$CO2_cons)
    
    temp_data$rate_CO2_cons_peak <- rates$rate
    temp_data$fit_CO2_cons <- rates$data$predicted_x
    temp_data$st_error <- rates$data$st_error
    
    rates_cons <- rbind(rates_cons,temp_data)
    
  }
}


#rejoin with full data

data <- left_join(data,rates_cons %>% select(country,year,rate_CO2_cons_peak,fit_CO2_cons),by = c("country", "year"))

data <- data %>% 
  group_by(country) %>% 
  mutate(rate_CO2_cons_peak=na.locf0(rate_CO2_cons_peak,fromLast=FALSE)) %>% 
  mutate(rate_CO2_cons_peak=na.locf0(rate_CO2_cons_peak,fromLast=TRUE)) %>% 
  mutate(rate_CO2_cons_peak=rate_CO2_cons_peak*100) 


```

```{r lulucf_data,echo=FALSE,warning=FALSE,include=FALSE}

load("../../Data/fao_land.RData")

fao_land <- fao_land %>%
  group_by(alpha.3,year) %>% 
  summarise(CO2_land=sum(value,na.rm=TRUE)) %>% 
  select(ISO=alpha.3,year,CO2_land)

data <- left_join(data,fao_land,by=c("ISO","year"))
data <- data %>% ungroup() %>% mutate(GHG_land = GHG+CO2_land)


rates_land <- data %>% 
  filter(country=="nothing") # create empty dataframe 

for (i in 1:length(unique(data$country))) {
  
  temp_data <- data %>% 
    filter(country==unique(data$country)[i])
  
  temp_data <- temp_data %>% 
    filter(year>=temp_data$peak_year[1])
  
  ### if peak year is before 1990, calculate rate from 1990 (start of FAO Land data)
  if (temp_data$peak_year<1990) {
    
    temp_data <- temp_data %>% 
      filter(year>=1990)
    
  }
  ### for countries with peak years before 1992, but no FAO data (FSU countries), calculate rate from 1993
  if (temp_data$peak_year<=1993) {
    if (is.na(temp_data$GHG_land[1])) {
      temp_data <- temp_data %>% 
        filter(year>=1993)
    }
    
  }
  
  ### special exception for Belgium
  if (unique(data$country)[i]=="Belgium") {
      temp_data <- temp_data %>% 
        filter(year>=2000)
  }
  
  
  ### if there is still no land data, just fill NaNs
  if (is.na(temp_data$GHG_land[1])==1) {
    
    temp_data$rate_GHG_land_peak <- NA
    temp_data$fit_GHG_land <- NA
    temp_data$st_error <- NA
    
  } else {
    
    rates <- growth_rate(temp_data$year,temp_data$GHG_land)
    
    temp_data$rate_GHG_land_peak <- rates$rate
    temp_data$fit_GHG_land <- rates$data$predicted_x
    temp_data$st_error <- rates$data$st_error
    
    rates_land <- rbind(rates_land,temp_data)
    
  }
}



#rejoin with full data

data <- left_join(data,rates_land %>% select(country,year,rate_GHG_land_peak,fit_GHG_land),by = c("country", "year"))

data <- data %>% 
  group_by(country) %>% 
  mutate(rate_GHG_land_peak=na.locf0(rate_GHG_land_peak,fromLast=FALSE)) %>% 
  mutate(rate_GHG_land_peak=na.locf0(rate_GHG_land_peak,fromLast=TRUE)) %>% 
  mutate(rate_GHG_land_peak=rate_GHG_land_peak*100) 


```


```{r renaming,echo=FALSE,warning=FALSE,include=FALSE}

data <- data %>% mutate(country=ifelse(country=="Swaziland","Eswatini",country))


```



```{r exclusions,echo=FALSE,warning=FALSE}


# exclude countries with recent major civil conflict or economic decline (Failed State Index Rank lower than 50)



fsi <- openxlsx::read.xlsx('../../Data/supplemetary data/fsi-2019.xlsx')
isos <- openxlsx::read.xlsx("C:/Users/lamw/ownCloud/Projects/Code/R/.Place names and codes/output/ISOcodes.xlsx","alternative_names")
fsi <- left_join(fsi %>% mutate(Country=tolower(Country)),isos,by=c("Country"="alternative.name"))
fsi$Rank <- gsub("st","",fsi$Rank)
fsi$Rank <- gsub("nd","",fsi$Rank)
fsi$Rank <- gsub("rd","",fsi$Rank)
fsi$Rank <- gsub("th","",fsi$Rank)
fsi$Rank <- as.numeric(fsi$Rank)

data <- left_join(data,fsi %>% select(alpha.3,fsi=Total,fsi_rank=Rank),by=c("ISO"="alpha.3"))

excluded <- data

data <- data %>% 
  filter(fsi_rank>50) %>% 
  select(-fsi,-fsi_rank)

# exclude countries with growth rates above or near 0

data <- data %>% 
  mutate(rate_CO2_peak=rate_CO2_peak*100) %>% 
  mutate(rate_GHG_peak=rate_GHG_peak*100) %>% 
  filter(rate_CO2_peak<0)

data <- data %>% 
  filter(abs(rate_CO2_peak) > 0.1)


# calculate absolute and relative reductions since peak

rates_CO2 <- rates_CO2 %>% 
  group_by(country) %>% 
  summarise(percent_reduction_CO2_peak=((first(CO2)-last(CO2))/first(CO2))*100,
            absolute_reduction_CO2_peak=first(CO2)-last(CO2),
            CO2_peak=first(CO2))

rates_GHG <- rates_GHG %>% 
  group_by(country) %>% 
  summarise(percent_reduction_GHG_peak=((first(GHG)-last(GHG))/first(GHG))*100,
            absolute_reduction_GHG_peak=first(GHG)-last(GHG),
            GHG_peak=first(GHG))

data <- left_join(data,rates_CO2,by = "country")
data <- left_join(data,rates_GHG,by = "country")

# exclude countries with growing GHG emissions since the same CO2 peak year

data <- data %>% filter(rate_GHG_peak<0)


# exclude small countries with large oil industries and therefore large yearly emissions variations

data <- data %>% 
  filter(country!="Equatorial Guinea") %>% 
  filter(country!="Timor-Leste") %>% 
  filter(country!="Trinidad and Tobago") %>% 
  filter(country!="Gabon")

# exclude Austria, which has an absolute increase in GHG emissions since CO2 peak year (special!)

data <- data %>% 
  filter(country!="Austria")

# exclude Uzbekistan, due to data issues

data <- data %>% 
  filter(country!="Uzbekistan")

# exclude countries with emissions growing since 2008

data <- data %>% filter(rate_GHG_2008<0)

included_countries <- data %>% ungroup() %>% select(ISO) %>% distinct() %>% mutate(included=1)
excluded <- left_join(excluded,included_countries,by="ISO")
#excluded <- excluded %>% filter(is.na(included))

## join annex1 categorisation to the excluded country, to check for failures

annex1 <- read.xlsx('../../Data/Codes and classifications/UNFCCC annex1.xlsx')
annex1 <- annex1 %>% select(country,annex1=`annex-1`)
annex1 <- left_join(annex1 %>% mutate(country=tolower(country)),isos,by=c("country"="alternative.name"))

excluded <- left_join(excluded,annex1 %>% select(ISO=alpha.3,annex1),by="ISO")

blarg <- excluded %>% filter(!is.na(annex1)) %>% filter(year==2018) %>% filter(is.na(included))
```




```{r clustering,echo=FALSE,warning=FALSE,include=FALSE}


data <- data %>% 
  group_by(country) %>% 
  mutate(CO2_rm = rollmean(CO2,1,na.pad=TRUE,align="right"))

## normalise

data <- data %>% 
  group_by(country) %>% 
  mutate(CO2_rm = CO2_rm/nth(CO2_rm,1)) %>% 
  ungroup()

## import manual clusters

cluster_data <- openxlsx::read.xlsx('../../Data/Codes and classifications/decarbonising_country_clusters.xlsx','clusters')

if ("cluster" %in% colnames(data)) {
  data <- data %>% select(-cluster)
}

data <- left_join(data,cluster_data %>% select(country,cluster),by="country")

```


```{r exclusion_table,echo=FALSE,warning=FALSE,include=FALSE}

## small table showing how different accounting methods change inclusion/exclusion

# remove countries with data issues (above)
changing_countries <- excluded %>%
  filter(fsi_rank>50) %>% 
  filter(country!="Equatorial Guinea") %>% 
  filter(country!="Timor-Leste") %>% 
  filter(country!="Trinidad and Tobago") %>% 
  filter(country!="Gabon") %>% 
  filter(country!="Uzbekistan")
  
# countries that would be included by GHG and LULUCF alone
changing_countries <- changing_countries %>% 
  mutate(LULUCF_inclusion = ifelse(is.na(included) & rate_GHG_land_peak<0,1,0))

# countries that would be excluded by GHG and LULUCF
changing_countries <- changing_countries %>% 
  mutate(LULUCF_exclusion = ifelse(!is.na(included) & rate_GHG_land_peak>0,1,0))


# countries that would be included by CO2 consumption alone
changing_countries <- changing_countries %>% 
  mutate(cons_inclusion = ifelse(is.na(included) & rate_CO2_cons_peak<0,1,0))

# countries that would be excluded by CO2 consumption
changing_countries <- changing_countries %>% 
  mutate(cons_exclusion = ifelse(!is.na(included) & rate_CO2_cons_peak>0,1,0))

changing_countries <- changing_countries %>%
  ungroup() %>% 
  select(ISO,LULUCF_inclusion,LULUCF_exclusion,cons_inclusion,cons_exclusion) %>% 
  distinct()


excluded <- left_join(excluded,changing_countries,by="ISO")

```


```{r LULUCF_included,echo=FALSE,warning=FALSE,fig.width=10,fig.height=10,fig.path="../../Results/Plots/Decarbonising countries/",dev=c('png','pdf')}



# set facet labels and order by growth rate

plot_data <- excluded %>% filter(LULUCF_inclusion==1)

plot_data <- plot_data %>%
  mutate(labels=paste0(country," (",round(rate_GHG_land_peak,3),"%/yr)"))

plot_data <- plot_data %>%
  mutate(labels=as.character(labels)) %>% 
  mutate(labels=as.factor(labels))

plot_data$labels=fct_reorder(plot_data$labels,plot_data$rate_GHG_land_peak)

plot_data <- gather(plot_data,paths,value,CO2,GHG,CO2_cons,GHG_land,fit_GHG_land)
plot_data$paths <- as.factor(plot_data$paths)
plot_data$paths <- factor(plot_data$paths,levels=levels(plot_data$paths)[c(1,2,4,5,3)])


plot_data %>%
  ggplot(.,aes(x=year,y=value,color=paths)) +
  geom_path(size=1) +
  #geom_text(data=data %>% filter(year==2015),aes(x=1970,y=0,label=cluster_name),hjust="inward",vjust="inward",size=3.5,color="#636363") +
  scale_x_continuous(limits=c(1970,2018),breaks=c(1970,1990,2010)) +
  scale_y_continuous(expand = c(0.1, .1), limits = c(0, NA)) +
  scale_color_manual(values=c("#66c2a5","#fc8d62","#8da0cb","#dd1c77","#525252"),labels=c("CO2 emissions\n(territorial)","CO2 emissions\n(consumption)","GHG emissions\n(territorial)","GHG emissions\n(incl. LULUCF CO2)","Fit since peak year\n(GHG incl. LULUCF CO2)")) +
  facet_wrap(.~labels,scales="free",labeller = label_wrap_gen(width=19,multi_line = TRUE)) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        axis.title = element_blank(),
        plot.title = element_text(size = 12),
        strip.text = element_text(size = 11)) +
  guides(color = guide_legend(override.aes = list(size = 2)))


LULUCF_incl_countries <- paste0(unique(plot_data$country),collapse=", ")
LULUCF_excl_countries <- excluded %>% filter(LULUCF_exclusion==1) %>% filter(year==2018)
LULUCF_excl_countries <- paste0(unique(LULUCF_excl_countries$country),collapse=", ")

```

```{r consumption_included,echo=FALSE,warning=FALSE,fig.width=10,fig.height=10,fig.path="../../Results/Plots/Decarbonising countries/",dev=c('png','pdf')}

# set facet labels and order by growth rate

plot_data <- excluded %>% filter(cons_inclusion==1)

plot_data <- plot_data %>%
  mutate(labels=paste0(country," (",round(rate_CO2_cons_peak,3),"%/yr)"))

plot_data <- plot_data %>%
  mutate(labels=as.character(labels)) %>% 
  mutate(labels=as.factor(labels))

plot_data$labels=fct_reorder(plot_data$labels,plot_data$rate_CO2_cons_peak)

plot_data <- gather(plot_data,paths,value,CO2,GHG,CO2_cons,GHG_land,fit_CO2_cons)
plot_data$paths <- as.factor(plot_data$paths)
plot_data$paths <- factor(plot_data$paths,levels=levels(plot_data$paths)[c(1,2,4,5,3)])


plot_data %>%
  ggplot(.,aes(x=year,y=value,color=paths)) +
  geom_path(size=1) +
  #geom_text(data=data %>% filter(year==2015),aes(x=1970,y=0,label=cluster_name),hjust="inward",vjust="inward",size=3.5,color="#636363") +
  scale_x_continuous(limits=c(1970,2018),breaks=c(1970,1990,2010)) +
  scale_y_continuous(expand = c(0.1, .1), limits = c(0, NA)) +
  scale_color_manual(values=c("#66c2a5","#fc8d62","#8da0cb","#dd1c77","#525252"),labels=c("CO2 emissions\n(territorial)","CO2 emissions\n(consumption)","GHG emissions\n(territorial)","GHG emissions\n(incl. LULUCF CO2)","Fit since peak year\n(CO2 consumption)")) +
  facet_wrap(.~labels,scales="free",labeller = label_wrap_gen(width=19,multi_line = TRUE)) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        axis.title = element_blank(),
        plot.title = element_text(size = 12),
        strip.text = element_text(size = 11)) +
  guides(color = guide_legend(override.aes = list(size = 2)))

cons_incl_countries <- paste0(unique(plot_data$country),collapse=", ")
cons_excl_countries <- excluded %>% filter(cons_exclusion==1) %>% filter(year==2018)
cons_excl_countries <- paste0(unique(cons_excl_countries$country),collapse=", ")

```
```{r jamaica,echo=FALSE,warning=FALSE}

jamaica <- edgar_GHG_ar6 %>% 
  filter(country=="Jamaica") %>% 
  filter(year %in% c(2006,2018)) %>% 
  group_by(year,chapter_title,subsector_title,sector_code,description) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE))

jamaica <- jamaica %>% 
  group_by(chapter_title,subsector_title,sector_code,description) %>% 
  summarise(difference = first(GHG)-last(GHG))

```


```{r save,echo=FALSE,warning=FALSE}

table = data.frame(x=c("GHG emissions + LULUCF CO2","Consumption-based CO2 emissions only"),y=c(LULUCF_incl_countries,cons_incl_countries),z=c(LULUCF_excl_countries,cons_excl_countries))

write.xlsx(table,"../../Results/Data/decarbonising_countries_incl_excl.xlsx",overwrite=TRUE)


save(data,excluded,file="../../Data/decarbonising_countries.RData")



```
