---
title: "emissions_by_sector_summary"
author: "William F. Lamb"
output: word_document
---

# Setup

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(ggplot2); theme_set(theme_bw())
library(RColorBrewer)
library(ggrepel)
library(patchwork)
library(zoo)
library(lubridate)

source("small_figures.R")

end_year = 2019

load('../../Data/edgar6_v5_data_ghg_gwp_ar6.RData')
load('../../Data/gwps.RData')
load('../../Data/indirect_CO2.RData')
load('../../Data/land.RData')

options(dplyr.summarise.inform = FALSE)


########## add land CO2 data

land <- land %>%
  filter(year>1989) %>% 
  filter(year<=end_year) %>% 
  mutate(subsector=7.7) %>% 
  mutate(subsector_title="LULUCF (CO2)") %>% 
  mutate(chapter=7) %>% 
  mutate(chapter_title="AFOLU") %>% 
  select(region_ar6_10,region_ar6_10_short,year,chapter,chapter_title,subsector,subsector_title,value=mean)


indirect_CO2_world <- gather(indirect_CO2_world,year,CO2_indirect,`1990`:`2019`) %>% 
  mutate(year=as.numeric(year))



blarg <- edgar_ghg %>% 
  filter(chapter_title=="Transport") %>% 
  filter(year %in% c(1990,2019)) %>% 
  group_by(region_ar6_10,year) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE)/1e9)

blarg_indirect <- indirect_CO2_regions %>% 
  filter(chapter_title=="Transport") %>% 
  filter(year %in% c(1990,2019)) %>% 
  group_by(region_ar6_10,year) %>% 
  summarise(GHG=sum(CO2_indirect,na.rm=TRUE))

blarg <- rbind(blarg,blarg_indirect)  
blarg <- blarg %>% 
  group_by(region_ar6_10,year) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE))

blarg <- blarg %>% 
  group_by(region_ar6_10) %>% 
  mutate(rate=((last(GHG)/first(GHG))^(1/(last(year)-first(year))))-1) %>% 
  filter(year==2019) %>% 
  mutate(rate=rate*100)


```

## Growth rate calculation

```{r growth_rate,echo=FALSE,warning=FALSE}

growth_rates <- function(data) {
  
  # leap year adjustment
  # rates <- data %>%
  #   mutate(leap_years = leap_year(year)) %>%
  #   mutate(value = ifelse(leap_years==TRUE,value*365/366,value)) %>%
  #   select(-leap_years)
  
  rates <- data %>% 
    filter(year %in% c(1990,1999,2000,2009,2010,end_year)) %>% 
    mutate(total_rate=NA)
  
  rates$total_rate[rates$year==1990] = ((rates$value[rates$year==1999]/rates$value[rates$year==1990])^(1/(1999-1990))-1)*100
  
  rates$total_rate[rates$year==2000] = ((rates$value[rates$year==2009]/rates$value[rates$year==2000])^(1/(2009-2000))-1)*100
  
  rates$total_rate[rates$year==2010] = ((rates$value[rates$year==end_year]/rates$value[rates$year==2010])^(1/(end_year-2010))-1)*100
  
  
  return(rates)
  
}

```


# Data
## Gather trend data

```{r trend_data,echo=FALSE,warning=FALSE}

trend_data <- edgar_ghg %>%
  filter(year>1989) %>%
  filter(year<=end_year) %>%
  group_by(year,chapter,chapter_title) %>%
  summarise(value=sum(GHG,na.rm=TRUE)/1e9) %>%
  mutate(CO2_land=NA,CO2_indirect=NA) %>%
  ungroup()


land_totals <- land %>%
  group_by(year,chapter,chapter_title) %>%
  summarise(value=sum(value,na.rm=TRUE)) %>%
  mutate(value=value/1e9) %>% 
  ungroup() %>% 
  mutate(CO2_land=value) %>% 
  mutate(CO2_indirect=NA)


trend_data <- rbind(trend_data,land_totals)
trend_data <- trend_data %>%
  group_by(year,chapter,chapter_title) %>%
  summarise(value=sum(value,na.rm=TRUE))

```



```{r trend_plot,echo=FALSE,warning=FALSE}

## align factors and labels
trend_data$chapter_title <- as.factor(trend_data$chapter_title)
trend_data$chapter_title <- factor(trend_data$chapter_title,levels=levels(trend_data$chapter_title)[c(3,4,1,5,2)])


## align labels
labels <- trend_data %>%
  filter(year==end_year) %>% 
  arrange(desc(chapter_title))

labels <- labels %>% 
  mutate(fractions=(value/sum(labels$value))*100)

labels$cum <- cumsum(labels$value)

for (j in 1:length(labels$year)) {
  labels$location[j] = labels$value[j]*0.5
}
for (j in 2:length(labels$year)) {
  labels$location[j] = labels$location[j] + labels$cum[j-1]
}

## calculate shares
shares <- trend_data %>%
  filter(year %in% c(1990,2000,2010,end_year)) %>%
  group_by(year) %>%
  mutate(totals=sum(value)) %>%
  ungroup() %>%
  group_by(year,chapter_title) %>%
  mutate(fractions=(value/totals)*100) %>%
  ungroup()

shares <- locate_shares(shares,"chapter_title",4)

# # calculate overall growth between years (time 1 time 2)
rates <- trend_data %>%
  group_by(year) %>%
  summarise(value=sum(value))

rates <- growth_rates(rates)

shares <- left_join(shares,rates %>% select(-value) %>% filter(year %in% c(1990,2000,2010)),by="year")

colours <- c("#66c2a5","#fc8d62","#8da0cb","#e78ac3","#a6d854","#ffd92f","#e5c494")



p1 <- trend_data %>%
  ggplot(.,aes(x=year,y=value,fill=chapter_title)) +
  geom_area(color='#737373') +
  
  
  #### text with the shares
  geom_text(data=shares,aes(x=year+0.25,y=location,label=paste(round(fractions,0),"%",sep="")),size=3.5,colour="#252525",hjust=0)+
  
  #### text with the rates
  geom_text(data=rates %>% filter(!is.na(total_rate)),inherit.aes = FALSE,
            aes(x=ifelse(year==2010,year+4.5,year+5),y=60,
                label=paste0("+",round(total_rate,1),"%/yr")),size=3.5,colour="#252525") +
  
  #### text with the totals
  geom_text(data=shares %>% filter(chapter_title==shares$chapter_title[1]),aes(x=year,y=62,label=paste(round(totals,0),  "Gt")),size=3.5,colour="#252525")+
  ylab(bquote("Greenhouse gas emissions (Gt" ~CO[2]* "eq/yr)")) +
  scale_y_continuous(breaks=c(0,10,20,30,40,50,60)) +
  scale_x_continuous(breaks=c(1990,2000,2010,end_year),limits = c(1990,end_year+2)) +
  geom_vline(xintercept=c(1990,2000,2010,end_year),alpha=0.3,linetype="dashed") +
  #scale_fill_brewer(type = "qual",palette="Set2") +
  scale_fill_manual(values=colours) +
  scale_color_manual(values=colours) +
  
  big_trend_theme +
  ggtitle(paste0("a. Trends in global GHG emissions by sector")) +
  theme(legend.position="right",
        axis.title.x = element_blank(),
        legend.title=element_blank(),
        legend.spacing.x= unit(0.25, 'cm'),
        plot.background = element_blank(),
        panel.background = element_blank(),
        legend.background = element_blank()) +
  ylab(bquote("GHG Emissions (Gt" ~CO[2]* "eq/yr)"))

p1
```

## Gather region data

```{r regional_data,echo=FALSE,warning=FALSE}

region_data <- edgar_ghg %>% 
  filter(region_ar6_10_short!="SEA") %>% 
  filter(region_ar6_10_short!="AIR") %>%
  filter(year %in% c(1990,2000,2010,end_year)) %>% 
  group_by(chapter,chapter_title,region_ar6_10,region_ar6_10_short,year) %>% 
  summarise(value=sum(GHG,na.rm=TRUE)) %>% 
  mutate(value=value/1e9) %>% 
  mutate(year=as.factor(year)) %>% 
  ungroup()

## Add land
land_regions <- land %>% 
  filter(year %in% c(1990,2000,2010,end_year)) %>% 
  select(chapter,chapter_title,region_ar6_10,region_ar6_10_short,year,value) %>% 
  mutate(value=value/1e9)

region_data <- rbind(region_data,land_regions)
region_data <- region_data %>% 
  group_by(chapter,chapter_title,region_ar6_10,region_ar6_10_short,year) %>% 
  summarise(value=sum(value,na.rm=TRUE))

```

```{r regional_plots,echo=FALSE,warning=FALSE}

## align factors and labels
region_data$chapter_title <- as.factor(region_data$chapter_title)
region_data$chapter_title <- factor(region_data$chapter_title,levels=levels(region_data$chapter_title)[c(3,4,1,5,2)])

colours <- c("#66c2a5","#fc8d62","#8da0cb","#e78ac3","#a6d854","#ffd92f","#e5c494")


p2 <- region_data %>% ggplot(.,aes(x=year,y=value,fill=chapter_title)) +
  geom_bar(stat='identity',colour="#737373") +
  facet_grid(.~region_ar6_10_short) +
  ylab(bquote("GHG Emissions (Gt" ~CO[2]* "eq/yr)")) +
  #scale_fill_brewer(type = "qual",palette="Set2") +
  scale_fill_manual(values=colours) +
  ggtitle(paste0("b. Regional GHG emissions trends by sector")) +
  big_trend_theme +
  theme(legend.position="none",
        axis.title.x = element_blank(),
        legend.title=element_blank(),
        axis.text.x = element_text(angle = 45,hjust=1),
        legend.spacing.x= unit(0.25, 'cm'),
        plot.background = element_blank(),
        panel.background = element_blank(),
        legend.background = element_blank())
p2


```

```{r subsector_trends,echo=FALSE,warning=FALSE,results='asis',fig.width=8,fig.height=6,fig.path="../../Results/Plots/Sectors/",dev=c('png','pdf','svg')}

time_start = 1990;

## growth by subsector
subsector_data <- edgar_ghg %>%
  filter(year>=1990) %>%
  group_by(year,chapter,chapter_title,subsector,subsector_title) %>%
  summarise(value=sum(GHG,na.rm=TRUE)/1e9) %>%
  ungroup()

# add land data
land_totals <- land %>%
  group_by(year,subsector,subsector_title) %>%
  summarise(value=sum(value,na.rm=TRUE)/1e9) %>%
  mutate(chapter=7) %>%
  mutate(chapter_title="AFOLU")


subsector_data <- rbind(subsector_data,land_totals)
subsector_data <- subsector_data %>%
  group_by(year,chapter,chapter_title,subsector,subsector_title) %>%
  summarise(value=sum(value,na.rm=TRUE))

## align factors and labels
subsector_data$chapter_title <- as.factor(subsector_data$chapter_title)
subsector_data$chapter_title <- factor(subsector_data$chapter_title,levels=levels(subsector_data$chapter_title)[c(3,4,1,5,2)])

# what is 90% of the emissions?
threshold <- subsector_data %>%
  filter(year==2019)
threshold <- sum(threshold$value,na.rm=T)*0.9


## calculate average annual and absolute growth

subsector_data <- subsector_data %>%
  filter(year>=time_start & year<=2019) %>%
  group_by(subsector,subsector_title) %>%
  mutate(avg_growth=(last(value)/first(value))^(1/(last(year)-time_start))-1) %>%
  mutate(abs_growth=last(value)-first(value)) %>%
  filter(year==2019) %>%
  mutate(avg_growth=avg_growth*100)

## remove subsectors below absolute emissions threshold

subsector_data <- subsector_data %>%
  ungroup() %>%
  arrange(desc(value)) %>%
  mutate(cumulative_GHG=cumsum(value)) %>%
  mutate(cutoff = ifelse(cumulative_GHG<threshold,1,0)) %>%
  select(-cumulative_GHG)

subsector_data <- gather(subsector_data,var,value,avg_growth,abs_growth)


plot_theme <- theme_bw() +
  theme(axis.title.y = element_blank(),
        plot.title = element_text(size = 11,color="#252525"),
        axis.title = element_text(color="#525252"),
        panel.grid.minor.x = element_blank(),
        legend.position="none",
        text = element_text(size=11),
        plot.background = element_blank())


#rate
p3 <- subsector_data %>%
  filter(cutoff==1) %>%
  filter(var=="avg_growth") %>%
  ggplot(.,aes(x = reorder(subsector_title,value),y = value, fill=chapter_title)) +
  geom_bar(stat='identity',colour="#737373") +
  coord_flip() +
  plot_theme +
  scale_fill_brewer(type = "qual",palette="Set2") +
  ylab("%") +
  ggtitle(str_wrap("c. Avg. annual GHG emissions change by subsector",width=38)) +
  annotate(geom = 'text', label = paste0('Years: ',time_start,'-2019'),
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.4,size=3.5,color="#525252")

#absolute
p4 <- subsector_data %>%
  filter(cutoff==1) %>%
  filter(var=="abs_growth") %>%
  ggplot(.,aes(x = reorder(subsector_title,value),y = value, fill=chapter_title)) +
  geom_bar(stat='identity',colour="#737373") +
  coord_flip() +
  plot_theme +
  scale_fill_brewer(type = "qual",palette="Set2") +
  ylab("Gt CO2eq/yr") +
  ggtitle(str_wrap("d. Change in annual GHG emissions level by subsector",width=35)) +
    annotate(geom = 'text', label = paste0('Years: ',time_start,'-2019'),
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#525252")


```



```{r sector_trends_1990,echo=FALSE,warning=FALSE,results='asis',dpi=300,fig.width=10,fig.height=12,fig.path="../../Results/Plots/",dev=c('png','pdf','svg')}


wrap_elements(p1) / wrap_elements(p2) / wrap_elements(p3 + p4)


```

```{r save,echo=FALSE,warning=FALSE}

wb <- openxlsx::createWorkbook(title = paste("sector summary"))

openxlsx::addWorksheet(wb,"trend data")
openxlsx::addWorksheet(wb,"emissions by sector and region")
openxlsx::addWorksheet(wb,"emissions by subsector")

openxlsx::writeData(wb, sheet = "trend data", spread(trend_data,year,value), colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "emissions by sector and region", spread(region_data %>% ungroup() %>% select(-chapter),chapter_title,value), colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "emissions by subsector", subsector_data, colNames = T, rowNames = F)


openxlsx::saveWorkbook(wb,paste0("../../Results/Plot data/ipcc_ar6_sector_summary_1990.xlsx"),overwrite=T)


```
