---
title: "emissions_by_country"
author: "William F. Lamb"
date: "17 11 2020"
output: 
  word_document:
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results") })

---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(ggplot2); theme_set(theme_bw())

source("small_figures.R")

options(dplyr.summarise.inform = FALSE)

load('../../Data/edgar6_v5_data_ghg_gwp_ar6.RData')
load('../../Data/gwps.RData')
load("../../Data/land.RData")
load('../../Data/WDI_gdp_pop.RData')

# set palette
ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2")

wb <- openxlsx::createWorkbook(title = "ipcc_ar6_region_and_countries_plot")


```

```{r region_data,echo=FALSE,warning=FALSE}

## copy this over from 'emissions_by_region.Rmd'

## sum GHG emissions for each region

plot_data <- edgar_ghg %>% 
  filter(year>1989) %>% 
  filter(year<2020) %>% 
  group_by(year,region_ar6_6,region_ar6_6_short,region_ar6_10) %>% 
  summarise(value=sum(GHG,na.rm=TRUE)/1e9) %>% 
  ungroup() %>% 
  mutate(region_ar6_6_short=as.character(region_ar6_6_short))


## group aviation and shipping into a single region

plot_data <- plot_data %>%
  mutate(region_ar6_6=ifelse(region_ar6_6_short=="AIR","Intl. Shipping & Aviation",region_ar6_6)) %>% 
  mutate(region_ar6_6=ifelse(region_ar6_6_short=="SEA","Intl. Shipping & Aviation",region_ar6_6)) %>%  
  mutate(region_ar6_6_short=ifelse(region_ar6_6=="Intl. Shipping & Aviation","AIRSEA",region_ar6_6_short))


## Add land use CO2

plot_data <- left_join(plot_data,land %>% select(region_ar6_10,year,mean),by=c("year","region_ar6_10"))
plot_data <- plot_data %>% 
  mutate(mean=mean/1e9) %>% 
  mutate(value=ifelse(region_ar6_6_short!="AIRSEA",value+mean,value))


## combine everything

plot_data <- plot_data %>% 
  group_by(year,region_ar6_6,region_ar6_6_short) %>%
  mutate(value=sum(value)) %>%
  select(-region_ar6_10,-mean) %>% 
  unique() %>% 
  ungroup()

## adjust levels

plot_data$region_ar6_6_short <- as.factor(plot_data$region_ar6_6_short)
plot_data$region_ar6_6_short <-  factor(plot_data$region_ar6_6_short,levels(plot_data$region_ar6_6_short)[c(2,3,4,5,6,1)])

plot_data$region_ar6_6 <- as.factor(plot_data$region_ar6_6)
plot_data$region_ar6_6 <-  factor(plot_data$region_ar6_6,levels(plot_data$region_ar6_6)[c(2,3,4,5,6,1)])



```

```{r region_panel, echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=4}


shares <- plot_data %>% 
  filter(year %in% c(1990,2000,2010,2019)) %>% 
  group_by(year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,region_ar6_6_short) %>% 
  mutate(fractions=(value/totals)*100)

shares <- locate_shares(shares,"region_ar6_6_short",4)

line_data <- data.frame(x=c(1990,1990,2000,2000,2010,2010,2019,2019),y=c(0,60))

p1 <- plot_data %>%
  ggplot(.,aes(x=year,y=value,fill=region_ar6_6_short)) +
  geom_area(colour="#737373") +
  
  geom_text(data=shares,aes(x=year+1.25,y=location,label=paste(round(fractions,0),"%",sep="")),size=3.5,colour="#525252")+
  
  geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed")  +
  
  #### text with the totals
  geom_text(data=shares %>% filter(region_ar6_6_short=="AIRSEA"),aes(x=year,y=62,label=paste(round(totals,1),  "Gt")),size=3.5,colour="#525252")+
  
  #### labels
  geom_text(data=shares %>% filter(year==2018),aes(x=2021,y=location,label=str_wrap(region_ar6_6,width=28),color=region_ar6_6_short),hjust=0) +
  
  
  scale_y_continuous(breaks=c(0,10,20,30,40,50,60)) +
  scale_x_continuous(breaks=c(1990,2000,2010,2019)) +
  coord_cartesian(xlim = c(1990,2032), # This focuses the x-axis on the range of interest
                  clip = 'off') +
  big_trend_theme +
  theme(legend.position="none",
        plot.title = element_text(size = 11,color="#252525"),
        axis.title = element_text(color="#525252")
        #plot.margin = unit(c(5.5,150,5.5,5.5),"points")
  ) +
  ylab('GHG Emissions (GtCO2eq/yr)') +
  ggtitle("a. Trends in global and regional greenhouse gas emissions")
p1


openxlsx::addWorksheet(wb,"region_trend")
openxlsx::writeData(wb, sheet = "region_trend", spread(plot_data,year,value), colNames = T, rowNames = F)


```


```{r country_changes,echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=6}

time_start=2010

## get country level data

countries <- edgar_ghg %>% 
  filter(region_ar6_6_short!="AIR") %>% 
  filter(region_ar6_6_short!="SEA") %>% 
  filter(year>=time_start & year<2020) %>% 
  group_by(country,ISO,year,region_ar6_6_short) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE))

# ### join pop and gdp
# basic <- basic %>%  
#   filter(Year>=time_start & Year<2019) %>% 
#   select(ISO,Year,pop_UN,gdp_ppp_WB)
# 
# ############## BRING FORWARD MISSING GDP DATA
# basic <- basic %>% 
#   group_by(ISO) %>% 
#   fill(gdp_ppp_WB)

countries <- left_join(countries,wdi_data_gdp_pop,by=c("ISO"="iso3c","year"="year"))

countries <- countries %>% 
  mutate(emissions_pc = GHG/population) %>% 
  mutate(emissions_pgdp = GHG/gdp_ppp)

# what is 75% of the emissions?
threshold <- countries %>%
  filter(year==2019)
threshold <- sum(threshold$GHG,na.rm=T)*0.75


## calculate average annual and absolute growth

countries <- countries %>% 
  filter(year %in% c(time_start,2019)) %>% 
  group_by(country) %>% 
  mutate(avg_growth=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
  mutate(abs_growth=last(GHG)-first(GHG)) %>%
  filter(year==2019) %>% 
  mutate(avg_growth=avg_growth*100)

## remove countries below absolute emissions threshold

countries <- countries %>% 
  ungroup() %>% 
  arrange(desc(GHG)) %>% 
  mutate(cumulative_GHG=cumsum(GHG)) %>% 
  mutate(cutoff = ifelse(cumulative_GHG<threshold,1,0))# %>% 
  #filter(cutoff==1)

countries <- gather(countries,var,value,avg_growth,abs_growth,emissions_pc,emissions_pgdp)


plot_theme <- theme_bw() +
  theme(axis.title.y = element_blank(),
        plot.title = element_text(size = 11,color="#252525"),
        axis.title = element_text(color="#525252"),
        panel.grid.minor.x = element_blank(),
        legend.position="none",
        text = element_text(size=11),
        plot.background = element_blank())

#rate
p2 <- countries %>% 
  filter(cutoff==1) %>% 
  filter(var=="avg_growth") %>% 
  ggplot(.,aes(x = reorder(country,value),y = value, fill=region_ar6_6_short)) +
  geom_bar(stat='identity',colour="#525252") + 
  coord_flip() +
  plot_theme +
  ylab("%") +
  ggtitle(str_wrap("b. Avg. annual GHG emissions growth",width=38)) +
  annotate(geom = 'text', label = 'Years: 2010-2018',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.4,size=3.5,color="#525252")

#absolute
p3 <- countries %>% 
  filter(cutoff==1) %>% 
  filter(var=="abs_growth") %>% 
  ggplot(.,aes(x = reorder(country,value),y = value/1e9, fill=region_ar6_6_short)) +
  geom_bar(stat='identity',colour="#737373") + 
  coord_flip() +
  plot_theme +
  ylab("Gt CO2eq") +
  ggtitle(str_wrap("c. Absolute GHG emissions growth",width=35)) +
    annotate(geom = 'text', label = 'Years: 2010-2018',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#525252")

#pc
p4 <- countries %>% 
  filter(cutoff==1) %>% 
  filter(var=="emissions_pc") %>%  
  ggplot(.,aes(x = reorder(country,value),y = value, fill=region_ar6_6_short)) +
  geom_bar(stat='identity',colour="#737373") + 
  coord_flip() +
  plot_theme +
  ylab("tCO2eq/cap") +
  ggtitle(str_wrap("d. GHG emissions per capita",width=35)) +
    annotate(geom = 'text', label = 'Year: 2018',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#737373")

#pgdp
p5 <- countries %>% 
  filter(cutoff==1) %>% 
  filter(var=="emissions_pgdp") %>% 
  ggplot(.,aes(x = reorder(country,value),y = value*1000, fill=region_ar6_6_short)) +
  geom_bar(stat='identity',colour="#737373") + 
  coord_flip() +
  plot_theme +
  ylab("kgCO2eq/$") +
  ggtitle(str_wrap("e. GHG emissions intensity",width=35)) +
    annotate(geom = 'text', label = 'Year: 2018',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#525252")



openxlsx::addWorksheet(wb,"countries_2018")
openxlsx::writeData(wb, sheet = "countries_2018", countries, colNames = T, rowNames = F)


```

```{r regions_countries,echo=FALSE,warning=FALSE,fig.width=8,fig.height=10,fig.path="../../Results/Plots/",dev=c('png','pdf')}

p1 / ((p2 + p3) / (p4 + p5)) + plot_layout(heights = c(1,2))


```



```{r per_capita_by_region,echo=FALSE,warning=FALSE}

per_capita <- edgar_ghg %>% 
  group_by(country,ISO,year,region_ar6_6) %>% 
  summarise(CO2=sum(CO2,na.rm=TRUE),GHG=sum(GHG,na.rm=TRUE)) %>% 
  ungroup()

per_capita <- left_join(per_capita,wdi_data_gdp_pop,by=c("year"="year","ISO"="iso3c")) %>%
  select(-gdp_ppp,-gdp_real)

per_capita <- per_capita %>% 
  filter(year==2019) %>% 
  mutate(CO2_pc = CO2/population) %>% 
  mutate(GHG_pc = GHG/population)

all_countries <- per_capita

### remove intl. shipping, aviation and countries at zero emissions and small countries
per_capita <- per_capita %>% 
  filter(region_ar6_6!="Intl. Aviation") %>% 
  filter(region_ar6_6!="Intl. Shipping") %>% 
  filter(CO2_pc>0) %>% 
  filter(population>1e6)

per_capita <- per_capita %>%
  group_by(region_ar6_6) %>% 
  summarise(GHG_pc_max=max(GHG_pc,na.rm=T),GHG_pc_min=min(GHG_pc,na.rm=T))

region_averages <- all_countries %>% 
  filter(region_ar6_6!="Intl. Aviation") %>% 
  filter(region_ar6_6!="Intl. Shipping") %>% 
  group_by(region_ar6_6) %>% 
  summarise_at(vars(CO2,GHG,population),sum,na.rm=TRUE)

per_capita <- left_join(per_capita,region_averages,by = "region_ar6_6")

per_capita <- per_capita %>% 
  mutate(GHG_mean = GHG/population) %>% 
  mutate(CO2_mean = CO2/population)

```

```{r cumulative_emissions_income,echo=FALSE,warning=FALSE}

cumulative_emissions_income <- edgar_ghg %>% 
  group_by(country,ISO,year,region_ar6_dev) %>% 
  summarise(CO2=sum(CO2,na.rm=TRUE),GHG=sum(GHG,na.rm=TRUE)) %>% 
  ungroup()

cumulative_1990 <- cumulative_emissions_income %>% 
  filter(year>1989) %>% 
  filter(year<2020) %>% 
  group_by(region_ar6_dev) %>% 
  summarise(GHG_since_1990=sum(GHG/1e9))

cumulative_2010 <- cumulative_emissions_income %>% 
  filter(year>2009) %>% 
  filter(year<2020) %>% 
  group_by(region_ar6_dev) %>% 
  summarise(GHG_since_2010=sum(GHG/1e9))

cumulative_emissions_income <- left_join(cumulative_1990,cumulative_2010)

total_2010 <- sum(cumulative_emissions_income$GHG_since_2010) 
total_1990 <- sum(cumulative_emissions_income$GHG_since_1990)

cumulative_emissions_income <- cumulative_emissions_income %>% 
  mutate(fraction_since_1990=GHG_since_1990/total_1990) %>% 
  mutate(fraction_since_2010=GHG_since_2010/total_2010)

```

```{r cumulative_emissions_geo,echo=FALSE,warning=FALSE}

cumulative_emissions_geo <- edgar_ghg %>% 
  group_by(country,ISO,year,region_ar6_6) %>% 
  summarise(CO2=sum(CO2,na.rm=TRUE),GHG=sum(GHG,na.rm=TRUE)) %>% 
  ungroup()

cumulative_1990 <- cumulative_emissions_geo %>% 
  filter(year>1989) %>% 
  filter(year<2020) %>% 
  group_by(region_ar6_6) %>% 
  summarise(GHG_since_1990=sum(GHG/1e9))

cumulative_2010 <- cumulative_emissions_geo %>% 
  filter(year>2009) %>% 
  filter(year<2020) %>% 
  group_by(region_ar6_6) %>% 
  summarise(GHG_since_2010=sum(GHG/1e9))

cumulative_emissions_geo <- left_join(cumulative_1990,cumulative_2010)

total_2010 <- sum(cumulative_emissions_geo$GHG_since_2010) 
total_1990 <- sum(cumulative_emissions_geo$GHG_since_1990)

cumulative_emissions_geo <- cumulative_emissions_geo %>% 
  mutate(fraction_since_1990=GHG_since_1990/total_1990) %>% 
  mutate(fraction_since_2010=GHG_since_2010/total_2010)

```

```{r region_comparison,echo=FALSE,warning=FALSE}

# blarg <- edgar_ghg %>%
#   filter(year==2018) %>% 
#   group_by(region_ar6_dev) %>% 
#   summarise(GHG=sum(GHG,na.rm=T)/1e9)
# 
# blarg2 <- edgar_ghg %>%
#   filter(year==2018) %>% 
#   group_by(region_ar6_6) %>% 
#   summarise(GHG=sum(GHG,na.rm=T)/1e9)
# 
# 
# regions <- edgar_ghg %>% 
#   filter(year==2018) %>%
#   group_by(country,ISO,year,region_ar6_dev,region_ar6_6) %>% 
#   summarise(GHG=sum(GHG,na.rm=T))
# 
# regions <- left_join(regions,basic %>% select(Year,ISO,pop_UN),by=c("year"="Year","ISO"="ISO"))
# 
# 
# regions <- regions %>% 
#   filter(region_ar6_6=="Developed countries" | region_ar6_dev=="developed")


```

```{r ridgeline_plot,echo=FALSE,warning=FALSE,fig.width=9,fig.height=5}
# 
# #load('../../Data/basic.RData')
# 
# ## get country level data
# 
# countries <- edgar_ghg %>% 
#   filter(region_ar6_6_short!="AIR") %>% 
#   filter(region_ar6_6_short!="SEA") %>% 
#   group_by(country,ISO,year,region_ar6_6_short,region_ar6_10) %>% 
#   summarise(GHG=sum(GHG,na.rm=TRUE))
# 
# ### join pop and gdp
# #basic <- basic %>%  
# #  select(ISO,Year,pop_UN)
# 
# countries <- left_join(countries,wdi_data_gdp_pop,by=c("ISO"="iso3c","year"="year"))
# 
# ### select two time frames
# 
# 
# countries_tf1 <- countries %>% 
#   filter(year>=1990 & year<2000) %>%
#   group_by(country,ISO,region_ar6_6_short,region_ar6_10) %>% 
#   summarise(GHG=sum(GHG)/10,pop_UN=sum(population)/10) %>% 
#   mutate(year='1990_1999')
# 
# countries_tf2 <- countries %>% 
#   filter(year>=2010 & year<2019) %>%
#   group_by(country,ISO,region_ar6_6_short,region_ar6_10) %>% 
#   summarise(GHG=sum(GHG)/10,population=sum(population)/10) %>% 
#   mutate(year='2000_2018')
# 
# countries <- rbind(countries_tf1,countries_tf2)
# 
# countries <- countries %>% 
#   mutate(emissions_pc=GHG/population)
# 
# library(ggridges)
# 
# countries %>% ggplot(.,aes(x=emissions_pc,y=region_ar6_10,fill=year)) +
#   geom_density_ridges() +
#   xlim(-10,100)
# 
# countries %>% ggplot(.,aes(x=emissions_pc,y=region_ar6_10,fill=year)) +
#   geom_boxplot() +
#   xlim(-10,100)

```

```{r save,echo=FALSE,warning=FALSE}

# 
# openxlsx::addWorksheet(wb,"country_emissions_2018")
# openxlsx::writeData(wb,"country_emissions_2018",all_countries, colNames = T, rowNames = F)

openxlsx::addWorksheet(wb,"region_summary_2018")
openxlsx::writeData(wb,"region_summary_2018",per_capita, colNames = T, rowNames = F)

openxlsx::addWorksheet(wb,"cumulative_GHG_emissions_income")
openxlsx::writeData(wb,"cumulative_GHG_emissions_income",cumulative_emissions_income, colNames = T, rowNames = F)

openxlsx::addWorksheet(wb,"cumulative_GHG_emissions_geo")
openxlsx::writeData(wb,"cumulative_GHG_emissions_geo",cumulative_emissions_geo, colNames = T, rowNames = F)

# openxlsx::addWorksheet(wb,"region_comparison")
# openxlsx::writeData(wb,"region_comparison",regions, colNames = T, rowNames = F)


#openxlsx::saveWorkbook(wb,paste0("../../Results/Data/ipcc_ar6_data_regions_countries",".xlsx"),overwrite=T)

```

```{r old,echo=FALSE,warning=FALSE}

########### side figures - per capita and per gdp ###########

# load('../Data/basic.RData')
# load('../Data/tsu_codes.RData')
# 
# basic <- basic %>%  
#   filter(Year>=1990 & Year<2019) %>% 
#   select(ISO,Year,pop_UN,gdp_ppp_WB) %>% 
#   filter(ISO!="WLD")
# 
# basic <- left_join(basic,tsu_codes %>% select(ISO,region_ar6_6))
# 
# basic <- basic %>% 
#   group_by(Year,region_ar6_6) %>% 
#   summarise_at(vars(gdp_ppp_WB,pop_UN),sum,na.rm=T)
# 
# 
# side_plot_data <- edgar_ghg %>% 
#   filter(year>1989) %>% 
#   filter(year<2019) %>% 
#   filter(region_ar6_6!="Intl. Aviation") %>% 
#   filter(region_ar6_6!="Intl. Shipping") %>% 
#   group_by(year,region_ar6_6,region_ar6_6_short) %>% 
#   summarise_at(vars(GHG),sum,na.rm=TRUE)
# 
# side_plot_data <- left_join(side_plot_data,basic,by=c("year"="Year","region_ar6_6"="region_ar6_6"))
# 
# 
# side_plot_data <- side_plot_data %>% 
#   mutate(GHG_pc = GHG/pop_UN) %>% 
#   mutate(GHG_pgdp = GHG/gdp_ppp_WB*1000) %>% 
#   mutate(GHG_pgdp = ifelse(year==2018,NA,GHG_pgdp))
# 
# 
# p2_1 <- side_plot_data %>% 
#   ggplot(.,aes(x=year,y=GHG_pc,colour=region_ar6_6_short)) +
#   geom_line() +
#   theme_bw() +
#   ylab('GHG Emissions\n(tCO2eq/cap)') +
#   theme(legend.position = "none",
#         axis.title.x = element_blank(),
#         text = element_text(size=11),
#         panel.grid.minor.x = element_blank(),
#         panel.grid.minor.y = element_blank())
# 
# p2_2 <- side_plot_data %>% 
#   ggplot(.,aes(x=year,y=GHG_pgdp,colour=region_ar6_6_short)) +
#   geom_line() +
#   theme_bw() +
#   ylab('GHG Emissions intensity\n(gCO2eq/$)') +
#   theme(legend.position = "bottom",
#         axis.title.x = element_blank(),
#         text = element_text(size=11),
#         panel.grid.minor.x = element_blank(),
#         panel.grid.minor.y = element_blank())
# 
# p2 <- ggarrange(p2_1,p2_2,ncol=1,nrow=2)

```
