---
title: "Long term CO2 emissions trends, sources and sinks"
author: "William F. Lamb"
output: 
  word_document:
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results") })
  
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(patchwork)
library(ggplot2); theme_set(theme_bw())
library(openxlsx)

source("small_figures.R")

load('../../Data/gwps.RData')
load("../../Data/land.RData")


# set palette
ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2")


```


```{r budget_trend, echo=FALSE,warning=FALSE,fig.width=10,fig.height=3}

######### load the global carbon budget ######### 

gcb <- openxlsx::read.xlsx('../../Data/Land and GCB/Global_Carbon_Budget_2020v1.0.xlsx',sheet="CDIAC CO2",rows=3:272,cols=1:9)
names(gcb) <- c("Year","Total","Gas","Oil","Coal","Cement","Flaring","LULUCF","Total_CO2")

co2_trend <- gather(gcb,key,value,-Year) %>% 
  filter(key!="Total_CO2",key!="Total") %>% 
  filter(Year>=1850) %>% 
  select(year=Year,everything())

co2_trend$key <- as.factor(co2_trend$key)
co2_trend$key <- factor(co2_trend$key,levels(co2_trend$key)[c(1,2,3,4,6,5)])

shares <- co2_trend %>% 
  filter(year %in% c(1850,1900,1950,1990,2019)) %>% 
  group_by(year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,key) %>% 
  mutate(fractions=(value/totals)*100)


shares <- locate_shares(shares,"key",5)


line_data <- data.frame(x=c(1850,1850,1900,1900,1950,1950,1990,1990,2019,2019),y=c(0,45))

shares <- shares %>% 
  mutate(include=ifelse(fractions<10 & year<2019,0,1))



p1 <- co2_trend %>% 
  ggplot(.,aes(x=year,y=value,fill=key,color=key)) + 
  geom_area(colour="#737373") +
  
  geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  
  geom_text(data=shares %>% filter(include==1),aes(x=year+1,y=location,label=paste(round(fractions,0),"%",sep="")),size=3.5,colour="#252525",hjust=0)+
  
  geom_text(data=shares %>% filter(key=="Cement"),
            aes(x=year,y=47,label=paste(round(totals,0),"Gt")),size=3.5,colour="#252525")+
  
  ylab(bquote(~CO[2]*" emissions (Gt" ~CO[2]* "/yr)")) +
  big_trend_theme +
  scale_x_continuous(breaks=c(1850,1900,1950,1990,2019))  +
  theme(legend.position = c(0.15,0.7),
        legend.title = element_blank(),
        legend.background = element_blank()) +
  ggtitle(bquote("a. Long term trend of anthropogenic"~CO[2]* " emissions sources"))

p1
```

```{r historical_budget, echo=FALSE,warning=FALSE,fig.width=4,fig.height=3}

## analysis of how much of the total budget is used up

table_historic <- expand.grid(budget=c("1.5 budget (2020-) 67% [400 GtCO2]","2.0 budget (2020-) 67% [1150 GtCO2]"),budget_uncertainty=c("High (+220 GtCO2)","Med (+0 GtCO2)","Low (-220 GtCO2)"),historic_emissions=c("High (2400+240 GtCO2)","Med (2400 GtCO2)","Low (2400-240 GtCO2)"))

table_historic <- table_historic %>% 
  mutate(budget_value=ifelse(budget=="1.5 budget (2020-) 67% [400 GtCO2]",400,1150))

table_historic <- table_historic %>% 
  mutate(budget_value=ifelse(budget_uncertainty=="High (+220 GtCO2)",budget_value+220,budget_value)) %>% 
  mutate(budget_value=ifelse(budget_uncertainty=="Low (-220 GtCO2)",budget_value-220,budget_value))

table_historic <- table_historic %>% 
  mutate(historic_emissions_value=2400) %>% 
  mutate(historic_emissions_value=ifelse(historic_emissions=="High (2400+240 GtCO2)",historic_emissions_value+240,historic_emissions_value)) %>% 
  mutate(historic_emissions_value=ifelse(historic_emissions=="Low (2400-240 GtCO2)",historic_emissions_value-240,historic_emissions_value))

table_historic <- table_historic %>% 
  mutate(total_historic_budget=budget_value+historic_emissions_value) %>% 
  mutate(fraction_used=round(historic_emissions_value/total_historic_budget,2))

table_historic <- table_historic %>% 
  arrange(budget,fraction_used)

```

```{r historical_cumulative, echo=FALSE,warning=FALSE,fig.width=4,fig.height=3}


luc_uncertainties <- read.xlsx('../../Data/Land and GCB/Global Carbon Budget uncertainties.xlsx',sheet=1)
luc_uncertainties <- luc_uncertainties %>% 
  mutate(uncertainty_LULUCF=uncertainty_LULUCF*(44/12))


# how much emissions occurred at different time periods?
#1970
cumulative_a <- gcb %>% 
  select(Year,CO2FFI=Total,LULUCF,value=Total_CO2) %>% 
  filter(Year>=1850) %>% 
  mutate(key=NA) %>%
  mutate(key=ifelse(Year>=1970, '1970- 2019',key)) %>% 
  filter(!is.na(key))

#1990
cumulative_b <- gcb %>% 
  select(Year,CO2FFI=Total,LULUCF,value=Total_CO2) %>% 
  filter(Year>=1850) %>% 
  mutate(key=NA) %>%
  mutate(key=ifelse(Year>=1990,'1990- 2019',key)) %>% 
  filter(!is.na(key))

#2010
cumulative_c <- gcb %>% 
  select(Year,CO2FFI=Total,LULUCF,value=Total_CO2) %>% 
  filter(Year>=1850) %>% 
  mutate(key=NA) %>%
  mutate(key=ifelse(Year>=2010,'2010- 2019',key)) %>% 
  filter(!is.na(key))

cumulative <- rbind(cumulative_a,cumulative_b)
cumulative <- rbind(cumulative,cumulative_c)


# get uncertainties for FFI and LUC
cumulative <- left_join(cumulative,luc_uncertainties,by=c("Year"="year"))
cumulative <- cumulative %>% 
  mutate(uncertainty_CO2FFI=0.05*CO2FFI)

cumulative <- cumulative %>% 
  mutate(key=as.factor(key))%>% 
  group_by(key) %>% 
  summarise(value=sum(value),CO2FFI=sum(CO2FFI),LULUCF=sum(LULUCF),uncertainty_CO2FFI=sum(uncertainty_CO2FFI),uncertainty_LULUCF=sum(uncertainty_LULUCF))


gcb_total <- gcb %>%  
  filter(Year>=1850)

cumulative <- cumulative %>% 
  mutate(ag_uncertainty=sqrt((uncertainty_CO2FFI^2)+(uncertainty_LULUCF^2))) %>% 
  mutate(fraction_since_1850=round(value/sum(gcb_total$Total_CO2),2))


```



```{r historical_budget_plot, echo=FALSE,warning=FALSE,fig.width=4,fig.height=3}




###### calculate historical cumulative CO2



historical_budget <- gcb %>% 
  select(Year,CO2FFI=Total,LULUCF,value=Total_CO2) %>% 
  filter(Year>=1850) %>% 
  mutate(key=NA) %>%
  mutate(key=ifelse(Year>=1850 & Year < 1990,'1850- 1989',key)) %>% 
  mutate(key=ifelse(Year>=1990 & Year < 2010,'1990- 2009',key)) %>% 
  mutate(key=ifelse(Year>=2010,'2010- 2019',key)) %>% 
  filter(!is.na(key))

# get uncertainties for FFI and LUC
historical_budget <- left_join(historical_budget,luc_uncertainties,by=c("Year"="year"))
historical_budget <- historical_budget %>% 
  mutate(uncertainty_CO2FFI=0.05*CO2FFI)

emissions_uncertainty <- historical_budget %>% 
  filter(Year==2019)

# get uncertainties by year for the 2019 estimate
# emissions_uncertainty <- historical_budget %>% 
#   mutate(uncertainty_CO2FFI=CO2FFI*0.08) %>% 
#   mutate(uncertainty_LULUCF=LULUCF*0.7) %>%
#   mutate(ag_uncertainty=sqrt((uncertainty_CO2FFI^2)+(uncertainty_LULUCF^2))) %>% 
#   filter(Year==2019)

# sum to cumulative totals and calculate cumulative uncertainty
historical_budget <- historical_budget %>% 
  mutate(key=as.factor(key))%>% 
  group_by(key) %>% 
  summarise(value=sum(value),CO2FFI=sum(CO2FFI),LULUCF=sum(LULUCF),uncertainty_CO2FFI=sum(uncertainty_CO2FFI),uncertainty_LULUCF=sum(uncertainty_LULUCF))

## readjust LULUCF uncertainty based on Julia Pongratz's sheet (see 'Global Carbon Budget uncertainties.xlsx' 1850-1989)
historical_budget <- historical_budget %>% 
  mutate(uncertainty_LULUCF=ifelse(key=="1850- 1989",51.535*(44/12),uncertainty_LULUCF))

historical_budget <- historical_budget %>% 
  mutate(ag_uncertainty=sqrt((uncertainty_CO2FFI^2)+(uncertainty_LULUCF^2)))


###### contrast historical cumulative CO2 with future 1.5C and 2C budgets
# Following from AR6_WGI_FGD_Chapter_05 Table 5.8 / AR6_WGI_FGD_Summary_For_Policymakers Table SPM2
# https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Chapter_05.pdf

budget <- data.frame(target=c("1.5 budget (2020-)","1.5 budget (2020-)","1.5 budget (2020-)","2.0 budget (2020-)","2.0 budget (2020-)","2.0 budget (2020-)"),category=c("67%","50%","33%","67%","50%","34%"),value=c(400,500,650,1150,1350,1700))

# Above are budgets from 1850-2019. We need to subtract 2019 emissions to get 2020- budgets
#budget <- budget %>% 
#  mutate(value=value-gcb$Total_CO2[gcb$Year==2019])

# Now we add the medium budgets to our bar plot
historical_budget <- historical_budget %>% 
  add_row(key="1.5 budget (2020-)",value=budget$value[budget$target=="1.5 budget (2020-)" & budget$category=="67%"]) %>% 
  add_row(key="2.0 budget (2020-)",value=budget$value[budget$target=="2.0 budget (2020-)" & budget$category=="67%"])

###### calculate start and end positions for the bar plots

historical_budget$end <- cumsum(historical_budget$value)
historical_budget$end[historical_budget$key=="2.0 budget"] <- historical_budget$end[historical_budget$key=="2.0 budget"] - historical_budget$value[historical_budget$key=="1.5 budget"]
historical_budget$start <- c(0, head(historical_budget$end, -1))
historical_budget$start[historical_budget$key=="2.0 budget"] <- historical_budget$start[historical_budget$key=="1.5 budget"]
historical_budget <- cbind(historical_budget,id=c(1,2,3,4,5))

# reset 2C budget to same starting level as 1.5
historical_budget <- historical_budget %>% 
  mutate(start = ifelse(key=="2.0 budget (2020-)",start-(budget$value[budget$target=="1.5 budget (2020-)" & budget$category=="67%"]),start)) %>% 
  mutate(end = ifelse(key=="2.0 budget (2020-)",end-(value=budget$value[budget$target=="1.5 budget (2020-)" & budget$category=="67%"]),end))


# add lower and higher budget levels
# historical_budget <- historical_budget %>%
#   mutate(lower_budget=ifelse(key=="1.5 budget (2020-)",start+(budget$value[budget$target=="1.5 budget (2020-)" & budget$category=="low"]),NA)) %>%
#   mutate(higher_budget=ifelse(key=="1.5 budget (2020-)",start+(budget$value[budget$target=="1.5 budget (2020-)" & budget$category=="high"]),NA)) %>%
#   mutate(lower_budget=ifelse(key=="2.0 budget (2020-)",start+(budget$value[budget$target=="2.0 budget (2020-)" & budget$category=="low"]),lower_budget)) %>%
#   mutate(higher_budget=ifelse(key=="2.0 budget (2020-)",start+(budget$value[budget$target=="2.0 budget (2020-)" & budget$category=="high"]),higher_budget))


# add additional budget uncertainty of +-220 GtCO2
historical_budget <- historical_budget %>%
  mutate(ag_uncertainty=ifelse(id>3,220,ag_uncertainty))


# add uncertainty in the historical budgets

historical_budget <- historical_budget %>% 
  mutate(lower_uncertainty=end-ag_uncertainty) %>% 
  mutate(higher_uncertainty=end+ag_uncertainty)





historical_budget <- historical_budget %>%
  mutate(key=ifelse(key=="1.5 budget (2020-)","1.5\u00B0C budget",key)) %>%
  mutate(key=ifelse(key=="2.0 budget (2020-)","2\u00B0C budget",key))

historical_budget$key <- as.factor(historical_budget$key)
historical_budget$key <- fct_reorder(historical_budget$key,historical_budget$id)

color_scale <- c("#ffffcc","#a1dab4","#41b6c4","#2c7fb8","#253494")



p2 <- historical_budget %>% 
  ggplot(.,aes(fill=key)) +
  geom_rect(aes(x=key,
    xmin = id - 0.4,
    xmax = id + 0.4,
    ymin = start,
    ymax = end),
    colour = "#737373") +
  
  geom_rect(aes(x=key,
    xmin = id,
    xmax = id,
    ymin = lower_uncertainty,
    ymax = higher_uncertainty),
    colour = "#232323") +

  geom_rect(aes(
    xmin = id - 0.2,
    xmax = id + 0.2,
    ymin = lower_uncertainty,
    ymax = lower_uncertainty
  ),colour = "#232323") +

  geom_rect(aes(
    xmin = id - 0.2,
    xmax = id + 0.2,
    ymin = higher_uncertainty,
    ymax = higher_uncertainty
  ),colour = "#232323") +
  
  geom_text(aes(x=id,y=higher_uncertainty+400,label=paste(signif(value,2),"\n±",plyr::round_any(ag_uncertainty,5))),size=3.5,color="#737373",lineheight=0.85) +

  #geom_text(aes(x=id,y=ifelse(!is.na(higher_budget),higher_budget+250,end+250),label=paste(signif(value,2))),size=3.5,color="#737373") +

  #ylab('Carbon emissions,\n cumulative (GtCO2)') +
  ylab(bquote(~CO[2]*" emissions (Gt" ~CO[2]* ")")) +
  
  ylim(0,4400) +
  big_trend_theme +
  scale_fill_manual(values=color_scale) +
  scale_x_discrete(labels=str_wrap(historical_budget$key,8)) +
  theme(legend.position= "none",
        axis.title.x = element_blank()) +
  ggtitle(str_wrap("b. Historic emissions vs. future carbon budgets",width=30))
p2

```


```{r build_budget_scenarios, echo=FALSE,warning=FALSE}

# table of possible uncertainty scenarios

table <- expand.grid(budget=paste0(budget$target," ",budget$category),budget_uncertainty=c("High (+220 GtCO2)","Med (+0 GtCO2)","Low (-220 GtCO2)"),current_emissions=c("High (2019 emissions + CO2 uncertainty)","Med (2019 emissions)","Low (2019 emissions - CO2 uncertainty)"),reduction_rate=c("High (-5%/yr)","Med (-2%/yr)","None (-0%/yr)"))

table <- left_join(table,budget %>% mutate(budget=paste0(target," ",category)) %>% select(budget,budget_value=value),by = "budget")

table <- table %>% 
  mutate(budget_value=ifelse(budget_uncertainty=="High (+220 GtCO2)",budget_value+220,budget_value)) %>% 
  mutate(budget_value=ifelse(budget_uncertainty=="Low (-220 GtCO2)",budget_value-220,budget_value))

table <- table %>% 
  mutate(current_emissions_value=emissions_uncertainty$value) %>% 
  mutate(current_emissions_value=ifelse(current_emissions=="High (2019 emissions + CO2 uncertainty)",current_emissions_value+emissions_uncertainty$ag_uncertainty,current_emissions_value)) %>% 
  mutate(current_emissions_value=ifelse(current_emissions=="Low (2019 emissions - CO2 uncertainty)",current_emissions_value-emissions_uncertainty$ag_uncertainty,current_emissions_value))

table <- table %>% 
  mutate(reduction_rate_value=ifelse(grepl("High",reduction_rate),0.05,NA)) %>% 
  mutate(reduction_rate_value=ifelse(grepl("Med",reduction_rate),0.02,reduction_rate_value)) %>%
  mutate(reduction_rate_value=ifelse(grepl("None",reduction_rate),0,reduction_rate_value)) %>% 
  mutate(reduction_rate_value=ifelse(reduction_rate_value!=0,reduction_rate_value*current_emissions_value,0))

table <- table %>% 
  mutate(no = row_number())

# calculate how long it would take for the budgets to be exceeded, under different assumptions
table <- full_join(table,spread(data.frame(year=c(2020:2100),year_exceed=NA),year,year_exceed),by = character())
table <- gather(table,year,year_exceed,`2020`:`2100`)

# set reduction in 2020 to 0 (emissions are constant!)
table <- table %>% 
  mutate(reduction_rate_value=ifelse(year==2020,0,reduction_rate_value))

table <- table %>%
  mutate(cumulative_reduction=NA) %>% 
  group_by(no) %>% 
  mutate(cumulative_reduction = cumsum(reduction_rate_value))

table <- table %>% 
  mutate(current_emissions_value=current_emissions_value-cumulative_reduction) %>% 
  mutate(cumulative_emissions=cumsum(current_emissions_value))

# extract first year where budget exceeds
table <- table %>%
  mutate(year_exceed=ifelse(cumulative_emissions>budget_value,year,year_exceed))

year_exceed_extract <- table %>% 
  na.omit() %>% 
  group_by(no) %>% 
  summarise(year_exceed=first(year_exceed))

table <- left_join(table %>% select(-year_exceed),year_exceed_extract, by = "no")

# extract first year of net zero
table <- table %>% 
  mutate(year_netzero=NA) %>% 
  mutate(year_netzero=ifelse(current_emissions_value<=0,year,year_netzero))

year_netzero_extract <- table %>% 
  select(-year_exceed) %>% 
  na.omit() %>% 
  group_by(no) %>% 
  summarise(year_netzero=first(year_netzero))

table <- left_join(table %>% select(-year_netzero),year_netzero_extract, by = "no")
table <- table %>% 
  arrange(no)


# calculate overshoot
table <- table %>% 
  mutate(overshoot=ifelse(year>year_exceed & year<year_netzero,current_emissions_value,NA)) %>% 
  mutate(overshoot=ifelse(year>year_exceed & is.na(year_netzero),current_emissions_value,overshoot))

table <- table %>% 
  mutate(scenario=ifelse(budget_uncertainty=="High (+220 GtCO2)" & current_emissions=="Low (2019 emissions - CO2 uncertainty)","Best case",NA)) %>% 
  mutate(scenario=ifelse(budget_uncertainty=="Low (-220 GtCO2)" & current_emissions=="High (2019 emissions + CO2 uncertainty)","Worst case",scenario)) %>% 
  mutate(scenario=ifelse(budget_uncertainty=="Med (+0 GtCO2)" & current_emissions=="Med (2019 emissions)","Medium case",scenario))



table <- table %>% 
  select(no,budget,scenario,everything()) %>% 
  arrange(no)

```

```{r summary_table, echo=FALSE,warning=FALSE}


summary_table <- table %>% 
  filter(budget=="1.5 budget (2020-) 67%" | budget=="2.0 budget (2020-) 67%") %>% 
  filter(!is.na(scenario)) %>%
  group_by(no,budget,scenario,budget_uncertainty,current_emissions,reduction_rate) %>% 
  summarise(reduction_rate_value=last(reduction_rate_value),year_exceed=last(year_exceed),year_netzero=last(year_netzero),overshoot=signif(sum(overshoot,na.rm = TRUE),2))
  

figure_table <- summary_table %>% 
  arrange(scenario) %>% 
  group_by(budget,reduction_rate) %>% 
  summarise(year_netzero=first(year_netzero),
            year_exceed=paste0(nth(year_exceed,2)," (",nth(year_exceed,3),"-",nth(year_exceed,1),")"),
            overshoot=paste0(nth(overshoot,2)," (",nth(overshoot,3),"-",nth(overshoot,1),")"))

figure_table <- figure_table %>% mutate(reduction_rate=as.character(reduction_rate))
figure_table <- figure_table %>% 
  mutate(reduction_rate=ifelse(reduction_rate=="High (-5%/yr)","-5%/yr reductions",reduction_rate)) %>% 
  mutate(reduction_rate=ifelse(reduction_rate=="Med (-2%/yr)","-2%/yr reductions",reduction_rate)) %>% 
  mutate(reduction_rate=ifelse(reduction_rate=="None (-0%/yr)","-0%/yr reductions",reduction_rate))

figure_table <- figure_table %>% 
  mutate(budget=ifelse(budget=="1.5 budget (2020-) 67%","1.5\u00B0C (67%)",budget)) %>% 
  mutate(budget=ifelse(budget=="2.0 budget (2020-) 67%","2.0\u00B0C (67%)",budget))




figure_table <- gather(figure_table,var,value,-budget,-reduction_rate)
figure_table <- spread(figure_table,reduction_rate,value)

figure_table <- figure_table %>% 
  mutate(var=ifelse(var=="year_exceed","Budget exceedance year",var)) %>% 
  mutate(var=ifelse(var=="year_netzero","Net zero emissions year",var)) %>% 
  mutate(var=ifelse(var=="overshoot","Overshoot (GtCO2)",var))




figure_table$var<- as.factor(figure_table$var)
#figure_table$var <- factor(figure_table$var,levels=levels(figure_table$var)[c(2,3,1)])
figure_table <- figure_table %>% 
  arrange(budget,var)


figure_table <- figure_table %>% 
  rename(Budget=budget) %>% 
  rename(Variable=var)

p4 <- ggtexttable(figure_table, rows = NULL,theme = ttheme("light")) + ggtitle("blarg")
p4


```


```{r budget_dates_sheet, echo=FALSE,warning=FALSE,fig.width=6,fig.height=3}

# future_budget <- summary_table %>% 
#   filter(current_emissions=="Med (2019 emissions)") %>% 
#   filter(budget=="1.5 budget (2020-) 67%" | budget=="2.0 budget (2020-) 67%") %>% 
#   filter(budget_uncertainty=="Med (+0 GtCO2)") %>% 
#   mutate(year_exceed=as.numeric(year_exceed)) %>% 
#   mutate(year_netzero=as.numeric(year_netzero))
# 
# p3 <- future_budget %>% ggplot(.,aes(x=year_exceed,y=budget)) +
#   geom_point(color="red") +
#   geom_text(aes(x=year_exceed+1,y=budget,label=year_exceed),hjust=0,size=4) +
#   geom_point(inherit.aes = FALSE,data=future_budget,aes(x=year_netzero,y=budget),colour="blue") +
#   geom_text(aes(x=year_netzero+1,y=budget,label=year_netzero),hjust=0,size=4) +
#   facet_grid(reduction_rate~.) +
#   scale_x_continuous(limits = c(2020,2100)) +
#   theme(legend.position='none',
#          axis.title.y=element_blank()) +
#    xlab('Year of budget exceedance') 
# p3


```



```{r save, echo=FALSE,warning=FALSE}

wb <- openxlsx::createWorkbook(title = paste("ipcc_ar6_plot_CO2"))

openxlsx::addWorksheet(wb,"panel a CO2 trend")
openxlsx::addWorksheet(wb,"panel b historical budget")
openxlsx::addWorksheet(wb,"panel c table")
openxlsx::addWorksheet(wb,"budget summary")
openxlsx::addWorksheet(wb,"budget calculations")
openxlsx::addWorksheet(wb,"cumulative co2 different years")

openxlsx::writeData(wb, sheet = "panel a CO2 trend", spread(co2_trend,year,value), colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "panel b historical budget", historical_budget, colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "panel c table", figure_table, colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "budget summary", summary_table, colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "budget calculations", table, colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "cumulative co2 different years", cumulative, colNames = T, rowNames = F)

openxlsx::saveWorkbook(wb,paste0("../../Results/Plot data/ipcc_ar6_figure_long_term_co2.xlsx"),overwrite=T)



```

```{r budget_dates_old_budgets, echo=FALSE,warning=FALSE,fig.width=6,fig.height=3}

# time_data <- openxlsx::read.xlsx("../../Data/co2_budget_analysis.xlsx",sheet=3,startRow=43)
# 
# time_data <- time_data %>% 
#   mutate(Rate=as.factor(Rate)) %>% 
#   mutate(Budget=as.factor(Budget))
# time_data$Budget <- factor(time_data$Budget,levels(time_data$Budget)[c(2,1)])
# 
# 
# p3 <- time_data %>% ggplot(.,aes(x=Year.of.exceedance,y=Budget)) +
#   geom_point(color="red") +
#   geom_text(aes(x=Year.of.exceedance+1,y=Budget,label=Year.of.exceedance),hjust=0,size=4) +
#   geom_point(inherit.aes = FALSE,data=time_data,aes(x=Net.zero,y=Budget),colour="blue") +
#   geom_text(aes(x=Net.zero+1,y=Budget,label=Net.zero),hjust=0,size=4) +
#   facet_grid(Rate~.) +
#   scale_x_continuous(limits = c(2020,2100)) +
#   theme(legend.position='none',
#          axis.title.y=element_blank()) +
#    xlab('Year of budget exceedance') 

```

```{r long_term_co2, echo=FALSE,warning=FALSE,fig.width=10,fig.height=3.5,fig.path="../../Results/Plots/",dev=c('png','pdf')}

#p1 / (p2 + p4 + plot_layout(widths = c(1,3)))

#p1 / (p2 + p4 + plot_layout(widths = c(1,2.5)))

(p1 + p2 + plot_layout(widths=c(2.5,1))) #/ wrap_elements(p4 + plot_annotation(title="c. Carbon budget exceedance under different assumptions of current emissions, reduction rates and uncertainty") & theme(plot.tag = element_text(size = 8)))


```