---
title: "GHG emissions trends by region"
author: "William F. Lamb"
output: 
  word_document:
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results/knitr/") })

---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggplot2)
library(patchwork)
library(ggplot2); theme_set(theme_bw())
library(openxlsx)

source("small_figures.R")

load('../../Data/edgar6_v5_data_ghg_gwp_ar6.RData')
load('../../Data/gwps.RData')
load("../../Data/land.RData")
load('../../Data/WDI_gdp_pop.RData')
load('../../Data/ipcc_regions.RData')

options(dplyr.summarise.inform = FALSE)

# custom color palette
colors = c("#66c2a5","#fc8d62","#8da0cb","#e78ac3","#a6d854","#ffd92f","#cccccc","#969696","#636363")



```


```{r gather_data, echo=FALSE,warning=FALSE,fig.width=8,fig.height=4}

## sum GHG emissions for each region

region_trend <- edgar_ghg %>% 
  filter(year>1989) %>% 
  filter(year<=2019) %>% 
  group_by(year,region_ar6_6,region_ar6_6_short,region_ar6_10) %>% 
  summarise(value=sum(GHG,na.rm=TRUE)/1e9) %>% 
  ungroup() %>% 
  mutate(region_ar6_6_short=as.character(region_ar6_6_short))


## group aviation and shipping into a single region

region_trend <- region_trend %>%
  mutate(region_ar6_6=ifelse(region_ar6_6_short=="AIR","Intl. Shipping & Aviation",region_ar6_6)) %>% 
  mutate(region_ar6_6=ifelse(region_ar6_6_short=="SEA","Intl. Shipping & Aviation",region_ar6_6)) %>%  
  mutate(region_ar6_6_short=ifelse(region_ar6_6=="Intl. Shipping & Aviation","AIRSEA",region_ar6_6_short))


## Add land use CO2

region_trend <- left_join(region_trend,land %>% select(region_ar6_6,region_ar6_10,year,mean),by=c("year","region_ar6_6","region_ar6_10"))
region_trend <- region_trend %>% 
  mutate(mean=mean/1e9) %>% 
  mutate(value=ifelse(region_ar6_6_short!="AIRSEA",value+mean,value))


## sum everything into 6 regions and merge aviation and shipping

region_trend <- region_trend %>% 
  group_by(year,region_ar6_6,region_ar6_6_short) %>%
  summarise(value=sum(value))
  
## adjust levels to put shipping and aviation last

region_trend$region_ar6_6_short <- as.factor(region_trend$region_ar6_6_short)
region_trend$region_ar6_6_short <-  factor(region_trend$region_ar6_6_short,levels(region_trend$region_ar6_6_short)[c(1,3,4,5,6,7,2)])

region_trend$region_ar6_6 <- as.factor(region_trend$region_ar6_6)
region_trend$region_ar6_6 <-  factor(region_trend$region_ar6_6,levels(region_trend$region_ar6_6)[c(1,3,4,5,6,7,2)])


```

```{r trend_plot, echo=FALSE,warning=FALSE,fig.width=8,fig.height=4}


shares <- region_trend %>% 
  filter(year %in% c(1990,2000,2010,2019)) %>% 
  group_by(year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,region_ar6_6_short) %>% 
  mutate(fractions=(value/totals)*100)

shares <- locate_shares(shares,"region_ar6_6_short",4)

line_data <- data.frame(x=c(1990,1990,2000,2000,2010,2010,2019,2019),y=c(0,60))


### get the growth rates between time periods
rates <- region_trend %>% 
  filter(year %in% c(1990,1999,2000,2009,2010,2019)) %>% 
  group_by(year) %>% 
  summarise(value=sum(value)) %>% 
  mutate(total_rate=NA)

### leap year adjustment
# rates <- rates %>% 
#   mutate(leap_year = leap_year(year)) %>%
#   mutate(value_ly_adjusted = ifelse(leap_year=="TRUE",value*365/366,value))

rates$total_rate[rates$year==1990] = ((rates$value[rates$year==1999]/rates$value[rates$year==1990])^(1/(1999-1990))-1)*100
rates$total_rate[rates$year==2000] = ((rates$value[rates$year==2009]/rates$value[rates$year==2000])^(1/(2009-2000))-1)*100
rates$total_rate[rates$year==2010] = ((rates$value[rates$year==2019]/rates$value[rates$year==2010])^(1/(2019-2010))-1)*100
  

p1 <- region_trend %>%
  ggplot(.,aes(x=year,y=value,fill=region_ar6_6_short)) +
  geom_area(colour="#737373") +
  
  #### text with the shares
  geom_text(data=shares,aes(x=year+0.25,y=location,label=paste(round(fractions,0),"%",sep="")),size=3.5,colour="#252525",hjust=0)+
  
  geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed")  +
  
  #### text with the totals
  geom_text(data=shares %>% filter(region_ar6_6_short=="AIRSEA"),aes(x=year,y=62,label=paste(signif(totals,2),  "Gt")),size=3.5,colour="#252525")+
  
  #### text with the rates
  geom_text(data=rates %>% filter(!is.na(total_rate)),inherit.aes = FALSE,
                            aes(x=ifelse(year==2010,year+4.5,year+5),y=60,
                                label=paste0("+",round(total_rate,1),"%/yr")),size=3.5,colour="#252525") +
  
  scale_y_continuous(breaks=c(0,10,20,30,40,50,60),limits=c(0,62)) +
  scale_x_continuous(breaks=c(1990,2000,2010,2019)) +
  coord_cartesian(xlim = c(1990,2020), 
                  clip = 'off') +
  scale_fill_brewer(palette = "Set2") +
  theme(legend.position="none",
        plot.title = element_text(size = 11,color="#252525"),
        axis.title = element_text(color="#252525"),
        plot.background = element_blank(),
        plot.margin = margin(0,0,0,0,"cm")) +
  ylab(bquote("GHG Emissions (Gt" ~CO[2]* "eq/yr)")) +
  ggtitle("a. Trends in global and regional greenhouse gas emissions")


# side panel for the labels
p_labels <- region_trend %>%
  ggplot(.,aes(x=year,y=value,fill=region_ar6_6_short)) +
  geom_text(data=shares %>% filter(year==2019),aes(x=1,y=location,label=str_wrap(region_ar6_6,width=28),color=region_ar6_6_short,lineheight=0.65),hjust=0) +
  scale_color_brewer(palette = "Set2") +
  xlim(1,1.1) +
  ylim(0,62) +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        plot.background = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        legend.position="none")

p1 <- p1 + p_labels + plot_layout(widths=c(5,2.1))

```

```{r scenario_data, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3}

# New script as of 11.11.2021 using data provided directly by Ed Byers to match scenario categories with other SPM figures

scenario_data <- read.xlsx("../../Data/supplemetary data/ar6_full_metadata_indicators2021_10_14_v7.xlsx",
                          sheet=4)

# constrain scenarios
scenario_data <- scenario_data %>% 
  mutate(aggregated_category=ifelse(Category=="C3" & policy_category=="P2","C3a: Immediate action",NA)) %>%
  mutate(aggregated_category=ifelse(Category=="C3" & policy_category=="P2a","C3a: Immediate action",aggregated_category)) %>%
  mutate(aggregated_category=ifelse(Category=="C3" & policy_category=="P2b","C3a: Immediate action",aggregated_category)) %>%
  mutate(aggregated_category=ifelse(Category=="C3" & policy_category=="P2c","C3a: Immediate action",aggregated_category)) %>%
  mutate(aggregated_category=ifelse(Category=="C3" & policy_category=="P4","C3a: Immediate action",aggregated_category)) %>% 
  mutate(aggregated_category=ifelse(Category=="C3" & policy_category=="P0_2","C3a: Immediate action",aggregated_category)) %>% 
  mutate(aggregated_category=ifelse(Category=="C3" & grepl(c('P3b'),policy_category),"C3b: NDCs",aggregated_category)) %>%  
  mutate(aggregated_category=ifelse(Category=="C1","C1: Below 1.5\u00B0C with no or low overshoot",aggregated_category))


scenario_data <- scenario_data %>%
  filter(!is.na(aggregated_category)) %>% 
  select(model,scenario,aggregated_category,ghg_2020=`GHG.emissions.2020.Gt.CO2-equiv/yr`,ghg_2040=`GHG.emissions.2040.Gt.CO2-equiv/yr`)

# calculate growth rates
scenario_data <- scenario_data %>% 
  mutate(rate=((((ghg_2040/ghg_2020)^(1/(2040-2020)))-1))*100)

# scenario summary
scenario_summary <- scenario_data %>% 
  group_by(aggregated_category) %>% 
  summarise(min=min(rate),max=max(rate),n=n())


# match country data frame
scenario_data <- scenario_data %>%
  mutate(country="x") %>%
  mutate(ISO="x") %>%
  mutate(facet="Scenario reduction rates (2020-2040)") %>%
  mutate(emissions_total_2019=NA) %>%
  select(country,ISO,model,scenario,aggregated_category,rate,facet,emissions_total_2019)


# select scenarios within the 5 - 95th percentiles
percentiles <- scenario_data %>% 
  group_by(aggregated_category) %>%
  summarise(percentile_5th = quantile(rate, probs = c(0.05)),percentile_95th = quantile(rate, probs = c(0.95)))


scenario_data <- left_join(scenario_data,percentiles,by="aggregated_category")
scenario_data <- scenario_data %>%
  filter(rate>percentile_5th) %>%
  filter(rate<percentile_95th) %>%
  select(-percentile_5th,-percentile_95th)


# only c1a and c3
scenario_data <- scenario_data %>% 
  filter(aggregated_category!="C3b: NDCs")

scenario_data <- scenario_data %>% 
  mutate(aggregated_category=ifelse(aggregated_category=="C3a: Immediate action","C3a: Likely below 2\u00B0C with immediate action",aggregated_category))

```

```{r scenario_rates_old, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3}

# scenario_data <- read.csv("../../Data/supplemetary data/ar6_2021_10_14_emission_reduction_benchmarks.csv")
# 
# 
# scenario_data <- scenario_data %>% rename(rate=reduction_rates_2020.2040)
# 
# 
# scenario_data <- scenario_data %>% 
#   mutate(aggregated_category=NA) %>% 
#   mutate(aggregated_category=ifelse(grepl("C1",Category_name),"Below 1.5\u00B0C with no or low overshoot (C1)",aggregated_category)) %>% 
#   mutate(aggregated_category=ifelse(grepl("C3",Category_name),"Likely below 2\u00B0C (C3)",aggregated_category)) %>% 
#   mutate(aggregated_category=ifelse(grepl("C4",Category_name),"Below 2\u00B0C (C4)",aggregated_category))
# 
# 
# scenario_data <- scenario_data %>%
#   filter(!is.na(aggregated_category)) %>% 
#   filter(!is.na(rate)) %>% 
#   mutate(country="x") %>%
#   mutate(ISO="x") %>%
#   mutate(facet="Scenario reduction rates (2020-2040)") %>%
#   mutate(emissions_total_2019=NA) %>%
#   select(country,ISO,model,scenario,aggregated_category,rate,facet,emissions_total_2019)
# 
# 
# # select scenarios within the 5 - 95th percentiles
# percentiles <- scenario_data %>% 
#   group_by(aggregated_category) %>%
#   summarise(percentile_5th = quantile(rate, probs = c(0.05)),percentile_95th = quantile(rate, probs = c(0.95)))
# 
# 
# scenario_data <- left_join(scenario_data,percentiles,by="aggregated_category")
# scenario_data <- scenario_data %>% 
#   filter(rate>percentile_5th) %>% 
#   filter(rate<percentile_95th) %>% 
#   select(-percentile_5th,-percentile_95th)

```

```{r country_rates, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3}

## calculate rates of change for each country
region_rates <- edgar_ghg %>% 
  filter(region_ar6_6_short!="AIR") %>% 
  filter(region_ar6_6_short!="SEA") %>% 
  group_by(country,ISO,year,region_ar6_6,region_ar6_6_short) %>% 
  summarise(GHG=sum(GHG,na.rm = TRUE)) %>% 
  ungroup() %>% 
  rename(emissions_total=GHG)

# remove outliers
# region_rates <- region_rates %>%
#   filter(country!="Syrian Arab Republic") %>%
#   filter(country!="Yemen, Rep.")

# region_rates <- region_rates %>%
#  filter(ISO!="COK") %>%
#  filter(ISO!="FRO") %>%
#  filter(ISO!="GRL") %>%
#  filter(ISO!="IMN")

time_start = 2010

region_rates <- region_rates %>% 
  filter(year %in% c(time_start,2019)) %>% 
  group_by(country,ISO,region_ar6_6) %>% 
  summarise(rate=(last(emissions_total)/first(emissions_total))^(1/(last(year)-first(year)))-1,emissions_total_2019=last(emissions_total)) %>% 
  ungroup() %>% 
  mutate(rate=rate*100) %>% 
  mutate(aggregated_category=region_ar6_6) %>% 
  select(country,ISO,aggregated_category,rate,emissions_total_2019) %>% 
  mutate(facet="Average annual emissions change (2010-2019)") %>% 
  mutate(model=NA) %>% 
  mutate(scenario=NA)

# join to scenario data
region_rates <- rbind(region_rates,scenario_data)


```

```{r estimate_mean_rates, echo=FALSE,warning=FALSE}

# calculate mean rates for the scenario categories

region_rates <- region_rates %>% 
  group_by(aggregated_category) %>% 
  mutate(mean=mean(rate,na.rm=TRUE)) %>% 
  ungroup()

# calculate mean rates for regions (without LULUCF)

region_averages_nolulucf <- edgar_ghg %>% 
  filter(year %in% c(time_start,2019)) %>% 
  group_by(year,region_ar6_6) %>% 
  summarise(value=sum(GHG,na.rm=TRUE)/1e9) %>% 
  ungroup()

region_averages_nolulucf <- region_averages_nolulucf %>% 
  group_by(region_ar6_6) %>% 
  summarise(region_mean=(last(value)/first(value))^(1/(last(year)-first(year)))-1) %>% 
  ungroup() %>% 
  mutate(region_mean=region_mean*100)

# join data
region_rates <- left_join(region_rates,region_averages_nolulucf,by=c("aggregated_category"="region_ar6_6"))
region_rates <- region_rates %>% 
  mutate(mean=ifelse(!is.na(region_mean),region_mean,mean)) %>% 
  select(-region_mean)

# join population data for scaling dots (but use emissions total instead!!)
load('../../Data/WDI_gdp_pop.RData')

region_rates <- left_join(region_rates,wdi_data_gdp_pop %>% select(ISO=iso3c,year,population) %>% filter(year==2019),by="ISO")

# give a fake population and emissions total numbers to the scenarios
region_rates <- region_rates %>% 
  mutate(population=ifelse(facet=="Scenario reduction rates (2020-2040)",5e6,population)) %>% 
  mutate(emissions_total_2019=ifelse(facet=="Scenario reduction rates (2020-2040)",1e7,emissions_total_2019))

# re-order the scenario levels

region_rates <- region_rates %>% 
  mutate(aggregated_category = as.factor(aggregated_category))

region_rates$aggregated_category <- factor(region_rates$aggregated_category,levels= levels(region_rates$aggregated_category)[c(1,2,6,7,8,9,4,5,3)])


region_summary <- region_rates %>% 
  group_by(aggregated_category,facet) %>% 
  summarise(rate=first(mean))


```

```{r regions_scenarios, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3,dpi=300,fig.path="../../Results/Plots/",dev=c('png','pdf','svg')}



p2 <- region_rates %>% 
    mutate(facet=ifelse(facet=="Scenario reduction rates (2020-2040)","Scenario reduction rates\n (2020-2040)",facet)) %>% 
  ggplot(.,aes(x=aggregated_category,rate,fill=aggregated_category,color=aggregated_category,size=emissions_total_2019)) +
  geom_hline(yintercept=0,color="#636363") +
  geom_point(shape=21,color="#636363") +
  stat_summary(data = region_summary %>% mutate(facet=ifelse(facet=="Scenario reduction rates (2020-2040)","Scenario reduction rates\n (2020-2040)",facet)), geom = "crossbar",
                 width = .7,aes(color=aggregated_category),size=0.4) +
  scale_fill_manual(values=alpha(colors,0.5)) +
  scale_color_manual(values=colors) +
  scale_size_continuous(range=c(1.5,12)) +
  scale_x_discrete(labels = function(aggregated_category) str_wrap(aggregated_category, width = 10)) +
  facet_grid(.~facet,scales="free",space="free") +
  theme_bw() +
  ylab(str_wrap("Average annual GHG emissions growth rates (%)",width=27)) +
  theme(axis.title.x = element_blank(),
        legend.position = "none",
        panel.grid.minor = element_blank(),
        title = element_text(size=10)) 
p2 

```
```{r descriptive_stats, echo=FALSE,warning=FALSE}


# 1990 - 2019 abs change and growth
# 2010 - 2019 abs change and growth

region_growth <- region_trend %>% 
  filter(year %in% c(1990,2010,2019))
region_growth <- spread(region_growth,year,value)
region_growth <- region_growth %>% 
  mutate(`1990-2019 change (GtCO2eq)`=`2019`-`1990`) %>% 
  mutate(`1990-2019 change (%)`=((`2019`-`1990`)/(`1990`))*100) %>% 
  mutate(`2010-2019 change (GtCO2eq)`=`2019`-`2010`) %>% 
  mutate(`2010-2019 change (%)`=((`2019`-`2010`)/(`2010`))*100)


country_ghg <- edgar_ghg %>% 
  filter(year %in% c(1990,2010,2019)) %>% 
  group_by(ISO,country,region_ar6_6,region_ar6_dev,year) %>% 
  summarise(ghg=sum(GHG,na.rm=TRUE))

country_ghg <- left_join(country_ghg,wdi_data_gdp_pop %>% select(year,ISO=iso3c,population),by=c("ISO","year"))

country_ghg <- country_ghg %>% 
  filter(population!=0) %>% 
  mutate(per_capita=ghg/population) %>% 
  filter(population>=1e6)

country_ghg <- country_ghg %>% 
  group_by(year,region_ar6_6) %>% 
  summarise(min=min(per_capita,na.rm=TRUE),max=max(per_capita,na.rm=TRUE),population=sum(population,na.rm=TRUE)/1e9,ghg=sum(ghg,na.rm=TRUE)/1e9,per_capita=sum(ghg,na.rm=TRUE)/sum(population,na.rm=TRUE))

country_ghg <- country_ghg %>% 
  filter(population!=0)
  


country_co2 <- edgar_ghg %>% 
  filter(year %in% c(1990,2010,2019)) %>% 
  group_by(ISO,country,region_ar6_6,region_ar6_dev,year) %>% 
  summarise(co2=sum(CO2,na.rm=TRUE))

country_co2 <- left_join(country_co2,wdi_data_gdp_pop %>% select(year,ISO=iso3c,population),by=c("ISO","year"))

country_co2 <- country_co2 %>% 
  filter(region_ar6_6!="Intl. Aviation") %>% 
  filter(region_ar6_6!="Intl. Shipping") %>% 
  mutate(per_capita=co2/population)

country_co2_averages <- country_co2 %>% 
  group_by(year,region_ar6_6) %>% 
  summarise(pop_total=sum(population,na.rm=TRUE)/1e9,
            co2_total=sum(co2,na.rm=TRUE)/1e9,
            per_capita=sum(co2,na.rm=TRUE)/sum(population,na.rm=TRUE))

country_co2 <- country_co2 %>% 
  group_by(year,region_ar6_6) %>% 
  filter(population>=1e6) %>% 
  summarise(`min (pop>1e6)`=min(per_capita,na.rm=TRUE),`max (pop>1e6)`=max(per_capita,na.rm=TRUE))

country_co2 <- left_join(country_co2,country_co2_averages, by = c("year", "region_ar6_6"))

```

```{r per_capita_fraction,echo=FALSE,include=FALSE,warning=FALSE}

fraction <- edgar_ghg %>%
  filter(year==2019) %>% 
  group_by(year,country,ISO) %>% 
  summarise(CO2=sum(CO2,na.rm=TRUE))

fraction <- left_join(fraction,wdi_data_gdp_pop %>% select(iso3c,year,population),by=c("ISO"="iso3c","year"))

fraction <- fraction %>% 
  mutate(CO2_pc=CO2/population) %>% 
  mutate(threshold=ifelse(CO2_pc>12,">12tCO2/cap",NA)) %>% 
  mutate(threshold=ifelse(CO2_pc<3,"<3tCO2/cap",threshold)) 

summary <- fraction %>% 
  group_by(threshold) %>% 
  summarise(population=sum(population,na.rm=TRUE)/sum(fraction$population,na.rm=TRUE),emissions=sum(CO2)/sum(fraction$CO2))

wb2 <- openxlsx::createWorkbook(title = "per_capita_summary")

addWorksheet(wb2,"data")
addWorksheet(wb2,"summary")

writeData(wb2, sheet="data",fraction,colNames=T,rowNames=F)
writeData(wb2, sheet="summary",summary,colNames=T,rowNames=F)

openxlsx::saveWorkbook(wb2,paste0("../../Results/Data/per_capita_summary.xlsx"),overwrite=T)


```


```{r region_trends_spm, echo=FALSE,warning=FALSE,fig.width=8,fig.height=7,dpi=300,fig.path="../../Results/Plots/",dev=c('png','pdf','svg')}

p2 <- p2 + ggtitle("b. Recent emission change by region vs. rates compatible with warming targets")
regions <- p1 / p2 + plot_layout(heights = c(2, 1))
regions

```

```{r save,echo=FALSE,warning=FALSE}
wb <- openxlsx::createWorkbook(title = "ipcc_ar6_figure_spm_regions")

addWorksheet(wb,"info")
addWorksheet(wb,"panel a")
addWorksheet(wb,"panel a totals and rates")
addWorksheet(wb,"panel a shares")
addWorksheet(wb,"panel b")
addWorksheet(wb,"overall growth (not in figure)")
addWorksheet(wb,"region per cap (not in figure)")


info = data.frame(x=c("Author","Last update","Code","","Units","Panel a","Panel a totals","Panel a growth rates","Panel a shares","Panel b rates","Panel b emission totals","Panel b mean rates by region or scenario"),y=c("William F. Lamb",as.character(Sys.time()),"https://github.com/mcc-apsis/AR6-Emissions-trends-and-drivers/blob/master/R/Analysis%20and%20figures/emissions_by_region.Rmd","","","GtCO2eq","GtCO2eq","%/yr","%","%/yr","tCO2eq","%/yr"))

writeData(wb, sheet="info",info,colNames=F,rowNames=F)
writeData(wb, sheet = "panel a", spread(region_trend %>% select(-region_ar6_6_short),year,value), colNames = T, rowNames = F)
writeData(wb, sheet = "panel a totals and rates",rates, colNames = T, rowNames = F)
writeData(wb, sheet = "panel a shares",shares %>% select(-value,-totals) %>% rename(shares=fractions), colNames = T, rowNames = F)
writeData(wb, sheet = "panel b", region_rates %>% select(-population), colNames = T, rowNames = F)
writeData(wb, sheet = "overall growth (not in figure)", region_growth, colNames = T, rowNames = F)
writeData(wb, sheet = "region per cap (not in figure)", country_co2, colNames = T, rowNames = F)

openxlsx::saveWorkbook(wb,paste0("../../Results/Plot data/ipcc_ar6_figure_spm_regions.xlsx"),overwrite=T)


```
