---
title: "equity_perspectives"
author: "William F. Lamb"
date: "15 6 2021"
output: word_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results") })
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggplot2); theme_set(theme_bw())
library(patchwork)
library(RColorBrewer)
library(openxlsx)
library(scales)

end_year = 2019

load('../../Data/data_edgar_ghg.RData')
load('../../Data/data_land_co2.RData')
load('../../Data/ipcc_regions.RData')
load('../../Data/data_WDI_gdp_pop.RData')
load('../../Data/data_cumulative_co2.RData')

options(dplyr.summarise.inform = FALSE)

isos <- openxlsx::read.xlsx("C:/Users/lamw/ownCloud/Projects/Code/R/.Place names and codes/output/ISOcodes.xlsx","alternative_names")

sids <- read.xlsx('../../Data/Codes and classifications/SIDS_countries.xlsx') %>% 
  mutate(SIDS=ifelse(SIDS=="SIDS","sids",SIDS)) %>% 
  select(-country)

```


```{r gather_data,include=FALSE}

### edgar co2 2019

co2 <- edgar_ghg %>%
  filter(year==2019) %>% 
  group_by(region_ar6_10) %>%
  summarise(value=sum(CO2,na.rm=TRUE)) %>% 
  mutate(var="Production CO2 FFI (2019)") %>% 
  mutate(category="a. Current population and emissions by region")

co2 <- co2 %>% 
  mutate(total=sum(co2$value)) %>% 
  mutate(fraction=(value/total)) %>% 
  mutate(label=paste0(round(total/1e9)," GtCO2"))

co2_dev <- edgar_ghg %>%
  filter(year==2019) %>% 
  group_by(region_ar6_dev) %>%
  summarise(value=sum(CO2,na.rm=TRUE)) %>% 
  mutate(var="Production CO2 FFI (2019)") %>% 
  mutate(category="a. Current population and emissions by region")

co2_dev <- co2_dev %>% 
  mutate(total=sum(co2_dev$value)) %>% 
  mutate(fraction=(value/total)) %>% 
  mutate(label=paste0(round(total/1e9)," GtCO2"))

co2 <- rbind(co2,co2_dev %>% filter(region_ar6_dev=="ldc") %>% rename(region_ar6_10=region_ar6_dev))

co2_sids <- left_join(edgar_ghg,sids,by="ISO")

co2_sids <- co2_sids %>% 
  filter(year==2019) %>% 
  group_by(SIDS) %>%
  summarise(value=sum(CO2,na.rm=TRUE)) %>% 
  mutate(var="Production CO2 FFI (2019)") %>% 
  mutate(category="a. Current population and emissions by region")

co2_sids <- co2_sids %>% 
  mutate(total=sum(co2_sids$value)) %>% 
  mutate(fraction=(value/total)) %>% 
  mutate(label=paste0(round(total/1e9)," GtCO2"))

co2 <- rbind(co2,co2_sids %>% filter(SIDS=="SIDS") %>% rename(region_ar6_10=SIDS))


# population

pop <- left_join(edgar_ghg %>% ungroup() %>% select(ISO,region_ar6_10) %>% distinct(),wdi_data_gdp_pop %>% select(ISO=iso3c,year,population), by = "ISO")

pop <- pop %>% 
  filter(year==2019) %>% 
  group_by(region_ar6_10) %>% 
  summarise(value=sum(population,na.rm=TRUE)) %>% 
  mutate(var="Population (2019)") %>% 
  mutate(category="a. Current population and emissions by region")

pop_total <- sum(pop$value)

pop <- pop %>% 
  mutate(total=pop_total) %>% 
  mutate(fraction=(value/total)) %>% 
  mutate(label=paste0(round(total/1e9)," billion"))


pop_dev <- left_join(edgar_ghg %>% ungroup() %>% select(ISO,region_ar6_dev) %>% distinct(),wdi_data_gdp_pop %>% select(ISO=iso3c,year,population), by = "ISO")

pop_dev <- pop_dev %>% 
  filter(year==2019) %>% 
  group_by(region_ar6_dev) %>% 
  summarise(value=sum(population,na.rm=TRUE)) %>% 
  mutate(var="Population (2019)") %>% 
  mutate(category="a. Current population and emissions by region")

pop_dev <- pop_dev %>% 
  mutate(total=pop_total) %>% 
  mutate(fraction=(value/total)) %>% 
  mutate(label=paste0(round(total/1e9)," billion"))

pop <- rbind(pop,pop_dev %>% filter(region_ar6_dev=="ldc") %>% rename(region_ar6_10=region_ar6_dev))


pop_sids <- left_join(sids,wdi_data_gdp_pop %>% select(ISO=iso3c,year,population), by = "ISO")

pop_sids <- pop_sids %>% 
  filter(year==2019) %>% 
  group_by(SIDS) %>% 
  summarise(value=sum(population,na.rm=TRUE)) %>% 
  mutate(var="Population (2019)") %>% 
  mutate(category="a. Current population and emissions by region")

pop_sids <- pop_sids %>% 
  mutate(total=pop_total) %>% 
  mutate(fraction=(value/total)) %>% 
  mutate(label=paste0(round(total/1e9)," billion"))

pop <- rbind(pop,pop_sids %>% filter(SIDS=="sids") %>% rename(region_ar6_10=SIDS))


# consumption CO2

gcp_consumption_co2 <- read.xlsx('../../Data/Supplementary datasets/National_Carbon_Emissions_2020v1.0.xlsx',sheet=3)
gcp_consumption_co2[8,1] <- "year"
names(gcp_consumption_co2) <- gcp_consumption_co2[8,]
gcp_consumption_co2 <- gcp_consumption_co2[9:69,]
gcp_consumption_co2 <- gather(gcp_consumption_co2,country,value,-year)
gcp_consumption_co2 <- gcp_consumption_co2 %>% 
  mutate(country=ifelse(country=="Taiwan","Taiwan, China",country))

gcp_consumption_co2 <- left_join(gcp_consumption_co2 %>% mutate(country=tolower(country)),isos,
                                 by=c("country"="alternative.name"))

uhoh <- anti_join(gcp_consumption_co2 %>% select(ISO=alpha.3,everything()),ipcc_regions,by = "ISO")
gcp_consumption_co2 <- left_join(gcp_consumption_co2 %>% select(ISO=alpha.3,everything()),ipcc_regions,by = "ISO")


gcp_consumption_co2 <- gcp_consumption_co2 %>% 
  mutate(value=as.numeric(value)) %>% 
  mutate(value=value*(44/12)) %>% 
  mutate(value=value*1e6)

co2_cons <- gcp_consumption_co2 %>% 
  filter(year==2018) %>% 
  group_by(region_ar6_10) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(var="Consumption CO2 FFI (2018)") %>% 
  filter(!is.na(region_ar6_10)) %>% 
  mutate(category="a. Current population and emissions by region")

co2_cons <- co2_cons %>% 
  mutate(total=sum(co2_cons$value)) %>% 
  mutate(fraction=(value/total)) %>% 
  mutate(label=paste0(round(total/1e9)," GtCO2"))

co2_cons_dev <- gcp_consumption_co2 %>% 
  filter(year==2018) %>% 
  group_by(region_ar6_dev) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(var="Consumption CO2 FFI (2018)") %>% 
  filter(!is.na(region_ar6_dev)) %>% 
  mutate(category="a. Current population and emissions by region")

co2_cons_dev <- co2_cons_dev %>% 
  mutate(total=sum(co2_cons_dev$value)) %>% 
  mutate(fraction=(value/total)) %>% 
  mutate(label=paste0(round(total/1e9)," GtCO2"))

co2_cons <- rbind(co2_cons,co2_cons_dev %>% filter(region_ar6_dev=="ldc") %>% rename(region_ar6_10=region_ar6_dev))



### ghg excl lulucf emissions 2019

ghg <- edgar_ghg %>%
  filter(year==2019) %>% 
  group_by(region_ar6_10) %>%
  summarise(value=sum(GHG,na.rm=TRUE)) %>% 
  mutate(var="Production GHG, excl. LULUCF (2019)") %>% 
  mutate(category="a. Current population and emissions by region")

ghg <- ghg %>% 
  mutate(total= sum(ghg$value)) %>% 
  mutate(fraction = value/total) %>% 
  mutate(label=paste0(round(total/1e9)," GtCO2eq"))

ghg_dev <- edgar_ghg %>%
  filter(year==2019) %>% 
  group_by(region_ar6_dev) %>%
  summarise(value=sum(GHG,na.rm=TRUE)) %>% 
  mutate(var="Production GHG, excl. LULUCF (2019)") %>% 
  mutate(category="a. Current population and emissions by region")

ghg_dev <- ghg_dev %>% 
  mutate(total= sum(ghg_dev$value)) %>% 
  mutate(fraction = value/total) %>% 
  mutate(label=paste0(round(total/1e9)," GtCO2eq"))

ghg <- rbind(ghg,ghg_dev %>% filter(region_ar6_dev=="ldc") %>% rename(region_ar6_10=region_ar6_dev))


### LULUCF CO2

co2_land <- land %>% 
  group_by(region_ar6_10,year) %>%
  summarise(value=sum(mean,na.rm=TRUE))

# 2019

co2_land <- co2_land %>% 
  filter(year==2019) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(var="LULUCF CO2 (2019)") %>% 
  mutate(category="a. Current population and emissions by region")

co2_land <- co2_land %>% 
  mutate(total=sum(co2_land$value)) %>% 
  mutate(fraction=(value/total)) %>% 
  mutate(label=paste0(round(total/1e9)," GtCO2"))


### ghg incl lulucf emissions 2019

ghg_lulucf <- edgar_ghg %>%
  filter(year==2019) %>% 
  group_by(region_ar6_10) %>%
  summarise(ghg=sum(GHG,na.rm=TRUE))

ghg_lulucf <- left_join(ghg_lulucf,co2_land %>% select(region_ar6_10,co2_land=value),by = "region_ar6_10")
ghg_lulucf <- ghg_lulucf %>% 
  mutate(value = ghg+co2_land)
ghg_lulucf <- ghg_lulucf %>% 
  mutate(total=sum(ghg_lulucf$value,na.rm=TRUE)) %>% 
  mutate(fraction = value/total) %>% 
  mutate(var="Production GHG, incl. LULUCF (2019)") %>% 
  mutate(category="a. Current population and emissions by region") %>%  
  mutate(label=paste0(round(total/1e9)," GtCO2eq")) %>% 
  select(-ghg,-co2_land)


### long time series CO2

# co2_1750 <- hist_1750_6 %>% 
#   rename(value=co2_cum,fraction=share) %>% 
#   mutate(var="Territorial CO2, excl. LULUCF (1750-2019)") %>% 
#   mutate(category="b. Historical cumulative emissions by region") %>% 
#   select(-source)
# co2_1750 <- co2_1750 %>% 
#   mutate(total=sum(co2_1750$value)) %>% 
#   mutate(fraction=fraction/100) %>% 
#   mutate(label=paste0(round(total,0)," GtCO2eq"))
# 
# co2_1750_dev <- hist_1750_dev %>% 
#   rename(value=co2_cum,fraction=share) %>% 
#   mutate(var="Territorial CO2, excl. LULUCF (1750-2019)") %>% 
#   mutate(category="b. Historical cumulative emissions by region") %>% 
#   select(-source)
# co2_1750_dev <- co2_1750_dev %>% 
#   mutate(total=sum(co2_1750_dev$value)) %>% 
#   mutate(fraction=fraction/100) %>% 
#   mutate(label=paste0(round(total,0)," GtCO2eq"))
# 
# co2_1750 <- rbind(co2_1750,co2_1750_dev %>% filter(region_ar6_dev=="ldc") %>% rename(region_ar6_6=region_ar6_dev))



# incl LULUCF
co2_1850 <- hist_1850_10 %>% 
  group_by(region_ar6_10) %>% 
  summarise(value=sum(co2_cum),fraction=sum(share))

co2_1850 <- co2_1850 %>% 
  mutate(total=sum(co2_1850$value)) %>% 
  mutate(fraction=value/total) %>% 
  mutate(label=paste0(round(total,0),"\nGtCO2eq")) %>% 
  mutate(var="Production CO2, incl. LULUCF (1850-2019)") %>% 
  mutate(category="b. Historical cumulative emissions by region")


## excl LULUCF
co2_1850_ex <- hist_1850_10 %>% 
  rename(value=co2_cum,fraction=share) %>% 
  filter(source=="CO2-FFI") %>% 
  select(-source)

co2_1850_ex <- co2_1850_ex %>% 
  mutate(total=sum(co2_1850_ex$value)) %>% 
  mutate(fraction=value/total) %>% 
  mutate(label=paste0(round(total,0),"\nGtCO2eq")) %>% 
  mutate(var="Production CO2, excl. LULUCF (1850-2019)") %>% 
  mutate(category="b. Historical cumulative emissions by region")

co2_1850_dev <- hist_1850_dev %>% 
  group_by(region_ar6_dev) %>% 
  summarise(value=sum(co2_cum),fraction=sum(share))

co2_1850_dev <- co2_1850_dev %>% 
  mutate(total=sum(co2_1850_dev$value)) %>% 
  mutate(fraction=value/total) %>% 
  mutate(label=paste0(round(total,0),"\nGtCO2eq")) %>% 
  mutate(var="Production CO2, excl. LULUCF (1850-2019)") %>% 
  mutate(category="b. Historical cumulative emissions by region")

co2_1850_ex <- rbind(co2_1850_ex,co2_1850_dev %>% filter(region_ar6_dev=="ldc") %>% rename(region_ar6_10=region_ar6_dev))

data <- rbind(pop,co2)
data <- rbind(data,co2_cons)
data <- rbind(data,ghg)
data <- rbind(data,ghg_lulucf)
#data <- rbind(data,co2_land)
#data <- rbind(data,co2_1750)
data <- rbind(data,co2_1850)
data <- rbind(data,co2_1850_ex)


data <- data %>% 
  #add_row(region_ar6_6="ldc",var="LULUCF CO2 (2019)",category="a. Current population and emissions by region") %>% 
  add_row(region_ar6_10="ldc",var="Production CO2, incl. LULUCF (1850-2019)",category="b. Historical cumulative emissions by region") %>% 
  add_row(region_ar6_10="ldc",var="Production GHG, incl. LULUCF (2019)",category="a. Current population and emissions by region")



data$var <- as.factor(data$var)
data$category <- as.factor(data$category)
data$var <- fct_relevel(data$var,"Population (2019)","Consumption CO2 FFI (2018)","Production CO2 FFI (2019)","Production GHG, excl. LULUCF (2019)","Production GHG, incl. LULUCF (2019)","Production CO2, excl. LULUCF (1850-2019)","Production CO2, incl. LULUCF (1850-2019)")


```


```{r find_positions,echo=FALSE,warning=FALSE}

##### find positions for each region and % value
data_dev <- data

data <- data %>%
  filter(region_ar6_10!="Intl. Shipping") %>% 
  filter(region_ar6_10!="Intl. Aviation") %>% 
  filter(region_ar6_10!="Int. Aviation and Shipping") %>% 
  filter(region_ar6_10!="ldc") %>% 
  arrange(desc(region_ar6_10)) %>% 
  group_by(var) %>% 
  mutate(cumsum=cumsum(fraction)) %>%
  ungroup() %>% 
  mutate(position=fraction/2)


for (i in 1:length(unique(data$var))) {
  
  handle = unique(data$var)[i]
  
  for (j in 2:(length(data$region_ar6_10[data$var==handle]))) {
    
    data$position[data$var==handle][j] <- data$position[data$var==handle][j] + data$cumsum[data$var==handle][j-1]
    
  }
}



```

```{r save}

wb <- openxlsx::createWorkbook(title = "ipcc_ar6_figure_equity_perspectives")

addWorksheet(wb,"info")
addWorksheet(wb,"top panels")
addWorksheet(wb,"lower panels")

data <- data %>% 
  filter(!grepl("life",var))

info = data.frame(x=c("Author","Last update","Code"),y=c("William F. Lamb",as.character(Sys.time()),"https://github.com/mcc-apsis/AR6-Emissions-trends-and-drivers/blob/master/R/Analysis%20and%20figures/equity_perspectives.Rmd"))

writeData(wb, sheet="info",info,colNames=F,rowNames=F)
writeData(wb, sheet = "top panels", data %>% filter(region_ar6_10!="ldc"), colNames = T, rowNames = F)
writeData(wb, sheet = "lower panels", data_dev %>% filter(region_ar6_10=="ldc"), colNames = T, rowNames = F)

saveWorkbook(wb,"../../Results/Plot data/ipcc_ar6_figure_equity_perspectives.xlsx",overwrite=T)



```


```{r equity_perspectives,dpi=300,fig.width=11,fig.height=6,fig.path="../../Results/Plots/",dev=c('png','pdf')}

colors = colorRampPalette(brewer.pal(8, "Set2"))(11)

p1 <- data %>%
  filter(region_ar6_10!="ldc") %>% 
  filter(region_ar6_10!="sids") %>% 
  ggplot(.,aes(x=var,y=fraction,fill=region_ar6_10)) +
  geom_bar(stat='identity',color="#737373") +
  geom_text(data=data %>% filter(region_ar6_10=="Africa"),aes(x=var,y=1.05,label=label),vjust=0,lineheight=0.75,color="#525252") +
  geom_text(data=data %>% filter(region_ar6_10!="sids"),aes(x=var,y=position,label=paste0(round(fraction,2)*100,"%")),color="#525252") +
  scale_fill_manual(values=colors) +
  facet_grid(.~category,scales="free",space="free",labeller = (label_wrap_gen(width = 32))) +
  scale_y_continuous(labels = percent,breaks=c(0,0.25,0.50,0.75,1),limits=c(0,1.12)) +
  theme(legend.title=element_blank(),
        legend.position="none",
        axis.title = element_blank(),
        title = element_text(face="plain"),
        axis.text.x = element_blank(),
        plot.background = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        axis.text = element_text(size=10),
        legend.text = element_text(size=10),
        strip.text = element_text(size=10)) 

# side panel for the labels
p_labels <- data %>%
  filter(region_ar6_10!="ldc") %>% 
  filter(region_ar6_10!="sids") %>% 
  filter(var=="Production CO2, incl. LULUCF (1850-2019)") %>%
  ggplot(.,aes(x=1,y=position,label=str_wrap(region_ar6_10,width=20),color=region_ar6_10)) +
  geom_text(hjust=0,lineheight=0.75) +
  xlim(1,1.1) +
  scale_color_manual(values=colors) +
  scale_y_continuous(labels = percent,breaks=c(0,0.25,0.50,0.75,1),limits=c(0,1.08)) +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        plot.background = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        legend.position="none")


p2 <- data_dev %>% 
  filter(region_ar6_10=="ldc") %>%  
  ggplot(.,aes(x=var,y="a",label=paste0(round(fraction*100,1),"%"))) +
  geom_text() +
  facet_grid(.~category,scales="free",space="free") +
  scale_x_discrete(labels=label_wrap_gen(width=13,multi_line = TRUE)) +
  theme(legend.position="none",
        axis.title = element_blank(),
        title = element_text(face="plain"),
        axis.text.y = element_blank(),
        axis.text = element_text(size=10),
        legend.text = element_text(size=10),
        strip.background = element_blank(),
        strip.text = element_blank())

  
p_labels_2 <- data_dev %>%
  filter(region_ar6_10=="ldc") %>% 
  filter(category=="b. Historical cumulative emissions by region") %>%
  filter(var=="Production GHG, incl. LULUCF (2019)") %>%
  ggplot(.,aes(x=1,y="a",label=str_wrap("Least Developed Countries",width=15))) +
  geom_text(hjust=0,color="Grey",lineheight=0.75) +
  xlim(1,1.1) +
  #scale_color_brewer(palette="Set2") +
  #scale_y_continuous(labels = percent,breaks=c(0,0.25,0.50,0.75,1),limits=c(0,1.08)) +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        plot.background = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        legend.position="none")

(p1 + p_labels + p2 + p_labels_2 + plot_layout(heights=c(8,1),ncol=2,widths=c(4,1)))

```
