---
title: "Global emissions trends by gas"
author: "William F. Lamb"
output: word_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results/knitr/") })

---


```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(patchwork)
library(openxlsx)
library(ggplot2); theme_set(theme_bw())
library(lubridate)
library(janitor)

source("plot_theme.R")
source("locate_shares.R")

load('../../Data/data_edgar_ghg.RData')
load('../../Data/gwps.RData')
load('../../Data/data_land_co2.RData')

uncertainties <- data.frame(gas=c('CO2 FFI','CO2 LULUCF','CH4','N2O','Fgas'),
                            uncertainty=c(0.08,0.7,0.3,0.6,0.3))


```

```{r waterfall_data, echo=FALSE,warning=FALSE,include=FALSE}

###### calculate total emissions for different gases using different GWPs

waterfall_data <- edgar_raw %>%
  group_by(year,gas,gwp100_ar2,gwp100_ar5,gwp100_ar5_feedbacks,gwp100_ar6) %>%
  summarise(value=sum(value,na.rm=TRUE)) %>%
  mutate(value=value/1e9) %>%
  ungroup()

waterfall_data <- waterfall_data %>%
  mutate(gwp_ar2=gwp100_ar2*value) %>%
  mutate(gwp_ar5=gwp100_ar5*value) %>%
  mutate(gwp_ar5_feedbacks=gwp100_ar5_feedbacks*value) %>%
  mutate(gwp_ar6=gwp100_ar6*value) %>%
  group_by(year,gas) %>%
  summarise_at(vars(gwp_ar2:gwp_ar6),sum,na.rm=TRUE)

#### calculate fgas and land emissions

fgas <- waterfall_data %>%
  filter(!gas %in% c("CO2","CH4","N2O")) %>%
  group_by(year) %>%
  summarise_at(vars(gwp_ar2:gwp_ar6),sum,na.rm=TRUE) %>%
  mutate(gas="Fgas") %>%
  select(year,gas,everything())

land_totals <- land %>%
  filter(year>1969) %>%
  filter(year<2020) %>%
  group_by(year) %>%
  summarise(CO2_LULUCF=sum(mean)/1e9)

waterfall_land <- land_totals %>%
  mutate(gas="CO2 LULUCF") %>%
  mutate(gwp_ar2=CO2_LULUCF) %>%
  mutate(gwp_ar5=CO2_LULUCF) %>%
  mutate(gwp_ar5_feedbacks=CO2_LULUCF) %>%
  mutate(gwp_ar6=CO2_LULUCF) %>%
  select(-CO2_LULUCF)

waterfall_data <- waterfall_data %>% filter(gas %in% c("CO2","CH4","N2O"))
waterfall_data <- rbind(waterfall_data,fgas)
waterfall_data <- rbind(waterfall_data,waterfall_land)

waterfall_data <- waterfall_data %>%
  mutate(gas=as.character(gas)) %>%
  mutate(gas=ifelse(gas=="CO2","CO2 FFI",gas))

waterfall_data <- waterfall_data %>%
  filter(year==2019) %>%
  select(-year)

# reorder levels
waterfall_data$gas <- as.factor(waterfall_data$gas)
waterfall_data$gas <-  factor(waterfall_data$gas,levels(waterfall_data$gas)[c(2,3,1,5,4)])
waterfall_data <- waterfall_data %>% arrange(gas)


######### save data #########

save_waterfall_data <- waterfall_data

######### plot different gwp totals in a waterfall


waterfall_data <- gather(waterfall_data,gwp,value,gwp_ar2:gwp_ar6)

waterfall_data <- waterfall_data %>%
  group_by(gwp) %>%
  mutate(end = cumsum(value)) %>%
  mutate(start = c(0, head(end, -1))) %>%
  mutate(id = c(5,4,3,2,1))

### add uncertainties

waterfall_data <- left_join(waterfall_data,uncertainties,by=c("gas"="gas"))
waterfall_data <- waterfall_data %>%
  group_by(gwp) %>%
  mutate(abs_uncertainty=value*uncertainty) %>%
  mutate(uncertainty_start=end-abs_uncertainty) %>%
  mutate(uncertainty_end=end+abs_uncertainty) %>%
  group_by(gwp) %>%
  mutate(total=sum(value))

waterfall_data$gas <- as.factor(waterfall_data$gas)
waterfall_data$gas <-  factor(waterfall_data$gas,levels(waterfall_data$gas)[c(4,5,1,3,2)])

waterfall_data$gwp <- as.factor(waterfall_data$gwp)
waterfall_data$gwp <-  factor(waterfall_data$gwp,levels(waterfall_data$gwp)[c(4,3,2,1)])


```

```{r waterfall_plot, echo=FALSE,warning=FALSE,include=FALSE,fig.width=3,fig.height=4}

### plot

colours = c("#e78ac3","#fc8d62","#8da0cb","#66c2a5","#a6d854")

p_waterfall <- waterfall_data %>%
  ggplot(., aes(fill = gas)) +
  scale_fill_manual(values=colours) +
  
  geom_rect(aes(
    x = gas,
    xmin = id - 0.48,
    xmax = id + 0.48,
    ymin = start,
    ymax = end
  ),colour = "#737373") +

  geom_rect(aes(
    xmin = id,
    xmax = id,
    ymin = uncertainty_start,
    ymax = uncertainty_end
  ),colour = "#252525") +

  geom_rect(aes(
    xmin = id - 0.2,
    xmax = id + 0.2,
    ymin = uncertainty_start,
    ymax = uncertainty_start
  ),colour = "#252525") +

  geom_rect(aes(
    xmin = id - 0.2,
    xmax = id + 0.2,
    ymin = uncertainty_end,
    ymax = uncertainty_end
  ),colour = "#252525") +

   facet_grid(~gwp,switch="both") +

   geom_text(data=waterfall_data %>% filter(gas=="CH4"),aes(x=gas,y=62,label=paste(round(total,0),  "Gt")),size=3.5,colour="#252525") +

   theme_bw() +
   scale_y_continuous(breaks=c(0,10,20,30,40,50,60)) +
   scale_x_discrete(labels=c("","","","","")) +
   theme(
     legend.position = "none",
     title = element_blank(),
     axis.title.y = element_blank(),
     axis.ticks.y = element_blank(),
     axis.text.y = element_blank(),
     axis.ticks.x = element_blank(),
     panel.grid.minor.x = element_blank(),
     panel.grid.minor.y = element_blank(),
     panel.grid.major.x = element_blank(),
     panel.spacing = unit(0, "mm"),
     strip.background = element_blank())

p_waterfall

```

```{r gas_trend, echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=4}


gas_trend <- edgar_ghg %>% 
  filter(year>1989) %>% 
  filter(year<2020) %>% 
  group_by(year) %>% 
  summarise(CO2=sum(CO2,na.rm=T)/1e9,CH4=sum(CH4,na.rm=T)/1e9,N2O=sum(N2O,na.rm=T)/1e9,Fgas=sum(Fgas,na.rm=T)/1e9)

### join land use data

gas_trend <- left_join(gas_trend,land_totals,by=c("year"="year"))
gas_trend<- gather(gas_trend,gas,value,-year) 
gas_trend <- gas_trend %>% 
  mutate(gas=ifelse(gas=="CO2","CO2 FFI",gas)) %>% 
  mutate(gas=ifelse(gas=="CO2_LULUCF","CO2 LULUCF",gas))

gas_trend$gas <- as.factor(gas_trend$gas)
gas_trend$gas <-  factor(gas_trend$gas,levels(gas_trend$gas)[c(4,5,1,3,2)])

### get the shares and totals in each time period

shares <- gas_trend %>% 
  filter(year %in% c(1990,2000,2010,2019)) %>% 
  group_by(year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,gas) %>% 
  mutate(fractions=(value/totals)*100) %>% 
  mutate(fractions=round(fractions,0))

shares <- locate_shares(shares,"gas",4)

line_data <- data.frame(x=c(1990,1990,2000,2000,2010,2010,2019,2019),y=c(0,60))

### get the growth rates between time periods
rates <- gas_trend %>% 
  filter(year %in% c(1990,1999,2000,2009,2010,2019)) %>% 
  group_by(year) %>% 
  summarise(value=sum(value)) %>% 
  mutate(total_rate=NA)

### leap year adjustment
# rates <- rates %>% 
#   mutate(leap_year = leap_year(year)) %>%
#   mutate(value_ly_adjusted = ifelse(leap_year=="TRUE",value*365/366,value))

rates$total_rate[rates$year==1990] = ((rates$value[rates$year==1999]/rates$value[rates$year==1990])^(1/(1999-1990))-1)*100
rates$total_rate[rates$year==2000] = ((rates$value[rates$year==2009]/rates$value[rates$year==2000])^(1/(2009-2000))-1)*100
rates$total_rate[rates$year==2010] = ((rates$value[rates$year==2019]/rates$value[rates$year==2010])^(1/(2019-2010))-1)*100
  
rates <- rates %>% 
  mutate(total_rate=round(total_rate,1)) %>% 
  mutate(value=signif(value,2))

p_gas_totals <- gas_trend %>% 
  ggplot(.,aes(x=year,y=value,fill=gas)) +
  geom_area(colour="#737373") +
  
  geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  
  #### text with the shares
  geom_text(data=shares,aes(x=year+0.25,y=location,label=paste(round(fractions,0),"%",sep="")),size=3.5,colour="#252525",hjust=0)+
  
  #### text with the rates
  geom_text(data=rates %>% filter(!is.na(total_rate)),inherit.aes = FALSE,
                            aes(x=ifelse(year==2010,year+4.5,year+5),y=60,
                                label=paste0("+",round(total_rate,1),"%/yr")),size=3.5,colour="#252525") +
  
  #### text with the totals
  geom_text(data=shares %>% filter(gas=="Fgas"),aes(x=year,y=62,label=paste(round(totals,0),  "Gt")),size=3.5,colour="#252525")+
  ylab(bquote("Greenhouse gas emissions (Gt" ~CO[2]* "eq/yr)")) +
  labs(fill="Gas") +
  scale_y_continuous(breaks=c(0,10,20,30,40,50,60)) +
  scale_x_continuous(breaks=c(1990,2000,2010,2019)) +
  scale_fill_manual(values=c("#e78ac3","#fc8d62","#8da0cb","#66c2a5","#a6d854")) +
  big_trend_theme +
  theme(
    legend.position="none",    
    legend.background = element_rect(linetype = 1, size = 0.5, colour = "#525252"),
    legend.margin = margin(l=5,t=5,b=5,r=10,unit="pt"),
    legend.text = element_text(size=8),
    legend.title = element_text(size=8)) +
  guides(fill=guide_legend(nrow=1,byrow=TRUE),
    shape = guide_legend(override.aes = list(size = 0.5)),
    color = guide_legend(override.aes = list(size = 0.5)))+
  ggtitle("a. Total anthropogenic GHG emissions 1990-2019")

p_gas_totals

```

```{r write_table, echo=FALSE,warning=FALSE}

# write uncertainties into the table of GHG estimates

table <- gas_trend
table <- left_join(table,uncertainties,by = "gas")
table <- table %>% 
  mutate(uncertainty=uncertainty*value) %>% 
  mutate(uncertainty2=uncertainty^2) %>% 
  rename(level=value)

table_total <- table %>% 
  group_by(year) %>% 
  summarise(gas="Total",level=sum(level),uncertainty=sqrt(sum(uncertainty2)))

table <- rbind(table %>% select(-uncertainty2),table_total)
table <- gather(table,var,value,level,uncertainty)

table$gas <- as.factor(table$gas)
table$gas <- factor(table$gas,levels(table$gas)[c(2,3,1,5,4,6)])


# produce a table to go under SPM1

spm_table <- spread(table,var,value)
spm_table <- spm_table %>% 
  filter(year==2019) %>% 
  group_by(gas) %>% 
  summarise(level=paste0(signif(level,2),"±",signif(uncertainty,2)))

growth <- gas_trend %>% 
  filter(year %in% c(1990,2019))

growth_total <- growth %>% 
  group_by(year) %>%
  summarise(gas="Total",value=sum(value))

growth <- rbind(growth,growth_total) %>% 
  group_by(gas) %>% 
  summarise(growth_abs=last(value)-first(value),growth_rel=((last(value)-first(value))/first(value))*100) %>% 
  mutate(growth_rel=growth_rel+100) #

growth <- growth %>%
  mutate(growth_rel=signif(growth_rel,3)) %>% 
  mutate(growth_abs=signif(growth_abs,2))


spm_table <- left_join(spm_table,growth,by = "gas")
names(spm_table) <- c("gas","2019 Emissions (GtCO2eq)","1990-2019 Growth (GtCO2eq)","Change in GHG emissions, relative to 1990 (%)") 

# spm_table <- spm_table %>% 
#   t %>% 
#   as.data.frame() %>% 
#   row_to_names(1)

```

```{r short_waterfall_plot, echo=FALSE,warning=FALSE,include=FALSE,fig.width=3,fig.height=4}

### plot

colours = c("#e78ac3","#fc8d62","#8da0cb","#66c2a5","#a6d854")

p_waterfall_short <- waterfall_data %>%
  filter(gwp=="gwp_ar6") %>% 
  ggplot(., aes(fill = gas)) +
  scale_fill_manual(values=colours) +
  
  geom_rect(aes(
    x = gas,
    xmin = id - 0.5,
    xmax = id + 0.5,
    ymin = start,
    ymax = end
  ),colour = "#737373") +

  geom_rect(aes(
    xmin = id,
    xmax = id,
    ymin = uncertainty_start,
    ymax = uncertainty_end
  ),colour = "#252525") +

  geom_rect(aes(
    xmin = id - 0.2,
    xmax = id + 0.2,
    ymin = uncertainty_start,
    ymax = uncertainty_start
  ),colour = "#252525") +

  geom_rect(aes(
    xmin = id - 0.2,
    xmax = id + 0.2,
    ymin = uncertainty_end,
    ymax = uncertainty_end
  ),colour = "#252525") +

   #facet_grid(~gwp,switch="both") +

   #geom_text(data=waterfall_data %>% filter(gas=="CH4"),aes(x=gas,y=62,label=paste(round(total,0),  "Gt")),size=3.5,colour="#252525") +

   theme_bw() +
   scale_y_continuous(breaks=c(0,10,20,30,40,50,60),limits=c(0,66)) +
   scale_x_discrete(labels=c("","","","","")) +
   theme(
     legend.position = "none",
     title = element_blank(),
     axis.title.y = element_blank(),
     axis.ticks.y = element_blank(),
     axis.text.y = element_blank(),
     axis.ticks.x = element_blank(),
     panel.grid.minor.x = element_blank(),
     panel.grid.minor.y = element_blank(),
     panel.grid.major.x = element_blank(),
     panel.spacing = unit(0, "mm"),
     strip.background = element_blank(),
     panel.border = element_blank())


stack_data <- table %>% 
  filter(year==2019) %>% 
  filter(var=="level") %>% 
  filter(gas!="Total") %>%
  ungroup() %>% 
  select(-var)

stack_data <- left_join(stack_data,table %>% filter(var=="uncertainty") %>% filter(gas=="Total") %>% select(year,uncertainty=value),by="year")

stack_data <- stack_data %>% 
  mutate(uncertainty_start=sum(stack_data$value)-uncertainty) %>% 
  mutate(uncertainty_end=sum(stack_data$value)+uncertainty) %>% 
  mutate(gas=as.character(gas)) %>% 
  mutate(gas=as.factor(gas))

stack_data$gas <- factor(stack_data$gas,levels=levels(stack_data$gas)[c(4,5,1,3,2)])

p_stack <- stack_data %>% 
  filter(year==2019) %>% 
  ggplot(.,aes(x=year,y=value,fill=gas)) +
  geom_bar(stat='identity',colour = "#252525",width=1) +
  
  geom_rect(aes(
    xmin = year,
    xmax = year,
    ymin = uncertainty_start,
    ymax = uncertainty_end
  ),colour = "#252525") +

  geom_rect(aes(
    xmin = year - 0.2,
    xmax = year + 0.2,
    ymin = uncertainty_start,
    ymax = uncertainty_start
  ),colour = "#252525") +

  geom_rect(aes(
    xmin = year - 0.2,
    xmax = year + 0.2,
    ymin = uncertainty_end,
    ymax = uncertainty_end
  ),colour = "#252525") +
  
  scale_fill_manual(values=colours) +
  theme_bw() +
  scale_y_continuous(breaks=c(0,10,20,30,40,50,60),limits=c(0,66)) +
  scale_x_continuous(breaks=c(2019)) +
  theme(
     legend.position = "none",
     title = element_blank(),
     axis.title.y = element_blank(),
     axis.ticks.y = element_blank(),
     axis.text.y = element_blank(),
     axis.ticks.x = element_blank(),
     panel.grid.minor.x = element_blank(),
     panel.grid.minor.y = element_blank(),
     panel.grid.major.x = element_blank(),
     panel.spacing = unit(0, "mm"),
     strip.background = element_blank(),
     panel.border = element_blank())
p_stack
p_waterfall_short <- p_stack + p_waterfall_short + plot_layout(widths=c(1,5))
p_waterfall_short
```



```{r ghgs_no_gwp, echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=2}


gas_trend_nogwp <- edgar_raw %>%
  filter(year<2020) %>% 
  filter(gas %in% c("CO2","CH4","N2O")) %>% 
  group_by(year,gas) %>%
  summarise(value=sum(value,na.rm=TRUE))

fgas_trend <- edgar_ghg %>% 
  filter(year<2020) %>% 
  group_by(year) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)) %>% 
  mutate(gas="Fgas")

gas_trend_nogwp <- rbind(gas_trend_nogwp,land_totals %>% select(year,value=CO2_LULUCF) %>% mutate(gas="CO2 LULUCF") %>% mutate(value=value*1e9))
gas_trend_nogwp <- rbind(gas_trend_nogwp,fgas_trend)
gas_trend_nogwp <- gas_trend_nogwp %>% mutate(gas=ifelse(gas=="CO2","CO2 FFI",gas))


# Normalise to 1 in 1990
gas_trend_nogwp <- gas_trend_nogwp %>%
  filter(year>1989) %>%
  group_by(gas) %>%
  mutate(value=value/(value[year==1990])) %>% 
  mutate(value=value*100)

# calculate error range
gas_trend_nogwp <- left_join(gas_trend_nogwp,uncertainties,by = "gas")

gas_trend_nogwp <- gas_trend_nogwp %>%
  mutate(high = value+((uncertainty*value))) %>%
  mutate(low = value-((uncertainty*value))) %>%
  select(-uncertainty)

# Normalise to 1 in 1990
# gas_trend_nogwp <- gas_trend_nogwp %>%
#   filter(year>1989) %>%
#   group_by(gas) %>%
#   mutate(high=high/(value[year==1990])) %>% 
#   mutate(low=low/(value[year==1990])) %>% 
#   mutate(value=value/(value[year==1990]))



#manually map colours
gas_trend_nogwp$gas <- as.factor(gas_trend_nogwp$gas)
gas_trend_nogwp$gas <- factor(gas_trend_nogwp$gas,levels=levels(gas_trend_nogwp$gas)[c(2,3,1,5,4)])
colours = c("#a6d854","#66c2a5","#8da0cb","#fc8d62","#e78ac3")


p_gas_trends <- gas_trend_nogwp %>%
  ggplot(.,aes(x=year,y=value)) +
  geom_hline(yintercept = 100,color="#636363") +
  geom_line(aes(color=gas)) +
  geom_ribbon(data=gas_trend_nogwp,aes(ymin=low,ymax=high,fill=gas),alpha=0.3)+
  scale_x_continuous(breaks=c(1990,2000,2010)) +
  scale_fill_manual(values=colours) +
  scale_color_manual(values=colours) +
  theme_bw() +
  ylab(str_wrap('Emissions (original units, relative to 1990)',width=26)) +
  facet_wrap(.~gas,nrow=1) +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_text(margin=margin(0,10,0,0)),
        text = element_text(size=11),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank())



p_gas_trends


```

```{r ghgs_no_gwp_scales, echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=2}


p1 <- gas_trend_nogwp %>%
  filter(gas!="Fgas") %>%
  ggplot(.,aes(x=year,y=value)) +
  geom_hline(yintercept = 100,color="#636363") +
  geom_line(aes(color=gas),width=2) +
  geom_ribbon(data=gas_trend_nogwp %>% filter(gas!="Fgas"),aes(ymin=low,ymax=high,fill=gas),alpha=0.3)+
  scale_x_continuous(breaks=c(1990,2000,2010)) +
  scale_fill_manual(values=colours) +
  scale_color_manual(values=colours) +
  theme_bw() +
  ylab('Change in GHG emissions\nrelative to 1990 (%)') +
  facet_wrap(.~gas,nrow=1) +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_text(margin=margin(0,10,0,0)),
        text = element_text(size=11),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  ggtitle("b. Change in GHG emissions and uncertainties - relative to 1990")

p2 <- gas_trend_nogwp %>%
  filter(gas=="Fgas") %>%
  ggplot(.,aes(x=year,y=value)) +
  geom_hline(yintercept = 100,color="#636363") +
  geom_line(aes(color=gas),width=2) +
  geom_ribbon(data=gas_trend_nogwp %>% filter(gas=="Fgas"),aes(ymin=low,ymax=high,fill=gas),alpha=0.3)+
  scale_x_continuous(breaks=c(1990,2000,2010)) +
  #scale_y_continuous(limits = c(-3,7),breaks=c(-2,1,2,4)) +
  scale_fill_manual(values="#e78ac3") +
  scale_color_manual(values="#e78ac3") +
  theme_bw() +
  facet_wrap(.~gas,nrow=1) +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size=11),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),plot.background = element_blank())


p_gas_trends_scaled <- p1 + p2 + plot_layout(width = c(4,1))
p_gas_trends_scaled

```

```{r gas_trends_spm, echo=FALSE,warning=FALSE,fig.width=8,fig.height=6,fig.path="../../Results/Plots/",dev=c('png','pdf')}


#########

(p_gas_totals + p_waterfall + plot_layout(width = c(3, 1))) / p_gas_trends_scaled + plot_layout(height = c(3,1))


```



```{r write_table_archive, echo=FALSE,warning=FALSE}

#dataset in the ipcc archive format


wb <- createWorkbook(title = paste("ipcc_ar6_figure_spm_1_archive"))

addWorksheet(wb,"panel_a")
addWorksheet(wb,"panel_a_totals_and_rates")
addWorksheet(wb,"panel_a_shares")
addWorksheet(wb,"panel_a_waterfall")
addWorksheet(wb,"panel_a_stack")
addWorksheet(wb,"panel_b")
addWorksheet(wb,"table")

table_archive <- gather(table,year,value,-gas,-var)
table_archive <- table_archive %>% filter(var=="level") %>% filter(gas!="Total") %>% select(-var)

waterfall_data_archive <- waterfall_data %>% 
  filter(gwp=="gwp_ar6") %>% 
  ungroup() %>% 
  select(gas,value,start,end,uncertainty=abs_uncertainty,uncertainty_start,uncertainty_end,total)

writeData(wb, sheet = "panel_a", table_archive, colNames = T, rowNames = F)
writeData(wb, sheet = "panel_a_totals_and_rates", rates %>% filter(!is.na(total_rate)) %>% select(year,total=value,rate=total_rate), colNames = T, rowNames = F)
writeData(wb, sheet = "panel_a_shares", shares %>% select(year,gas,shares=fractions), colNames = T, rowNames = F)
writeData(wb, sheet = "panel_a_waterfall",waterfall_data_archive, colNames = T, rowNames = F)
writeData(wb, sheet = "panel_a_stack",stack_data %>% select(-year), colNames = T, rowNames = F)
writeData(wb, sheet = "panel_b", gas_trend_nogwp, colNames = T, rowNames = F)
writeData(wb, sheet = "table", spm_table, colNames = T, rowNames = F)

saveWorkbook(wb,paste0("../../Results/Plot data/ipcc_ar6_figure_spm_1_archive.xlsx"),overwrite=T)


```



```{r save_data, echo=FALSE,warning=FALSE}

##### write data

wb <- createWorkbook(title = paste("ipcc_ar6_figure_spm1_gases"))

addWorksheet(wb,"panel_a")
addWorksheet(wb,"panel_a_totals_and_rates")
addWorksheet(wb,"panel_a_shares")
addWorksheet(wb,"panel_a_waterfall")
addWorksheet(wb,"panel_a_stack")
addWorksheet(wb,"panel_b")
addWorksheet(wb,"table")

info = data.frame(x=c("Author","Last update","Code","","Units","Panel a","Panel a totals","Panel a rates","Panel a shares","Panel b","Panel c"),y=c("William F. Lamb",as.character(Sys.time()),"https://github.com/mcc-apsis/AR6-Emissions-trends-and-drivers/blob/master/R/Analysis%20and%20figures/emissions_by_gas.Rmd","","","GtCO2eq","GtCO2eq","%/yr","%","GtCO2eq","t native units (normalised to 1 in 1990)"))

gas_trend_nogwp_spread <- gather(gas_trend_nogwp,var,value,value:low)
gas_trend_nogwp_spread <- spread(gas_trend_nogwp_spread,year,value)

writeData(wb, sheet = "panel_a", table <- spread(table,year,value) %>% arrange(var), colNames = T, rowNames = F)
writeData(wb, sheet = "panel_a_totals_and_rates", rates %>% filter(!is.na(total_rate)) %>% select(year,total=value,rate=total_rate), colNames = T, rowNames = F)
writeData(wb, sheet = "panel_a_shares", shares %>% select(year,gas,shares=fractions), colNames = T, rowNames = F)
writeData(wb, sheet = "panel_a_waterfall",waterfall_data_archive, colNames = T, rowNames = F)
writeData(wb, sheet = "panel_a_stack",stack_data %>% select(-year), colNames = T, rowNames = F)
writeData(wb, sheet = "panel_b", gas_trend_nogwp_spread, colNames = T, rowNames = F)
writeData(wb, sheet = "table", spm_table, colNames = T, rowNames = F)

saveWorkbook(wb,paste0("../../Results/Plot data/ipcc_ar6_figure_spm_gases.xlsx"),overwrite=T)

```
