---
title: "emissions_by_country"
author: "William F. Lamb"
date: "17 11 2020"
output: 
  word_document:
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results/knitr/") })

---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(openxlsx)
library(ggplot2); theme_set(theme_bw())

source("locate_shares.R")
source("plot_theme.R")

options(dplyr.summarise.inform = FALSE)

load('../../Data/data_edgar_ghg.RData')
load("../../Data/data_land_co2.RData")
load('../../Data/data_WDI_gdp_pop.RData')
load('../../Data/data_primap_ghg.RData')
load('../../Data/gwps.RData')

# set palette
ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2")


```

```{r region_data,echo=FALSE,warning=FALSE,include=FALSE}

## sum GHG emissions for each region

plot_data <- edgar_ghg %>% 
  filter(year>=1990) %>% 
  filter(year<=2019) %>% 
  group_by(year,region_ar6_6,region_ar6_6_short,region_ar6_10) %>% 
  summarise(value=sum(GHG,na.rm=TRUE)/1e9) %>% 
  ungroup() %>% 
  mutate(region_ar6_6_short=as.character(region_ar6_6_short))


## group aviation and shipping into a single region

plot_data <- plot_data %>%
  mutate(region_ar6_6=ifelse(region_ar6_6_short=="AIR","Intl. Shipping & Aviation",region_ar6_6)) %>% 
  mutate(region_ar6_6=ifelse(region_ar6_6_short=="SEA","Intl. Shipping & Aviation",region_ar6_6)) %>%  
  mutate(region_ar6_6_short=ifelse(region_ar6_6=="Intl. Shipping & Aviation","AIRSEA",region_ar6_6_short))


## Add land use CO2

plot_data <- left_join(plot_data,land %>% select(region_ar6_10,year,mean),by=c("year","region_ar6_10"))
plot_data <- plot_data %>% 
  mutate(mean=mean/1e9) %>% 
  mutate(value=ifelse(region_ar6_6_short!="AIRSEA",value+mean,value))


## combine everything

plot_data <- plot_data %>% 
  group_by(year,region_ar6_6,region_ar6_6_short) %>%
  mutate(value=sum(value)) %>%
  select(-region_ar6_10,-mean) %>% 
  unique() %>% 
  ungroup()

## adjust levels

plot_data$region_ar6_6_short <- as.factor(plot_data$region_ar6_6_short)
plot_data$region_ar6_6_short <-  factor(plot_data$region_ar6_6_short,levels(plot_data$region_ar6_6_short)[c(1,3,4,5,6,7,2)])

plot_data$region_ar6_6 <- as.factor(plot_data$region_ar6_6)
plot_data$region_ar6_6 <-  factor(plot_data$region_ar6_6,levels(plot_data$region_ar6_6)[c(1,3,4,5,6,7,2)])

```

```{r region_panel, echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=4}


shares <- plot_data %>% 
  filter(year %in% c(1990,2000,2010,2019)) %>% 
  group_by(year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,region_ar6_6_short) %>% 
  mutate(fractions=(value/totals)*100)

shares <- locate_shares(shares,"region_ar6_6_short",4)

line_data <- data.frame(x=c(1990,1990,2000,2000,2010,2010,2019,2019),y=c(0,60))


### get the growth rates between time periods
rates <- plot_data %>% 
  filter(year %in% c(1990,1999,2000,2009,2010,2019)) %>% 
  group_by(year) %>% 
  summarise(value=sum(value)) %>% 
  mutate(total_rate=NA)

### leap year adjustment
# rates <- rates %>% 
#   mutate(leap_year = leap_year(year)) %>%
#   mutate(value_ly_adjusted = ifelse(leap_year=="TRUE",value*365/366,value))

rates$total_rate[rates$year==1990] = ((rates$value[rates$year==1999]/rates$value[rates$year==1990])^(1/(1999-1990))-1)*100
rates$total_rate[rates$year==2000] = ((rates$value[rates$year==2009]/rates$value[rates$year==2000])^(1/(2009-2000))-1)*100
rates$total_rate[rates$year==2010] = ((rates$value[rates$year==2019]/rates$value[rates$year==2010])^(1/(2019-2010))-1)*100
  

p1 <- plot_data %>%
  ggplot(.,aes(x=year,y=value,fill=region_ar6_6_short)) +
  geom_area(colour="#737373") +
  
  #### text with the shares
  geom_text(data=shares,aes(x=year+0.25,y=location,label=paste(round(fractions,0),"%",sep="")),size=3.5,colour="#252525",hjust=0)+
  
  geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed")  +
  
  #### text with the totals
  geom_text(data=shares %>% filter(region_ar6_6_short=="AIRSEA"),aes(x=year,y=62,label=paste(signif(totals,2),  "Gt")),size=3.5,colour="#252525")+
  
  #### text with the rates
  geom_text(data=rates %>% filter(!is.na(total_rate)),inherit.aes = FALSE,
                            aes(x=ifelse(year==2010,year+4.5,year+5),y=60,
                                label=paste0("+",round(total_rate,1),"%/yr")),size=3.5,colour="#252525") +
  
  scale_y_continuous(breaks=c(0,10,20,30,40,50,60),limits=c(0,62)) +
  scale_x_continuous(breaks=c(1990,2000,2010,2019)) +
  coord_cartesian(xlim = c(1990,2020), 
                  clip = 'off') +
  big_trend_theme +
  theme(legend.position="none",
        plot.title = element_text(size = 11,color="#252525"),
        axis.title = element_text(color="#252525"),
        plot.background = element_blank(),
        plot.margin = margin(0,0,0,0,"cm")) +
  ylab(bquote("GHG Emissions (Gt" ~CO[2]* "eq/yr)")) +
  ggtitle("a. Trends in global and regional greenhouse gas emissions")


# side panel for the labels
p_labels <- plot_data %>%
  ggplot(.,aes(x=year,y=value,fill=region_ar6_6_short)) +
  geom_text(data=shares %>% filter(year==2019),aes(x=1,y=location,label=str_wrap(region_ar6_6,width=28),color=region_ar6_6_short,lineheight=0.65),hjust=0) +
  xlim(1,1.1) +
  ylim(0,62) +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        plot.background = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        legend.position="none")

p1 <- p1 + p_labels + plot_layout(widths=c(5,2.1))

```


```{r country_changes,echo=FALSE,warning=FALSE,include=FALSE,fig.width=8,fig.height=6}

time_start=2010
#time_start=1990

## get country level data

countries <- edgar_ghg %>% 
  filter(region_ar6_6_short!="AIR") %>% 
  filter(region_ar6_6_short!="SEA") %>% 
  filter(year>=time_start & year<=2019) %>% 
  group_by(country,ISO,year,region_ar6_6_short) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(region_ar6_6_short=as.character(region_ar6_6_short))

countries$region_ar6_6_short <- as.factor(countries$region_ar6_6_short)
countries$region_ar6_6_short <-  factor(countries$region_ar6_6_short,levels(plot_data$region_ar6_6_short)[1:6])

countries <- left_join(countries,wdi_data_gdp_pop,by=c("ISO"="iso3c","year"="year"))

countries <- left_join(countries,crf_ghg %>% filter(gas=="GHG"),by=c("ISO","year"))

countries <- countries %>% 
  select(-gas,-gwp_crf_ar5) %>%
  rename("GHG_crf"="gwp_crf_ar6") %>%
  mutate(emissions_pc = GHG/population) %>% 
  mutate(emissions_pgdp = (GHG/gdp_ppp)*1e3) %>%
  mutate(emissions_pc_crf = GHG_crf/population*1e9) %>% 
  mutate(emissions_pgdp_crf = (GHG_crf/gdp_ppp)*1e12) %>%
  mutate(GHG=GHG/1e9) #%>%
  #mutate(GHG_crf=GHG_crf/1e9)

# what is 75% of the emissions?
threshold <- countries %>%
  filter(year==2019)
threshold <- sum(threshold$GHG,na.rm=T)*0.8


## calculate average annual and absolute growth

countries <- countries %>% 
  filter(year %in% c(time_start,2019)) %>% 
  group_by(country) %>% 
  mutate(avg_growth=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
  mutate(abs_growth=last(GHG)-first(GHG)) %>%
  mutate(avg_growth_crf=(last(GHG_crf)/first(GHG_crf))^(1/(last(year)-time_start))-1) %>% 
  mutate(abs_growth_crf=last(GHG_crf)-first(GHG_crf)) %>%
      #mutate(GHG_1990=first(GHG))%>%
      #mutate(GHG_1990_crf=first(GHG_crf))%>%
  filter(year==2019) %>% 
  mutate(avg_growth=avg_growth*100) %>%
  mutate(avg_growth_crf=avg_growth_crf*100)

## remove countries below absolute emissions threshold

countries <- countries %>% 
  ungroup() %>% 
  arrange(desc(GHG)) %>% 
  mutate(cumulative_GHG=cumsum(GHG)) %>% 
  mutate(cutoff = ifelse(cumulative_GHG<threshold,1,0))# %>% 
  #filter(cutoff==1)


# actually we go with the 20 largest emitters instead
countries <- countries %>% 
  mutate(cutoff=1:n()) %>% 
  mutate(cutoff=ifelse(cutoff<=20,1,0))

#countries <- gather(countries,var,value,avg_growth,abs_growth,emissions_pc,emissions_pgdp)#,avg_growth_crf, abs_growth_crf,emissions_pc_crf,emissions_pgdp_crf)


plot_theme <- theme_bw() +
  theme(axis.title.y = element_blank(),
        plot.title = element_text(size = 11,color="#252525"),
        axis.title = element_text(color="#525252"),
        panel.grid.minor.x = element_blank(),
        legend.position="none",
        text = element_text(size=11),
        plot.background = element_blank())

#rate
p2 <- countries %>%
  filter(cutoff==1) %>%
  ggplot(.,aes(x = reorder(country,avg_growth)))+
  geom_bar(aes(y = avg_growth,fill=region_ar6_6_short),stat='identity',colour="#525252")+
  geom_point(aes(y = avg_growth_crf),stat='identity',colour="#525252",fill="yellow",size=2,shape=21)+
  coord_flip() +
  plot_theme +
  ylab("%/yr") +
  ggtitle(str_wrap("b. Avg. annual GHG emissions change",width=32)) +
  annotate(geom = 'text', label = paste0('Years: ',time_start,'-2019'),
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.4,size=3.5,color="#525252")

#absolute
p3 <- countries %>% 
  filter(cutoff==1) %>% 
  #filter(var=="abs_growth") %>% 
  #ggplot(.,aes(x = reorder(country,value),y = value/1e9, fill=region_ar6_6_short)) +
  ggplot(.,aes(x = reorder(country,abs_growth)))+
  geom_bar(aes(y = abs_growth,fill=region_ar6_6_short),stat='identity',colour="#525252")+
  geom_point(aes(y = abs_growth_crf),stat='identity',colour="#525252",fill="yellow",size=2,shape=21)+
  #geom_bar(stat='identity',colour="#737373") + 
  coord_flip() +
  plot_theme +
  ylab(bquote("Gt" ~CO[2]* "eq/yr")) +
  ggtitle(str_wrap("c. Change in annual GHG emission level",width=35)) +
    annotate(geom = 'text', label = paste0('Years: ',time_start,'-2019'),
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#525252")

#pc
p4 <- countries %>% 
  filter(cutoff==1) %>% 
  #filter(var=="emissions_pc") %>%  
  #ggplot(.,aes(x = reorder(country,value),y = value, fill=region_ar6_6_short)) +
  #geom_bar(stat='identity',colour="#737373") + 
  ggplot(.,aes(x = reorder(country,emissions_pc)))+
  geom_bar(aes(y = emissions_pc ,fill=region_ar6_6_short),stat='identity',colour="#525252")+
  geom_point(aes(y = emissions_pc_crf),stat='identity',colour="#525252",fill="yellow",size=2,shape=21)+
  coord_flip() +
  plot_theme +
  ylab(bquote("t" ~CO[2]* "eq/cap")) +
  ggtitle(str_wrap("d. GHG emissions per capita",width=35)) +
    annotate(geom = 'text', label = 'Year: 2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#737373")

#pgdp
p5 <- countries %>% 
  filter(cutoff==1) %>% 
  #filter(var=="emissions_pgdp") %>% 
  #ggplot(.,aes(x = reorder(country,value),y = value*1000, fill=region_ar6_6_short)) +
  #geom_bar(stat='identity',colour="#737373") + 
  ggplot(.,aes(x = reorder(country,emissions_pgdp)))+
  geom_bar(aes(y = emissions_pgdp ,fill=region_ar6_6_short),stat='identity',colour="#525252")+
  geom_point(aes(y = emissions_pgdp_crf),stat='identity',colour="#525252",fill="yellow",size=2,shape=21)+
  coord_flip() +
  plot_theme +
  ylab(bquote("kg" ~CO[2]* "eq/$")) +
  ggtitle(str_wrap("e. GHG emissions intensity",width=35)) +
    annotate(geom = 'text', label = 'Year: 2019',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.3,size=3.5,color="#525252")


```

```{r regions_countries,echo=FALSE,warning=FALSE,fig.width=8,fig.height=11,dpi=300,fig.path="../../Results/Plots/",dev=c('png','pdf','svg')}

wrap_elements(p1) / wrap_elements((p2 + p3) / (p4 + p5)) + plot_layout(heights = c(1,2))


```


```{r save,echo=FALSE,warning=FALSE}

wb <- openxlsx::createWorkbook(title = "ipcc_ar6_figure_regions_countries")

info = data.frame(x=c("Author","Last update","Code","","Units","Panel a","Panel a totals","Panel a growth rates","Panel a shares","Panel b avg_growth","Panel b abs_growth","Panel b emissions_pc","Panel b emissions_pgdp"),y=c("William F. Lamb",as.character(Sys.time()),"https://github.com/mcc-apsis/AR6-Emissions-trends-and-drivers/blob/master/R/Analysis%20and%20figures/emissions_by_country_with_crf.Rmd","","","GtCO2eq","GtCO2eq","%/yr","%","%/yr","GtCO2eq/yr","tCO2eq/cap","kgCO2eq/$"))


addWorksheet(wb,"info")
addWorksheet(wb,"panel a")
addWorksheet(wb,"panel a totals and rates")
addWorksheet(wb,"panel a shares")
addWorksheet(wb,"panel b-e")

writeData(wb, sheet="info",info,colNames=F,rowNames=F)
writeData(wb, sheet = "panel a", spread(plot_data %>% select(-region_ar6_6_short),year,value), colNames = T, rowNames = F)
writeData(wb, sheet = "panel a totals and rates",rates, colNames = T, rowNames = F)
writeData(wb, sheet = "panel a shares",shares %>% select(-value,-totals) %>% rename(shares=fractions), colNames = T, rowNames = F)
writeData(wb, sheet = "panel b-e",countries %>% filter(cutoff==1) %>% select(country,ISO,region_ar6_6_short,avg_growth,abs_growth,emissions_pc,emissions_pgdp), colNames = T, rowNames = F)



openxlsx::saveWorkbook(wb,paste0("../../Results/Plot data/ipcc_ar6_figure_regions_countries.xlsx"),overwrite=T)



```