---
title: "Covid emissions"
author: "William F. Lamb"
output: word_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results/knitr/") })
  
---

## Setup

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(openxlsx)
library(RColorBrewer)
library(ggplot2); theme_set(theme_bw())
library(patchwork)
library(zoo)

load('../../Data/data_edgar_ghg.RData')

Sys.setlocale("LC_ALL","English")

# set palette
ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2")


```

## Table of emissions changes in 2020

```{r table, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3.5}

reductions <- function(edgar_raw,group) {
  
  reductions <- edgar_raw %>%
    filter(year>=2015) %>% 
    filter(year<2020) %>% 
    filter(gas=="CO2") %>% 
    group_by(across(group)) %>% 
    summarise(value=((sum(value,na.rm=TRUE)/5))/1e9) %>% 
    mutate(var="2015-2019 avg.")
  
  reductions <- rbind(reductions,edgar_raw %>% 
                        filter(year==2019) %>% 
                        filter(gas=="CO2") %>% 
                        group_by(across(group)) %>%
                        summarise(value=sum(value,na.rm=TRUE)/1e9) %>% 
                        mutate(var="2019"))
  
  reductions <- rbind(reductions,edgar_raw %>% 
                        filter(year==2020) %>% 
                        filter(gas=="CO2") %>% 
                        group_by(across(group)) %>%
                        summarise(value=sum(value,na.rm=TRUE)/1e9) %>% 
                        mutate(var="2020"))
  
  reductions <- spread(reductions,var,value)
  
  reductions <- reductions %>% 
    mutate(`2020 vs 2019 (GtCO2)`=`2020`-`2019`) %>% 
    mutate(`2020 vs 2019 (%)`=(`2020 vs 2019 (GtCO2)`/`2019`)*100) %>% 
    mutate(`2020 vs 2015-2019 (GtCO2)`=`2020`-`2015-2019 avg.`) %>% 
    mutate(`2020 vs 2015-2019 (%)`=(`2020 vs 2015-2019 (GtCO2)`/`2015-2019 avg.`)*100)
  
  reductions <- gather(reductions,var,value,`2015-2019 avg.`:`2020 vs 2015-2019 (%)`)
  reductions <- reductions %>% 
    mutate(value=round(value,2))
  reductions <- spread(reductions,var,value)
  
}

```

```{r covid_sectors, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3,dpi=300,fig.path="../../Results/Plots/",dev=c('png','pdf')}


edgar_sectors <- reductions(edgar_raw,"sector_title")
edgar_sector_total <- reductions(edgar_raw,"gas")
edgar_sector_total <- edgar_sector_total %>% 
  filter(gas=="CO2") %>% 
  mutate(sector_title="Total") %>% 
  select(-gas)
edgar_sectors <- rbind(edgar_sectors,edgar_sector_total)


p <- edgar_sectors %>% ggplot(.,aes(y=-`2020 vs 2019 (GtCO2)`,x=reorder(sector_title,desc(`2020 vs 2019 (GtCO2)`)),fill=sector_title)) +
  geom_bar(stat='identity',color="#737373") +
  geom_text(aes(y=-`2020 vs 2019 (GtCO2)`+0.1,x=reorder(sector_title,desc(`2020 vs 2019 (GtCO2)`)),label=paste0(round(`2020 vs 2019 (%)`,1),"%"))) +
  coord_flip() +
  ylab("Reduction in 2020 emissions relative to 2019 (GtCO2)") +
  theme(legend.position="none",
        #axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle("Change in emissions by sector (EDGARv6), 2019-2020")

p


```

```{r covid_subsectors, echo=FALSE,warning=FALSE,fig.width=8,fig.height=4,dpi=300,fig.path="../../Results/Plots/",dev=c('png','pdf')}


edgar_subsectors <- reductions(edgar_raw,c("sector_title","subsector_title"))
# remove minority CO2 subsectors
edgar_subsectors <- edgar_subsectors %>% 
  filter(sector_title!="AFOLU") %>% 
  filter(subsector_title!="Waste") %>% 
  filter(subsector_title!="Non-CO2 (all buildings)")

colors = colorRampPalette(brewer.pal(8, "Set2"))(19)

p <- edgar_subsectors %>% ggplot(.,aes(y=-`2020 vs 2019 (GtCO2)`,x=reorder(subsector_title,desc(`2020 vs 2019 (GtCO2)`)),fill=subsector_title)) +
  geom_bar(stat='identity',color="#737373") +
  geom_text(aes(y=-`2020 vs 2019 (GtCO2)`+0.04,x=reorder(subsector_title,desc(`2020 vs 2019 (GtCO2)`)),label=paste0(round(`2020 vs 2019 (%)`,1),"%"))) +
  coord_flip() +
  scale_fill_manual(values=colors) +
  ylab("Reduction in 2020 emissions relative to 2019 (GtCO2)") +
  theme(legend.position="none",
        #axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle("Change in emissions by subsector (EDGARv6), 2019-2020")

p

```

```{r covid_regions, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3.5,dpi=300,fig.path="../../Results/Plots/",dev=c('png','pdf')}

edgar_regions <- reductions(edgar_raw,c("region_ar6_6","region_ar6_10","region_ar6_10_short"))

colors = colorRampPalette(brewer.pal(8, "Set2"))(12)

p <- edgar_regions %>% ggplot(.,aes(y=-`2020 vs 2019 (GtCO2)`,x=reorder(region_ar6_10,desc(`2020 vs 2019 (GtCO2)`)),fill=region_ar6_10)) +
  geom_bar(stat='identity',color="#737373") +
  geom_text(aes(y=-`2020 vs 2019 (GtCO2)`+0.04,x=reorder(region_ar6_10,desc(`2020 vs 2019 (GtCO2)`)),label=paste0(round(`2020 vs 2019 (%)`,1),"%"))) +
  coord_flip() +
  scale_fill_manual(values=colors) +
  ylab("Reduction in 2020 emissions relative to 2019 (GtCO2)") +
  theme(legend.position="none",
        #axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle("Change in emissions by region (EDGARv6), 2019-2020")

p

```

```{r save_covid_edgar, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3.5}


wb <- openxlsx::createWorkbook(title = "ipcc_ar6_data_covid")

addWorksheet(wb,"info")
addWorksheet(wb,"EDGAR sectors")
addWorksheet(wb,"EDGAR subsectors")
addWorksheet(wb,"EDGAR regions")

info = data.frame(x=c("Author","Last update","Code"),y=c("William F. Lamb",as.character(Sys.time()),"https://github.com/mcc-apsis/AR6-Emissions-trends-and-drivers/blob/master/R/Analysis%20and%20figures/covid_emissions.Rmd"))

writeData(wb, sheet="info",info,colNames=F,rowNames=F)
writeData(wb, sheet = "EDGAR sectors", edgar_sectors, colNames = T, rowNames = F)
writeData(wb, sheet = "EDGAR subsectors", edgar_subsectors, colNames = T, rowNames = F)
writeData(wb, sheet = "EDGAR regions", edgar_regions, colNames = T, rowNames = F)

saveWorkbook(wb,"../../Results/Public data/ipcc_ar6_data_covid.xlsx",overwrite=T)


```

## Annual emissions 1970-2020

```{r annual_gcp, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3}

carbon_monitor <- read.csv('../../Data/Supplementary datasets/carbonmonitor-global_datas_2021-08-31.csv')
carbon_monitor <- carbon_monitor %>% 
  filter(country=="WORLD") %>% 
  mutate(date=as.Date(date, "%d/%m/%Y")) %>% 
  mutate(year=format(date,format="%Y"))
carbon_monitor <- carbon_monitor %>% 
  group_by(year) %>% 
  summarise(value=sum(value)/1000) %>% 
  mutate(dataset="Carbon Monitor (CM)")
carbon_monitor <- carbon_monitor %>% 
  filter(year!=2021) %>% 
  group_by(dataset) %>% 
  mutate(change=first(value)-last(value)) %>% 
  mutate(rate=(change/first(value))*100)

data <- edgar_raw %>% 
  filter(gas=="CO2") %>% 
  filter(year>1969) %>% 
  group_by(year) %>% 
  summarise(value=sum(value,na.rm=TRUE)/1e9) %>% 
  ungroup() %>% 
  mutate(dataset="EDGAR")


#### calculate rate of decline for different crises

crises <- data %>% 
  filter(dataset=="EDGAR") %>% 
  filter(year %in% c(1973,1974,1991,1992,2008,2009,2019,2020))

crises <- left_join(crises,data.frame(year=c(1973,1974,1991,1992,2008,2009,2019,2020),
                                      label=c("1973 Oil Crisis","1973 Oil Crisis",
                                              "1991 Soviet Union\ndissolusion",
                                              "1991 Soviet Union\ndissolusion",
                                              "2008 Global\nfinancial crisis",
                                              "2008 Global\nfinancial crisis",
                                              "2020 COVID-19\npandemic",
                                              "2020 COVID-19\npandemic"),
                                      position=c(16,16,20,20,29,29,36,36)))
crises <- crises %>% 
  group_by(label) %>% 
  mutate(change=first(value)-last(value)) %>% 
  mutate(rate=(change/first(value))*100) %>% 
  mutate(rate=round(rate,1))

crises <- crises %>% 
  group_by(label,rate,position) %>% 
  summarise(year=first(year)) %>% 
  mutate(year=ifelse(label=="2020 COVID-19\npandemic",year+1,year))

crises <- crises %>% 
  mutate(label2=paste0(label,"\n","-",rate,"%")) %>% 
  mutate(label2 = ifelse(year==2020,paste0(label,"\n-",rate,"% (EDGAR)\n-5.6% (GCB)\n-6.3% (BP)\n-5.8% (IEA)\n-6.0% (CM)"),label2))

# uncertainty bands
data <- data %>% 
  mutate(high=value+(value*0.08)) %>% 
  mutate(low=value-(value*0.08))

# # regression lines
# regres <- data %>% 
#   mutate(event=ifelse(year<=1973 & year>=1971,"Oil crisis",NA)) %>% 
#   mutate(event=ifelse(year<=1991 & year>=1989,"Soviet Union",event)) %>% 
#   mutate(event=ifelse(year<=2008 & year>=2006,"Financial crisis",event)) %>% 
#   mutate(event=ifelse(year<=2019 & year>=2017,"COVID",event)) %>% 
#   filter(!is.na(event))
# 
# growth_rate <- function(years,y) {
#   
#   data <- data.frame(years,y)
#   
#   fit <- lm(log(y) ~ years,data = data)
#   
#   data <- data %>% 
#     mutate(rate=fit$coefficients[2]) %>% 
#     mutate(predicted_x = exp(predict(fit,data %>% select(years)))) %>% 
#     mutate(st_error = sqrt(diag(vcov(fit)))[2])
#   
#   newdata <- data.frame(years=c(first(years):(last(years)+3)))
#   newdata <- newdata %>% 
#     mutate(predicted_x = exp(predict(fit,newdata %>% select(years))))
#   
#   return(newdata)
# }
# 
# regres <- rbind(growth_rate(regres$year[regres$event=="Oil crisis"],regres$value[regres$event=="Oil crisis"]) %>% mutate(event="Oil crisis"),
#                growth_rate(regres$year[regres$event=="Soviet Union"],regres$value[regres$event=="Soviet Union"]) %>% mutate(event="Soviet Union"),
#                growth_rate(regres$year[regres$event=="Financial crisis"],regres$value[regres$event=="Financial crisis"]) %>% mutate(event="Financial crisis"),
#                growth_rate(regres$year[regres$event=="COVID"],regres$value[regres$event=="COVID"]) %>% mutate(event="COVID"))


p_annual_gcb <- data %>% 
  ggplot(.,aes(x=year,y=value)) +
  geom_path(aes(group=dataset,color=dataset)) +
  geom_ribbon(aes(ymin=low,ymax=high,fill=dataset),alpha=0.3,) +
  
  #geom_path(data=regres,aes(group=event,x=years,y=predicted_x)) +
  
  geom_vline(data=crises,aes(xintercept=year),linetype="dashed") +
  
  geom_text(data=crises,aes(x=year+0.5,y=position,label=label2),vjust=1,hjust=0,size=3.5) +
  
  ylab(bquote(~CO[2]*" Emissions (Gt" ~CO[2]* "/yr)")) +
  scale_y_continuous(limits=c(10,42)) +
  scale_x_continuous(limits=c(1970,2030),breaks=c(1970,1980,1990,2000,2010,2020))  +
  ggtitle(bquote("a. Global"~CO[2]*" emissions and the impact of economic and geopolitical events")) +
  theme(
        legend.position="none",
        axis.title.x = element_blank(),
        plot.title = element_text(size=12))

p_annual_gcb

```
## Daily emissions 2020
### Carbon Monitor

```{r sectors_cm, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3}

covid_sectors_cm <- read.csv(file="../../Data/Supplementary datasets/carbonmonitor-global_datas_2021-08-31.csv")

covid_sectors_cm <- covid_sectors_cm %>% 
  filter(country=="WORLD") %>% 
  mutate(date=as.Date(date, "%d/%m/%Y")) %>% 
  select(country,date,sector,medium=value,timestamp)

## total
covid_sectors_total <- covid_sectors_cm %>% 
  group_by(date,timestamp) %>% 
  summarise(medium=sum(medium,na.rm=TRUE)) %>% 
  mutate(country="WORLD") %>% 
  mutate(sector="Total") 

covid_sectors_cm <- rbind(covid_sectors_cm,covid_sectors_total)

### sum domestic and intl. aviation

covid_sectors_cm <- covid_sectors_cm %>% 
  mutate(sector=ifelse(sector=="Domestic Aviation","Aviation",sector)) %>% 
  mutate(sector=ifelse(sector=="International Aviation","Aviation",sector))

covid_sectors_cm <- covid_sectors_cm %>% 
  group_by(sector,date,timestamp) %>% 
  summarise(medium=sum(medium)) %>% 
  ungroup()

### Match other sectors to Le Quere
covid_sectors_cm <- covid_sectors_cm %>% 
  mutate(sector=ifelse(sector=="Ground Transport","Land Transport",sector))


## add uncertainty
covid_sectors_cm <- covid_sectors_cm %>% 
  mutate(uncertainty=0.072*medium) %>% 
  mutate(high=medium+uncertainty) %>% 
  mutate(low=medium-uncertainty) %>% 
  select(-uncertainty)

covid_sectors_cm <- gather(covid_sectors_cm,var,value,medium,high,low)

### subtract daily emissions in 2020 from 2019

covid_sectors_cm <- covid_sectors_cm %>% 
  mutate(year=format(date,format="%Y")) %>% 
  mutate(day=format(date,format="%m-%d")) %>% 
  select(-date,-timestamp)

covid_sectors_cm <- spread(covid_sectors_cm,year,value)
covid_sectors_cm <- covid_sectors_cm %>% 
  mutate(change=`2020`-`2019`) %>% 
  filter(!is.na(change)) %>% 
  mutate(date=paste0("2020-",day)) %>% 
  mutate(date=as.Date(date))

## rolling average 7 day (anomaly)
covid_sectors_cm <- covid_sectors_cm %>% 
  group_by(sector,var) %>% 
  mutate(change=change-first(change)) %>% 
  mutate(change_smooth=rollmean(change,k=7,align="center",fill=NA))

## rolling average 7 day (total)
# covid_sectors_cm <- covid_sectors_cm %>% 
#   group_by(sector) %>%  
#   mutate(`2020_smooth`=rollmean(`2020`,k=7,align="center",fill=NA))


covid_sectors_cm <- spread(covid_sectors_cm %>% select(sector,var,date,change_smooth),var,change_smooth)


```

### Global Carbon Project

```{r sectors_gcp, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3}


## load in new data from Le Quere et al. 2020
## available here https://www.icos-cp.eu/gcp-covid19

sheet_names <- getSheetNames(file = "../../Data/Supplementary datasets/PublicData_v15_Countries_UNFCCC-accounting-corr.xlsx")

covid_sectors_gcp <- read.xlsx("../../Data/Supplementary datasets/PublicData_v15_Countries_UNFCCC-accounting-corr.xlsx",sheet="GLOBAL")
covid_sectors_gcp <- covid_sectors_gcp %>% filter(REGION_ID!="None")

covid_sectors_gcp <- gather(covid_sectors_gcp,key,value,TOTAL_CO2_MED:AVI_CO2_HIGH) %>% 
  mutate(value=as.numeric(value))

covid_sectors_gcp <- covid_sectors_gcp %>% 
  mutate(estimate=ifelse(grepl("MED",key),"medium",NA)) %>% 
  mutate(estimate=ifelse(grepl("HIGH",key),"high",estimate)) %>% 
  mutate(estimate=ifelse(grepl("LOW",key),"low",estimate))

covid_sectors_gcp <- covid_sectors_gcp %>% 
  mutate(sector=ifelse(grepl("PWR",key),"Power",NA)) %>% 
  mutate(sector=ifelse(grepl("IND",key),"Industry",sector)) %>% 
  mutate(sector=ifelse(grepl("TRS",key),"Land Transport",sector)) %>% 
  mutate(sector=ifelse(grepl("PUB",key),"Public sector",sector)) %>% 
  mutate(sector=ifelse(grepl("RES",key),"Residential",sector)) %>% 
  mutate(sector=ifelse(grepl("AVI",key),"Aviation",sector)) %>% 
  mutate(sector=ifelse(grepl("TOTAL",key),"Total",sector)) %>% 
  mutate(date=convertToDate(DATE)) %>% 
  select(-key,-DATE)

covid_sectors_gcp <- spread(covid_sectors_gcp,estimate,value)

```

### Sector comparison plot

```{r sector_comparison, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3}

covid_sectors <- rbind(covid_sectors_gcp %>% 
                         select(sector,date,value=medium,high,low) %>% 
                         mutate(dataset="Le Quéré et al. (2021)"),
                       covid_sectors_cm %>% 
                         select(sector,date,value=medium,high,low) %>% 
                         mutate(dataset="Carbon Monitor (CM)"))

fake_data_for_legend <- covid_sectors %>% 
  filter(dataset=="Carbon Monitor (CM)") %>% 
  mutate(value=NA) %>% 
  mutate(high=NA) %>% 
  mutate(low=NA) %>% 
  mutate(dataset="EDGAR")

covid_sectors <- rbind(covid_sectors,fake_data_for_legend)

covid_sectors$dataset = as.factor(covid_sectors$dataset)
covid_sectors$dataset = factor(covid_sectors$dataset,levels=levels(covid_sectors$dataset)[c(1,3,2)])

par(lheight=0.5) 
p_covid_sectors <- covid_sectors %>% 
  filter(sector!="Total") %>% 
  filter(sector!="Public sector") %>% 
  ggplot(.,aes(x=date,y=value,color=reorder(dataset,desc(dataset)),fill=reorder(dataset,desc(dataset)))) +
  geom_line() +
  geom_ribbon(aes(ymin=low,ymax=high),alpha=0.3,) +
  scale_x_date(breaks= as.Date(c("2020-01-01","2020-04-01","2020-07-01","2020-10-01")),date_labels = "%b") +
  facet_grid(.~sector) +
  ylab(bquote(atop("Change in global daily",~CO[2]*" emissions (Mt" ~CO[2]* "/day)"))) +
  ggtitle(bquote("b. Daily"~CO[2]*" emissions in 2020 versus 2019 and the impact of COVID-19 lockdown measures")) +
  
  theme(legend.position="bottom",
        legend.title=element_blank(),
        axis.title.x = element_blank(),
        plot.title=element_text(size=12),
        panel.grid.minor = element_blank())

p_covid_sectors_total <- covid_sectors %>% 
  filter(sector=="Total") %>% 
  ggplot(.,aes(x=date,y=value,color=reorder(dataset,desc(dataset)),fill=reorder(dataset,desc(dataset)))) +
  geom_line() +
  geom_ribbon(aes(ymin=low,ymax=high),alpha=0.3,) +
  scale_x_date(breaks= as.Date(c("2020-01-01","2020-04-01","2020-07-01","2020-10-01")),date_labels = "%b") +
  facet_grid(.~sector) +
  theme(legend.position="none",
        legend.title=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.background = element_blank(),
        panel.grid.minor = element_blank())

p_covid_sectors <- (p_covid_sectors + p_covid_sectors_total + plot_layout(widths=c(5,1)))
p_covid_sectors
```

```{r covid_emissions, echo=FALSE,warning=FALSE,dpi=300,fig.width=8,fig.height=5.5,fig.path="../../Results/Plots/",dev=c('png','pdf')}


p <- p_annual_gcb / p_covid_sectors + plot_layout(heights=c(0.6,0.4))
p
```


### Total sector reductions

```{r annual_reduction, echo=FALSE,warning=FALSE,fig.width=8,fig.height=3}

## Carbon Monitor
covid_sectors_cm <- read.csv(file="../../Data/Supplementary datasets/carbonmonitor-global_datas_2021-08-31.csv")

covid_sectors_cm <- covid_sectors_cm %>% 
  filter(country=="WORLD") %>% 
  mutate(date=as.Date(date, "%d/%m/%Y")) %>% 
  mutate(year=format(date,format="%Y")) %>%
  select(year,sector,value)

### sum domestic and intl. aviation
covid_sectors_cm <- covid_sectors_cm %>% 
  mutate(sector=ifelse(sector=="Domestic Aviation","Aviation",sector)) %>% 
  mutate(sector=ifelse(sector=="International Aviation","Aviation",sector))

### Match other sectors to Le Quere
covid_sectors_cm <- covid_sectors_cm %>% 
  mutate(sector=ifelse(sector=="Ground Transport","Land Transport",sector))

### sum to annual value
covid_sectors_cm <- covid_sectors_cm %>%
  group_by(sector,year) %>%
  summarise(value=sum(value,na.rm=TRUE)) %>%
  filter(year!=2021)

covid_total_cm <- covid_sectors_cm %>%
  group_by(year) %>%
  summarise(value=sum(value,na.rm=TRUE)) %>%
  mutate(sector="Total")

covid_sectors_cm <- rbind(covid_sectors_cm,covid_total_cm)

### calculate change
covid_sectors_cm <- covid_sectors_cm %>%
  summarise(annual_reduction_CM=(last(value)/first(value)-1)*100)


## Le Quere et al. 2020
covid_sectors_gcp <- read.xlsx("../../Data/Supplementary datasets/PublicData_v15_Countries_UNFCCC-accounting-corr.xlsx",sheet="GLOBAL")
covid_sectors_gcp <- covid_sectors_gcp %>% filter(REGION_ID!="None")

mean_emissions_gcp <- read.xlsx("../../Data/Supplementary datasets/PublicData_v15_Countries_UNFCCC-accounting-corr.xlsx",sheet="mean")

mean_emissions_gcp <- mean_emissions_gcp %>%
  filter(REGION_NAME=="Global")

mean_emissions_gcp <- gather(mean_emissions_gcp,sector,mean,TOTAL_CO2:AVIATION) %>%
  mutate(sector=ifelse(sector=="POWER","Power",sector)) %>% 
  mutate(sector=ifelse(sector=="INDUSTRY","Industry",sector)) %>% 
  mutate(sector=ifelse(sector=="SURFACE_TRANSPORT","Land Transport",sector)) %>% 
  mutate(sector=ifelse(sector=="PUBLIC","Public sector",sector)) %>% 
  mutate(sector=ifelse(sector=="RESIDENTIAL","Residential",sector)) %>% 
  mutate(sector=ifelse(sector=="AVIATION","Aviation",sector)) %>% 
  mutate(sector=ifelse(sector=="TOTAL_CO2","Total",sector))

covid_sectors_gcp <- gather(covid_sectors_gcp,key,value,TOTAL_CO2_MED:AVI_CO2_HIGH) %>% 
  mutate(value=as.numeric(value))

covid_sectors_gcp <- covid_sectors_gcp %>% 
  mutate(estimate=ifelse(grepl("MED",key),"medium",NA)) %>% 
  mutate(estimate=ifelse(grepl("HIGH",key),"high",estimate)) %>% 
  mutate(estimate=ifelse(grepl("LOW",key),"low",estimate))

covid_sectors_gcp <- covid_sectors_gcp %>% 
  mutate(sector=ifelse(grepl("PWR",key),"Power",NA)) %>% 
  mutate(sector=ifelse(grepl("IND",key),"Industry",sector)) %>% 
  mutate(sector=ifelse(grepl("TRS",key),"Land Transport",sector)) %>% 
  mutate(sector=ifelse(grepl("PUB",key),"Public sector",sector)) %>% 
  mutate(sector=ifelse(grepl("RES",key),"Residential",sector)) %>% 
  mutate(sector=ifelse(grepl("AVI",key),"Aviation",sector)) %>% 
  mutate(sector=ifelse(grepl("TOTAL",key),"Total",sector)) %>% 
  mutate(date=convertToDate(DATE)) %>% 
  mutate(year=format(date,format="%Y")) %>%
  select(-key,-DATE)

covid_sectors_gcp <-covid_sectors_gcp %>%
  filter(estimate=="medium") %>%
  group_by(year,sector) %>%
  summarise(value=mean(value,na.rm=TRUE))

covid_sectors_gcp <- left_join(covid_sectors_gcp,mean_emissions_gcp %>% select(sector,mean),by="sector")

covid_sectors_gcp <- covid_sectors_gcp %>%
  mutate(mean=as.numeric(mean)) %>%
  mutate(annual_reduction_GCP=value/mean*100)

annual_reductions<-left_join(covid_sectors_gcp,covid_sectors_cm) %>%
  select(-value,-mean)


wb <- openxlsx::createWorkbook(title = "ipcc_ar6_figure_covid2020")
openxlsx::addWorksheet(wb,"panel a")
openxlsx::addWorksheet(wb,"panel a reduction rates")
openxlsx::addWorksheet(wb,"panel b")
openxlsx::addWorksheet(wb,"percentage annual reductions")
openxlsx::addWorksheet(wb,"EDGAR reductions")
openxlsx::writeData(wb,"panel a",data, colNames = T, rowNames = F)
openxlsx::writeData(wb,"panel a reduction rates",crises, colNames = T, rowNames = F)
openxlsx::writeData(wb,"panel b",covid_sectors, colNames = T, rowNames = F)
openxlsx::writeData(wb,"percentage annual reductions",annual_reductions, colNames = T, rowNames = F)
openxlsx::writeData(wb,"EDGAR reductions",edgar_sectors, colNames = T, rowNames = F)
openxlsx::saveWorkbook(wb,paste0("../../Results/Plot data/ipcc_ar6_figure_covid2020",".xlsx"),overwrite=T)

```