---
title: "Kaya buildings"
author: "William F. Lamb"
date: "2 12 2020"
output: word_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results") })

---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(gganimate)
library(openxlsx)
library(ggplot2); theme_set(theme_bw())
library(data.table)
library(janitor)

load("../../Data/ipcc_regions.RData")
load('../../Data/basic.RData')
load('../../Data/activity.RData')
load('../../Data/edgar_data_gwp_ar6.RData')
load('../../Data/indirect_CO2.RData')

wb <- openxlsx::createWorkbook(title = "kaya_buildings")


# floor space from IEA EE indicators
# residential/services energy from IEA EE indicators
# GHG from EDGAR, indirect CO2 from IEA
# pop from UN

## floor space and pop from IEA EE indicators

floor_space <- act %>% 
  filter(product %in% c("Residential floor area (10^9 m2)","Services floor area (10^9 m2)"))

floor_space <- floor_space %>% 
  mutate(product=ifelse(product=="Residential floor area (10^9 m2)","residential",product)) %>% 
  mutate(product=ifelse(product=="Services floor area (10^9 m2)","services",product))

floor_space <- floor_space %>% 
  mutate(value=value*1e9) %>% 
  mutate(pop=pop*1e6)

floor_space <- floor_space %>% 
  mutate(subsector_title=ifelse(product=="residential","Residential","Non-residential")) %>% 
  select(-activity,-product,-region_ar6_5,-region_ar6_5_short) %>% 
  select(everything(),floor_space_m2=value,pop_persons=pop)


## energy from IEA EE indicators

energy <- IEA_EE %>% 
  filter(end_use %in% c("Total Residential","Total Services")) %>% 
  filter(product=="Total final energy (PJ)")

energy <- energy %>%
  mutate(subsector_title=ifelse(end_use=="Total Residential","Residential","Non-residential")) %>% 
  mutate(value=value*1e6) %>% 
  select(-product,-end_use,-region_ar6_5,-region_ar6_5_short) %>% 
  select(everything(),tot_fin_energy_GJ=value)

## CO2 direct

co2 <- edgar_GHG_ar6 %>% 
  filter(chapter_title=="Buildings") %>% 
  group_by(country,ISO,region_ar6_10,year,subsector_title,) %>% 
  summarise(CO2_t=sum(CO2,na.rm=TRUE))

## CO2 indirect

co2_indirect <- indirect_CO2_countries %>% 
  filter(chapter_title=="Buildings") %>% 
  group_by(country,ISO,region_ar6_10,year,subsector_title) %>% 
  summarise(CO2_indirect_t=sum(CO2_indirect*1e9,na.rm=TRUE))

## join all

data <- left_join(co2,co2_indirect,by = c("country", "ISO", "year", "subsector_title"))
data <- left_join(data,energy,by = c("country", "ISO", "year", "subsector_title"))
data <- left_join(data,floor_space,by = c("country", "ISO", "year", "subsector_title"))

```

```{r floor_area_descriptive,echo=FALSE,warning=FALSE,fig.width=6,fig.height=4,fig.path="../../Results/Plots/Supplementary/",dev=c('png','pdf')}

floor_space_plot <- floor_space %>% 
  mutate(floor_space_percapita = floor_space_m2/pop_persons) %>% 
  filter(country!="Ukraine")

floor_space_plot <- left_join(floor_space_plot,basic %>% select(ISO,year=Year,gdp_ppp_WB),by = c("ISO", "year"))

floor_space_plot <- floor_space_plot %>% 
  filter(year %in% c(2000,2017)) %>% 
  filter(subsector_title=="Residential") %>% 
  mutate(gdp_pc = gdp_ppp_WB/pop_persons)


library(RColorBrewer)


floor_space_plot <- floor_space_plot %>% 
  filter(country %in% c("Australia","Canada","Czech Republic","Finland","Hungary","France","Germany","Japan","United Kingdom","Mexico","United States")) 

mycolors <- colorRampPalette(brewer.pal(8, "Set2"))(length(unique(floor_space_plot$country)))



floor_space_plot %>% ggplot(.,aes(x=gdp_pc,y=floor_space_percapita,color=country,group=country)) +
  geom_path() +
  geom_point() +
  geom_text(data=floor_space_plot %>% filter(year==2017),
            inherit.aes=FALSE,aes(x=gdp_pc+1000,y=floor_space_percapita,label=country,color=country),hjust=0) + 
  scale_color_manual(values=mycolors) +
  xlim(15000,65000) +
  theme(legend.position="none") +
  ggtitle("Residential floor space vs. GDP per capita (2000 & 2017)") +
  ylab("Floor space per capita (m2/person)") +
  xlab("GDP per capita (US$ PPP)")

```


```{r gather_historical_data, include=FALSE}

data <- read.xlsx("../../Data/supplemetary data/2020-12-07 Data for plots to Will2.xlsx",sheet=1)

data <- gather(data,year,value,`1990`:`2018`) %>% 
  filter(!is.na(Region))

co2_buildings <- left_join(co2,co2_indirect,by = c("country", "ISO", "region_ar6_10", "year", "subsector_title"))

co2_buildings <- co2_buildings %>% 
  mutate(CO2_indirect_t=ifelse(is.na(CO2_indirect_t),0,CO2_indirect_t)) %>% 
  mutate(CO2_t=ifelse(is.na(CO2_t),0,CO2_t))

co2_buildings <- co2_buildings %>%  
  mutate(CO2_total_t = CO2_t+CO2_indirect_t)

# Move Belarus and Macedonia from Eurasia to Europe and Israel from Middle East to Europe

co2_buildings <- co2_buildings %>%
  ungroup() %>% 
  mutate(region_ar6_10=ifelse(country=="Belarus","Europe",region_ar6_10)) %>% 
  mutate(region_ar6_10=ifelse(country=="Macedonia, FYR","Europe",region_ar6_10)) %>% 
  mutate(region_ar6_10=ifelse(country=="Israel","Europe",region_ar6_10)) 

co2_buildings <- co2_buildings %>%
  mutate(region_ar6_10=ifelse(region_ar6_10=="Southern Asia","Southern Asia, South East Asia and Developing Pacific",region_ar6_10)) %>% 
  mutate(region_ar6_10=ifelse(region_ar6_10=="South-East Asia and Developing Pacific","Southern Asia, South East Asia and Developing Pacific",region_ar6_10))

co2_buildings <- co2_buildings %>% 
  group_by(region_ar6_10,year,subsector_title) %>% 
  summarise(value=sum(CO2_total_t)) %>% 
  mutate(Variable="Total CO2 emissions") %>%
  mutate(Unit = "tCO2") %>% 
  filter(subsector_title!="Non-CO2 (all buildings)") %>%
  filter(year %in% c(1990,2000,2005,2010,2015,2018)) %>% 
  select(Region=region_ar6_10,Variable,Unit,year,value,subsector_title) %>% 
  ungroup()

data <- data %>% 
  mutate(subsector_title=ifelse(grepl("Residential",Variable),"Residential",NA)) %>% 
  mutate(subsector_title=ifelse(grepl("Non-residential",Variable),"Non-residential",subsector_title))

data <- data %>% 
  filter(!is.na(subsector_title)) %>% 
  filter(Unit!="MtCO2")

data <- rbind(data,co2_buildings)


pop <- basic %>% select(ISO,year=Year,pop_UN)
pop <- left_join(pop,ipcc_regions,by = "ISO")


pop <- pop %>%
  ungroup() %>% 
  mutate(region_ar6_10=ifelse(ISO=="BLR","Europe",region_ar6_10)) %>% 
  mutate(region_ar6_10=ifelse(ISO=="MKD","Europe",region_ar6_10)) %>% 
  mutate(region_ar6_10=ifelse(ISO=="ISR","Europe",region_ar6_10)) 

pop <- pop %>%
  mutate(region_ar6_10=ifelse(region_ar6_10=="Southern Asia","Southern Asia, South East Asia and Developing Pacific",region_ar6_10)) %>% 
  mutate(region_ar6_10=ifelse(region_ar6_10=="South-East Asia and Developing Pacific","Southern Asia, South East Asia and Developing Pacific",region_ar6_10))

pop <- pop %>%
  filter(year %in% c(1990,2000,2005,2010,2015,2018)) %>%
  group_by(region_ar6_10,year) %>%
  summarise(value=sum(pop_UN)) %>%
  filter(!is.na(region_ar6_10))
pop <- pop %>%
  mutate(Variable="Population") %>%
  mutate(Unit="persons") %>%
  select(Region=region_ar6_10,Variable,Unit,year,value) %>%
  ungroup()

data <- rbind(data,pop %>% mutate(subsector_title="Residential"))
data <- rbind(data,pop %>% mutate(subsector_title="Non-residential"))

pop <- pop %>% 
  group_by(Variable,Unit,year) %>% 
  summarise(value=sum(value)) %>% 
  mutate(Region="World") %>% 
  select(Region,Variable,Unit,year,value) %>% 
  ungroup()

co2_buildings <- co2_buildings %>% 
  group_by(Variable,Unit,year,subsector_title) %>% 
  summarise(value=sum(value)) %>% 
  mutate(Region="World") %>% 
  select(Region,Variable,Unit,year,value,subsector_title) %>% 
  ungroup()

data <- rbind(data,pop %>% mutate(subsector_title="Residential"))
data <- rbind(data,pop %>% mutate(subsector_title="Non-residential"))
data <- rbind(data,co2_buildings)

data <- data %>% 
  mutate(Variable=paste0(Variable," (",Unit,")"))

```


```{r calc_kaya_residential, include=FALSE}

residential <- data %>% 
  filter(subsector_title=="Residential") %>% 
  select(-Unit,-subsector_title) %>% 
  mutate(value=as.numeric(value))

residential <- spread(residential,Variable,value)

names(residential) <- c("region","year","pop","energy","floor","co2")

residential <- residential %>% 
  mutate(energy = energy*1e6) %>% 
  mutate(floor = floor*1e6)

residential <- residential %>% 
  mutate(floor_pop = floor/pop) %>% 
  mutate(energy_floor = energy/floor) %>% 
  mutate(co2_energy = co2/energy)


openxlsx::addWorksheet(wb,"residential")
openxlsx::writeData(wb, sheet = "residential",residential, colNames = T, rowNames = F)


residential <- gather(residential,var,value,co2,pop,floor_pop,energy_floor,co2_energy)


residential <- residential %>% 
  group_by(region,var) %>% 
  mutate(value=value/first(value))

residential <- residential %>% 
  mutate(value=value-1) %>% 
  filter(region!="World") %>% 
  ungroup()


openxlsx::addWorksheet(wb,"residential (normalised)")
openxlsx::writeData(wb, sheet = "residential (normalised)",residential, colNames = T, rowNames = F)


```

## Residential

```{r residential_plot,echo=FALSE,warning=FALSE,fig.width=8,fig.height=7,fig.path="../../Results/Plots/Supplementary/",dev=c('png','pdf')}


# plot

residential %>% 
  filter(var!="co2") %>% 
  ggplot(.) +
  geom_bar(stat='identity',color="#636363",aes(x=year,y=value,fill=var)) +
  geom_point(data=residential %>% filter(var=="co2"),aes(x=year,y=value,color=var))+
  facet_wrap(region~.,labeller = label_wrap_gen(width=40,multi_line = TRUE),scales="free") +
  scale_fill_brewer(palette = "Set2",labels=c("CO2/Energy","Energy/Floor area","Floor area/Population","Population")) +
  scale_color_manual(values="#636363",labels="CO2") +
  theme(legend.position = "bottom",
        axis.title = element_blank(),
        legend.title = element_blank(),
        panel.grid.minor = element_blank())


```

```{r calc_kaya_non-residential, include=FALSE}

nonresidential <- data %>% 
  filter(subsector_title=="Non-residential") %>% 
  select(-Unit,-subsector_title) %>% 
  mutate(value=as.numeric(value))

nonresidential <- spread(nonresidential,Variable,value)

names(nonresidential) <- c("region","year","energy","value","pop","co2")

nonresidential <- nonresidential %>% 
  mutate(energy = energy*1e6) %>% 
  mutate(value=value*1e6)

#CO2= Value added*[Energy/Value Added]*[CO2/Energy] 

nonresidential <- nonresidential %>% 
  mutate(energy_value = energy/value) %>% 
  mutate(co2_energy = co2/energy)

openxlsx::addWorksheet(wb,"non-residential")
openxlsx::writeData(wb, sheet = "non-residential",nonresidential, colNames = T, rowNames = F)


nonresidential <- gather(nonresidential,var,value,co2,value,energy_value,co2_energy)

nonresidential <- nonresidential %>% 
  group_by(region,var) %>% 
  mutate(value=value/first(value))

nonresidential <- nonresidential %>% 
  mutate(value=value-1) %>% 
  filter(region!="World") %>% 
  ungroup()

openxlsx::addWorksheet(wb,"non-residential (normalised)")
openxlsx::writeData(wb, sheet = "non-residential (normalised)",nonresidential, colNames = T, rowNames = F)


```

## Non-residential

```{r nonresidential_plot,echo=FALSE,warning=FALSE,fig.width=8,fig.height=7,fig.path="../../Results/Plots/Supplementary/",dev=c('png','pdf')}


# plot

nonresidential %>% 
  filter(var!="co2") %>% 
  ggplot(.) +
  geom_bar(stat='identity',color="#636363",aes(x=year,y=value,fill=var)) +
  geom_point(data=nonresidential %>% filter(var=="co2"),aes(x=year,y=value,color=var))+
  facet_wrap(region~.,labeller = label_wrap_gen(width=40,multi_line = TRUE),scales="free") +
  scale_fill_brewer(palette = "Set2",labels=c("CO2/Energy","Energy/Value added","Value added")) +
  scale_color_manual(values="#636363",labels="CO2") +
  theme(legend.position = "bottom",
        axis.title = element_blank(),
        legend.title = element_blank(),
        panel.grid.minor = element_blank())


```

# scenarios


```{r scenarios_data,echo=FALSE,warning=FALSE}



data_sd <- read.xlsx("../../Data/supplemetary data/2020-12-07 Data for plots to Will2.xlsx",sheet=2)

data_sd <- gather(data_sd,year,value,`2020`:`2050`) %>% 
  filter(!is.na(Region)) %>% 
  mutate(scenario="Sustainable development")

data_sp <- read.xlsx("../../Data/supplemetary data/2020-12-07 Data for plots to Will2.xlsx",sheet=3)

data_sp <- gather(data_sp,year,value,`2020`:`2050`) %>% 
  filter(!is.na(Region)) %>% 
  mutate(scenario="Stated policy")

data_cp <- read.xlsx("../../Data/supplemetary data/2020-12-07 Data for plots to Will2.xlsx",sheet=4)

data_cp <- gather(data_cp,year,value,`2020`:`2050`) %>% 
  filter(!is.na(Region)) %>% 
  mutate(scenario="Current policy")

data <- bind_rows(data_sd,data_sp)
data <- bind_rows(data,data_cp)

names(data) <- c("region","variable","unit","year","value","scenario")


data <- data %>% 
  mutate(subsector_title=ifelse(grepl("Residential",variable),"Residential",NA)) %>% 
  mutate(subsector_title=ifelse(grepl("Non-residential",variable),"Non-residential",subsector_title)) %>%   mutate(subsector_title=ifelse(grepl("Population",variable),"Residential",subsector_title))

data <- data %>% 
  filter(!is.na(subsector_title))

```

```{r scenarios_residential_calc,echo=FALSE,warning=FALSE}


scenario_residential <- data %>% 
  filter(subsector_title=="Residential") %>% 
  select(-unit,-subsector_title)

scenario_residential <- spread(scenario_residential,variable,value)

names(scenario_residential) <- c("region","year","scenario","pop","energy","floor","co2")

scenario_residential <- scenario_residential %>% 
  mutate(energy = energy*1e6) %>% 
  mutate(floor = floor*1e6)

scenario_residential <- scenario_residential %>% 
  mutate(floor_pop = floor/pop) %>% 
  mutate(energy_floor = energy/floor) %>% 
  mutate(co2_energy = co2/energy)


openxlsx::addWorksheet(wb,"scenario residential")
openxlsx::writeData(wb, sheet = "scenario residential",scenario_residential, colNames = T, rowNames = F)


scenario_residential <- gather(scenario_residential,var,value,co2,pop,floor_pop,energy_floor,co2_energy)

scenario_residential <- scenario_residential %>% 
  filter(year %in% c(2020,2030,2040,2050)) %>% 
  group_by(scenario,region,var) %>% 
  mutate(value=value/first(value))

scenario_residential <- scenario_residential %>% 
  mutate(value=value-1) %>% 
  ungroup()


openxlsx::addWorksheet(wb,"scenario residential (norm)")
openxlsx::writeData(wb, sheet = "scenario residential (norm)",scenario_residential, colNames = T, rowNames = F)






```

# Residential 

```{r scenarios_residential,echo=FALSE,warning=FALSE,fig.width=6,fig.height=9,fig.path="../../Results/Plots/Supplementary/",dev=c('png','pdf')}
# plot

scenario_residential %>% 
  filter(region!="World") %>%  
  filter(var!="co2") %>% 
  ggplot(.) +
  geom_bar(stat='identity',color="#636363",aes(x=year,y=value,fill=var)) +
  geom_point(data=scenario_residential %>% filter(var=="co2") %>% filter(region!="World"),aes(x=year,y=value,color=var))+
  facet_grid(region~scenario,labeller = label_wrap_gen(width=40,multi_line = TRUE),scales="free") +
  scale_fill_brewer(palette = "Set2",labels=c("CO2/Energy","Energy/Floor area","Floor area/Population","Population")) +
  scale_color_manual(values="#636363",labels="CO2") +
  theme(legend.position = "bottom",
        axis.title = element_blank(),
        legend.title = element_blank(),
        panel.grid.minor = element_blank())

```

```{r scenarios_residential_world,echo=FALSE,warning=FALSE,fig.width=6,fig.height=3,fig.path="../../Results/Plots/Supplementary/",dev=c('png','pdf')}
# plot

scenario_residential %>% 
  filter(region=="World") %>%  
  filter(var!="co2") %>% 
  ggplot(.) +
  geom_bar(stat='identity',color="#636363",aes(x=year,y=value,fill=var)) +
  geom_point(data=scenario_residential %>% filter(var=="co2") %>% filter(region=="World"),aes(x=year,y=value,color=var))+
  facet_grid(.~scenario,labeller = label_wrap_gen(width=40,multi_line = TRUE),scales="free",space="free") +
  scale_fill_brewer(palette = "Set2",labels=c("CO2/Energy","Energy/Floor area","Floor area/Population","Population")) +
  scale_color_manual(values="#636363",labels="CO2") +
  theme(legend.position = "bottom",
        axis.title = element_blank(),
        legend.title = element_blank(),
        panel.grid.minor = element_blank())

```

# Non-residential

```{r scenarios_nonresidential_calc,echo=FALSE,warning=FALSE}


scenario_nonresidential <- data %>% 
  filter(subsector_title=="Non-residential") %>% 
  select(-unit,-subsector_title)

scenario_nonresidential <- spread(scenario_nonresidential,variable,value)

names(scenario_nonresidential) <- c("region","year","scenario","energy","co2","value")

scenario_nonresidential <- scenario_nonresidential  %>% 
  mutate(energy = energy*1e6) %>% 
  mutate(value=value*1e6)


#CO2= Value added*[Energy/Value Added]*[CO2/Energy] 

scenario_nonresidential <- scenario_nonresidential %>% 
  mutate(energy_value = energy/value) %>% 
  mutate(co2_energy = co2/energy)

openxlsx::addWorksheet(wb,"scenario non-residential")
openxlsx::writeData(wb, sheet = "scenario non-residential",scenario_nonresidential, colNames = T, rowNames = F)


scenario_nonresidential <- gather(scenario_nonresidential,var,value,co2,value,energy_value,co2_energy)

scenario_nonresidential <- scenario_nonresidential %>% 
  filter(year %in% c(2020,2030,2040,2050)) %>% 
  group_by(scenario,region,var) %>% 
  mutate(value=value/first(value))

scenario_nonresidential <- scenario_nonresidential %>% 
  mutate(value=value-1) %>% 
  ungroup()

openxlsx::addWorksheet(wb,"scenario non-residential (norm)")
openxlsx::writeData(wb, sheet = "scenario non-residential (norm)",scenario_nonresidential, colNames = T, rowNames = F)






```

```{r scenarios_nonresidential,echo=FALSE,warning=FALSE,fig.width=6,fig.height=9,fig.path="../../Results/Plots/Supplementary/",dev=c('png','pdf')}
# plot

scenario_nonresidential %>% 
  filter(region!="World") %>%  
  filter(var!="co2") %>% 
  ggplot(.) +
  geom_bar(aes(x=year,y=value,fill=var),stat='identity',color="#636363") +
  geom_point(data=scenario_nonresidential %>% filter(var=="co2") %>% filter(region!="World"),aes(x=year,y=value,color=var))+
  facet_grid(region~scenario,labeller = label_wrap_gen(width=40,multi_line = TRUE),scales="free") +
  scale_fill_brewer(palette = "Set2",labels=c("CO2/Energy","Energy/Added value","Added value")) +
  scale_color_manual(values="#636363",labels="CO2") +
  theme(legend.position = "bottom",
        axis.title = element_blank(),
        legend.title = element_blank(),
        panel.grid.minor = element_blank())

```

```{r scenarios_nonresidential_world,echo=FALSE,warning=FALSE,fig.width=6,fig.height=3,fig.path="../../Results/Plots/Supplementary/",dev=c('png','pdf')}
# plot

scenario_nonresidential %>% 
  filter(region=="World") %>%
  filter(var!="co2") %>% 
  ggplot(.) +
  geom_bar(stat='identity',color="#636363",aes(x=year,y=value,fill=var)) +
  geom_point(data=scenario_nonresidential %>% filter(var=="co2") %>% filter(region=="World"),aes(x=year,y=value,color=var)) +
  facet_grid(.~scenario,labeller = label_wrap_gen(width=40,multi_line = TRUE),scales="free",space="free") +
  scale_fill_brewer(palette = "Set2",labels=c("CO2/Energy","Energy/Added value","Added value")) +
  scale_color_manual(values="#636363",labels="CO2") +
  theme(legend.position = "bottom",
        axis.title = element_blank(),
        legend.title = element_blank(),
        panel.grid.minor = element_blank())

```


```{r save}


openxlsx::saveWorkbook(wb,"../../Results/Data/building_kaya.xlsx",overwrite=T)



```
