---
title: "Kaya decomposition of sectoral CO2 emissions"
author: "William F. Lamb"
date: "7 6 2020"
output: 
  word_document:
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results") })
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(openxlsx)
library(ggplot2); theme_set(theme_bw())
library(data.table)
library(janitor)

wb <- openxlsx::createWorkbook(title = "sector_kaya_data",Sys.Date())

load('../../Data/Old data versions/edgar_data_gwp_ar6_late_2020.RData')
load('../../Data/land.RData')

land <- land %>%
  filter(year>1969) %>% 
  mutate(chapter=7,
         chapter_title="AFOLU",
         sector_code="land_CO2",
         description="Land-use CO2",
         subsector=7.7,
         subsector_title="Land-use CO2",
         CO2=mean,
         CH4=NA,N2O=NA,Fgas=NA,GHG=mean) %>% 
  select(-blue,-houghton,-mean)

load('../../Data/basic.RData')
load("../../Data/ipcc_regions.RData")

# load data from Robbie
kaya_data <- openxlsx::read.xlsx("../../Data/kaya/kaya_data_flat_201201.xlsx")
names(kaya_data) <- tolower(names(kaya_data))
kaya_data <- kaya_data %>% select(ISO=iso,everything())

pop_gdp <- kaya_data %>% 
  filter(sector=="---") %>%
  filter(variable=="POP" | variable=="GCP") %>% 
  select(-sector)
pop_gdp <- spread(pop_gdp,variable,value)
pop_gdp <- pop_gdp %>% 
  select(ISO,year,GDP=GCP,POP)

kaya_data <- left_join(kaya_data %>% filter(sector!="---"),
                       pop_gdp,by = c("ISO", "year"))

kaya_data <- kaya_data %>% 
  mutate(sector=ifelse(grepl("EGY",sector),"Energy systems",sector)) %>% 
  mutate(sector=ifelse(grepl("BLD",sector),"Buildings",sector)) %>% 
  mutate(sector=ifelse(grepl("IND",sector),"Industry",sector)) %>% 
  mutate(sector=ifelse(grepl("LUC",sector),"AFOLU",sector)) %>% 
  mutate(sector=ifelse(grepl("TOT",sector),"Total",sector)) %>% 
  mutate(sector=ifelse(grepl("TRA",sector),"Transport",sector)) %>% 
  mutate(variable=ifelse(grepl("EGY",variable),"energy",variable)) %>% 
  mutate(variable=ifelse(grepl("CO2",variable),"CO2",variable))

kaya_data <- spread(kaya_data,variable,value)
kaya_data <- kaya_data %>% 
  filter(year<2019) %>% 
  filter(year>1989)

# join IPCC regions
kaya_data <- left_join(kaya_data,ipcc_regions %>% select(ISO,name,region_ar6_6,region_ar6_6_short,region_ar6_10),by=c("ISO"="ISO"))

uhoh <- anti_join(kaya_data,ipcc_regions %>% select(ISO,name,region_ar6_6,region_ar6_6_short,region_ar6_10),by=c("ISO"="ISO"))

kaya_data <- kaya_data %>% 
  select(ISO,name,region_ar6_6,region_ar6_6_short,region_ar6_10,sector,year,everything()) %>% 
  mutate(year=as.numeric(year))

# edit units
kaya_data <- kaya_data %>% 
  mutate(GDP = as.numeric(GDP)) %>% 
  mutate(POP = as.numeric(POP)) %>% 
  mutate(CO2 = as.numeric(CO2)) %>% 
  mutate(energy = as.numeric(energy))
kaya_data <- kaya_data %>% 
  mutate(GDP = GDP*1e9) %>% 
  mutate(POP = POP*1000) %>% 
  mutate(CO2 = CO2*1000) %>% 
  mutate(energy = energy*1000)

country_kaya_data <- kaya_data

world_pop <- kaya_data %>% 
  filter(sector=="Total") %>% 
  filter(ISO!="WLD") %>% 
  group_by(year) %>% 
  summarise(POP=sum(POP,na.rm=TRUE)/1e6)

save(file='../../Data/kaya/kaya.RData',kaya_data)

# blarg <- kaya_data %>% 
#   filter(ISO=="WLD") %>% 
#   filter(sector=="Total")
# 
# blarg <- kaya_data %>% 
#   filter(ISO=="WLD") %>% 
#   filter(year==2018) %>% 
#   select(sector,energy,CO2)
# 
# eddy <- edgar_GHG_ar6 %>% 
#   filter(year==2018) %>% 
#   group_by(chapter_title) %>% 
#   summarise(eddy=sum(CO2,na.rm=TRUE))
# 
# blarg <- left_join(blarg,eddy,by=c("sector"="chapter_title"))

```


```{r decomposition, include=FALSE}

# change World into a region
kaya_data <- kaya_data %>% 
  mutate(region_ar6_10=as.character(region_ar6_10)) %>% 
  mutate(name=ifelse(ISO=="WLD","World",name)) %>% 
  mutate(region_ar6_6=ifelse(ISO=="WLD","World",region_ar6_6)) %>% 
  mutate(region_ar6_6_short=ifelse(ISO=="WLD","World",region_ar6_6_short)) %>% 
  mutate(region_ar6_10=ifelse(ISO=="WLD","World",region_ar6_10))

kaya_data$region_ar6_10 <- as.factor(kaya_data$region_ar6_10)

# sum all variables to regions - first check for nan countries

missing_countries <- kaya_data[!complete.cases(kaya_data),]
missing_countries <- missing_countries %>% 
  filter(sector!="AFOLU") %>% 
  filter(sector!="OTH") %>% 
  filter(sector!="NON") %>% 
  filter(sector!="STT")

kaya_data <- kaya_data %>% 
  na.omit()

kaya_data <- kaya_data %>% 
  group_by(region_ar6_10,sector,year) %>% 
  summarise_at(vars(CO2,energy,GDP,POP),sum,na.rm=TRUE)

# calculate kaya components
kaya_data <- kaya_data %>% 
  mutate(CO2_energy=CO2/energy) %>%
  mutate(energy_GDP=energy/GDP) %>%
  mutate(GDP_POP=GDP/POP)


meta <- data.frame("Variable" = c("CO2","energy","GDP","POP","ag_production_kcal","land_area_hectares","GHG"),
                   "Description" = c("Carbon emissions","Energy","Gross Domestic Product","Population","Agricultural production","Land area","Greenhouse gas emissions"),
                   "Units" = c("tCO2","GJ","$ (PPP 2010 USD)","persons","kcals","hectares","tCO2eq"),
                   "Source" = c("IEA World Energy Balances","IEA World Energy Balances","World Bank, IMF","UN Population division","Hong et al. 2020","Hong et al. 2020","EDGAR & BLUE"))


wb2 <- openxlsx::createWorkbook(title = "kaya_data")
openxlsx::addWorksheet(wb2,"metadata")
openxlsx::addWorksheet(wb2,"data")
openxlsx::writeData(wb2, sheet = "metadata",meta, colNames = T, rowNames = F)
openxlsx::writeData(wb2, sheet = "data",country_kaya_data %>% filter(sector!="AFOLU"), colNames = T, rowNames = F)


```


```{r plot_function,include=FALSE,fig.width=9,fig.height=9}

sector_label ="Energy systems"

kaya_plots_10 <- function(kaya,sector_label) {
  
  kaya_plot_data <- kaya_data %>% 
    filter(sector==sector_label) %>% 
    filter(year>1989)
  rates <- gather(kaya_plot_data,var,value,CO2:GDP_POP)
  
  rates <- rates %>% 
    filter(year %in% c(2010,2018)) %>% 
    group_by(region_ar6_10,sector,var) %>% 
    mutate(rate=((last(value)/first(value))^(1/(last(year)-first(year)))-1)*100) %>% 
    filter(year==2018)
  
  output_data <- gather(kaya_plot_data,var,value,CO2:GDP_POP)
  output_data <- spread(output_data,year,value)
  
  output_data <- left_join(output_data,rates %>% select(-value,-year),by = c("region_ar6_10","sector", "var"))
  output_data <- output_data %>% 
    select(region_ar6_10,sector,var,rate_2010_2017=rate,everything())
  
  kaya_plot_data <- gather(kaya_plot_data %>% select(-GDP),var,value,GDP_POP,POP,CO2,energy,CO2_energy,energy_GDP)
  
  kaya_plot_data <- kaya_plot_data %>% 
    group_by(region_ar6_10,var) %>% 
    mutate(value=value/first(value))
  
  kaya_plot_data <- left_join(kaya_plot_data,rates %>% select(-value),by = c("region_ar6_10", "year", "sector", "var"))
  
  p <- kaya_plot_data %>%
    ggplot(.,aes(x=year,y=value,group=var,colour=var)) +
    geom_hline(yintercept=1) +
    geom_vline(xintercept=2010,alpha=0.3,linetype="dashed") +
    geom_path(size = 1.5) +
    geom_point(size = 0.75,colour="white") +
    geom_text(data=kaya_plot_data %>% filter(year==2018),
              aes(x=year+1,y=value,label=paste0(ifelse(rate>0,"+","-"),round(abs(rate),1),"%")),hjust=0,show.legend = FALSE) +
    theme_bw() +
    scale_colour_brewer(type = "qual",palette="Set2",labels=c("CO2 Emissions","CO2/Energy","Energy","Energy/GDP","GDP/Population","Population")) +
    scale_x_continuous(breaks=c(1990,2000,2010,2018),limits=c(1990,2023.5)) + 
    facet_wrap(.~region_ar6_10,ncol=3,scales="free") +
    theme(legend.position = c(0.75,0.1),
          axis.title = element_blank(),
          legend.title = element_blank(),
          panel.grid.minor = element_blank())
  
  return(list("plot"=p,"data"=output_data,"normalised_data"=spread(kaya_plot_data %>% select(-rate),year,value)))
}

```

```{r total_10,echo=FALSE,warning=FALSE,fig.width=9,fig.height=9,fig.path="../../Results/Plots/Kaya/",dev=c('png','pdf')}

p <- kaya_plots_10(kaya,"Total")
p$p


openxlsx::addWorksheet(wb,"all_sectors")
openxlsx::addWorksheet(wb,"all_sectors_normalised")
openxlsx::writeData(wb, sheet = "all_sectors",p$data, colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "all_sectors_normalised",p$normalised_data, colNames = T, rowNames = F)



```

```{r AFOLU_10,echo=FALSE,warning=FALSE,fig.width=9,fig.height=9,fig.path="../../Results/Plots/Kaya/",dev=c('png','pdf')}

# p <- kaya_plots_10(kaya,"AFOLU")
# p$p
# 
# 


```

# Energy systems

```{r energy_systems_10,echo=FALSE,warning=FALSE,fig.width=9,fig.height=9,fig.path="../../Results/Plots/Kaya/",dev=c('png','pdf')}

p <- kaya_plots_10(kaya,"Energy systems")
p$p


openxlsx::addWorksheet(wb,"energy_systems")
openxlsx::addWorksheet(wb,"energy_systems_normalised")
openxlsx::writeData(wb, sheet = "energy_systems",p$data, colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "energy_systems_normalised",p$normalised_data, colNames = T, rowNames = F)




```

# Buildings

```{r buildings_10,echo=FALSE,warning=FALSE,fig.width=9,fig.height=9,fig.path="../../Results/Plots/Kaya/",dev=c('png','pdf')}

p <- kaya_plots_10(kaya,"Buildings")
p$p


openxlsx::addWorksheet(wb,"buildings")
openxlsx::addWorksheet(wb,"buildings_normalised")
openxlsx::writeData(wb, sheet = "buildings",p$data, colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "buildings_normalised",p$normalised_data, colNames = T, rowNames = F)

```

# Transport

```{r transport_10,echo=FALSE,warning=FALSE,fig.width=9,fig.height=9,fig.path="../../Results/Plots/Kaya/",dev=c('png','pdf')}

p <- kaya_plots_10(kaya,"Transport")
p$p


openxlsx::addWorksheet(wb,"transport")
openxlsx::addWorksheet(wb,"transport_normalised")
openxlsx::writeData(wb, sheet = "transport",p$data, colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "transport_normalised",p$normalised_data, colNames = T, rowNames = F)


```

# Industry

```{r industry_10,echo=FALSE,warning=FALSE,fig.width=9,fig.height=9,fig.path="../../Results/Plots/Kaya/",dev=c('png','pdf')}

p <- kaya_plots_10(kaya,"Industry")
p$p


openxlsx::addWorksheet(wb,"industry")
openxlsx::addWorksheet(wb,"industry_normalised")
openxlsx::writeData(wb, sheet = "industry",p$data, colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "industry_normalised",p$normalised_data, colNames = T, rowNames = F)



```

# AFOLU (Hong et al. decomposition)

```{r AFOLU_hong,echo=FALSE,warning=FALSE,fig.width=9,fig.height=9,fig.path="../../Results/Plots/Kaya/",dev=c('png','pdf')}

hong_a <- openxlsx::read.xlsx('../../Data/Land and GCB/DataPortal_LUE_28Jun20.xlsx',sheet='Ag_production_kcal')
names(hong_a) <- c("country","product",1961:2017)
hong_a <- gather(hong_a,year,ag_production_kcal,`1961`:`2017`)
hong_a <- hong_a %>% 
  group_by(year,country) %>% 
  summarise(ag_production_kcal=sum(ag_production_kcal,na.rm=TRUE))

hong_b <- openxlsx::read.xlsx('../../Data/Land and GCB/DataPortal_LUE_28Jun20.xlsx',sheet='Land_area_hectares')
names(hong_b) <- c("country","product",1961:2017)
hong_b <- gather(hong_b,year,land_area_hectares,`1961`:`2017`)
hong_b <- hong_b %>% 
  group_by(year,country) %>% 
  summarise(land_area_hectares=sum(land_area_hectares,na.rm=TRUE))

hong <- left_join(hong_a,hong_b,by = c("year", "country"))
codes <- openxlsx::read.xlsx('C:/Users/lamw/Documents/SpiderOak Hive/Work/Code/R/.Place names and codes/output/ISOcodes.xlsx',sheet = 'alternative_names')

hong <- left_join(hong %>% mutate(country=tolower(country)),codes,by=c("country"="alternative.name"))

hong <- hong %>% 
  mutate(alpha.3=ifelse(grepl("d ivoire",country),"CIV",alpha.3)) %>% 
  mutate(alpha.3=ifelse(grepl("china, taiwan province of",country),"TWN",alpha.3)) %>% 
  mutate(alpha.3=ifelse(grepl("union",country),"REU",alpha.3))  %>% 
  mutate(alpha.3=ifelse(grepl("pacific islands trust territory",country),"PCI",alpha.3)) %>%
  ungroup() %>% 
  mutate(year=as.numeric(year))

afolu_GHG <- edgar_GHG_ar6_late_2020 %>% 
  filter(chapter_title=="AFOLU") %>% 
  group_by(ISO,year,region_ar6_10) %>% 
  summarise(GHG=sum(GHG,na.rm = TRUE))

hong <- left_join(hong,afolu_GHG,by=c("alpha.3"="ISO","year"="year"))
hong <- hong %>% 
  filter(year>1989) %>% 
  filter(!is.na(region_ar6_10)) %>% 
  select(ISO=alpha.3,country,region_ar6_10,year,everything())

hong <- left_join(hong,basic %>% select(ISO,year=Year,pop_UN),by = c("ISO", "year"))
all_data <- hong

################## now calculate kaya

wld <- hong %>% 
  group_by(year) %>% 
  summarise_at(vars(pop_UN,GHG,ag_production_kcal,land_area_hectares),sum,na.rm=TRUE)
wld <- wld %>% 
  mutate(region_ar6_10="World") %>% 
  select(year,region_ar6_10,pop_UN,GHG,ag_production_kcal,land_area_hectares)

hong <- hong %>% 
  group_by(year,region_ar6_10) %>% 
  summarise_at(vars(pop_UN,GHG,ag_production_kcal,land_area_hectares),sum,na.rm=TRUE)

hong <- hong %>% 
  bind_rows(wld)

hong <- hong %>% 
  mutate(production_percap=ag_production_kcal/pop_UN) %>% 
  mutate(land_production=land_area_hectares/ag_production_kcal) %>% 
  mutate(ghg_land=GHG/land_area_hectares)

hong <- hong %>% 
  select(region_ar6_10,year,GHG,POP=pop_UN,production_percap,land_production,ghg_land)

######################## rates and output data


rates <- gather(hong,var,value,-region_ar6_10,-year)
rates <- rates %>% 
  filter(year %in% c(2010,2017)) %>% 
  group_by(region_ar6_10,var) %>% 
  mutate(rate=((last(value)/first(value))^(1/(last(year)-first(year)))-1)*100) %>% 
  filter(year==2017)

output_data <- gather(hong,var,value,-region_ar6_10,-year)
output_data <- spread(output_data,year,value)

output_data <- left_join(output_data,rates %>% select(-value,-year),by = c("region_ar6_10", "var"))

output_data <- output_data %>% 
  mutate(sector="AFOLU") %>%
  select(region_ar6_10,sector,var,rate_2010_2017=rate,everything())


######################## plot

hong_kaya <- gather(hong,var,value,GHG,POP,production_percap,land_production,ghg_land)
hong_kaya <- hong_kaya %>% 
  group_by(region_ar6_10,var) %>% 
  mutate(value=value/first(value))
                    
hong_kaya <- left_join(hong_kaya,rates %>% select(-value),by = c("region_ar6_10", "year", "var"))

hong_kaya %>%
  ggplot(.,aes(x=year,y=value,group=var,colour=var)) +
  geom_hline(yintercept=1) +
  geom_vline(xintercept=2010,alpha=0.3,linetype="dashed") +
  geom_path(size = 1.5) +
  geom_point(size = 0.75,colour="white") +
  geom_text(data=hong_kaya %>% filter(year==2017),
            aes(x=year+1,y=value,label=paste0(ifelse(rate>0,"+","-"),round(abs(rate),1),"%")),hjust=0,show.legend = FALSE) +
  theme_bw() +
  scale_colour_brewer(type = "qual",palette="Set2",labels=c("GHG Emissions","GHG/Land area","Land area/Agricultural output","Population","Agricultural output/Population")) +
  scale_x_continuous(breaks=c(1990,2000,2010,2017),limits=c(1990,2022.5)) + 
  facet_wrap(.~region_ar6_10,ncol=3,scales="free") +
  theme(legend.position = c(0.8,0.1),
        axis.title = element_blank(),
        legend.title = element_blank(),
        panel.grid.minor = element_blank())


openxlsx::addWorksheet(wb,"AFOLU")
openxlsx::addWorksheet(wb,"AFOLU_normalised")
openxlsx::writeData(wb, sheet = "AFOLU",output_data, colNames = T, rowNames = F)
openxlsx::writeData(wb, sheet = "AFOLU_normalised",spread(hong_kaya %>% select(-rate),year,value), colNames = T, rowNames = F)



```

``` {r write,include=TRUE,warning=FALSE}

openxlsx::saveWorkbook(wb,paste0("../../Results/Data/sector_kaya_analysis_",Sys.Date(),".xlsx"),overwrite=T)

openxlsx::addWorksheet(wb2,"afolu_data")
openxlsx::writeData(wb2, sheet = "afolu_data",all_data, colNames = T, rowNames = F)
#openxlsx::saveWorkbook(wb2,"../../Results/Data/kaya_data.xlsx",overwrite=T)


```



``` {r checks,include=FALSE}

wb <- openxlsx::createWorkbook(title = "kaya_tests")

# Do regions add up to global totals each year?

region_test <- kaya_data %>%
  filter(region_ar6_10!="World") %>%
  filter(sector=="Total") %>%
  group_by(year) %>%
  summarise_at(vars(CO2,energy,GDP,POP),sum,na.rm=TRUE)

region_test <- gather(region_test,var,region_value,-year)

world <- kaya_data %>%
  filter(region_ar6_10=="World") %>%
  filter(sector=="Total") %>%
  group_by(year) %>%
  summarise_at(vars(CO2,energy,GDP,POP),sum,na.rm=TRUE)

world <- gather(world,var,world_value,-year)

region_test <- left_join(region_test,world,by = c("year", "var"))

openxlsx::addWorksheet(wb,"region_totals")
openxlsx::writeData(wb, sheet = "region_totals", region_test, colNames = T, rowNames = F)


# Do sectors add up to the total sector each year?

sector_test <- kaya_data %>%
  filter(region_ar6_10=="World") %>%
  filter(sector!="Total") %>% 
  group_by(year) %>%
  summarise_at(vars(CO2,energy),sum,na.rm=TRUE)

sector_test <- gather(sector_test,var,sector_value,-year)

total <- kaya_data %>%
  filter(region_ar6_10=="World") %>%
  filter(sector=="Total") %>%
  group_by(year) %>%
  summarise_at(vars(CO2,energy),sum,na.rm=TRUE)

total <- gather(total,var,total_value,-year)

sector_test <- left_join(sector_test,total,by = c("year", "var"))

openxlsx::addWorksheet(wb,"sector_totals")
openxlsx::writeData(wb, sheet = "sector_totals", sector_test, colNames = T, rowNames = F)

openxlsx::saveWorkbook(wb,"../../Results/Data/kaya_tests.xlsx",overwrite=T)


save(kaya_data,hong,file="../../Data/kaya.RData")

```
