---
title: "SDGs and emissions"
author: "William F. Lamb"
output: 
  word_document:
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results") })
  
---

```{r setup, include=FALSE}

# 1. poverty          SI.POV.DDAY
# 2. nutrition
# 3. life expectancy  SP.DYN.LE00.IN
# 4. education        SE.SEC.ENRR
# 5. gender??
# 6. sanitation       SH.STA.BASS.ZS
# 7. electricity      EG.ELC.ACCS.ZS
# 8. employment       SL.UEM.TOTL.ZS
# 10. inequality      


rm(list = ls())
library(wbstats)
library(tidyverse)
library(zoo)
library(ggpubr)
library(ggplot2); theme_set(theme_bw())
library(cluster)
library(ggrepel)



 vars <- wbsearch(pattern = "population")

 
load('C:\\Users\\lamw\\Documents\\SpiderOak Hive\\Work\\Code\\R\\Database\\SWIID\\SWIID.RData')

# 
# sdgs <- wb(country="all",indicator=c("SI.POV.DDAY","SP.DYN.LE00.IN","SH.DYN.MORT","SE.SEC.ENRR","SH.STA.BASS.ZS","EG.ELC.ACCS.ZS","SL.UEM.TOTL.ZS","SP.POP.TOTL","NY.GDP.MKTP.KD"))
# 
# sdgs <- sdgs %>%
#   mutate(indicatorID=ifelse(grepl("SI.POV.DDAY",indicatorID),"Poverty",indicatorID)) %>%
#   mutate(indicatorID=ifelse(grepl("SP.DYN.LE00.IN",indicatorID),"Life_expectancy",indicatorID)) %>%
#   mutate(indicatorID=ifelse(grepl("SH.DYN.MORT",indicatorID),"Mortality",indicatorID)) %>%
#   mutate(indicatorID=ifelse(grepl("SE.SEC.ENRR",indicatorID),"Education",indicatorID)) %>%
#   mutate(indicatorID=ifelse(grepl("SH.STA.BASS.ZS",indicatorID),"Sanitation",indicatorID)) %>%
#   mutate(indicatorID=ifelse(grepl("EG.ELC.ACCS.ZS",indicatorID),"Electricity",indicatorID)) %>%
#   mutate(indicatorID=ifelse(grepl("SL.UEM.TOTL.ZS",indicatorID),"Employment",indicatorID)) %>%
#   mutate(indicatorID=ifelse(grepl("SP.POP.TOTL",indicatorID),"Population",indicatorID)) %>%
#   mutate(indicatorID=ifelse(grepl("NY.GDP.MKTP.KD",indicatorID),"GDP_PPP",indicatorID))
# 
# save(sdgs,file='../../Data/sdgs.RData')


load('../../Data/sdgs.RData')
load('../../Data/edgar_data_gwp_ar6.RData')
load('../../Data/basic.RData')

```




```{r prepare_table,echo=FALSE,inclue=FALSE}

# list <- sdgs %>% 
#   select(indicatorID,indicator) %>% 
#   distinct() %>% 
#   mutate(source="World Bank")
# 
# openxlsx::write.xlsx(list,'../Data/SDGs/sdgs.xlsx')

table <- sdgs %>% 
  select(iso=iso3c,country,year=date,sdg=indicatorID,-indicator,value)

table <- spread(table,sdg,value)

###### linear interpolate missing years, maxgap of 3

table <- table %>% 
  group_by(country) %>% 
  mutate_at(vars(-country,-iso,-year),
            na.approx,na.rm=FALSE,maxgap=3)

# table <- table %>% 
#   filter(iso=="IND") %>% 
#   group_by(country) %>% 
#   mutate_at(vars(-group_cols()),na.approx,na.rm=FALSE,maxgap=3)
#   mutate_at(vars(-group_cols()),funs(na.locf(.,fromLast=TRUE,na.rm=FALSE))) ##fill everything backwards (no interpolation)
#   mutate_at(vars(-group_cols()),funs(na.locf(.,na.rm=FALSE))) ##fill everything forwards (no interpolation)

table <- table %>% 
  group_by(country) %>% 
  mutate_at(vars(-group_cols()),funs(na.locf(.,na.rm=FALSE))) %>%  #!!!!!!!!!!!!!!!!
  mutate(Employment=100-Employment) %>% 
  mutate(Poverty=100-Poverty) %>% 
  mutate(Mortality=100-(0.1*Mortality)) %>% 
  mutate(year=as.numeric(year)) %>% 
  ungroup() %>% 
  select(-Life_expectancy)

table <- table %>% 
  filter(year==2018)

thresholds = data.frame(sdg=c("Poverty","Mortality","Education","Sanitation","Electricity","Employment"),
                        upper=c(95,95,95,95,95,94),lower=c(80,60,80,80,80,80))


labels = data.frame(sdg=c("Poverty","Mortality","Education","Sanitation","Electricity","Employment"),
                        label=c("Poverty headcount\n(% > $1.90/day)",
                                "Under-5 survival rate\n(% to 5 years)",
                                "Secondary education\n(% gross enrollment)",
                                "Improved sanitation\n(% Access)",
                                "Household electricity\n(% Access)",
                                "Employment\n(%)"))


table <- table %>%
  group_by(country,year) %>%
  mutate(group=0) %>%
  mutate(group=ifelse(Poverty>=thresholds$upper[thresholds$sdg=="Poverty"],group+1,group)) %>%
  mutate(group=ifelse(Mortality>=thresholds$upper[thresholds$sdg=="Mortality"],group+1,group)) %>%
  mutate(group=ifelse(Education>=thresholds$upper[thresholds$sdg=="Education"],group+1,group)) %>%
  mutate(group=ifelse(Sanitation>=thresholds$upper[thresholds$sdg=="Sanitation"],group+1,group)) %>%
  mutate(group=ifelse(Electricity>=thresholds$upper[thresholds$sdg=="Electricity"],group+1,group)) %>%
  mutate(group=ifelse(Employment>=thresholds$upper[thresholds$sdg=="Employment"],group+1,group)) %>%
  ungroup() %>%
  select(iso,country,year,Population,everything())

# table <- table %>%
#   filter(!is.na(group))


## join with Edgar


edgar_countries <- edgar_GHG_ar6 %>%
  filter(year==2018) %>% 
  group_by(ISO,country,region_ar6_5,region_ar6_5_short) %>%
  summarise(GHG=sum(GHG,na.rm=T)) %>%
  ungroup()

edgar_countries <- left_join(edgar_countries,table %>% select(-country),by=c("ISO"="iso"))

edgar_countries <- edgar_countries %>% 
  filter(!is.na(group))

edgar_countries <- edgar_countries %>% 
  mutate(GHG_pc=GHG/Population)

#edgar_countries$group <- as.factor(edgar_countries$group)


# ##### which countries move groups?
# 
# 
# edgar_countries <- edgar_countries %>% 
#   filter(!is.na(group)) %>% 
#   #filter(year>2000) %>% 
#   group_by(country) %>% 
#   mutate(moving=nth(group,1)) %>% 
#   ungroup() %>% 
#   group_by(country,year) %>% 
#   mutate(moving=ifelse(group==moving,0,1)) %>% 
#   group_by(country) %>% 
#   mutate(defmoving=ifelse(sum(moving)!=0,1,0))

```


```{r ch1_plot, echo=FALSE,warning=FALSE,results='asis',fig.width=8,fig.height=4,fig.path="../../Results/Plots/sdgs/",dev=c('png','pdf')}
# 
# data <- edgar_GHG_ar6 %>% 
#   filter(year>1989) %>% 
#   group_by(year,ISO,country,region_ar6_5,region_ar6_5_short) %>% 
#   summarise(GHG=sum(GHG,na.rm=T))
# 
# pop <- basic %>% 
#   filter(Year>1989) %>% 
#   select(ISO,year=Year,pop_UN)
# 
# data <- left_join(data,pop,by = c("year", "ISO"))
# 
# blarg <- data %>% 
#   filter(year==2018)
# 
# data <- data %>% 
#   filter(year==2018) %>% 
#   filter(region_ar6_5_short!="AIR") %>% 
#   filter(region_ar6_5_short!="SEA") %>% 
#   group_by(year,region_ar6_5,region_ar6_5_short) %>% 
#   summarise(GHG=sum(GHG,na.rm=T),pop=sum(pop_UN,na.rm=T)) %>% 
#   mutate(GHG_pc=GHG/pop)
# 
# data <- data %>% 
#   mutate(fake=ifelse(region_ar6_5_short=="AME",1,NA)) %>% 
#   mutate(fake=ifelse(region_ar6_5_short=="APC",2,fake))%>% 
#   mutate(fake=ifelse(region_ar6_5_short=="DEV",5,fake))%>% 
#   mutate(fake=ifelse(region_ar6_5_short=="EEA",4,fake))%>% 
#   mutate(fake=ifelse(region_ar6_5_short=="LAM",3,fake))


# data %>% 
#   ggplot(.,aes(x=GHG_pc,y=fake,size=pop,label=region_ar6_5,color=region_ar6_5)) +
#   geom_point() +
#   geom_text(aes(y=fake+0.5),size=4,hjust=0) +
#   scale_size(range = c(.1, 24)) +
#   xlim(0,20) +
#   theme(legend.position ="none")

edgar_countries %>% 
  ggplot(.,aes(x=GHG_pc,y=group,size=Population,fill=region_ar6_5)) +
  geom_point(shape = 21,alpha=0.7,stroke=0,colour="#636363") +
  #geom_text(aes(y=fake+0.5),size=4,hjust=0) +
  scale_size(range = c(1, 20)) +
  xlim(0,30) +
  labs(fill = "Region") +
  guides(fill = guide_legend(override.aes = list(size=8))) +
  theme(legend.position ="right") +
  ylab("No. SDG thresholds achieved") +
  xlab("GHG emissions (CO2eq/capita)")


```

```{r time_trend, echo=FALSE,warning=FALSE}


data <- sdgs %>% 
  select(iso=iso3c,country,year=date,sdg=indicatorID,-indicator,value) %>% 
  filter(country=="World")

data <- spread(data,sdg,value)

data <- data %>% 
  select(-Sanitation,-Electricity,-Employment,-Mortality,-iso,-country) %>% 
  mutate(Poverty=100-Poverty) %>% 
  mutate(year=as.numeric(year))


## join emissions

world_emissions <- edgar_GHG_ar6 %>% 
  group_by(year) %>% 
  summarise(CO2=sum(CO2,na.rm=TRUE))

data <- left_join(data,world_emissions,by="year")

## join energy

energy <- openxlsx::read.xlsx("../../Data/IEA/2020 update/iea_web.xlsx")
energy <- energy %>% 
  slice(31)
energy <- gather(energy,year,Energy,`1960`:`2019`)
energy <- energy %>% 
  filter(year>1970) %>% 
  filter(year<2019) %>% 
  select(-X1,-TIME) %>% 
  mutate(Energy=as.numeric(Energy)) %>% 
  mutate(year=as.numeric(year))

data <- left_join(data,energy,by="year")


## normalise to 1990

data <- gather(data,var,value,Education:Energy)

data <- data %>% 
  group_by(var) %>% 
  mutate(value=value/nth(value,31)) %>% 
  ungroup() %>% 
  mutate(var=ifelse(var=="Education","Secondary education (% gross enrollment)",var)) %>% 
  mutate(var=ifelse(var=="GDP_PPP","GDP ($)",var)) %>% 
  mutate(var=ifelse(var=="Life_expectancy","Life expectancty (years)",var)) %>% 
  mutate(var=ifelse(var=="CO2","Carbon emissions (CO2)",var)) %>% 
  mutate(var=ifelse(var=="Population","Population (persons)",var)) %>% 
  mutate(var=ifelse(var=="Poverty","Poverty headcount (% > $1.90/day)",var)) %>% 
  mutate(var=ifelse(var=="Energy","Final energy consumption (GJ)",var))

labels <- data %>% 
  group_by(var) %>% 
  mutate(value=na.locf(value,na.rm=FALSE)) %>% 
  filter(year==2018)



p1 <- data %>% ggplot(.,aes(x=year,y=value,group=var,color=var)) + 
  geom_path(size=1.5) +
  geom_text_repel(inherit.aes=FALSE,data=labels,aes(x=year+2,y=value,color=var,label=str_wrap(var,width=20)),
                  hjust=0,
                  direction = "y",
                  segment.color = 'transparent',
                  xlim = c(1960,2050)) +
  theme_bw() +
  scale_x_continuous(limits=c(1960,2050),breaks=c(1960,1980,2000,2020)) + 
  scale_color_brewer(palette="Set2") +
  theme(legend.position="none",
        axis.title = element_blank(),panel.grid.minor = element_blank())
p1

```

```{r distribution, echo=FALSE,warning=FALSE}


codes <- openxlsx::read.xlsx('C:/Users/lamw/Documents/SpiderOak Hive/Work/Code/R/.Place names and codes/output/ISOcodes.xlsx',sheet = 'alternative_names')


tfec <- openxlsx::read.xlsx("../../Data/IEA/2020 update/tfec.xlsx")
tfec <- tfec %>% 
  mutate(country=tolower(TIME))

tfec <- gather(tfec,year,value,`1960`:`2019`)

tfec <- left_join(tfec,codes,by=c("country"="alternative.name"))

regions <- tfec

tfec <- tfec %>% 
  filter(!is.na(alpha.3)) %>% 
  filter(alpha.3!="ZZZZ") %>% 
  mutate(value=ifelse(value=="..",NA,value)) %>% 
  mutate(value=as.numeric(value)) %>% 
  mutate(value=value*1000) %>% 
  mutate(year=as.numeric(year)) %>% 
  select(alpha.3,year,Energy=value)

lex_gdp <- sdgs %>% 
  filter(indicatorID %in% c("GDP_PPP","Life_expectancy","Population")) %>% 
  select(alpha.3=iso3c,year=date,value,indicatorID) %>% 
  mutate(year=as.numeric(year))

lex_gdp <- spread(lex_gdp,indicatorID,value)

plot_data <- left_join(lex_gdp,tfec,by = c("year","alpha.3"))

load("../../Data/ipcc_regions.RData")

plot_data <- left_join(plot_data,ipcc_regions %>% select(alpha.3=ISO,region_ar6_5))

p2 <- plot_data %>% filter(year==2018) %>% 
  filter(alpha.3!="WLD") %>% 
  ggplot(.,aes(x=Energy/Population,y=Life_expectancy,size=Population,fill=region_ar6_5)) +
  geom_point(shape = 21,alpha=0.7,stroke=0,colour="#636363") +
  scale_size(range = c(1, 25)) +
  theme(legend.position="none",panel.grid.minor = element_blank()) +
  ylab("Life expectancy at birth (years)") +
  xlab("Final energy consumption  (GJ/capita)")

p3 <- plot_data %>% filter(year==2018) %>% 
  filter(alpha.3!="WLD") %>% 
  ggplot(.,aes(x=Energy/Population,y=GDP_PPP/Population,size=Population,fill=region_ar6_5)) +
  geom_point(shape = 21,alpha=0.7,stroke=0,colour="#636363") +
  scale_y_continuous(trans = "log",breaks=c(1000,5000,10000,20000,50000,100000),labels = scales::comma) +
  scale_x_continuous(trans = "log",breaks=c(0,100,200,300,400,500)) +
  scale_size(range = c(1, 25)) +
  #theme(legend.position="none",panel.grid.minor = element_blank()) +
  ylab("GDP (log PPP 2010$ / capita)") +
  xlab("Final energy consumption (log GJ / capita)")
  
p3
```
```{r sdg_figure, echo=FALSE,warning=FALSE,results='asis',fig.width=10,fig.height=6,fig.path="../../Results/Plots/sdgs/",dev=c('png','pdf')}

library(patchwork)

(p1 + plot_spacer()) / (p3 + p2)


```

```{r clustering_pathways, echo=FALSE,warning=FALSE,results='asis',fig.width=8,fig.height=4,fig.path="../../Results/Plots/sdgs/",dev=c('png','pdf')}
# 
# emissions_data <- edgar_GHG_ar6 %>% 
#   group_by(country,ISO,region_ar6_5,year) %>% 
#   summarise_at(vars(CO2,GHG),sum,na.rm=TRUE)
# 
# emissions_data <- left_join(emissions_data,basic %>% select(ISO,year=Year,pop_UN,gdp_ppp_WB))
# 
# ############## !!!!!!!!!!!!!!
# emissions_data <- emissions_data %>% 
#   group_by(country) %>% 
#   mutate(gdp_ppp_WB=na.locf(gdp_ppp_WB,na.rm=FALSE))
# ############## !!!!!!!!!!!!!!
# 
# 
# emissions_data <- emissions_data %>% 
#   mutate(CO2pc=CO2/pop_UN) %>% 
#   mutate(GHGpc=GHG/pop_UN) %>% 
#   mutate(GDPpc=gdp_ppp_WB/pop_UN) %>% 
#   mutate(var=CO2pc)
# 
# 
# 
# world <- emissions_data %>% 
#   group_by(year) %>% 
#   summarise_at(vars(pop_UN,CO2,GHG,gdp_ppp_WB),sum,na.rm=TRUE) %>% 
#   filter(year==2018) %>% 
#   select(-year)
# 
# emissions_data <- emissions_data %>% 
#   filter(!is.na(var)) %>% 
#   filter(country!="Qatar") %>% 
#   #filter(country!="Trinidad and Tobago") %>% 
#   mutate(inc=ifelse(year==2018 & pop_UN>1e6,1,0)) %>% 
#   group_by(country) %>% 
#   mutate(inc=max(inc)) %>%
#   ungroup() %>% 
#   filter(inc==1)
# 
# cluster_data <- emissions_data %>% 
#   filter(year %in% c(1980,1985,1990,1995,2000,2005,2010,2015,2018))
# 
# cluster_data <- spread(cluster_data %>% select(country,ISO,year,var),year,var)
# 
# clusters <- pam(cluster_data %>% select(-country,-ISO),6)
# 
# cluster_data <- cbind(cluster_data,cluster=clusters$clustering) ### bind clusters to dataset
# cluster_data$cluster <- as.factor(clusters$clustering) ### convert to factor
# 
# emissions_data <- left_join(emissions_data,cluster_data %>% select(ISO,cluster),by=c("ISO"="ISO"))
# 
# 
# summary_table <- emissions_data %>% 
#   filter(year==2018) %>% 
#   group_by(cluster) %>% 
#   summarise(countries=paste0(country,collapse=", "), pop=sum(pop_UN),CO2=sum(CO2),GHG=sum(GHG),CO2pc=mean(CO2pc),GDP=sum(gdp_ppp_WB,na.rm=T),GDPpc=mean(GDPpc,na.rm=T))
# 
# 
# summary_table <- summary_table %>% 
#   mutate(Population=pop/world$pop_UN*100) %>% 
#   mutate(`CO2 Emissions`=CO2/world$CO2*100) %>% 
#   mutate(`GHG Emissions`=GHG/world$GHG*100) %>% 
#   mutate(`GDP (ppp)`=GDP/world$gdp_ppp_WB*100) %>% 
#   arrange(CO2pc)
# 
# summary_table <- cbind(summary_table,data.frame(rank=c(1:6))) %>% 
#   mutate(rank=factor(rank))
# 
# emissions_data <- left_join(emissions_data,summary_table %>% select(cluster,rank),by=c("cluster"="cluster"))
# 
# emissions_data <- emissions_data %>% 
#   select(-cluster,cluster=rank)
# 
# summary_table <- summary_table %>% 
#   select(-cluster,cluster=rank)
# 
# p1 <- emissions_data %>% ggplot(.,aes(x=year,y=var,color=cluster,group=ISO)) +
#   geom_line() +
#   scale_y_continuous(trans = "log",breaks = c(0,1,5,10,20,40,80)) +
#   #geom_text(data=summary_table)
#   facet_grid(.~cluster,scales="free") +
#   scale_x_continuous(breaks=c(1980,2010)) +
#   ylab("CO2 emissions (log tCO2/year)") +
#   theme(legend.position="none",
#         axis.title.x = element_blank(),
#         panel.grid.minor.y = element_blank(),
#         plot.title = element_text(size = 11)) +
#   ggtitle("a. Historical carbon emissions pathways grouped by trends and levels")
# p1
# 
# xlsx::write.xlsx(summary_table,"../../Results/Data/sdg_clusters.xlsx")
# 

```

```{r clusters_descriptive, echo=FALSE,warning=FALSE,results='asis',fig.width=8,fig.height=2,fig.path="../../Results/Plots/sdgs/",dev=c('png','pdf')}
# 
# 
# plot_data <- gather(summary_table,key,value,Population:`GDP (ppp)`)
# plot_data$key <- factor(plot_data$key)
# plot_data$key <- factor(plot_data$key,levels = levels(plot_data$key)[c(3,1,2,4)])
# 
# p2 <- plot_data %>% 
#   ggplot(.,aes(x=key,y=value,fill=cluster)) +
#   geom_bar(stat='identity',color="#737373",width=0.5) +
#   coord_flip() +
#   facet_grid(.~cluster) +
#   scale_y_continuous(breaks = c(0,20,40)) +
#   theme(legend.position = "none",
#         axis.title = element_blank(),
#         strip.background = element_blank(),
#         strip.text.x = element_blank(),
#         plot.title = element_text(size = 11)) +
#   ggtitle("b. Fraction of global population, GDP and emissions by group")
# 
# p2

```

```{r clusters_sdgs, echo=FALSE,warning=FALSE,results='asis',fig.width=8,fig.height=4,fig.path="../../Results/Plots/sdgs/",dev=c('png','pdf')}

# 
# yy <- left_join(emissions_data,table %>%                     select(-country,-Population),by=c("ISO"="iso","year"="year"))









# yy <- gather(yy,sdg,value,Education:Sanitation) %>% 
#   filter(year==2000 | year==2015) %>% 
#   mutate(year=as.factor(year))
# 
# yy <- left_join(yy,labels,by = c("sdg"="sdg"))
# 
# yy$year <- factor(yy$year,levels(yy$year)[c(2,1)])
# 
# p3 <- ggplot(yy,aes(x=label,y=value,fill=cluster,color=year)) +
#   geom_boxplot(position = position_dodge(0.65),width=0.5) +
#   facet_grid(.~cluster) +
#   coord_flip() +
#   scale_y_continuous(breaks = c(0,50,100),limits=c(0,100)) +
#   scale_colour_manual(values=c("#737373","#737373")) +
#   theme(legend.position="none",
#         axis.title = element_blank(),
#         strip.background = element_blank(),
#         strip.text.x = element_blank(),
#         plot.title = element_text(size = 11)) +
#   ggtitle("c. Key SDG indicators by group, 2000 and 2015 (higher vs. lower boxplots)")
# p3

```


```{r combined_sdg_plots, echo=FALSE,warning=FALSE,results='asis',fig.width=8,fig.height=8,fig.path="../../Results/Plots/sdgs/",dev=c('png','pdf')}




# 
# ggarrange(p1,p2,p3,nrow=3,ncol=1,align="v",heights = c(.4,.18,.42))

```

```{r emissions_v_sdgs, echo=FALSE}

# edgar_countries <- gather(edgar_countries,sdg,value,Education:Sanitation)
# 
# edgar_countries %>% 
#   filter(year==2018) %>% 
#   ggplot(.,aes(x=CO2/Population,y=value,fill=sdg)) +
#   geom_point() +
#   facet_wrap(~sdg)


```

```{r plots, echo=FALSE}



# edgar_countries %>% 
#   filter(!is.na(group)) %>% 
#   filter(year>2000) %>% 
#   ggplot(.,aes(x=year,y=CO2/Population,color=group)) +
#   geom_point() +
#   facet_grid(~group)


# 
# p1 <- edgar_countries %>% 
#   filter(defmoving==1) %>%  
#   ggplot(.,aes(x=year,y=CO2/Population,color=group,label=ISO)) +
#   geom_point() +
#   #geom_text() +
#   facet_grid(~group) +
#   theme(legend.position="none",
#         axis.title.x = element_blank())
# 
# p2 <- edgar_countries %>% 
#   filter(defmoving==0) %>%  
#   ggplot(.,aes(x=year,y=CO2/Population,color=group,label=ISO)) +
#   geom_point() +
#   #geom_text() +
#   facet_grid(~group) +
#   theme(legend.position="none",
#         axis.title.x = element_blank())
# 
# 
# p <- ggarrange(p1,p2,nrow=2)
# p
# 

```


```{r sdgs,echo=FALSE,warning=FALSE,results='asis',fig.width=10,fig.height=5,fig.path="../Results/Plots/",dev=c('png','pdf')}

# time_start=2000
# 
# growth <- edgar_countries %>% 
#   group_by(country) %>% 
#   mutate(rate=(last(CO2)/first(CO2))^(1/(last(year)-time_start+1))-1) %>% 
#   ungroup() %>% 
#   mutate(rate=rate*100)
# 
# growth <- growth %>% 
#   group_by(country) %>% 
#   mutate(trend_group = NA) %>% 
#   mutate(trend_group=ifelse(rate<0,"negative",trend_group)) %>% 
#   mutate(trend_group=ifelse(rate>0,"positive",trend_group)) %>% 
#   ungroup() %>% 
#   mutate(trend_group = as.factor(trend_group)) +
#   ggtitle("Emissions and pathways of countries achieving up to 6 SDGs")
# 
# growth %>% 
#   ggplot(.,aes(x=year,y=CO2/Population,color=group,label=ISO)) +
#   geom_point() +
#   facet_grid(trend_group~group) +
#   theme(legend.position="none",
#         axis.title.x = element_blank())
# 
# 
# growth <- growth %>% 
#   mutate(SDG=paste0(group," SDGs"))
# 
# growth %>% 
#   ggplot(.,aes(x=year,y=GHG/Population*1000,color=SDG,label=ISO,group=ISO)) +
#   geom_point() +
#   geom_line() +
#   facet_grid(.~SDG) +
#   ylab("GHG Emissions (tCO2eq/capita)") +
#   theme(legend.position="none",
#         axis.title.x = element_blank()) +
#   ggtitle("Emissions and pathways of countries achieving up to 6 SDGs")
# 
# 




```

```{r qwertz,echo=FALSE,warning=FALSE,results='asis',fig.width=10,fig.height=5,fig.path="../Results/Plots/",dev=c('png','pdf')}
# 
# blarg <- edgar_countries %>% 
#   mutate(group=as.numeric(group)) %>% 
#   mutate(sdg_group=ifelse(group<=3,"0-2 SDGs",NA)) %>% 
#   mutate(sdg_group=ifelse(group>2 & group<5,"3-4 SDGs",sdg_group)) %>% 
#   mutate(sdg_group=ifelse(group>4,"5-6 SDGs",sdg_group))
#   
# blarg <- blarg %>% 
#   group_by(country) %>% 
#   mutate(rate=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
#   mutate(rate_direction =ifelse(rate<0,"Negative growth",NA)) %>% 
#   mutate(rate_direction =ifelse(rate>0,"Positive growth",rate_direction))
# 
# blarg %>% ggplot(.,aes(year,GHG/Population,group=ISO)) +
#   geom_point() +
#   geom_line() +
#   facet_grid(rate_direction~sdg_group)



```





```{r table,echo=FALSE,warning=FALSE}

# 
# finaltable <- left_join(table,edgar_countries %>% ungroup() %>%  select(ISO,region_ar6_5,year,GHG),by=c("iso"="ISO","year"="year")) %>% 
#   distinct()
# 
# finaltable <- finaltable %>% 
#   filter(year==2017) %>% 
#   select(iso,country,region_ar6_5,year,GHG,everything(),SDGs=group)
# 
# openxlsx::write.xlsx(finaltable,file="../Results/ipcc_ar6_sdg_table")

```