---
title: "sector_summary"
author: "William F. Lamb"
output: word_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../Results") })
---

# Setup
```{r setup, include=FALSE,echo=FALSE,warning=FALSE}

## notes
# these figures have multiple components
# 1. overall global trend by subsector
# 2. per capita levels by region
# 3. kaya trends by region
#
# For #1 we use the most comprehensive data (direct/indirect CO2, LULUCF CO2)
# For #2 we use slightly less comprehensive data: direct/indirect CO2 for countries, which does not sum to world - some emissions are missing in the IEA data; also regional LULUCF CO2 data forces us to only show per capita regional values
# For #3 we use only CO2 from IEA, without direct/indirect CO2, GHGs and LULUCF CO2

rm(list = ls())
library(tidyverse)
library(ggplot2); theme_set(theme_bw())
library(patchwork)
library(RColorBrewer)
library(ggrepel)


source("small_figures.R")

end_year = 2019

load('../../Data/edgar6_v5_data_ghg_gwp_ar6.RData')
load('../../Data/gwps.RData')
load('../../Data/indirect_CO2.RData')
load('../../Data/land.RData')
load('../../Data/ipcc_regions.RData')
load('../../Data/WDI_gdp_pop.RData')
load('../../Data/kaya.RData')

options(dplyr.summarise.inform = FALSE)

kaya_data <- kaya_data %>% 
  mutate(region_ar6_10=as.character(region_ar6_10)) %>% 
  mutate(region_ar6_10=ifelse(region_ar6_10=="South-East Asia and Developing Pacific","South-East Asia and developing Pacific",region_ar6_10)) %>% 
  mutate(region_ar6_10=as.factor(region_ar6_10))


## simplify datasets

data <- edgar_ghg %>% 
  group_by(ISO,country,region_ar6_10,region_ar6_10_short,year,chapter_title,subsector_title) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE))

# land CO2 data

land <- land %>%
  filter(year>1969) %>% 
  filter(year<=end_year) %>% 
  mutate(chapter_title="AFOLU") %>% 
  select(region_ar6_10,region_ar6_10_short,year,chapter_title,CO2_land=mean)

# population data

pop <- left_join(ipcc_regions %>% select(ISO,region_ar6_10,region_ar6_10_short),wdi_data_gdp_pop %>% select(ISO=iso3c,year,population), by = "ISO")

data <- left_join(data,pop,by = c("region_ar6_10", "region_ar6_10_short", "year","ISO"))

# indirect CO2 data (save for later...)

indirect_CO2_countries <- indirect_CO2_countries %>% 
  group_by(ISO,country,region_ar6_10,year,chapter_title,subsector_title) %>% 
  summarise(CO2_indirect=sum(CO2_indirect,na.rm=TRUE)*1e9)


# blarg <- edgar_ghg %>% 
#   filter(year==2019) %>% 
#   group_by(region_ar6_10_short,year) %>% 
#   summarise(GHG=sum(GHG,na.rm=TRUE))
# blarg <- left_join(blarg,land)
# blarg <- blarg %>% 
#   mutate(GHG_total=GHG+CO2_land) %>% 
#   mutate(GHG_total=ifelse(region_ar6_10_short=="AIR",GHG,GHG_total)) %>%
#   mutate(GHG_total=ifelse(region_ar6_10_short=="SEA",GHG,GHG_total)) 
# 
# blarg <- blarg %>% 
#   mutate(world_total=sum(blarg$GHG_total)) %>% 
#   mutate(fraction=(GHG_total/world_total)*100)
# 
# blarg <- left_join(blarg,pop_regions)
# blarg <- blarg %>% 
#   mutate(per_capita=GHG_total/population)

```

# Data preparation

## Growth rate calculation

```{r growth_rate,echo=FALSE,warning=FALSE}

growth_rates <- function(data) {
  
  # leap year adjustment
  # rates <- data %>%
  #   mutate(leap_years = leap_year(year)) %>% 
  #   mutate(value = ifelse(leap_years==TRUE,value*365/366,value)) %>% 
  #   select(-leap_years)
  
  rates <- data %>% 
    filter(year %in% c(1990,1999,2000,2009,2010,end_year)) %>% 
    mutate(total_rate=NA)
  
  rates$total_rate[rates$year==1990] = ((rates$value[rates$year==1999]/rates$value[rates$year==1990])^(1/(1999-1990))-1)*100
  
  rates$total_rate[rates$year==2000] = ((rates$value[rates$year==2009]/rates$value[rates$year==2000])^(1/(2009-2000))-1)*100
  
  rates$total_rate[rates$year==2010] = ((rates$value[rates$year==end_year]/rates$value[rates$year==2010])^(1/(end_year-2010))-1)*100
  
  
  return(rates)
             
}



```

## Total sector & subsector trend

```{r sector_ghg_total,echo=FALSE,warning=FALSE}

### here we calculate the total trend by sector and subsector (no regions)

sector_ghg_total <- data %>% 
  group_by(chapter_title,subsector_title,year) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE)/1e9)

# for AFOLU, we add LULUCF CO2 as a subsector

sector_ghg_total_land <- land %>% 
  group_by(chapter_title,year) %>% 
  summarise(GHG=sum(CO2_land,na.rm=TRUE)/1e9) %>% 
  mutate(subsector_title="LULUCF (CO2)")

sector_ghg_total <- rbind(sector_ghg_total,sector_ghg_total_land)
sector_ghg_total <- sector_ghg_total %>% arrange(chapter_title,subsector_title,year)
rm(sector_ghg_total_land)

# for transport, buildings, industry we add CO2 indirect as subsectors

indirect_CO2_world <- gather(indirect_CO2_world,year,GHG,`1990`:`2019`)
indirect_CO2_world <- indirect_CO2_world %>% 
  group_by(chapter_title,subsector_title,year) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE))

# keep building subsectors but merge the rest
indirect_CO2_world <- indirect_CO2_world %>% 
  mutate(subsector_title=ifelse(chapter_title=="Buildings",subsector_title,"Indirect CO2")) %>% 
  mutate(subsector_title=ifelse(chapter_title=="Buildings",paste0(subsector_title," (indirect CO2)"),subsector_title))

indirect_CO2_world <- indirect_CO2_world %>% 
  group_by(chapter_title,subsector_title,year) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE)) %>% 
  mutate(year=as.numeric(year))

sector_ghg_total <- rbind(sector_ghg_total,indirect_CO2_world)

```

## % of sector emissions in each region
```{r sector_ghgs_regions,echo=FALSE,warning=FALSE}

#### here we calculate the proportion of emissions in each region relative to the global sector total
## Note that the sums of each sector here are slightly different to the previous chunk, because the IEA indirect CO2 data for regions and countries does not add up to the IEA world CO2 indirect value.

sector_ghgs_regions <- data %>% 
  #filter(region_ar6_10_short!="AIR") %>% 
  #filter(region_ar6_10_short!="SEA") %>% 
  filter(year %in% c(2010,2019)) %>% 
  group_by(region_ar6_10,region_ar6_10_short,chapter_title,year) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE)/1e9)


# add land use (LULUCF) for AFOLU
sector_ghgs_regions <- left_join(sector_ghgs_regions,land,by = c("region_ar6_10", "region_ar6_10_short", "chapter_title", "year")) %>% 
  mutate(CO2_land = CO2_land/1e9)

# add indirect emissions for industry, buildings, transport

indirect_CO2_regions <- indirect_CO2_regions %>% 
  group_by(region_ar6_10,region_ar6_10_short,chapter_title,year) %>% 
  summarise(CO2_indirect = sum(CO2_indirect,na.rm=TRUE)) %>% 
  filter(year %in% c(2010,2019)) %>% 
  filter(chapter_title!="Energy systems")

sector_ghgs_regions <- left_join(sector_ghgs_regions,indirect_CO2_regions,by = c("region_ar6_10", "region_ar6_10_short", "chapter_title", "year"))

sector_ghgs_regions <- sector_ghgs_regions %>% 
  group_by(region_ar6_10,region_ar6_10_short,chapter_title,year) %>% 
  mutate(GHG_total = sum(GHG,CO2_land,CO2_indirect,na.rm=TRUE))

# calculate the total emissions by each sector, to estimate the regional fraction

sector_ghg_totals <- sector_ghgs_regions %>% 
  group_by(chapter_title,year) %>% 
  summarise(sector_GHG_total=sum(GHG_total,na.rm=TRUE))

# join and calculate the region fraction of each sector total

sector_ghgs_regions <- left_join(sector_ghgs_regions,sector_ghg_totals, by = c("chapter_title", "year"))
sector_ghgs_regions <- sector_ghgs_regions %>% 
  mutate(region_fraction_of_sector=(GHG_total/sector_GHG_total)*100)
rm(sector_ghg_totals)

# calculate growth rate since 2010

sector_ghgs_regions <- sector_ghgs_regions %>% 
  group_by(region_ar6_10,chapter_title) %>% 
  mutate(rate=(last(GHG_total)/first(GHG_total))^(1/(last(year)-first(year)))-1) %>% 
  mutate(rate=rate*100)

sector_ghgs_regions <- sector_ghgs_regions %>% filter(year==2019)

## add population to calculate regional average per capita emissions

pop_regions <- pop %>% 
  group_by(region_ar6_10,year) %>% 
  summarise(population=sum(population,na.rm=TRUE))

sector_ghgs_regions <- left_join(sector_ghgs_regions,pop_regions,by = c("region_ar6_10", "year"))
sector_ghgs_regions <- sector_ghgs_regions %>% 
  mutate(region_per_capita = (GHG_total*1e9)/population)


```

## Per capita sector emissions by region
```{r sector_emissions_per_capita,echo=FALSE,warning=FALSE}

per_capita <- left_join(data,indirect_CO2_countries,by = c("ISO", "country", "region_ar6_10","year", "chapter_title", "subsector_title"))

### get average world values for each sector
# add indirect CO2 to the sector if its not Energy systems
# for AFOLU, we will use the region per capita data calculated in the last chunk

pop_world <- wdi_data_gdp_pop %>% 
  filter(year==2019) %>% 
  filter(iso3c=="WLD")

per_capita_world <- sector_ghgs_regions %>% 
  ungroup() %>% 
  select(chapter_title,sector_GHG_total) %>%
  distinct()

per_capita_world <- per_capita_world %>% 
  mutate(population=pop_world$population) %>% 
  mutate(GHG_total_pc=(sector_GHG_total*1e9)/population) %>% 
  mutate(label="World average")

per_capita <- per_capita %>% 
  filter(region_ar6_10_short!="AIR") %>% 
  filter(region_ar6_10_short!="SEA") %>% 
  filter(year %in% c(2019)) %>% 
  group_by(ISO,country,region_ar6_10,region_ar6_10_short,chapter_title,year) %>% 
  summarise(GHG=sum(GHG),population=nth(population,1),CO2_indirect=sum(CO2_indirect,na.rm=TRUE)) %>% 
  mutate(GHG_total=ifelse(chapter_title!="Energy systems",GHG+CO2_indirect,GHG)) %>% 
  mutate(GHG_pc=GHG_total/population) %>% 
  mutate(year=as.factor(year))

```

## Kaya analysis
```{r kaya_rates,echo=FALSE,warning=FALSE}

kaya_rates <- gather(kaya_data %>% select(-GDP),var,value,CO2,energy,energy_GDP,CO2_energy,GDP_POP,POP) %>%   filter(sector!="AFOLU") %>% 
  #filter(region_ar6_10!="World") %>% 
  filter(year %in% c(2010,2019)) %>% 
  select(chapter_title=sector,everything())

kaya_rates <- kaya_rates %>% 
  group_by(region_ar6_10,chapter_title,var) %>%
  mutate(rate=(last(value)/first(value))^(1/(last(year)-first(year)))-1) %>% 
  mutate(rate=rate*100) %>% 
  filter(year==2019) %>% 
  ungroup() %>% 
  select(-value,-year)

# join ghg data
# 
# ghg_rates <- sector_ghgs_regions %>% 
#   ungroup() %>% 
#   filter(year==2019) %>% 
#   filter(chapter_title!="AFOLU") %>% 
#   select(region_ar6_10,chapter_title,rate) %>% 
#   mutate(var="GHG") %>% 
#   filter(region_ar6_10!="Intl. Aviation") %>% 
#   filter(region_ar6_10!="Intl. Shipping")
# 
# kaya_rates <- rbind(kaya_rates,ghg_rates)


# set colour thresholds
kaya_rates <- kaya_rates %>% 
  mutate(rate_colour = ifelse(rate>0 & abs(rate)>1,"Growing (> +1%/yr)","Stable (~0%/yr)")) %>% 
  mutate(rate_colour = ifelse(rate<0 & abs(rate)>1,"Declining (< -1%/yr)",rate_colour))

kaya_rates$rate_colour <- as.factor(kaya_rates$rate_colour)
kaya_rates$rate_colour <- factor(kaya_rates$rate_colour,levels=levels(kaya_rates$rate_colour)[c(2,3,1)])

# facet titles
titles <- data.frame(var=c("CO2","energy","energy_GDP","CO2_energy","GDP_POP","POP"),facet=c("CO2","Energy cons.","Energy intensity","Carbon intensity","GDP/ pop","Pop"))

kaya_rates <- left_join(kaya_rates,titles,by = "var")

# reorder vars
kaya_rates$facet <- as.factor(kaya_rates$facet)
kaya_rates$facet <- factor(kaya_rates$facet,levels=levels(kaya_rates$facet)[c(2,1,4,3,5,6)])


kaya_rates <- left_join(kaya_rates,ipcc_regions %>% select(region_ar6_10,region_ar6_10_short) %>% distinct(),by = "region_ar6_10")
kaya_rates <- kaya_rates %>% 
  mutate(region_ar6_10_short=ifelse(region_ar6_10=="World","World",region_ar6_10_short))

```

## Kaya analysis AFOLU
```{r kaya_rates_afolu,echo=FALSE,warning=FALSE}


hong_a <- openxlsx::read.xlsx('../../Data/Kaya/LUE_Data_2019_CH.xlsx',sheet='8.1.AgProd')
names(hong_a) <- c("country",1961:2019)
hong_a <- gather(hong_a,year,ag_production_kcal,`1961`:`2019`)

hong_b <- openxlsx::read.xlsx('../../Data/Kaya/LUE_Data_2019_CH.xlsx',sheet='9.1.AgLand')
names(hong_b) <- c("country",1961:2019)
hong_b <- gather(hong_b,year,land_area_hectares,`1961`:`2019`)

hong <- left_join(hong_a,hong_b,by = c("year", "country"))
codes <- openxlsx::read.xlsx('C:/Users/lamw/Documents/SpiderOak Hive/Work/Code/R/.Place names and codes/output/ISOcodes.xlsx',sheet = 'alternative_names')

hong <- left_join(hong %>% mutate(country=tolower(country)),codes,by=c("country"="alternative.name"))

hong <- hong %>% 
  mutate(alpha.3=ifelse(grepl("china- taiwan province of",country),"TWN",alpha.3)) %>% 
  mutate(alpha.3=ifelse(grepl("china- hong kong sar",country),"HKG",alpha.3)) %>% 
  mutate(alpha.3=ifelse(grepl("china- macao sar",country),"MAC",alpha.3)) %>% 
  mutate(alpha.3=ifelse(grepl("china- mainland",country),"CHN",alpha.3)) %>% 
  mutate(alpha.3=ifelse(grepl("saint helena- ascension and tristan da cunha",country),"SHN",alpha.3)) %>%
  ungroup() %>% 
  mutate(year=as.numeric(year)) %>% 
  filter(year>=1970)

afolu_GHG <- edgar_ghg %>% 
  filter(chapter_title=="AFOLU") %>% 
  group_by(ISO,year,region_ar6_10) %>% 
  summarise(GHG=sum(GHG,na.rm = TRUE))

hong <- left_join(hong,afolu_GHG,by=c("alpha.3"="ISO","year"="year"))

blarg <- anti_join(afolu_GHG,hong,by=c("ISO"="alpha.3","year"))

hong <- hong %>% 
  filter(year>1989) %>% 
  filter(!is.na(region_ar6_10)) %>% 
  select(ISO=alpha.3,country,region_ar6_10,year,everything())

hong <- left_join(hong,wdi_data_gdp_pop %>% select(ISO=iso3c,year,population),by=c("ISO","year"))

kaya_rates_afolu <- hong %>% 
  filter(year %in% c(2010,2019)) %>% 
  mutate(chapter_title="AFOLU") %>% 
  group_by(region_ar6_10,chapter_title,year) %>% 
  summarise(ag_production_kcal=sum(ag_production_kcal,na.rm=TRUE),
            land_area_hectares=sum(land_area_hectares,na.rm=TRUE),
            GHG=sum(GHG,na.rm=TRUE),
            population=sum(population,na.rm=TRUE))



#kaya_rates_afolu <- left_join(kaya_rates_afolu,land,by = c("region_ar6_10", "chapter_title", "year"))
#kaya_rates_afolu <- kaya_rates_afolu %>% 
#  mutate(GHG_total=GHG+CO2_land)

kaya_rates_afolu <- kaya_rates_afolu %>% 
  mutate(GHG_total=GHG)



# calculate kaya values
kaya_rates_afolu <- kaya_rates_afolu %>% 
  mutate(production_percap=ag_production_kcal/population) %>% 
  mutate(land_production=land_area_hectares/ag_production_kcal) %>% 
  mutate(ghg_land_area=GHG_total/land_area_hectares)

kaya_rates_afolu <- gather(kaya_rates_afolu %>% select(-ag_production_kcal,-land_area_hectares,-GHG),
                           var,value,population:ghg_land_area)


kaya_rates_afolu <- kaya_rates_afolu %>% 
  group_by(region_ar6_10,chapter_title,var) %>%
  mutate(rate=(last(value)/first(value))^(1/(last(year)-first(year)))-1) %>% 
  mutate(rate=rate*100) %>% 
  filter(year==2019) %>% 
  ungroup() %>% 
  select(-value,-year)


# set colour thresholds
kaya_rates_afolu <- kaya_rates_afolu %>% 
  mutate(rate_colour = ifelse(rate>0 & abs(rate)>1,"Growing (> +1%/yr)","Stable (~0%/yr)")) %>% 
  mutate(rate_colour = ifelse(rate<0 & abs(rate)>1,"Declining (< -1%/yr)",rate_colour))

kaya_rates_afolu$rate_colour <- as.factor(kaya_rates_afolu$rate_colour)
kaya_rates_afolu$rate_colour <- factor(kaya_rates_afolu$rate_colour,levels=levels(kaya_rates_afolu$rate_colour)[c(2,3,1)])

# facet titles
titles <- data.frame(var=c("population","GHG_total","production_percap","land_production","ghg_land_area"),facet=c("Population","GHG","Agricultural output","Land efficiency","GHG intensity"))

kaya_rates_afolu <- left_join(kaya_rates_afolu,titles,by = "var")

# reorder vars
kaya_rates_afolu$facet <- as.factor(kaya_rates_afolu$facet)
kaya_rates_afolu$facet <- factor(kaya_rates_afolu$facet,levels=levels(kaya_rates_afolu$facet)[c(2,3,4,1,5)])


# add short regions
kaya_rates_afolu <- left_join(kaya_rates_afolu,ipcc_regions %>% select(region_ar6_10,region_ar6_10_short) %>% distinct(),by = "region_ar6_10")

```

# Figures
## Trend figure

```{r trend_figure,echo=FALSE,warning=FALSE}

trend_figure <- function(trend_data,sector) {
  
  trend_data <- trend_data %>% 
    mutate(value=GHG) %>% 
    filter(year<=end_year)
  
  ## align labels
  labels <- trend_data %>%
    filter(year==end_year) %>% 
    arrange(desc(subsector_title))
  
  labels <- labels %>% 
    mutate(fractions=(value/sum(labels$value))*100)
  
  labels$cum <- cumsum(labels$value)
  
  for (j in 1:length(labels$year)) {
    labels$location[j] = labels$value[j]*0.5
  }
  for (j in 2:length(labels$year)) {
    labels$location[j] = labels$location[j] + labels$cum[j-1]
  }
  
  ## calculate shares
  shares <- trend_data %>%
    filter(year %in% c(1990,2000,2010,end_year)) %>%
    group_by(year) %>%
    mutate(totals=sum(value)) %>%
    ungroup() %>%
    group_by(year,subsector_title) %>%
    mutate(fractions=(value/totals)*100) %>%
    ungroup()
  
  shares <- locate_shares(shares,"subsector_title",4)
  
  # # calculate overall growth between years (time 1 time 2)
  growth_data <- trend_data %>%
    group_by(year) %>%
    summarise(value=sum(value))
  
  growth_data <- growth_rates(growth_data)
  
  
  shares <- left_join(shares,growth_data %>% select(-value) %>% filter(year %in% c(1990,2000,2010)),by="year")
  
  colours <- c("#66c2a5","#fc8d62","#8da0cb","#e78ac3","#a6d854","#ffd92f","#e5c494")
  if (shares$chapter_title[1]=="Buildings") {
    colours <- c("#bdbdbd","#969696","#fc8d62","#8da0cb","#e78ac3","#a6d854","#ffd92f","#e5c494")
  }
  if (shares$chapter_title[1]=="Industry" | shares$chapter_title[1]=="Transport") {
    colours <- c("#bdbdbd","#66c2a5","#fc8d62","#8da0cb","#e78ac3","#a6d854","#ffd92f","#e5c494")
  }
  
  title = paste0("a. ",shares$chapter_title[1], " global GHG emission trends by subsectors")
  if (sector=="Total") {
    
    title = paste0("a. Total global GHG emission trends by sectors")
    
  }
  
  
  
  p <- trend_data %>%
    ggplot(.,aes(x=year,y=value,fill=subsector_title)) +
    geom_area(color='#737373') +
    
    geom_vline(xintercept=c(1990,2000,2010,end_year),alpha=0.3,linetype="dashed") +
    
    geom_text(data=shares %>% filter(subsector_title==shares$subsector_title[1]),aes(x=year,y=1.09*max(shares$totals),label=paste(signif(totals,2),  "Gt")),size=4,colour="#252525") +
    
    #geom_text(data=labels,aes(x=year+0.5,y=location,label=paste0(ifelse(rate>0,"+","-"),round(abs(rate),1),"%")),hjust=0,size=3.5,colour="#252525") +
    
    geom_text_repel(inherit.aes =FALSE,data=labels,
                    aes(x=year+0.5,
                        y=location,
                        label=paste0(round(fractions,0),"%"),
                        color=subsector_title),
                    direction    = "y",
                    hjust        = 0,
                    segment.colour = NA,
                    size=4,
                    show.legend = FALSE) +
    
    # geom_text(data=labels,aes(x=year+0.5,y=location,label=paste0(round(fractions,0),"%")),hjust=0,size=3.5,colour="#252525") +
    
    geom_text(data=shares %>% filter(subsector_title==shares$subsector_title[1]) %>% filter(year<=end_year),aes(x=ifelse(year==2010,year+4,year+5),y=1.072*max(shares$totals),label=paste0(ifelse(total_rate>0,"+","-"),round(abs(total_rate),1),"%")),size=4,colour="#252525") +
    
    scale_x_continuous(breaks=c(1990,2000,2010,end_year),limits = c(1990,end_year+2)) +
    scale_y_continuous() +
    expand_limits(y=c(0,max(shares$totals)*1.12)) +
    #scale_fill_brewer(type = "qual",palette="Set2") +
    scale_fill_manual(values=colours) +
    scale_color_manual(values=colours) +
    
    big_trend_theme +
    ggtitle(title) +
    theme(legend.position="right",
          axis.title.x = element_blank(),
          legend.title=element_blank(),
          legend.text = element_text(size=10),
          axis.text = element_text(size=11),
          legend.spacing.x= unit(0.25, 'cm')) +
    ylab(bquote("GHG Emissions (Gt" ~CO[2]* "eq/yr)"))
  
  
  return(p)
  
}

```

## Fraction figure

```{r fraction_figure,echo=FALSE,warning=FALSE}
sector="Energy systems"
fraction_figure <- function(sector_ghgs_regions,sector) {
  
  colors = colorRampPalette(brewer.pal(8, "Set2"))(10)
  colors = c(colors,"#f8766dff")
  
  fraction_data <- sector_ghgs_regions %>% 
    filter(chapter_title==sector) %>% 
    filter(region_ar6_10_short!="AIR") %>% 
    filter(region_ar6_10_short!="SEA") %>% 
    mutate(facet=paste0("% of tot. sector GHG emissions"))
  
  fraction_data <- rbind(fraction_data,
                         data.frame(region_ar6_10="World",
                                    region_ar6_10_short="World",
                                    region_fraction_of_sector=NA,
                                    facet="% of tot. sector GHG emissions"))
  
   title <- data.frame(title=ifelse(sector=="AFOLU","Emissions by region in 2019\n(all GHGs, incl. LULUCF CO2)","Emissions by region in 2019\n(all GHGs, incl. Indirect CO2)"))
  title <- title %>% 
    mutate(title=ifelse(sector=="Energy systems","Emissions by region in 2019\n(all GHGs)",title)) %>% 
    mutate(title=ifelse(sector=="Total","Emissions by region in 2019\n(all GHGs, incl. LULUCF CO2, excl. Indirect CO2",title))
  
  
    p <- fraction_data %>% 
    ggplot(aes(x=reorder(region_ar6_10_short,desc(region_ar6_10_short)),
               y=region_fraction_of_sector,fill=region_ar6_10_short)) +
    geom_bar(stat='identity',color="#737373") +
    geom_text(aes(y=region_fraction_of_sector+1.5,label=paste0(round(region_fraction_of_sector,0),"%")),hjust=0,size=3.5) +
    expand_limits(y=c(0,max(sector_ghgs_regions$region_fraction_of_sector)*1.2)) +
    coord_flip() +
    facet_grid(.~facet,labeller = label_wrap_gen(width=20)) +
    scale_fill_manual(values=colors) +
    theme(axis.title.y = element_blank(),
          #axis.text.y = element_blank(),
          #axis.ticks.y = element_blank(),
          axis.title.x = element_blank(),
          #axis.ticks.x = element_blank(),
          #axis.text.x = element_blank(),
          axis.text = element_text(size=11),
          panel.grid.major.x = element_blank(),
          plot.title = element_text(size = 11),
          plot.background = element_blank(),
          legend.position="none") +
    ggtitle(paste0("b. ",title$title))
  
    return(p)
  
}


```


## Per capita figure


```{r per_capita_figure,echo=FALSE,warning=FALSE}

per_capita_figure <- function(per_capita,per_capita_world,sector_ghgs_regions,sector) {
  
  colors = colorRampPalette(brewer.pal(8, "Set2"))(10)
  colors = c(colors,"#f8766dff")
  
  per_capita_data <- per_capita %>% 
    filter(chapter_title==sector) %>% 
    filter(year==2019) %>% 
    mutate(facet="Per capita GHG emissions (tCO2eq/capita)")
  
  per_capita_data <- rbind(per_capita_data,data.frame(ISO="WLD",
                                                      country="World",
                                                      region_ar6_10="World",
                                                      region_ar6_10_short="World",
                                                      GHG_pc=NA,
                                                      facet="Per capita GHG emissions (tCO2eq/capita)"))
  
  # mean by region
  mean = sector_ghgs_regions %>%
    ungroup() %>% 
    filter(region_ar6_10_short!="AIR") %>% 
    filter(region_ar6_10_short!="SEA") %>% 
    filter(chapter_title==sector) %>% 
    select(region_ar6_10_short,chapter_title,GHG_pc=region_per_capita)
  
  mean <- rbind(mean,data.frame(region_ar6_10_short="World",
                                chapter_title=sector,
                                GHG_pc=per_capita_world$GHG_total_pc[per_capita_world$chapter_title==sector]))
  
  
  ## if its the AFOLU sector, we dont actually want to show countries, because of missing LULUCF CO2
  # solution is to hide them behind the regional means
  if (sector=="AFOLU") {
    per_capita_data <- left_join(per_capita_data %>% select(-GHG_pc),mean,by = c("region_ar6_10_short", "chapter_title"))}
  if (sector=="Total") {
    per_capita_data <- left_join(per_capita_data %>% select(-GHG_pc),mean,by = c("region_ar6_10_short", "chapter_title"))}
  
  
  
  p <- per_capita_data %>% 
    ggplot(aes(x=reorder(region_ar6_10_short,desc(region_ar6_10_short)),y=GHG_pc,fill=region_ar6_10_short)) +
    #geom_boxplot(outlier.alpha = 0.5,color="#737373",show.legend=FALSE) +
    geom_point(shape=21,color="#636363",show.legend=FALSE,size=2,alpha=0.5) +
    geom_point(data=mean,color="#636363",shape=23,size=5,show.legend=FALSE) +
    geom_hline(data=per_capita_world %>% filter(chapter_title==sector),
               aes(yintercept=GHG_total_pc,colour=label),alpha=1,linetype="dashed") +
    #stat_summary(data = mean, geom = "crossbar",
    #             width = 0.7,fun="mean",aes(color=region_ar6_10_short),size=0.8) +
    coord_flip() +
    facet_grid(.~facet,labeller = label_wrap_gen(width=25)) +
    #scale_fill_manual(values=alpha(colors,0.5)) +
    scale_fill_manual(values=colors) +
    #scale_color_manual(values="#636363") +
    #scale_size_continuous(range=c(1.5,8)) +
    ylab("GHG emissions per capita (tCO2eq/capita)") +
    theme(legend.position = "bottom",
          legend.title=element_blank(),
          legend.background = element_blank(),
          legend.text = element_text(size=10),
          legend.margin = margin(t = 0, unit='cm'),
          axis.text = element_text(size=11),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          axis.ticks.y = element_blank(),
          axis.text.y = element_blank(),
          plot.background = element_blank(),
          plot.title = element_text(size = 11))
  
  return(p)
}

```

## Kaya figure

```{r kaya_figure,echo=FALSE,warning=FALSE}

kaya_figure <- function(kaya_rates,sector) {
  
  
  kaya_rates <- kaya_rates %>% 
    filter(chapter_title==sector) %>% 
    filter(var!="GHG") %>% 
    mutate(region_ar6_10_short=as.factor(region_ar6_10_short))
  
  
   title <- data.frame(title=ifelse(sector=="AFOLU","c. Avg. annual change in kaya factors 2010-2019\n(GHG excl. LULUCF CO2)","c. Avg. annual change in kaya factors, 2010-2019\n(CO2 only, excl. indirect CO2)"))
  title <- title %>% 
    mutate(title=ifelse(sector=="Energy systems","c. Avg. annual change in kaya factors 2010-2019\n(CO2 only)",title)) %>% 
    mutate(title=ifelse(sector=="Total","c. Avg. annual change in kaya factors 2010-2019\n(CO2 only, excl. LULUCF CO2, excl. indirect CO2)",title))
   
   
  p <- kaya_rates %>% 
    ggplot(aes(x=reorder(region_ar6_10_short,desc(region_ar6_10_short)),y="a",
               label=paste0(ifelse(rate>0,"+","-"),round(abs(rate),1),"%"),colour=rate_colour)) +
    geom_text(size=3.5,key_glyph = draw_key_point) +
    coord_flip() +
    scale_colour_manual(values = c("#d7191c", "#404040", "#2c7bb6")) +
    facet_grid(.~facet,labeller = label_wrap_gen(width=8)) +
    theme(axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
          axis.text = element_text(size=11),
          panel.grid.major.x = element_blank(),
          plot.title = element_text(size = 11),
          legend.position = "bottom",
          legend.title=element_blank(),
          legend.background = element_blank(),
          legend.text = element_text(size=10),
          legend.margin = margin(t = 0, unit='cm')) +
    ggtitle(title)
  
  return(p)
}


```

# Results
## AFOLU

```{r afolu_summary,echo=FALSE,warning=FALSE,dpi=300,fig.width=9,fig.height=8,fig.path="../../Results/Plots/Sectors/",dev=c('png','pdf')}


trend_data <- sector_ghg_total %>%
  filter(chapter_title=="AFOLU")

trend_data$subsector_title <- as.factor(trend_data$subsector_title)
trend_data$subsector_title <- factor(trend_data$subsector_title,levels=levels(trend_data$subsector_title)[c(3,2,4,6,5,7,1)])


p1_afolu <- trend_figure(trend_data,"AFOLU")
p2_afolu <- fraction_figure(sector_ghgs_regions,"AFOLU")
p2_afolu <- p2_afolu + ylim(0,40)
p3_afolu <- per_capita_figure(per_capita,per_capita_world,sector_ghgs_regions,"AFOLU")
p3_afolu <- p3_afolu + ylim(0,6)
p4_afolu <- kaya_figure(kaya_rates_afolu,"AFOLU")

(wrap_elements(p1_afolu) / wrap_elements(p2_afolu + p3_afolu + p4_afolu + plot_layout(widths=c(1,1.4,3)))) + plot_layout(heights=c(1,1.3))


```

## Energy systems

```{r energy_summary,echo=FALSE,warning=FALSE,dpi=300,fig.width=9,fig.height=8,fig.path="../../Results/Plots/Sectors/",dev=c('png','pdf')}


trend_data <- sector_ghg_total %>% 
  filter(chapter_title=="Energy systems") %>% 
  filter(subsector_title!="Indirect CO2")

trend_data$subsector_title <- as.factor(trend_data$subsector_title)
trend_data$subsector_title <- factor(trend_data$subsector_title,levels=levels(trend_data$subsector_title)[c(2,3,4,1,5)])

p1_energy <- trend_figure(trend_data,"Energy systems")
p2_energy <- fraction_figure(sector_ghgs_regions,"Energy systems")
p3_energy <- per_capita_figure(per_capita,per_capita_world,sector_ghgs_regions,"Energy systems")
p3_energy <- p3_energy + ylim(0,25)
p4_energy <- kaya_figure(kaya_rates,"Energy systems")

(wrap_elements(p1_energy) / wrap_elements(p2_energy + p3_energy + p4_energy + plot_layout(widths=c(1,1.4,3)))) + plot_layout(heights=c(1,1.3))

```

## Industry

```{r industry_summary,echo=FALSE,warning=FALSE,dpi=300,fig.width=9,fig.height=8,fig.path="../../Results/Plots/Sectors/",dev=c('png','pdf')}



trend_data <- sector_ghg_total %>% 
  filter(chapter_title=="Industry")

trend_data$subsector_title <- as.factor(trend_data$subsector_title)
trend_data$subsector_title <- factor(trend_data$subsector_title,levels=levels(trend_data$subsector_title)[c(3,5,4,2,6,1)])

p1_industry <- trend_figure(trend_data,"Industry")
p2_industry <- fraction_figure(sector_ghgs_regions,"Industry")
p2_industry <- p2_industry + ylim(0,60)
p3_industry <- per_capita_figure(per_capita,per_capita_world,sector_ghgs_regions,"Industry")
p4_industry <- kaya_figure(kaya_rates,"Industry")

(wrap_elements(p1_industry) / wrap_elements(p2_industry + p3_industry + p4_industry + plot_layout(widths=c(1,1.4,3)))) + plot_layout(heights=c(1,1.3))


```

## Buildings

```{r buildings_summary,echo=FALSE,warning=FALSE,dpi=300,fig.width=9,fig.height=8,fig.path="../../Results/Plots/Sectors/",dev=c('png','pdf')}

trend_data <- sector_ghg_total %>% 
  filter(chapter_title=="Buildings")

trend_data$subsector_title <- as.factor(trend_data$subsector_title)
trend_data$subsector_title <- factor(trend_data$subsector_title,levels=levels(trend_data$subsector_title)[c(5,3,4,2,1)])

p1_buildings <- trend_figure(trend_data,"Buildings")
p2_buildings <- fraction_figure(sector_ghgs_regions,"Buildings")
p2_buildings <- p2_buildings + ylim(0,40)
p3_buildings <- per_capita_figure(per_capita,per_capita_world,sector_ghgs_regions,"Buildings")
p4_buildings <- kaya_figure(kaya_rates,"Buildings")

(wrap_elements(p1_buildings) / wrap_elements(p2_buildings + p3_buildings + p4_buildings + plot_layout(widths=c(1,1.4,3)))) + plot_layout(heights=c(1,1.3))

```

## Transport

```{r transport_summary,echo=FALSE,warning=FALSE,dpi=300,fig.width=9,fig.height=8,fig.path="../../Results/Plots/Sectors/",dev=c('png','pdf')}


trend_data <- sector_ghg_total %>% 
  filter(chapter_title=="Transport")

trend_data$subsector_title <- as.factor(trend_data$subsector_title)
trend_data$subsector_title <- factor(trend_data$subsector_title,levels=levels(trend_data$subsector_title)[c(2,8,5,4,1,6,3,7)])


p1_transport <- trend_figure(trend_data,"Transport")
p2_transport <- fraction_figure(sector_ghgs_regions,"Transport")
p2_transport <- p2_transport + ylim(0,40)
p3_transport <- per_capita_figure(per_capita,per_capita_world,sector_ghgs_regions,"Transport")
p3_transport <- p3_transport + ylim(0,7.5)
p4_transport <- kaya_figure(kaya_rates,"Transport")

(wrap_elements(p1_transport) / wrap_elements(p2_transport + p3_transport + p4_transport + plot_layout(widths=c(1,1.4,3)))) + plot_layout(heights=c(1,1.3))


```

## Total

```{r total_summary,echo=FALSE,warning=FALSE,dpi=300,fig.width=9,fig.height=8,fig.path="../../Results/Plots/Sectors/",dev=c('png','pdf')}

# Re-build data for all sectors together
# Remove indirect components
overall_ghg_totals <- sector_ghg_total %>% 
  filter(grepl("Indirect CO2",subsector_title)!=1) %>% 
  filter(grepl("indirect CO2",subsector_title)!=1)

overall_ghg_totals <- overall_ghg_totals %>% 
  group_by(chapter_title,year) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE)) %>% 
  mutate(subsector_title=chapter_title) %>% 
  mutate(chapter_title="Total")

overall_ghg_totals$subsector_title <- as.factor(overall_ghg_totals$subsector_title)
overall_ghg_totals$subsector_title <- factor(overall_ghg_totals$subsector_title,levels=levels(overall_ghg_totals$subsector_title)[c(3,4,1,5,2)])

# Re-build data for the fractions
overall_ghg_regions <- sector_ghgs_regions %>% 
  select(-CO2_indirect) %>% 
  mutate(GHG_total=sum(GHG,CO2_land,na.rm=TRUE))

overall_ghg_regions <- overall_ghg_regions %>% 
  group_by(region_ar6_10,region_ar6_10_short,year) %>% 
  summarise(GHG=sum(GHG,na.rm=TRUE),CO2_land=sum(CO2_land,na.rm=TRUE),GHG_total=sum(GHG_total,na.rm=TRUE),population=first(population))

# calculate overall totals and per capita
per_capita_world <- rbind(per_capita_world,data.frame(
  chapter_title="Total",
  sector_GHG_total=sum(overall_ghg_regions$GHG_total),
  population=per_capita_world$population[1],
  GHG_total_pc=NA,
  label="World average"))

per_capita_world <- per_capita_world %>% 
  mutate(GHG_total_pc = sector_GHG_total*1e9/population)

overall_ghg_regions <- overall_ghg_regions %>% 
  mutate(sector_GHG_total=per_capita_world$sector_GHG_total[per_capita_world$chapter_title=="Total"]) %>% 
  mutate(region_fraction_of_sector=(GHG_total/sector_GHG_total)*100) %>% 
  mutate(region_per_capita = GHG_total*1e9/population) %>% 
  mutate(chapter_title="Total")


p1_total <- trend_figure(overall_ghg_totals,"Total")
p2_total <- fraction_figure(overall_ghg_regions,"Total")
p2_total <- p2_total + ylim(0,40)
p3_total <- per_capita_figure(per_capita %>% mutate(chapter_title="Total"),per_capita_world,overall_ghg_regions,"Total")
#p3 <- p3 + ylim(0,7.5)
p4_total <- kaya_figure(kaya_rates,"Total")

(wrap_elements(p1_total) / wrap_elements(p2_total + p3_total + p4_total + plot_layout(widths=c(1,1.4,3)))) + plot_layout(heights=c(1,1.25))


```


## Combined figure

```{r combined_panel_a,echo=FALSE,warning=FALSE,dpi=300,fig.width=10,fig.height=4.5,fig.path="../../Results/Plots/Sectors/",dev=c('png','pdf')}


p2_total + p3_total + p4_total + plot_layout(widths=c(1,1.4,3))





```