---
title: "International energy and emissions inequality"
author: "William F. Lamb"
output: 
  word_document:
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../Results") })
  
---

```{r setup, include=FALSE}


rm(list = ls())
library(tidyverse)
library(xlsx)

load('../Data/basic.RData')

data <- read.xlsx('../Data/supplemetary data/confidential_yannick_oswald_data.xlsx',sheetName='data') %>% 
  select(vars=country.Code.,everything())

data <- gather(data,country,value,-vars)

data <- data %>% 
  filter(vars!="country ID") %>% 
  filter(vars!="region code") %>% 
  group_by(country) %>% 
  mutate(region=nth(value,1)) %>% 
  mutate(income_category=nth(value,2)) %>% 
  mutate(pop=nth(value,3)) %>% 
  mutate(energy_use=nth(value,4)) %>% 
  select(ISO=country,everything()) %>%
  select(-vars,-value) %>% 
  distinct()

data$ISO <- gsub(".1","",data$ISO)
data$ISO <- gsub(".2","",data$ISO)
data$ISO <- gsub(".3","",data$ISO)
data$ISO <- gsub(".4","",data$ISO)
data$ISO <- gsub(".5","",data$ISO)
data$ISO <- gsub("USA.","USA",data$ISO)
data$income_category <- gsub(" ","",data$income_category)

#data <- data %>% 
 # filter(!income_category %in% c("Q1","Q2","Q3","Q4","Q5"))

data$income_category <- as.factor(data$income_category)
data$energy_use <- as.numeric(data$energy_use)

load('../Data/tsu_codes.RData')

data <- left_join(data,tsu_codes,by = "ISO")


```







```{r income_ranking,echo=FALSE,warning=FALSE,fig.width=8,fig.height=12,fig.path="../Results/Plots/",dev=c('png','pdf')}

load('../Data/basic.RData')
codes <- read.xlsx('C:/Users/lamw/Documents/SpiderOak Hive/Work/Code/R/.Place names and codes/output/ISOcodes.xlsx',sheetName = 'ISO_master')

basic <- basic %>% 
  filter(Year==2016) %>% 
  select(ISO,pop_UN,gdp_ppp_WB)

basic <- left_join(basic,codes %>% select(alpha.3,WB.income),by=c("ISO"="alpha.3"))


basic <- basic %>%
  mutate(gdp_ppp_pc_2016 = gdp_ppp_WB/pop_UN) %>%
  select(ISO,gdp_ppp_pc_2016,WB.income)


## bring in more regional codes


data <- left_join(data,basic,by=c("ISO"="ISO"))
data$WB.income <- factor(data$WB.income,levels(data$WB.income)[c(2,3,4,1)])

data %>% 
  filter(!is.na(WB.income)) %>% 
  ggplot(.,aes(x=reorder(name, desc(gdp_ppp_pc_2016)),y=energy_use,color=income_category)) +
  geom_point(size=2.5) +
  coord_flip() +
  ylim(0,500) +
  theme_bw() +
  facet_grid(WB.income~.,space = 'free',scales = 'free') +
  ylab("Energy use (GJ/cap)") +
  theme(
    axis.title.y = element_blank(),
    legend.position = 'bottom'
  )


openxlsx::write.xlsx(data,'inequality_data.xlsx')


```