---
title: "plot_countries"
author: "William F. Lamb"
date: "1 5 2020"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../Results") })
  
---
```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(gganimate)
library(xlsx)
library(ggplot2); theme_set(theme_bw())

source("small_figures.R")
source("decomp_figure_countries.R")
source("decomp_figure_sectors.R")
source("waterfall_plot.R")


load('../Data/edgar_data_gwp_ar5.RData')
load('../Data/gwps.RData')

# set palette
# ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2")
# ipcc_palette <- c("#737373","#737373","#66c2a5","#fc8d62","#8da0cb","#e78ac3","#a6d854");


uncertainties <- data.frame(gas=c('CO2 FFI','CO2 FOLU','CH4','N2O','Fgas','GHG'),
                            uncertainty=c(0.08,0.5,0.2,0.6,0.2,0.1))

wb <- openxlsx::createWorkbook(title = paste("ipcc_plot_data_",Sys.Date()))


```

```{r countries, echo=FALSE,warning=FALSE,fig.width=6,fig.height=6,fig.path="../Results/Plots/Countries/",dev=c('png','pdf')}

blarg <- "Australia"


gases <- edgar_GHG_ar5 %>% 
  filter(country==blarg) %>% 
  group_by(year) %>%  
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE)

gases <- gather(gases,gas,value,CO2:Fgas)
gases$gas <- as.factor(gases$gas)
gases$gas <-  factor(gases$gas,levels(gases$gas)[c(4,5,1,3,2)])


p1 <- gases %>% ggplot(.,aes(x=year,y=value,fill=gas)) +
  geom_area(colour="#737373") +
  big_trend_theme +
  ylab('GHG Emissions (tCO2eq/yr)') +
  theme(legend.position="right",
        #legend.position = c(0.225,0.85),
        legend.background = element_rect(linetype = 1, size = 0.5, colour = "#525252"),
        legend.margin = margin(l=5,t=5,b=5,r=10,unit="pt"),
        legend.text = element_text(size=8),
        legend.title = element_text(size=8)) +
  ggtitle(blarg)


y <- edgar_GHG_ar5 %>% 
  filter(country==blarg) %>% 
  filter(year==2017) %>% 
  group_by(chapter,chapter_title) %>% 
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE) %>% 
  ungroup()

total <- sum(y$GHG)

y <- y %>% 
  mutate(fraction=GHG/total*100)

sectors <- edgar_GHG_ar5 %>% 
  filter(country==blarg) %>% 
  filter(year==2018) %>% 
  group_by(chapter,chapter_title,sector_code,description) %>% 
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE) %>% 
  ungroup() %>% 
  top_n(20,wt = GHG)

sectors <- gather(sectors,gas,value,CO2:Fgas)
sectors$gas <- as.factor(sectors$gas)
sectors$gas <-  factor(sectors$gas,levels(sectors$gas)[c(4,5,1,3,2)])

p2 <- sectors %>% ggplot(aes(x=reorder(description,value),y=value,fill=gas)) +
  geom_bar(stat='identity') +
  coord_flip() +
  ylab('GHG Emissions in 2018 (tCO2eq)') +
  theme(axis.title.y = element_blank(),
        legend.position="none") +
    annotate(geom = 'text', label = 'Top 20 categories in 2018',
             x = -Inf, y = Inf, hjust = 1.05, vjust = -0.6,size=3.5,color="#737373")

ggarrange(p1,p2,nrow=2,ncol=1)

```








