---
title: "edgar6_check_v6newold"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  word_document:
    toc: yes
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../../Results/knitr/") })
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(openxlsx)
library(patchwork)
library(zoo)

knitr::opts_chunk$set(echo = FALSE,warning=FALSE)
options(dplyr.summarise.inform = FALSE)
theme_set(theme_bw())
ggplot <- function(...) ggplot2::ggplot(...) + scale_fill_brewer(palette="Set2")

#load('../../../Data/edgar5_data_raw.RData')
#edgar_raw_v5 <- edgar_raw #%>% filter(sector_code!="4E")
load('../../../Data/edgar6_v3_data_raw.RData')
edgar_raw_v6_3 <- edgar_raw
load('../../../Data/edgar6_v4_data_raw.RData')
edgar_raw_v6_4 <- edgar_raw %>%
  filter(!is.na(value))
rm(edgar_raw)

#load('../../../Data/edgar5_data_ghg_gwp_ar6.RData')
#edgar_ghg_v5 <- edgar_ghg #%>% filter(sector_code!="4E")
load('../../../Data/edgar6_v3_data_ghg_gwp_ar6.RData')
edgar_ghg_v6_3 <- edgar_ghg
load('../../../Data/edgar6_v4_data_ghg_gwp_ar6.RData')
edgar_ghg_v6_4 <- edgar_ghg
rm(edgar_ghg)



load('../../../Data/WDI_gdp_pop.RData')
edgar_ghg_v6_3 <- left_join(edgar_ghg_v6_3,wdi_data_gdp_pop %>% select(ISO=iso3c,year,population), by = c("ISO", "year"))
edgar_ghg_v6_4 <- left_join(edgar_ghg_v6_4,wdi_data_gdp_pop %>% select(ISO=iso3c,year,population), by = c("ISO", "year"))


```

\newpage
# Global trends and totals
###  CO2, CH4, N2O emissions

```{r global_trend_co2_ch4_n2o,fig.width=8,fig.height=3}

plot_data_v6_3 <- edgar_raw_v6_3 %>%  
  group_by(year,gas) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(version="edgar_v6_3")

plot_data_v6_4 <- edgar_raw_v6_4 %>% 
  group_by(year,gas) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(version="edgar_v6_4")

plot_data <- rbind(plot_data_v6_3,plot_data_v6_4)

plot_data %>% filter(gas %in% c("CO2","CH4","N2O")) %>%  
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path() +
  geom_vline(xintercept=2019,colour="blue",linetype=3) +
  facet_wrap(.~gas,scales="free") +
  ylab("t native units") +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom")


blarg <- spread(plot_data,gas,value)

```

### Fgas emissions

```{r global_trend_fgas,fig.width=10,fig.height=8}

plot_data %>% 
  filter(gas != "CO2") %>%
  filter(gas != "CH4") %>% 
  filter(gas != "N2O") %>% 
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path() +
  facet_wrap(.~gas,scales="free") + 
  ylab("t native units") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom")

```


### All gases (GWPs applied)

```{r global_trend_gases_gwps,fig.width=8,fig.height=3}

plot_data_v6_3 <- edgar_ghg_v6_3 %>% 
  group_by(year) %>% 
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE) %>% 
  mutate(version="edgar_v6_3")

plot_data_v6_4 <- edgar_ghg_v6_4 %>% 
  group_by(year) %>% 
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE) %>% 
  mutate(version="edgar_v6_4")

plot_data <- rbind(plot_data_v6_3,plot_data_v6_4)

totals <- plot_data %>% 
  select(year,GHG,version) %>% 
  filter(year %in% c(1970,1980,1990,2000,2010,2019)) %>% 
  mutate(value=GHG/1e9)

plot_data <- gather(plot_data %>% select(-GHG),gas,value,CO2:Fgas) %>% 
  mutate(value=value/1e9)

line_data <- data.frame(x=c(1970,1970,1980,1980,1990,1990,2000,2000,2010,2010,2019,2019),y=c(0,58))

plot_data %>% ggplot(.,aes(x=year,y=value,fill=gas)) +
  geom_area(colour="#737373") +
  geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  geom_text(data=totals,inherit.aes=FALSE,aes(x=year,y=60,label=round(value,1)),size=3.5,colour="#252525") +
  facet_grid(.~version) +
  ylab("GHG emissions (GtCO2eq)") +
  theme(axis.title.x = element_blank(),
          legend.title = element_blank())



```


# IPCC 1996 sector trends

```{r global_trend_sectors,fig.width=8,fig.height=4,results='asis'}

sector_total_v6_4 <- edgar_ghg_v6_4 %>% 
  group_by(year,sector_code,fossil_bio,description,chapter_title,subsector_title) %>% 
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE) %>% 
  mutate(version="edgar_v6_4") %>% 
  mutate(label=paste0(sector_code,"_",fossil_bio))%>%
  filter(label!="7A2_fossil")  #hotfix (code stopped running for this label)

sector_total_v6_4 <- gather(sector_total_v6_4 %>% select(-GHG),gas,value,CO2:Fgas) %>% 
  arrange(chapter_title) %>% 
  mutate(value=value/1e9)

sector_total_v6_3 <- edgar_ghg_v6_3 %>% 
  group_by(year,sector_code,fossil_bio,description,chapter_title,subsector_title) %>% 
  summarise(value=sum(GHG,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v6_3") %>% 
  mutate(label=paste0(sector_code,"_",fossil_bio)) %>%
  filter(label!="7A2_fossil")  #hotfix (code stopped running for this label)

### countries per capita

sector_countries_v6_4 <- edgar_ghg_v6_4 %>% 
  filter(year==2018) %>% 
  group_by(ISO,country,sector_code,fossil_bio,description,chapter_title,subsector_title) %>% 
  summarise(value_pc=GHG/population)

sector_global_v6_4 <- edgar_ghg_v6_4 %>% 
  filter(year==2018) %>% 
  group_by(sector_code,fossil_bio,description,chapter_title,subsector_title) %>% 
  summarise(value_pc=sum(GHG,na.rm=TRUE)/sum(population,na.rm=TRUE)) %>% 
  mutate(ISO="WLD") %>% 
  mutate(country="World")

sector_countries_v6_4 <- rbind(sector_countries_v6_4,sector_global_v6_4) %>% 
  mutate(version="edgar_v6_4")

sector_countries_v6_3 <- edgar_ghg_v6_3 %>% 
  filter(year==2018) %>% 
  group_by(ISO,country,sector_code,fossil_bio,description,chapter_title,subsector_title) %>% 
  summarise(value_pc=GHG/population)

sector_global_v6_3 <- edgar_ghg_v6_3 %>% 
  filter(year==2018) %>% 
  group_by(sector_code,fossil_bio,description,chapter_title,subsector_title) %>% 
  summarise(value_pc=sum(GHG,na.rm=TRUE)/sum(population,na.rm=TRUE)) %>% 
  mutate(ISO="WLD") %>% 
  mutate(country="World")

sector_countries_v6_3 <- rbind(sector_countries_v6_3,sector_global_v6_3) %>% 
  mutate(version="edgar_v6_3")

sector_countries <- rbind(sector_countries_v6_3,sector_countries_v6_4) %>% 
  mutate(label=paste0(sector_code,"_",fossil_bio))%>%
  filter(label!="7A2_fossil")  #hotfix (code stopped running for this label)

for (i in 1:length(unique(sector_total_v6_4$chapter_title))) {

  chapter_handle = unique(sector_total_v6_4$chapter_title)[i]
  cat("\n\n### ", chapter_handle,"sectors" , "\n")
  
  data <- sector_total_v6_4 %>% 
    filter(chapter_title==chapter_handle)
  data_v6_3 <- sector_total_v6_3 %>% 
    filter(chapter_title==chapter_handle)
  countries <- sector_countries  %>% 
    filter(chapter_title==chapter_handle)
  
  for (j in 1:length(unique(data$label))) {
  #for (j in 1:2) {
    
    sector_handle = unique(data$label)[j]
  
    p <- data %>% 
      filter(label==sector_handle) %>% 
      ggplot(.,aes(x=year,y=value,fill=gas)) +
      geom_area(color="#737373") +
      geom_path(data=data_v6_3 %>% filter(label==sector_handle), inherit.aes=FALSE,aes(x=year,y=value,color=version),size=0.75) +
      #facet_wrap(label~description,scales="free",labeller = label_wrap_gen(width=30,multi_line = TRUE)) +
      scale_x_continuous(breaks=c(1970,1990,2010)) +
      scale_color_manual(values="#b30000") +
      ylab("GHG emissions (GtCO2eq)") +
      theme(axis.title.x = element_blank(),
          legend.position = "bottom",
          legend.title = element_blank(),
          legend.spacing = unit(0, 'cm'),
          legend.margin = margin(l=0,unit="pt"))
                       
    
    
    p2 <- countries %>%
      filter(label==sector_handle) %>% 
      filter(version=="edgar_v6_4") %>% 
      arrange(desc(value_pc)) %>% 
      head(10) %>% 
      ggplot(.,aes(x=reorder(country,-value_pc),y=value_pc)) +
      geom_bar(stat='identity',fill="#2c7fb8") +
      geom_hline(data=countries %>% filter(ISO=="WLD") %>% filter(version=="edgar_v6_4") %>% filter(label==sector_handle),
                  aes(yintercept=value_pc),linetype="dashed",color="#252525",size=0.75) +
      geom_text(data=countries %>% filter(ISO=="WLD") %>% filter(version=="edgar_v6_4") %>% filter(label==sector_handle),
                aes(x=-Inf,y=value_pc,label="World average (edgar_v6_4)"),color="#252525",hjust=-0.5,vjust=-0.3) +
      ylab("Sector emissions (tCO2eq/person)") +
      theme(axis.title.x = element_blank(),
            axis.text.x = element_text(angle = 45,hjust=1))
    
    print(wrap_elements(p) + wrap_elements(p2) + 
            plot_annotation(title = paste0("IPCC.1996 sector: ",data$label[data$label==sector_handle]),                                    subtitle = paste0("EDGAR description: ",data$description[data$label==sector_handle],"\n","IPCC AR6 subsector: ",data$subsector_title[data$label==sector_handle],"\n")))
    cat("\n")
  
  }
  
}

# for (i in 1:length(unique(sector_total_v6_4$chapter_title))) {
# 
#   handle = unique(sector_total_v6_4$chapter_title)[i]
#   cat("\n\n### ", handle,"sectors" , "\n")
#   
#   data <- sector_total_v6_4 %>% 
#     filter(chapter_title==handle)
#   
#   data_v6_3 <- sector_total_v6_3 %>% 
#     filter(chapter_title==handle)
#   
#   numbers <- data.frame(label=unique(data$label),number=1:length(unique(data$label)))
#   data <- left_join(data,numbers,by="label")
#   data_v6_3 <- left_join(data_v6_3,numbers,by="label")
#   
#   for (j in seq(1,length(unique(data$label)),6)) {
#   
#     p <- data %>% 
#       filter(number>=j) %>% 
#       filter(number<j+6) %>% 
#       ggplot(.,aes(x=year,y=value,fill=gas)) +
#       geom_area(color="#737373") +
#       geom_path(data=data_v6_3 %>% filter(number>=j) %>% filter(number<j+6),aes.inherit=FALSE,aes(x=year,y=value,fill=NA,color=version),size=0.5) +
#       #geom_text(data=data %>% filter(year==1970) %>% filter(number>=j) %>% filter(number<j+6), aes(x = -Inf, y = Inf,label=subsector_title),hjust = -0.02, vjust = "inward",size=3.5,color="#636363") +
#       facet_wrap(label~description,scales="free",labeller = label_wrap_gen(width=30,multi_line = TRUE)) +
#       scale_x_continuous(breaks=c(1970,1990,2010)) +
#       #scale_color_manual(values="#b30000") +
#       ylab("GHG emissions (GtCO2eq)") +
#       theme(axis.title.x = element_blank(),
#           legend.position = "bottom",
#           legend.title = element_blank())
#     
#     print(p)
#     cat("\n")
#   
#   }
#   
# }


```
# Region trends

```{r region_trends,fig.width=10,fig.height=10,results='asis'}

plot_data_gases <- edgar_ghg_v6_4 %>% 
  group_by(year,region_ar6_10) %>% 
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE)
plot_data_gases <- gather(plot_data_gases %>% select(-GHG),gas,value,CO2:Fgas) %>% 
  mutate(value=value/1e9)

plot_data_sectors <- edgar_ghg_v6_4 %>% 
  group_by(year,region_ar6_10,chapter_title) %>% 
  summarise(value=sum(GHG,na.rm=TRUE)/1e9)

numbers <- data.frame(region_ar6_10=unique(plot_data_gases$region_ar6_10),number=1:length(unique(plot_data_gases$region_ar6_10)))

plot_data_gases <- left_join(plot_data_gases,numbers,by="region_ar6_10")
plot_data_sectors <- left_join(plot_data_sectors,numbers,by="region_ar6_10")


### v5

plot_data_gases_v6_3 <- edgar_ghg_v6_3 %>% 
  group_by(year,region_ar6_10) %>% 
  summarise(value=sum(GHG,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v6_3")

plot_data_gases_v6_3 <- left_join(plot_data_gases_v6_3,numbers,by="region_ar6_10")

for (i in c(1,6)) {
  
  p1 <- plot_data_gases %>% 
    filter(number>=i) %>% 
    filter(number<i+6) %>%  
    ggplot(.,aes(x=year,y=value,fill=gas)) +
    geom_area(colour="#737373") +
    geom_path(data=plot_data_gases_v6_3 %>% filter(number>=i) %>% filter(number<i+6), aes.inherit=FALSE,aes(x=year,y=value,fill=NA,color=version),size=0.5) +
    scale_color_manual(values="#b30000") +
    ylab("GHG emissions (GtCO2eq)") +
    facet_grid(region_ar6_10~.,scales="free",labeller = label_wrap_gen(width=22,multi_line = TRUE)) +
    theme(legend.position="bottom",
          axis.title.x = element_blank(),
          legend.title = element_blank())

  p2 <- plot_data_sectors %>% 
    filter(number>=i) %>% 
    filter(number<i+6) %>%
    ggplot(.,aes(x=year,y=value,fill=chapter_title)) +
    geom_area(colour="#737373") +
    geom_path(data=plot_data_gases_v6_3 %>% filter(number>=i) %>% filter(number<i+6), aes.inherit=FALSE,aes(x=year,y=value,fill=NA,color=version),size=0.5) +
    facet_grid(region_ar6_10~.,scales="free",labeller = label_wrap_gen(width=22,multi_line = TRUE)) +
    scale_color_manual(values="#b30000") +
    theme(legend.position="bottom",
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          legend.title = element_blank()) + 
    guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  p <- p1 + p2
  print(p)
  cat("\n")
}
  



```


# Country trends


```{r country_trends,fig.width=10,fig.height=10,results = "asis"}

# plot_data_gases <- edgar_ghg_v6_4 %>% 
#   group_by(year,country) %>% 
#   summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE)
# plot_data_gases <- gather(plot_data_gases %>% select(-GHG),gas,value,CO2:Fgas) %>% 
#   mutate(value=value/1e6)
# 
# plot_data_gases_v6_3 <- edgar_ghg_v6_3 %>% 
#   group_by(year,country) %>% 
#   summarise(value=sum(GHG,na.rm=TRUE)/1e6) %>% 
#   mutate(version="edgar_v6_3")
# 
# plot_data_sectors <- edgar_ghg_v6_4 %>% 
#   group_by(year,country,chapter_title) %>% 
#   summarise(value=sum(GHG,na.rm=TRUE)/1e6)
# 
# plot_data_subsectors <- edgar_ghg_v6_4 %>% 
#   group_by(year,country,chapter_title,subsector_title) %>% 
#   summarise_at(vars(CO2,CH4,N2O,Fgas),sum,na.rm=TRUE)
# plot_data_subsectors <- gather(plot_data_subsectors,gas,value,CO2:Fgas) %>% 
#   mutate(value=value/1e6)
# 
# plot_data_subsectors_v6_3 <- edgar_ghg_v6_3 %>% 
#   group_by(year,country,chapter_title,subsector_title) %>% 
#   summarise(value=sum(GHG,na.rm=TRUE)/1e6) %>% 
#   mutate(version="edgar_v6_3")
# 
# for (i in 1:length(unique(plot_data_gases$country))) {
# #for (i in 35:36) {
#   
#   country_handle = unique(plot_data_gases$country)[i]
#   
#   p1 <- plot_data_gases %>% 
#     filter(country==country_handle) %>% 
#     ggplot(.,aes(x=year,y=value,fill=gas)) +
#     geom_area(colour="#737373") +
#     ylab("GHG emissions (MtCO2eq)") +
#     theme(legend.position="bottom",
#           axis.title.x = element_blank(),
#           legend.title = element_blank()) +
#     ggtitle(paste0(country_handle," emissions by gas"))
# 
#   if (length(plot_data_gases_v6_3$value[plot_data_gases_v6_3$country==country_handle])>0) {
#     
#     p1 <- p1 +
#       geom_path(data=plot_data_gases_v6_3 %>% filter(country==country_handle), inherit.aes=FALSE,aes(x=year,y=value,fill=NA,color=version),size=0.5) +
#     scale_color_manual(values="#b30000")
#     
#   }
#   
#   
#   p2 <- plot_data_sectors %>% 
#     filter(country==country_handle) %>% 
#     ggplot(.,aes(x=year,y=value,fill=chapter_title)) +
#     geom_area(colour="#737373") +
#     theme(legend.position="bottom",
#           axis.title.y = element_blank(),
#           axis.title.x = element_blank(),
#           legend.title = element_blank()) +
#     ggtitle(paste0(country_handle," emissions by sector")) + 
#     guides(fill=guide_legend(nrow=2,byrow=TRUE))
#   
#   if (length(plot_data_gases_v6_3$value[plot_data_gases_v6_3$country==country_handle])>0) {
#     
#     p2 <- p2 +
#       geom_path(data=plot_data_gases_v6_3 %>% filter(country==country_handle), inherit.aes=FALSE,aes(x=year,y=value,fill=NA,color=version),size=0.5) +
#     scale_color_manual(values="#b30000")
#     
#   }
#   
#   
#   p3 <- plot_data_subsectors %>% 
#     filter(country==country_handle) %>% 
#     filter(year==2018) %>% 
#     ggplot(.,aes(x=reorder(subsector_title,value),y=value,fill=gas)) + 
#     facet_grid(chapter_title~.,scales="free",space="free",labeller = label_wrap_gen(width=20,multi_line = TRUE)) +
#     geom_bar(stat='identity',colour="#737373") +
#     ylab("GHG emissions in 2018 (MtCO2eq)") +
#     coord_flip() +
#     theme(axis.title.y = element_blank(),
#           legend.title = element_blank())
#   
#   data = plot_data_subsectors_v6_3 %>% filter(country==country_handle) %>% filter(year==2018)
#   
#   if (length(data$value)>0) {
#     
#     p3 <- p3 +
#     geom_point(data=data,aes.inherit=FALSE,aes(x=reorder(subsector_title,value),y=value,color=version,fill=NA),size=2) +
#     scale_color_manual(values="#737373")
#     
#   }
#   
#   
#   
#   p <- wrap_elements(p1 + p2) / wrap_elements(p3) +  plot_layout(heights = c(1,1.4))
#   
#   cat("\n\n\\pagebreak\n### ", country_handle, "\n")
#   print(p)
#   cat("  \n")
# }
#   



```


