---
title: "fgas_check"
output: word_document
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(openxlsx)
library(patchwork)
library(zoo)
library(pals)
library(Polychrome)

knitr::opts_chunk$set(echo = FALSE,warning=FALSE)
options(dplyr.summarise.inform = FALSE)
theme_set(theme_bw())
ggplot <- function(...) ggplot2::ggplot(...)# + scale_fill_brewer(palette="Set2")

load('../../../Data/edgar6_data_raw.RData')
edgar_raw_v6_1 <- edgar_raw %>%
  filter(!is.na(value))%>%
  filter(year<2019)
load('../../../Data/edgar5_data_raw.RData')
edgar_raw_v5 <- edgar_raw %>%
  filter(!is.na(value))%>%
  filter(year<2019)
load('../../../Data/edgar6_v2_data_raw.RData')
edgar_raw_v6_2 <- edgar_raw %>%
  filter(!is.na(value))%>%
  filter(year<2019)
load('../../../Data/edgar6_v3_data_raw.RData')
edgar_raw_v6_3 <- edgar_raw %>%
  filter(!is.na(value))%>%
  filter(year<2019)
rm(edgar_raw)

load('../../../Data/edgar6_data_ghg_gwp_ar6.RData')
edgar_ghg_v6_1 <- edgar_ghg %>%
  filter(!is.na(Fgas))%>%
  filter(year<2019)
load('../../../Data/edgar5_data_ghg_gwp_ar6.RData')
edgar_ghg_v5 <- edgar_ghg %>%
  filter(!is.na(Fgas))%>%
  filter(year<2019)
load('../../../Data/edgar6_v2_data_ghg_gwp_ar6.RData')
edgar_ghg_v6_2 <- edgar_ghg %>%
  filter(!is.na(Fgas))%>%
  filter(year<2019)
load('../../../Data/edgar6_v3_data_ghg_gwp_ar6.RData')
edgar_ghg_v6_3 <- edgar_ghg %>%
  filter(!is.na(Fgas))%>%
  filter(year<2019)
rm(edgar_ghg)

crf_data<-read_csv("../../../Data/supplemetary data/Guetschow-et-al-2021-PRIMAP-crf96_2021-v1.csv")
annexIcountries<-unique(crf_data$`area (ISO3)`)
annexIcountries<-annexIcountries[annexIcountries!="EU27BX" & annexIcountries!="EU28"]
annexIcountries<-as.data.frame(cbind(countries=annexIcountries,annexI="Annex I"))

```


```{r compile_data_no_gwp,fig.width=10,fig.height=8}


fgas_data_v5 <- edgar_raw_v5 %>%  
  group_by(year,gas,gwp100_ar5,gwp100_ar6) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(version="edgar_v5")

fgas_data_v6_3 <- edgar_raw_v6_3 %>% 
  group_by(year,gas,gwp100_ar5,gwp100_ar6) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(version="edgar_v6_3")

fgas_data <- rbind(fgas_data_v5,fgas_data_v6_3)


fgas_data <- fgas_data %>% 
  filter(gas != "CO2") %>%
  filter(gas != "CH4") %>% 
  filter(gas != "N2O")


fgas_data %>% 
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  facet_wrap(.~gas,scales="free") + 
  ylab("t native units") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom")


```

```{r regions,fig.width=8,fig.height=6}


fgas_data_v5_gwp <- edgar_ghg_v5 %>%  
  group_by(year,region_ar6_10) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v5_ar6_gwp") %>% 
  mutate(region_ar6_10=ifelse(region_ar6_10=="South-East Asia and Developing Pacific","South-East Asia and developing Pacific",region_ar6_10))

fgas_data_v6_3_gwp <- edgar_ghg_v6_3 %>% 
  group_by(year,region_ar6_10) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v6_3_ar6_gwp")


fgas_data_gwp <- rbind(fgas_data_v5_gwp,fgas_data_v6_3_gwp)


fgas_data_gwp %>% 
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  facet_wrap(.~region_ar6_10,scales="free") +
  ylab("GtCO2eq") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title=element_blank())




```


```{r compile_data_no_gwp_1,fig.width=4,fig.height=4}


fgas_data_v5_gwp <- edgar_ghg_v5 %>%  
  group_by(year) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v5_ar6_gwp")

fgas_data_v6_3_gwp <- edgar_ghg_v6_3 %>% 
  group_by(year) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v6_3_ar6_gwp")

fgas_data_gwp <- rbind(fgas_data_v5_gwp,fgas_data_v6_3_gwp)


fgas_data_gwp %>% 
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  ylab("GtCO2eq") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title=element_blank())


fgas_data_gwp <- spread(fgas_data_gwp %>% filter(year==2018),version,value)




```

```{r compile_data_gwp,fig.width=10,fig.height=4}

fgas_data <- fgas_data %>%
  mutate(value=(value*gwp100_ar6)/1e9)%>% 
  mutate(version=paste(version,"_ar6_gwp",sep=""))

fgas_data %>% ggplot(.,aes(x=year,y=value,fill=gas)) +
  geom_area(colour="#737373") +
  scale_fill_manual(values=unname(alphabet()))+
  #scale_fill_brewer(palette = unname(alphabet()))+
  #geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  #geom_text(data=totals,inherit.aes=FALSE,aes(x=year,y=60,label=round(value,1)),size=3.5,colour="#252525") +
  facet_grid(.~version) +
  ylab("GHG emissions (GtCO2eq)") +
  theme(axis.title.x = element_blank(),
          legend.title = element_blank())

fgas_2018<-fgas_data %>%
  filter(year==2018) %>%
  group_by(version) %>%
  mutate(total=sum(value)) %>%
  mutate(share=(value/total)*100)

fgas_2018 %>% ggplot(.,aes(y=version,x=share,fill=gas)) +
  geom_bar(stat="identity",colour="#737373") +
  scale_fill_manual(values=unname(alphabet()))+
  #scale_fill_brewer(palette = unname(alphabet()))+
  #geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  #geom_text(data=totals,inherit.aes=FALSE,aes(x=year,y=60,label=round(value,1)),size=3.5,colour="#252525") +
  xlab("%-share in 2018") +
  theme(axis.title.y = element_blank(),
          legend.title = element_blank())

```

```{r plots by region,fig.width=10,fig.height=4}

fgas_data_v5_gwp <- edgar_ghg_v5 %>%  
  group_by(year,region_ar6_6) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v5_ar6_gwp")

fgas_data_v6_3_gwp <- edgar_ghg_v6_3 %>% 
  group_by(year,region_ar6_6) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v6_3_ar6_gwp")

fgas_data_gwp <- rbind(fgas_data_v5_gwp,fgas_data_v6_3_gwp)


fgas_data_gwp %>% 
  filter(region_ar6_6!="Intl. Aviation") %>%
  filter(region_ar6_6!="Intl. Shipping") %>%
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  facet_grid(.~region_ar6_6) +
  ylab("GtCO2eq") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title=element_blank())

fgas_data_gwp %>% 
  filter(region_ar6_6!="Intl. Aviation") %>%
  filter(region_ar6_6!="Intl. Shipping") %>%
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  facet_wrap(.~region_ar6_6,scales = "free",nrow=1) +
  ylab("GtCO2eq") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title=element_blank())

```

```{r annxI vs non-annexI,fig.width=10,fig.height=12}


fgas_data_v5_gwp <- edgar_ghg_v5 %>%  
  group_by(year,ISO) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v5_ar6_gwp")

fgas_data_v6_3_gwp <- edgar_ghg_v6_3 %>% 
  group_by(year,ISO) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v6_3_ar6_gwp")

fgas_data_gwp <- rbind(fgas_data_v5_gwp,fgas_data_v6_3_gwp)

fgas_data_gwp <- left_join(fgas_data_gwp,annexIcountries,by=c("ISO"="countries"))

fgas_data_gwp <- fgas_data_gwp %>%
  mutate(ISO=ifelse(is.na(annexI),"non-Annex I",ISO)) %>%
  group_by(ISO,year,version) %>%
  summarise(value=sum(value,na.rm = TRUE))

fgas_data_gwp %>% 
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  facet_wrap(.~ISO,scales = "free") +
  ylab("GtCO2eq") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title=element_blank())

```


```{r compile_data_no_gwp_3,fig.width=10,fig.height=8}


fgas_data_v6_1 <- edgar_raw_v6_1 %>%  
  group_by(year,gas,gwp100_ar5,gwp100_ar6) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(version="edgar_v6_1")

fgas_data_v6_3 <- edgar_raw_v6_3 %>% 
  group_by(year,gas,gwp100_ar5,gwp100_ar6) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(version="edgar_v6_3")

fgas_data <- rbind(fgas_data_v6_1,fgas_data_v6_3)


fgas_data <- fgas_data %>% 
  filter(gas != "CO2") %>%
  filter(gas != "CH4") %>% 
  filter(gas != "N2O")


fgas_data %>% 
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  facet_wrap(.~gas,scales="free") + 
  ylab("t native units") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom")


```
```{r compile_data_no_gwp_4,fig.width=4,fig.height=4}


fgas_data_v6_1_gwp <- edgar_ghg_v6_1 %>%  
  group_by(year) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v6_1_ar6_gwp")

fgas_data_v6_3_gwp <- edgar_ghg_v6_3 %>% 
  group_by(year) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v6_3_ar6_gwp")

fgas_data_gwp <- rbind(fgas_data_v6_1_gwp,fgas_data_v6_3_gwp)


fgas_data_gwp %>% 
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  ylab("GtCO2eq") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title=element_blank())


#fgas_data_gwp <- spread(fgas_data_gwp %>% filter(year==2018),version,value)




```

```{r compile_data_gwp_1,fig.width=10,fig.height=4}

fgas_data <- fgas_data %>%
  mutate(value=(value*gwp100_ar6)/1e9) %>% 
  mutate(version=paste(version,"_ar6_gwp",sep=""))

fgas_data %>% ggplot(.,aes(x=year,y=value,fill=gas)) +
  geom_area(colour="#737373") +
  scale_fill_manual(values=unname(alphabet()))+
  #scale_fill_brewer(palette = unname(alphabet()))+
  #geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  #geom_text(data=totals,inherit.aes=FALSE,aes(x=year,y=60,label=round(value,1)),size=3.5,colour="#252525") +
  facet_grid(.~version) +
  ylab("GHG emissions (GtCO2eq)") +
  theme(axis.title.x = element_blank(),
          legend.title = element_blank())

fgas_2018<-fgas_data %>%
  filter(year==2018) %>%
  group_by(version) %>%
  mutate(total=sum(value)) %>%
  mutate(share=(value/total)*100)

fgas_2018 %>% ggplot(.,aes(y=version,x=share,fill=gas)) +
  geom_bar(stat="identity",colour="#737373") +
  scale_fill_manual(values=unname(alphabet()))+
  #scale_fill_brewer(palette = unname(alphabet()))+
  #geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  #geom_text(data=totals,inherit.aes=FALSE,aes(x=year,y=60,label=round(value,1)),size=3.5,colour="#252525") +
  xlab("%-share in 2018") +
  theme(axis.title.y = element_blank(),
          legend.title = element_blank())

```

```{r plots by region 1,fig.width=10,fig.height=4}

fgas_data_v5_gwp <- edgar_ghg_v5 %>%  
  group_by(year,region_ar6_6) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v5_ar6_gwp")

fgas_data_v6_3_gwp <- edgar_ghg_v6_3 %>% 
  group_by(year,region_ar6_6) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v6_3_ar6_gwp")

fgas_data_gwp <- rbind(fgas_data_v5_gwp,fgas_data_v6_3_gwp)


fgas_data_gwp %>% 
  filter(region_ar6_6!="Intl. Aviation") %>%
  filter(region_ar6_6!="Intl. Shipping") %>%
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  facet_grid(.~region_ar6_6) +
  ylab("GtCO2eq") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title=element_blank())

fgas_data_gwp %>% 
  filter(region_ar6_6!="Intl. Aviation") %>%
  filter(region_ar6_6!="Intl. Shipping") %>%
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  facet_wrap(.~region_ar6_6,scales = "free",nrow=1) +
  ylab("GtCO2eq") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title=element_blank())

```

```{r annexI vs non-annexI 1,fig.width=10,fig.height=12}


fgas_data_v5_gwp <- edgar_ghg_v5 %>%  
  group_by(year,ISO) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v5_ar6_gwp")

fgas_data_v6_3_gwp <- edgar_ghg_v6_3 %>% 
  group_by(year,ISO) %>% 
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>% 
  mutate(version="edgar_v6_3_ar6_gwp")

fgas_data_gwp <- rbind(fgas_data_v5_gwp,fgas_data_v6_3_gwp)

fgas_data_gwp <- left_join(fgas_data_gwp,annexIcountries,by=c("ISO"="countries"))

fgas_data_gwp <- fgas_data_gwp %>%
  mutate(ISO=ifelse(is.na(annexI),"non-Annex I",ISO)) %>%
  #mutate(ISO=ifelse(is.na(annexI),"non-Annex I","Annex I")) %>%
  group_by(ISO,year,version) %>%
  summarise(value=sum(value,na.rm = TRUE))

fgas_data_gwp %>% 
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  facet_wrap(.~ISO,scales = "free") +
  ylab("GtCO2eq") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title=element_blank())

```

```{r annexI compare with primap,fig.width=10,fig.height=12}

crf_fgas<-crf_data %>% filter(entity=="FGASES (AR5GWP100)")%>%
   filter(`category (IPCC1996)`=="M.0.EL")

crf_fgas<-gather(crf_fgas,key = "year", value = "value", "1986":"2019") %>%
  filter(`area (ISO3)`!="EU27BX")%>%
  filter(`area (ISO3)`!="EU28") %>%
  filter(`area (ISO3)`!="LIE") %>%
  filter(`area (ISO3)`!="MCO") %>%
  mutate(year=as.numeric(year))
  
crf_fgas<-crf_fgas %>%
  select(ISO=`area (ISO3)`,everything()) %>% 
  group_by(year,ISO)%>%
  summarise(value=sum(value)/1e6)%>% 
  mutate(version="primap_crf_ar5_gwp_annexI")

load('../../../Data/edgar6_v2_data_ghg_gwp_ar5.RData')
edgar_ghg_v6_3_ar5 <- edgar_ghg %>%
  filter(!is.na(Fgas))

edgar_ghg_v6_3_ar5<-left_join(edgar_ghg_v6_3_ar5,annexIcountries,by=c("ISO"="countries")) %>%
  filter(!is.na(annexI))

fgas_data_v6_3_gwp_ar5 <- edgar_ghg_v6_3_ar5 %>%
  group_by(year,ISO,country) %>%
  summarise(value=sum(Fgas,na.rm=TRUE)/1e9) %>%
  mutate(version="edgar_v6_3_ar5_gwp_annexI")

fgas_data_gwp <- rbind(fgas_data_v6_3_gwp_ar5,crf_fgas)

blarg <- fgas_data_gwp %>% 
  filter(year==2018) %>% 
  filter(version=="primap_crf_ar5_gwp_annexI") %>% 
  arrange(desc(value)) %>% 
  head(15) %>% 
  mutate(include=1) %>% 
  ungroup()

fgas_data_gwp <- left_join(fgas_data_gwp,blarg %>% select(-year,-country,-value,-version))


fgas_data_gwp %>% 
  filter(include==1) %>% 
  ggplot(.,aes(x=year,y=value,colour=version)) +
  geom_path(na.rm = TRUE) +
  facet_wrap(.~ISO,scales="free") +
  ylab("GtCO2eq") +
  scale_x_continuous(breaks=c(1970,1990,2010)) +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title=element_blank())
#unique(crf_data$entity)

```

```{r save, echo=FALSE}

# fgas_data <- spread(fgas_data,version,value) %>% 
#   filter(year==2018)
# 
# fgas_data <- fgas_data %>% 
#   mutate(edgar_v5_gwp_ar5 = edgar_v5*gwp100_ar5) %>% 
#   mutate(edgar_v6_3_gwp_ar5 = edgar_v6_3*gwp100_ar5) %>% 
#   mutate(edgar_v5_gwp_ar6 = edgar_v5*gwp100_ar6) %>% 
#   mutate(edgar_v6_3_gwp_ar6 = edgar_v6_3*gwp100_ar6)
# 
# write.xlsx(fgas_data,"edgar_fgas.xlsx")


```
