---
title: "Emissions trends and drivers: overview"
author: "William F. Lamb"
output: html_document
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(gganimate)
library(xlsx)
load('Data/edgar.RData')


######### load basic development and emissions data ######### 

# load('Data/basic.RData')
# 
# ## bring in more regional codes
# codes <- read.xlsx('C:/Users/lamw/Documents/SpiderOak Hive/Work/Code/R/.Place names and codes/output/ISOcodes.xlsx',sheetName = 'ISO_master')
# 
# basic <- left_join(basic,codes %>% select(Code,WB.income),by=c("ISO"="Code")) %>% 
#   select(Country,ISO,Year,UN6,RCP5,IAM10,WB.income,pop_UN,everything())
# 
# basic$WB.income <- factor(basic$WB.income,levels(basic$WB.income)[c(1,4,3,2)])
# 
# # any other adjustments here
# basic$UN6 <- gsub("LATIN AMERICA AND THE CARIBBEAN","LATIN AMERICA",basic$UN6)
# 
# basic <- basic %>% 
#   mutate(gdp_ppp_pc = gdp_ppp_WB/pop_UN)
# 
# basic$income_category  <- cut(basic$gdp_ppp_pc,breaks = c(1700,4300,8600,15000,29000,150000),dig.lab=10,include.lowest=TRUE)



```

### Total GHGs, split by region

```{r ghgs_total_income, echo=FALSE,warning=FALSE,fig.width=8,fig.path="Results/Plots/",dev=c('png','pdf')}

load('Data/edgar.RData')

plot_data <- edgar_GHG %>%
  group_by(Year,WB.income) %>% 
  summarise(total_ghg=sum(GHG,rm.na=T)/1e6)

shares <- plot_data %>% 
  filter(Year %in% c(1970,1980,1990,2000,2010,2017)) %>% 
  group_by(Year) %>% 
  mutate(totals=sum(total_ghg)) %>% 
  ungroup() %>% 
  group_by(Year,WB.income) %>% 
  mutate(fractions=(total_ghg/totals)*100)


plot_data %>% 
  ggplot(.,aes(x=Year,y=total_ghg,fill=WB.income,color=WB.income)) +
  geom_area() +
  geom_text(data=shares,aes(x=Year,y=totals-total_ghg,label=paste(round(fractions,0),"%",sep="")))+
  geom_vline(xintercept=c(1970,1980,1990,2000,2010,2017),alpha=0.3,linetype="dashed") +
  ylab("GHG emissions (GtCO2eq/yr)") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
          legend.position = c(0.12,0.8),
        legend.title=element_blank(),
        legend.background = element_blank())

plot_data <- spread(plot_data,Year,total_ghg)

xlsx::write.xlsx(as.data.frame(plot_data),file=paste("Results/IPCC_plot_data_",Sys.Date(),".xlsx",sep=""),sheetName = "Total_GHGs_Income",row.names=FALSE)

```

### Total GHGs, split by sector

```{r ghgs_5sectors, echo=FALSE,warning=FALSE,fig.width=8,fig.path="Results/Plots/",dev=c('png','pdf')}

load('Data/edgar.RData')

plot_data <- edgar_GHG %>% 
  group_by(Year,IPCC_AR5_chapter) %>% 
  summarise(total_ghg=sum(GHG,rm.na=T)/1e6) %>% 
  ungroup()

plot_data <- plot_data %>% 
  mutate(IPCC_AR5_chapter=ifelse(IPCC_AR5_chapter==7,"Energy",IPCC_AR5_chapter)) %>% 
  mutate(IPCC_AR5_chapter=ifelse(IPCC_AR5_chapter==8,"Transport",IPCC_AR5_chapter)) %>% 
  mutate(IPCC_AR5_chapter=ifelse(IPCC_AR5_chapter==9,"Buildings",IPCC_AR5_chapter)) %>% 
  mutate(IPCC_AR5_chapter=ifelse(IPCC_AR5_chapter==10,"Industry",IPCC_AR5_chapter)) %>% 
  mutate(IPCC_AR5_chapter=ifelse(IPCC_AR5_chapter==11,"Agriculture",IPCC_AR5_chapter)) %>% 
  #### add NA's to industry ####
  mutate(IPCC_AR5_chapter = ifelse(is.na(IPCC_AR5_chapter),"Industry",IPCC_AR5_chapter)) %>% 
  group_by(Year,IPCC_AR5_chapter) %>% 
  summarise(total_ghg=sum(total_ghg)) %>% 
  ungroup()

  
data <- xlsx::read.xlsx('Data/data from Jan.xlsx',sheetIndex = "EDGAR gas - Figure 1",startRow = 10,endRow = 16,check.names=FALSE)

data <- gather(data,Year,value,-source,-gas) %>% 
  mutate(Year=as.numeric(Year)) %>% 
  filter(!is.na(value)) %>%
  filter(gas=="CO2 landuse") %>% 
  mutate(IPCC_AR5_chapter="FOLU (CO2)") %>% 
  select(Year,IPCC_AR5_chapter,total_ghg=value) 


plot_data <- rbind(plot_data,data)
#plot_data$IPCC_AR5_chapter <- as.factor(plot_data$IPCC_AR5_chapter)
#plot_data$IPCC_AR5_chapter <- factor(plot_data$IPCC_AR5_chapter,levels(plot_data$IPCC_AR5_chapter)[c(4,7,2,5,1,3,6)])


### merge agriculture and FOLU
plot_data <- plot_data %>% 
  mutate(IPCC_AR5_chapter=ifelse(IPCC_AR5_chapter=="Agriculture","AFOLU",IPCC_AR5_chapter)) %>% 
  mutate(IPCC_AR5_chapter=ifelse(IPCC_AR5_chapter=="FOLU (CO2)","AFOLU",IPCC_AR5_chapter)) %>% 
  group_by(Year,IPCC_AR5_chapter) %>% 
  summarise(total_ghg=sum(total_ghg)) %>% 
  ungroup()

plot_data$IPCC_AR5_chapter <- as.factor(plot_data$IPCC_AR5_chapter)
plot_data$IPCC_AR5_chapter <- factor(plot_data$IPCC_AR5_chapter,levels(plot_data$IPCC_AR5_chapter)[c(3,5,2,4,1)])


shares <- plot_data %>% 
  filter(Year %in% c(1970,1980,1990,2000,2010,2017)) %>% 
  group_by(Year) %>% 
  mutate(totals=sum(total_ghg)) %>% 
  ungroup() %>% 
  group_by(Year,IPCC_AR5_chapter) %>% 
  mutate(fractions=(total_ghg/totals)*100)


plot_data %>%
  #filter(IPCC_AR5_chapter!="NA") %>% 
  #filter(IPCC_AR5_chapter!="Agriculture") %>% 
  ggplot(.,aes(x=Year,y=total_ghg,fill=IPCC_AR5_chapter,color=IPCC_AR5_chapter)) +
  geom_area() +
  geom_text(data=shares,aes(x=Year,y=totals-total_ghg,label=paste(round(fractions,0),"%",sep="")))+
  geom_vline(xintercept=c(1970,1980,1990,2000,2010,2017),alpha=0.3,linetype="dashed") +
  ylab("GHG emissions (GtCO2eq/yr)") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
          legend.position = c(0.12,0.8),
        legend.title=element_blank(),
        legend.background = element_blank())


plot_data <- spread(plot_data,Year,total_ghg)
sum(plot_data$`2017`)

xlsx::write.xlsx(as.data.frame(plot_data),file=paste("Results/IPCC_plot_data_",Sys.Date(),".xlsx",sep=""),sheetName = "Total_GHGs_Sector",append=TRUE,row.names=FALSE)


```


### GHG emissions by gas (Figure 1)

```{r Fig1_trend, echo=FALSE,warning=FALSE,fig.width=8,fig.path="Results/Plots/",dev=c('png','pdf')}

######### load Jan data ######### 


plot_data <- edgar_GHG %>% 
  group_by(Year) %>% 
  summarise(CO2=sum(CO2,na.rm=T)/1e6,CH4=sum(CH4,na.rm=T)/1e6,N2O=sum(N2O,na.rm=T)/1e6,Fgas=sum(Fgas,na.rm=T)/1e6)

data <- xlsx::read.xlsx('Data/data from Jan.xlsx',sheetIndex = "EDGAR gas - Figure 1",startRow = 10,endRow = 16,check.names=FALSE)

data <- gather(data,Year,value,-source,-gas) %>% 
  mutate(Year=as.numeric(Year)) %>% 
  filter(!is.na(value)) %>%
  filter(gas=="CO2 landuse") %>% 
  select(Year,CO2_Landuse=value) 

plot_data <- left_join(plot_data,data,by=c("Year"="Year"))

plot_data<- gather(plot_data,gas,value,-Year) 
plot_data <- plot_data %>% 
  mutate(gas=ifelse(gas=="CO2","CO2 FFI",gas)) %>% 
  mutate(gas=ifelse(gas=="CO2_Landuse","CO2 FOLU",gas))
plot_data$gas <- as.factor(plot_data$gas)
plot_data$gas <- factor(plot_data$gas,levels(plot_data$gas)[c(3,2,1,5,4)])


shares <- plot_data %>% 
  filter(Year %in% c(1970,1980,1990,2000,2010,2017)) %>% 
  group_by(Year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(Year,gas) %>% 
  mutate(fractions=(value/totals)*100)

plot_data %>% 
  ggplot(.,aes(x=Year,y=value,fill=gas,color=gas)) +
  geom_area() +
  geom_text(data=shares,aes(x=Year,y=round(totals-value),label=paste(round(fractions,0),"%",sep="")))+
  geom_vline(xintercept=c(1970,1980,1990,2000,2010,2017),alpha=0.3,linetype="dashed") +
  ylab('GHG Emissions (GtCO2eq/yr)') +
  theme_bw() +
  theme(axis.title.x = element_blank(),
          legend.position = c(0.12,0.8),
        legend.title=element_blank(),
        legend.background = element_blank()) 

plot_data <- spread(plot_data,Year,value)

xlsx::write.xlsx(as.data.frame(plot_data),file=paste("Results/IPCC_plot_data_",Sys.Date(),".xlsx",sep=""),sheetName = "Total_GHG_gas",append=T,row.names=FALSE)

# z <- gather(plot_data,Year,value,-gas)
# z <- spread(z,gas,value) %>%
#   filter(Year %in% c(1970,1980,1990,2000,2010,2017)) %>%
#   mutate(CH4_rate=NA,CO2_rate=NA,Fgas_rate=NA,N2O_rate=NA)
# 
# for (i in 1:4) {
# 
#   z$CH4_rate[i+1] = ((z$CH4[i+1]/z$CH4[i])^(1/10))-1
#   z$CO2_rate[i+1] = ((z$CO2[i+1]/z$CO2[i])^(1/10))-1
#   z$Fgas_rate[i+1] = ((z$Fgas[i+1]/z$Fgas[i])^(1/10))-1
#   z$N2O_rate[i+1] = ((z$N2O[i+1]/z$N2O[i])^(1/10))-1
# 
# }
# z$CH4_rate[6] = ((z$CH4[6]/z$CH4[5])^(1/7))-1
# z$CO2_rate[6] = ((z$CO2[i+1]/z$CO2[i])^(1/7))-1
# z$Fgas_rate[6] = ((z$Fgas[i+1]/z$Fgas[i])^(1/7))-1
# z$N2O_rate[6] = ((z$N2O[i+1]/z$N2O[i])^(1/7))-1



```

### Long term CO2 emissions sources and sinks (Figure 2)


```{r Fig2_budget, echo=FALSE,warning=FALSE,fig.width=10,fig.height=6,fig.path="Results/Plots/",dev=c('png','pdf')}

######### load the global carbon budget ######### 

gcb <- xlsx::read.xlsx('Data/data from Jan.xlsx',sheetIndex = "CDIAC CO2 - Figure 2",startRow = 3,endRow = 270,colIndex=1:9)
names(gcb) <- c("Year","Total","Gas","Oil","Coal","Cement","Flaring","Net land-use","Total_CO2")

# fft <- read.xlsx('Data/Global_Carbon_Budget_2018v1.0.xlsx',sheetIndex = 'Fossil Emissions by Fuel Type',startRow = 13,endRow = 2017,colIndex = 1:8)

budget_data <- gather(gcb,key,value,-Year) %>% 
  filter(key!="Total_CO2",key!="Total") %>% 
  filter(Year>=1850) 

budget_data$key <- as.factor(budget_data$key)
budget_data$key <- factor(budget_data$key,levels(budget_data$key)[c(1,2,3,4,6,5)])

fractions <- budget_data %>% 
  filter(Year %in% c(1850,1900,1950,2000)) %>% 
  group_by(Year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(Year,key) %>% 
  mutate(fractions=(value/totals)*100)

p1 <- budget_data %>% 
  ggplot(.,aes(x=Year,y=value,fill=key,color=key)) + 
  geom_area() +
  geom_text(data=fractions,aes(x=Year,y=value+totals,label=paste(round(fractions,0),"%",sep=""))) +
  geom_vline(xintercept=c(1850,1900,1950,2000),alpha=0.3,linetype="dashed") +
  ylab("Carbon emissions (GtCO2/yr)") +
  theme_bw() +
  theme(legend.position = c(0.15,0.7),
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        legend.background = element_blank())

##### future budget code

# future_budget <- data.frame(target=c("1.5oC target","2oC target"),budget=c(500,1000)) %>% 
#   mutate(years=ceiling(budget/as.vector(plot_data %>% filter(Year==2017) %>% summarise(total=sum(value)))[[1]]))
# 
# p2 <- future_budget %>% 
#   ggplot(.,aes(x=target,y=budget)) +
#   geom_bar(stat='identity') +
#   geom_text(aes(x=target,y=budget+50,label=paste("Years: ",years))) +
#   theme(axis.title.x = element_blank()) +
#   ylab("Total carbon budget relative to climate targets (GtCO2)")

###
date_data <- gcb %>% 
  select(Year,value=Total_CO2) %>% 
  filter(Year>=1850) %>% 
  mutate(key=ifelse(Year>=1850 & Year < 1890,'1850-1889',NA)) %>% 
  mutate(key=ifelse(Year>=1890 & Year < 1930,'1890-1930',key)) %>% 
  mutate(key=ifelse(Year>=1930 & Year < 1970,'1930-1970',key)) %>% 
  mutate(key=ifelse(Year>=1970 & Year < 2010,'1970-2010',key)) %>% 
  mutate(key=ifelse(Year>=2010,'2010-2017',key)) %>% 
  filter(!is.na(key))

date_data <- date_data %>% 
  mutate(key=as.factor(key)) %>% 
  group_by(key) %>% 
  summarise(value=sum(value)) %>% 
  add_row(key="1.5",value=420) %>% 
  add_row(key="2.0",value=1170)


date_data$key <- factor(date_data$key,levels(date_data$key)[c(7,6,5,4,3,2,1)])

p2 <- date_data %>% 
  ggplot(.,aes(x='x',y=value,fill=key)) +
  geom_bar(stat='identity') +
  ylab('Carbon emissions, cumulative (GtCO2)') +
  theme_bw() +
  theme(legend.position= c(0.5,0.5),
        legend.background = element_blank(),
        axis.title.x = element_blank())


time_data <- data.frame(target=c("1.5oC target","2oC target"),budget=c(420,1170)) %>% 
  group_by(budget) %>% 
  mutate(current_emissions=budget/as.vector(budget_data %>% filter(Year==2017) %>% summarise(total=sum(value)))[[1]]) %>% 
  mutate(current_emissions=round(current_emissions,0)+2017) %>% 
  ungroup()

time_data <- cbind(time_data,data.frame(three=c(2030,2084),seven=c(2037,NA)))
time_data <- gather(time_data,key,value,-budget,-target) %>% 
  mutate(key=as.factor(key))

time_data$key <- factor(time_data$key,levels(time_data$key)[c(2,3,1)])


p3 <- time_data %>% 
  ggplot(.,aes(x=key,y=value,fill=target)) + 
  geom_bar(stat='identity') +
  geom_text(aes(x=key,y=value+2,label=round(value-2017,0))) +
  #scale_y_continuous(limits=c(2017,2100),oob =rescale_none) +
  coord_flip(ylim = c(2017,2100)) +
  facet_grid(target~.) +
  theme_bw() +
  theme(legend.position='none',
        axis.title.y=element_blank()) +
  ylab('Year of budget exceedance') 

p4<- ggarrange(p2,p3,ncol=2,widths=c(1,2))

p <- ggarrange(p1,p4,nrow=2)
p

budget_data <- spread(budget_data,Year,value)

xlsx::write.xlsx(as.data.frame(budget_data),file=paste("Results/IPCC_plot_data_",Sys.Date(),".xlsx",sep=""),sheetName = "CO2_budget",append=T,row.names=FALSE)

```

### Regional per capita trends

```{r percapita_trends, echo=FALSE,warning=FALSE,fig.width=8,fig.height=4,fig.path="Results/Plots/",dev=c('png','pdf')}

######
load('Data/edgar.RData')
load('Data/basic.RData')

edgar_GHG <- left_join(edgar_GHG,basic %>% select(ISO,pop_UN,Year,gdp_real_WB),by=c("ISO"="ISO","Year"="Year"))

######

region <- edgar_GHG %>% 
  filter(Year>1969 & Year<2018) %>% 
  select(Year,WB.income,Country,GHG,gdp_real_WB,pop_UN) %>% 
  group_by(Year,Country,WB.income) %>% 
  summarise(GHG=sum(GHG,na.rm=T),pop_UN=first(pop_UN),gdp_real_WB=first(gdp_real_WB)) %>% 
  group_by(Year,WB.income) %>% 
  summarise(ghg_total = sum(GHG,na.rm=T)*1000,pop=sum(pop_UN,na.rm=T),gdp=sum(gdp_real_WB,na.rm=T)) %>% 
  mutate(ghg_pc = ghg_total/pop,ghg_gdp = ghg_total/gdp)
  

# region <- edgar_GHG %>% 
#   filter(Year>1969 & Year<2018) %>% 
#   #filter(!is.na(WB.income)) %>% 
#   group_by(WB.income,Year) %>% 
#   summarise(ghg_total = sum(GHG,na.rm=T)*1000,pop=sum(pop_UN,na.rm=T),gdp=sum(gdp_real_WB,na.rm=T)) %>% 
#   mutate(ghg_pc = ghg_total/pop,ghg_gdp = ghg_total/gdp)

## cumulative emissions total (horizontal bar chart)
# p1 <- region %>% 
#   group_by(WB.income) %>% 
#   summarise(cumulative_ghg = sum(ghg_total)/1e6) %>% 
#   ggplot(.,aes(y=cumulative_ghg,x=WB.income,fill=WB.income)) +
#   geom_bar(stat='identity') +
#   ylab("Cumulative GHG emissions (GtCO2eq)") +
#   coord_flip() +
#   theme(legend.title = element_blank(), legend.position = "none") +
#   theme(axis.title.y = element_blank()) 

## total ghg emissions (stacked area)
# p2 <- region %>% ggplot(.,aes(x=Year,y=ghg_total/1e6,fill=WB.income)) +
#   geom_area() +
#   ylab("GHG Emissions (GtCO2eq/yr)") +
#   theme(legend.title = element_blank(),legend.position = "none")

## per capita ghg emissions (line chart)
p3 <- region %>% 
  filter(!is.na(WB.income)) %>% 
  ggplot(.,aes(x=Year,y=ghg_pc,colour=WB.income)) +
  ylab('GHG Emissions per capita (tCO2eq/capita/yr)') +
  geom_path(size=1) +
  theme_bw() +
  theme(legend.position = c(0.12,0.8),
        legend.title=element_blank(),
        legend.background = element_blank(),
        axis.title.x = element_blank())

## ghg emissions per gdp (line chart)
p4 <- region %>% 
  filter(!is.na(WB.income)) %>% 
  ggplot(.,aes(x=Year,y=ghg_gdp,colour=WB.income)) +
  ylab('GHG Emissions per $GDP (tCO2eq/$/yr)') +
  theme_bw() +
  geom_path(size=1) +
  theme(legend.title = element_blank(), legend.position = "none",
        axis.title.x = element_blank())


#ggarrange(p1, p2, p3, p4, nrow=2,ncol=2)
ggarrange(p3,p4,nrow=1,ncol=2)

xlsx::write.xlsx(as.data.frame(region),file=paste("Results/IPCC_plot_data_",Sys.Date(),".xlsx",sep=""),sheetName = "per_capita_trends",append=T,row.names=FALSE)


```



```{r edgar_prep,include=FALSE}

sector=7
gas="GHG"
time_start=2010
category="IPCC_AR5_chapter"
rate_or_abs="rate"

library(openxlsx)

######### load edgar data ######### 

load('Data/edgar.RData')

edgar_emissions_plot <- function(time_start,category,sector,gas,rate_or_abs) {
  
  ##############  calculate growth rates in given time period ############## 
  
  sector_code <- edgar_GHG %>%
    filter_at(vars(category),all_vars(.==sector))
  sector_code <- substr(sector_code$sector_code[[1]],1,as.numeric(str_sub(category,-1)))
  
  rates <- edgar_GHG %>% 
    filter_at(vars(category),all_vars(.==sector)) %>% 
    filter(!is.na(WB.income)) %>% 
    filter(Year>=time_start & Year<2018) %>% 
    group_by(Country,Year,WB.income) %>% 
    summarise_at(gas,sum,na.rm=TRUE) %>% 
    ungroup() %>% 
    rename_at(gas,funs(sprintf('value')))
  
  ####### CHECK DATA HERE FOR ZEROS AND NANS ####### 
  
  
  # what is 80% of the emissions?
  blarg <- rates %>%
    filter(Year==2017)
  threshold <- sum(blarg$value,na.rm=T)*0.8
  
  ## remove countries below absolute emissions threshold
  
  rates <- rates %>% 
    group_by(Country) %>% 
    mutate(rate=(last(value)/first(value))^(1/(last(Year)-time_start+1))-1) %>% 
    mutate(abs_growth=last(value)-first(value)) %>%
    filter(Year==2017) %>% 
    na.omit() %>% 
    arrange(desc(value))
  
  
  rates$cutoff <- 0
  z <- 0
  for (i in 1:length(rates$Country)){
    z <- z + rates$value[i]
    if (z > threshold) {
      break
    }
    rates$cutoff[i] <- 1
  }
  
  country_list <- rates %>% select(Country,cutoff)
  
  #### calculate growth rates for countries below threshold, grouped by region ####
  
  blarg <- edgar_GHG %>% 
    filter_at(vars(category),all_vars(.==sector)) %>% 
    filter(!is.na(WB.income)) %>% 
    filter(Year>=time_start & Year<2018) %>% 
    group_by(Country,Year,WB.income) %>% 
    summarise_at(gas,sum,na.rm=TRUE) %>% 
    ungroup() %>% 
    rename_at(gas,funs(sprintf('value')))
  
  blarg <- left_join(blarg,country_list,by=c("Country"="Country")) %>% 
    filter(cutoff==0) %>% 
    filter(!is.na(WB.income)) %>% 
    filter(Year>=time_start & Year<2018) %>% 
    group_by(WB.income,Year) %>% 
    summarise_at('value',sum,na.rm=TRUE)
  
  blarg <- blarg %>% 
    group_by(WB.income) %>% 
    mutate(rate=(last(value)/first(value))^(1/(last(Year)-time_start+1))-1) %>% 
    mutate(abs_growth=last(value)-first(value)) %>%
    filter(Year==2017) %>% 
    na.omit() %>% 
    mutate(Country=paste(WB.income,"(rest)"))
  
  
  ### join and plot
  rates <- rbind(rates %>% filter(cutoff==1) %>% select(-cutoff),blarg)
  
    rates <- gather(rates %>% mutate(rate=rate*100),var,value,rate:abs_growth)
  
  p2 <- rates %>% 
    filter(var==rate_or_abs) %>% 
    ggplot(.,aes(x = reorder(Country,value),y = value, fill=WB.income)) +
    geom_bar(stat='identity') + 
    ylab(paste(ifelse(rate_or_abs=="rate","Rate of","Absolute")," change in ",gas," emissions (Sector ",sector,") ",time_start,"-2017\n (Countries responsible for 80% of sector emissions are shown)",sep="")) +
    coord_flip() +
    theme_bw() +
    theme(legend.position="none",
          axis.title.y = element_blank()) 

  regions <- left_join(edgar_GHG,country_list,by=c("Country"="Country")) %>%
    filter_at(vars(category),all_vars(.==sector)) %>% 
    filter(!is.na(WB.income)) %>% 
    filter(Country!="World") %>% 
    filter(Year>1979 & Year<2018) %>% 
    filter(cutoff==0) %>% 
    group_by(WB.income,Year) %>% 
    summarise_at(gas,sum,na.rm=TRUE) %>% 
    mutate(Country=paste(WB.income,"(rest)")) %>% 
    ungroup() %>% 
    rename_at(gas,funs(sprintf('value')))
  
  rect <- data.frame(xmin=time_start, xmax=2017, ymin=-Inf, ymax=Inf)
  
  p1 <-regions %>%
    ggplot(.,aes(x=Year,y=value,fill=WB.income)) +
    geom_area() +
    geom_rect(data=rect, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),
              fill="grey20",
              alpha=0.35,
              inherit.aes = FALSE) +
    theme_bw() +
    theme(legend.position='bottom',
          legend.title=element_blank(),
          axis.title.x = element_blank()) +
    ylab(paste(gas,"Emissions, Gg CO2eq")) +
    ggtitle(paste("IPCC Sector ",sector,", ",gas," Emissions",sep=""))
  
  
  ############## plot absolute values ############## 
  
  countries <- left_join(edgar_GHG,country_list,by=c("Country"="Country")) %>%
    filter_at(vars(category),all_vars(.==sector)) %>% 
    filter(!is.na(WB.income)) %>% 
    filter(Country!="World") %>% 
    filter(Year>1979 & Year<2018) %>% 
    filter(cutoff==1) %>% 
    group_by(Country,Year,WB.income) %>% 
    summarise_at(gas,sum,na.rm=TRUE) %>% 
    ungroup() %>% 
    rename_at(gas,funs(sprintf('value')))
  
  
  p4 <- ggarrange(p1,p2,ncol=1,nrow=2)
  return(list("plot"=p4,"data"=rates))
}


```

### Total sector trends & rates of change


```{r total_sector_trends,echo=FALSE,warning=FALSE,fig.width=8,fig.height=10,fig.path="Results/Plots/",dev=c('png','pdf')}

########### total sector emissions



########### create totals
load('Data/edgar.RData')
totals <- edgar_GHG %>% 
  group_by(ISO,Year,WB.income,Country) %>% 
  summarise(CO2=sum(CO2,rm.na=T),CH4=sum(CH4,rm.na=T),N2O=sum(N2O,rm.na=T),Fgas=sum(Fgas,rm.na=T),GHG=sum(GHG,rm.na=T)) %>% 
  mutate(sector_code="Total",category_final="Total",category_1="Total",category_2="Total",category_3="Total",IPCC_AR5_chapter=0,IPCC_AR5_sector=0) %>% 
  select(ISO,sector_code,category_final,category_1,category_2,category_3,Year,CO2,CH4,N2O,Fgas,GHG,Country,WB.income,IPCC_AR5_chapter,IPCC_AR5_sector)

edgar_GHG <- edgar_GHG %>% 
  bind_rows(totals)

p1 <- edgar_emissions_plot(2010,"sector_code","Total","GHG",'rate')
p2 <- edgar_emissions_plot(2010,"sector_code","Total","GHG",'abs_growth')
p1$plot
p2$plot
rm(edgar_GHG)

data <- as.data.frame(p1$data %>% 
  select(-Year))

xlsx::write.xlsx(data,file=paste("Results/IPCC_plot_data_",Sys.Date(),".xlsx",sep=""),sheetName="Total_sector_rates_by_country",append=TRUE,row.names=FALSE)


```

### Regional trends & rates of change by IPCC sector


```{r edgar_plots_rates,echo=FALSE,warning=FALSE,fig.width=8,fig.height=10,fig.path="Results/Plots/",dev=c('png','pdf')}


########### rates of change: sectors 7-11
# load('Data/edgar.RData')
# c=1
# data = data.frame()
# plot_list = list()
# time_start = 2010
# category = 'IPCC_AR5_chapter'
# gas = 'GHG'
# 
# for (i in 7:11) {
#   
#   p <- edgar_emissions_plot(time_start,category,i,gas,'rate')
#   
#   plot_list[[c]] <- p$plot
#   
#   if (c==1) {
#     data <- p$data %>% 
#       mutate(run=paste(category,i,gas,time_start,sep="_"))
#   } else {
#     data <- rbind(data,p$data %>% mutate(run=paste(category,i,gas,time_start,sep="_")))
#   }
#   
#   c=c+1
#   
# }
# plot_list
# 
# data <- as.data.frame(data %>% select(-Year))
# 
# xlsx::write.xlsx(data,file=paste("Results/IPCC_plot_data_",Sys.Date(),".xlsx",sep=""),sheetName="Sectors_rates_by_country",append=TRUE,row.names=FALSE)


```

### Regional trends & absolute change by IPCC sector


```{r edgar_plots_abs,echo=FALSE,warning=FALSE,fig.width=8,fig.height=10,fig.path="Results/Plots/",dev=c('png','pdf')}

########### absolute growth: sectors 7-11
# c=1
# data = data.frame()
# plot_list = list()
# time_start = 2010
# category = 'IPCC_AR5_chapter'
# gas = 'GHG'
# 
# for (i in 7:11) {
#   
#   p <- edgar_emissions_plot(time_start,category,i,gas,'abs_growth')
#   
#   plot_list[[c]] <- p$plot
#   
#   if (c==1) {
#     data <- p$data %>% 
#       mutate(run=paste(category,i,gas,time_start,sep="_"))
#   } else {
#     data <- rbind(data,p$data %>% mutate(run=paste(category,i,gas,time_start,sep="_")))
#   }
#   
#   c=c+1
#   
# }
# plot_list



```