---
title: "Emissions trends and drivers: overview"
author: "William F. Lamb"
output: 
  word_document:
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../Results") })
  
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(gganimate)
library(xlsx)
library(ggplot2); theme_set(theme_bw())

source("small_figures.R")
source("decomp_figure_countries.R")
source("decomp_figure_sectors.R")
source("waterfall_plot.R")


load('../Data/edgar_data_gwp_ar6.RData')
load('../Data/gwps.RData')

# set palette
# ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2")
# ipcc_palette <- c("#737373","#737373","#66c2a5","#fc8d62","#8da0cb","#e78ac3","#a6d854");


uncertainties <- data.frame(gas=c('CO2 FFI','CO2 FOLU','CH4','N2O','Fgas','GHG'),
                            uncertainty=c(0.08,0.5,0.2,0.6,0.2,0.1))

wb <- openxlsx::createWorkbook(title = paste("ipcc_plot_data_",Sys.Date()))


```

### Figure 1: GHG emissions by gas

```{r Fig1_trend, echo=FALSE,warning=FALSE,fig.width=8,fig.height=6,fig.path="../Results/Plots/",dev=c('png','pdf')}


plot_data <- edgar_GHG_ar6 %>% 
  filter(year>1989) %>% 
  filter(year<2019) %>% 
  group_by(year) %>% 
  summarise(CO2=sum(CO2,na.rm=T)/1e9,CH4=sum(CH4,na.rm=T)/1e9,N2O=sum(N2O,na.rm=T)/1e9,Fgas=sum(Fgas,na.rm=T)/1e9)


######### load data from global carbon budget ######### 

land_data <- openxlsx::read.xlsx('../Data/Land and GCB/Global_Carbon_Budget_2019v1.0.xlsx',sheet="Global Carbon Budget",rows=19:79,cols=2:4) %>% 
  select(year=Year,CO2_landuse="land-use.change.emissions")

#### convert from C to CO2

land_data <- land_data %>% 
  mutate(CO2_landuse=CO2_landuse*(44/12))

plot_data <- left_join(plot_data,land_data,by=c("year"="year"))
plot_data<- gather(plot_data,gas,value,-year) 
plot_data <- plot_data %>% 
  mutate(gas=ifelse(gas=="CO2","CO2 FFI",gas)) %>% 
  mutate(gas=ifelse(gas=="CO2_landuse","CO2 FOLU",gas))

plot_data$gas <- as.factor(plot_data$gas)
plot_data$gas <-  factor(plot_data$gas,levels(plot_data$gas)[c(4,5,1,3,2)])

shares <- plot_data %>% 
  filter(year %in% c(1990,2000,2010,2018)) %>% 
  group_by(year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,gas) %>% 
  mutate(fractions=(value/totals)*100)

shares <- locate_shares(shares,"gas",4)

line_data <- data.frame(x=c(1990,1990,2000,2000,2010,2010,2018,2018),y=c(0,60))


p1 <- plot_data %>% 
  ggplot(.,aes(x=year,y=value,fill=gas)) +
  geom_area(colour="#737373") +
  
  geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  
  #geom_vline(xintercept=c(1990,2000,2010,2018),alpha=0.3,linetype="dashed") +
  
  #### text with the shares
  geom_text(data=shares,aes(x=year+0.75,y=location,label=paste(round(fractions,0),"%",sep="")),size=3.5,colour="#252525")+
  
  #### text with the totals
  geom_text(data=shares %>% filter(gas=="Fgas"),aes(x=year,y=62,label=paste(round(totals,0),  "Gt")),size=3.5,colour="#252525")+
  
  ylab('GHG Emissions (GtCO2eq/yr)') +
  labs(fill="Gas") +
  scale_y_continuous(breaks=c(0,10,20,30,40,50,60)) +
  scale_x_continuous(breaks=c(1990,2000,2010,2018)) +
  big_trend_theme +
  theme(legend.position="top",
        #legend.position = c(0.225,0.85),
        legend.background = element_rect(linetype = 1, size = 0.5, colour = "#525252"),
        legend.margin = margin(l=5,t=5,b=5,r=10,unit="pt"),
        legend.text = element_text(size=8),
        legend.title = element_text(size=8)) +
  guides(fill=guide_legend(nrow=1,byrow=TRUE),
         shape = guide_legend(override.aes = list(size = 0.5)),
         color = guide_legend(override.aes = list(size = 0.5)))


#########

plot_data_nogwp <- plot_data %>% 
  filter(gas!="Fgas")
  
plot_data_nogwp <- left_join(plot_data_nogwp,gwps %>% select(gas,gwp_ar5),by=c("gas"="gas"))

plot_data_nogwp <- plot_data_nogwp %>% 
  mutate(gwp_ar5=ifelse(is.na(gwp_ar5),1,gwp_ar5)) %>% 
  mutate(value=value/gwp_ar5)

p2 <- plot_data_nogwp %>%
  ggplot(.,aes(x=year,y=value,color=gas)) +
  geom_line() +
  scale_x_continuous(breaks=c(1995,2010)) +
  theme_bw() +
  ylab('Emissions \n(Gt/yr - original units)') +
  facet_wrap(.~gas,scales='free',nrow=1) +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_text(margin=margin(0,10,0,0)),
        text = element_text(size=11),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank())


##### write data

openxlsx::addWorksheet(wb,"Fig1_trend")
openxlsx::writeData(wb, sheet = "Fig1_trend", spread(plot_data,year,value), colNames = T, rowNames = F)

##### waterfalls

ar5_waterfall <- waterfall_plot(plot_data,gwps,"gwp_ar5",uncertainties,"no")
ar6_waterfall <- waterfall_plot(plot_data,gwps,"gwp_ar6",uncertainties,"no")
ar2_waterfall <- waterfall_plot(plot_data,gwps,"gwp_ar2",uncertainties,"yes")

waterfall_data <- ar5_waterfall$data %>% select(gas,value_gwp_ar5=newvalue)
waterfall_data <- left_join(waterfall_data,ar6_waterfall$data %>% select(gas,value_gwp_ar6=newvalue))
waterfall_data <- left_join(waterfall_data,ar2_waterfall$data %>% select(gas,value_gwp_ar2=newvalue))



ggarrange(ar2_waterfall$plot + xlab ("GWP100 AR2") + ylab("GHG Emissions in 2017 (GtCO2eq)") + theme(axis.title.x = element_text(),axis.title.y = element_text(angle = 90,vjust = 3)),ar5_waterfall$plot + xlab ("GWP100 AR5") + theme(axis.title.x = element_text()),ar6_waterfall$plot + xlab ("GWP100 AR6") + theme(axis.title.x = element_text()),nrow=1,ncol=3)

openxlsx::addWorksheet(wb,"Fig1_waterfall")
openxlsx::writeData(wb, sheet = "Fig1_waterfall", waterfall_data, colNames = T, rowNames = F)


##### plot

mylegend<-g_legend(p1)


plot <- ggarrange(p1 + theme(legend.position="none"),ar5_waterfall$plot,ar6_waterfall$plot,ar2_waterfall$plot,nrow=1,ncol=4,widths = c(7.75,0.75,0.75,0.75),align = "h")
plot <- ggarrange(plot,p2,nrow=2,ncol=1,heights = c(0.7,0.3),align="v",mylegend)

plot 


```

### Figure 2: Long term CO2 emissions sources and sinks


```{r Fig2_budget, echo=FALSE,warning=FALSE,fig.width=10,fig.height=6,fig.path="../Results/Plots/",dev=c('png','pdf')}

######### load the global carbon budget ######### 

gcb <- openxlsx::read.xlsx('../Data/Land and GCB/CDIAC_fossilfuel_updated_GCP2019.xlsx',sheet="CDIAC CO2",rows=3:271,cols=1:9)
names(gcb) <- c("Year","Total","Gas","Oil","Coal","Cement","Flaring","Net land-use","Total_CO2")


budget_data <- gather(gcb,key,value,-Year) %>% 
  filter(key!="Total_CO2",key!="Total") %>% 
  filter(Year>=1850) %>% 
  select(year=Year,everything())

budget_data$key <- as.factor(budget_data$key)
budget_data$key <- factor(budget_data$key,levels(budget_data$key)[c(1,2,3,4,6,5)])

shares <- budget_data %>% 
  filter(year %in% c(1850,1900,1950,2000,2018)) %>% 
  group_by(year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,key) %>% 
  mutate(fractions=(value/totals)*100)


shares <- locate_shares(shares,"key",5)


line_data <- data.frame(x=c(1850,1850,1900,1900,1950,1950,2000,2000,2018,2018),y=c(0,45))


p1 <- budget_data %>% 
  ggplot(.,aes(x=year,y=value,fill=key,color=key)) + 
  geom_area(colour="#737373") +
  
  geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  
  geom_text(data=shares,aes(x=year+3.5,y=location,label=paste(round(fractions,0),"%",sep="")),size=3.5,colour="#252525")+
  
  geom_text(data=shares %>% filter(key=="Cement"),
            aes(x=year,y=47,label=paste(round(totals,0),"Gt")),size=3.5,colour="#252525")+
  
  ylab("Carbon emissions (GtCO2/yr)") +
  big_trend_theme +
  theme(legend.position = c(0.15,0.7),
        legend.title = element_blank(),
        legend.background = element_blank())



###### budget date data

date_data <- gcb %>% 
  select(Year,value=Total_CO2) %>% 
  filter(Year>=1850) %>% 
  mutate(key=NA) %>%
  mutate(key=ifelse(Year>1850 & Year < 2010,'1850- 2009',key)) %>% 
  mutate(key=ifelse(Year>=2010,'2010- 2018',key)) %>% 
  filter(!is.na(key))

date_data <- date_data %>% 
  mutate(key=as.factor(key)) %>% 
  group_by(key) %>% 
  summarise(value=sum(value)) %>% 
  add_row(key="1.5 budget",value=420-gcb$Total_CO2[gcb$Year==2018]) %>% 
  add_row(key="2.0 budget",value=1170-gcb$Total_CO2[gcb$Year==2018])

#date_data$key <- factor(date_data$key,levels(date_data$key)[c(4,3,2,1)])


date_data$end <- cumsum(date_data$value)
date_data$end[date_data$key=="2.0 budget"] <- date_data$end[date_data$key=="2.0 budget"] - date_data$value[date_data$key=="1.5 budget"]
date_data$start <- c(0, head(date_data$end, -1))
date_data$start[date_data$key=="2.0 budget"] <- date_data$start[date_data$key=="1.5 budget"]
date_data <- cbind(date_data,id=c(1,2,3,4))

p2 <- date_data %>% 
  ggplot(.,aes(fill=key)) +
  geom_rect(aes(x=key,
    xmin = id - 0.4,
    xmax = id + 0.4,
    ymin = start,
    ymax = end),
    colour = "#737373") +
  
  geom_text(aes(x=id,y=end+150,label=paste(round(value,0)))) +
  
  ylab('Carbon emissions,\n cumulative (GtCO2)') +
  ylim(0,4000) +
  big_trend_theme +
  scale_x_discrete(labels=function(key){sub("\\s", "\n", key)}) +
  theme(legend.position= "none",
        axis.title.x = element_blank())


time_data <- data.frame(target=c("1.5oC target","2oC target"),budget=c(420,1170)) %>% 
  group_by(budget) %>% 
  mutate(current_emissions=budget/as.vector(budget_data %>% filter(year==2017) %>% summarise(total=sum(value)))[[1]]) %>% 
  mutate(current_emissions=round(current_emissions,0)+2017) %>% 
  ungroup()

time_data <- cbind(time_data,data.frame(three=c(2030,2084),seven=c(2037,NA)))
time_data <- gather(time_data,key,value,-budget,-target) %>% 
  mutate(key=as.factor(key))

time_data <- time_data %>% 
  mutate(value=value-1)


time_data$key <- factor(time_data$key,levels(time_data$key)[c(2,3,1)])


p3 <- time_data %>% 
  ggplot(.,aes(x=key,y=value,fill=target)) + 
  geom_bar(stat='identity',colour="#737373") +
  geom_text(aes(x=key,y=value+2,label=round(value-2017,0))) +
  #scale_y_continuous(limits=c(2017,2100),oob =rescale_none) +
  coord_flip(ylim = c(2017,2100)) +
  facet_grid(target~.) +
  theme_bw() +
  theme(legend.position='none',
        axis.title.y=element_blank()) +
  ylab('Year of budget exceedance') 

p4<- ggarrange(p2,p3,ncol=2,widths=c(1,2))

p <- ggarrange(p1,p4,nrow=2)
p



openxlsx::addWorksheet(wb,"Fig2_budget")
openxlsx::writeData(wb, sheet = "Fig2_budget", spread(budget_data,year,value), colNames = T, rowNames = F)


```


### Figure 5: Total GHGs, split by region

```{r Fig5_ghgs_region, echo=FALSE,warning=FALSE,fig.width=8,fig.height=12,fig.path="../Results/Plots/",dev=c('png','pdf')}

source("decomp_figure_countries.R")
#ipcc_palette <- c("#737373","#66c2a5","#fc8d62","#8da0cb","#e78ac3","#a6d854","#ffd92f");
ipcc_palette <- c("#737373","#737373","#66c2a5","#fc8d62","#8da0cb","#e78ac3","#a6d854");



plot_data <- edgar_GHG_ar6 %>% 
  filter(year>1989) %>% 
  filter(year<2019) %>% 
  group_by(year,region_ar6_5,region_ar6_5_short) %>% 
  summarise(value=sum(GHG,na.rm=TRUE)/1e9) %>% 
  ungroup()


## group aviation and shipping

plot_data <- plot_data %>% 
  mutate(region_ar6_5=ifelse(region_ar6_5=="Intl. Shipping","Intl. Shipping & Aviation",region_ar6_5)) %>%   mutate(region_ar6_5=ifelse(region_ar6_5=="Intl. Aviation","Intl. Shipping & Aviation",region_ar6_5))   

plot_data$region_ar6_5_short[plot_data$region_ar6_5_short=="SEA"] <- "AIR"

plot_data <- plot_data %>% 
  group_by(year,region_ar6_5,region_ar6_5_short) %>%
  mutate(value=sum(value)) %>% 
  unique() %>% 
  ungroup()

## Add FOLU


######### load data from global carbon budget ######### 

land_data <- openxlsx::read.xlsx('../Data/Land and GCB/Global_Carbon_Budget_2019v1.0.xlsx',sheet="Global Carbon Budget",rows=19:79,cols=2:4) %>% 
  select(year=Year,value="land-use.change.emissions")

#### convert from C to CO2

land_data <- land_data %>% 
  mutate(value=value*(44/12)) %>% 
  mutate(region_ar6_5_short="LAND") %>% 
  mutate(region_ar6_5="Land use emissions (CO2)") %>% 
  select(year,region_ar6_5,region_ar6_5_short,value)

plot_data <- rbind(plot_data,land_data) %>% 
  arrange(year)

plot_data$region_ar6_5_short <- as.factor(plot_data$region_ar6_5_short)

plot_data$region_ar6_5_short <-  factor(plot_data$region_ar6_5_short,levels(plot_data$region_ar6_5_short)[c(3,4,5,6,7,1,8)])

# plot_data$gas <- as.factor(plot_data$gas)
# plot_data$gas <-  factor(plot_data$gas,levels(plot_data$gas)[c(4,5,1,3,2)])


shares <- plot_data %>% 
  filter(year %in% c(1990,2000,2010,2018)) %>% 
  group_by(year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,region_ar6_5_short) %>% 
  mutate(fractions=(value/totals)*100)

shares <- locate_shares(shares,"region_ar6_5_short",4)

line_data <- data.frame(x=c(1990,1990,2000,2000,2010,2010,2018,2018),y=c(0,60))

p1 <- plot_data %>%
  ggplot(.,aes(x=year,y=value,fill=region_ar6_5_short)) +
  #scale_fill_manual(values=ipcc_palette) +
  #scale_color_manual(values=ipcc_palette) +
  geom_area(colour="#737373") +
  
  geom_text(data=shares,aes(x=year+0.75,y=location,label=paste(round(fractions,0),"%",sep="")),size=3.5,colour="#252525")+
  
  # geom_text(data=shares %>% filter(year==2018),aes(x=2019,y=location,label=region_ar6_5,color=region_ar6_5_short,hjust=0)) +
  
  geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  
  #### text with the totals
  geom_text(data=shares %>% filter(region_ar6_5_short=="AIR"),aes(x=year,y=62,label=paste(round(totals,0),  "Gt")),size=3.5,colour="#252525")+
  
  labs(fill="Gas") +
  scale_y_continuous(breaks=c(0,10,20,30,40,50,60)) +
  scale_x_continuous(breaks=c(1990,2000,2010,2018),limits = c(1990,2019)) +
  big_trend_theme +
  theme(legend.position="bottom",
        legend.background = element_rect(linetype = 1, size = 0.5, colour = "#525252"),
        legend.margin = margin(l=5,t=5,b=5,r=10,unit="pt"),
        legend.text = element_text(size=8),
        legend.title = element_blank()) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE),
         shape = guide_legend(override.aes = list(size = 0.5)),
         color = guide_legend(override.aes = list(size = 0.5))) +
  ylab('GHG Emissions (GtCO2eq/yr)')
  


########### side figures - per capita and per gdp ###########

load('../Data/basic.RData')
load('../Data/tsu_codes.RData')

basic <- basic %>%  
  filter(Year>=1990 & Year<2019) %>% 
  select(ISO,Year,pop_UN,gdp_ppp_WB) %>% 
  filter(ISO!="WLD")

basic <- left_join(basic,tsu_codes %>% select(ISO,region_ar6_5))

basic <- basic %>% 
  group_by(Year,region_ar6_5) %>% 
  summarise_at(vars(gdp_ppp_WB,pop_UN),sum,na.rm=T)


side_plot_data <- edgar_GHG_ar6 %>% 
  filter(year>1989) %>% 
  filter(year<2019) %>% 
  filter(region_ar6_5!="Intl. Aviation") %>% 
  filter(region_ar6_5!="Intl. Shipping") %>% 
  group_by(year,region_ar6_5,region_ar6_5_short) %>% 
  summarise_at(vars(GHG),sum,na.rm=TRUE)

side_plot_data <- left_join(side_plot_data,basic,by=c("year"="Year","region_ar6_5"="region_ar6_5"))


side_plot_data <- side_plot_data %>% 
  mutate(GHG_pc = GHG/pop_UN) %>% 
  mutate(GHG_pgdp = GHG/gdp_ppp_WB*1000) %>% 
  mutate(GHG_pgdp = ifelse(year==2018,NA,GHG_pgdp))


p2_1 <- side_plot_data %>% 
  ggplot(.,aes(x=year,y=GHG_pc,colour=region_ar6_5_short)) +
  geom_line() +
  theme_bw() +
  ylab('GHG Emissions\n(tCO2eq/cap)') +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        text = element_text(size=11),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank())

p2_2 <- side_plot_data %>% 
  ggplot(.,aes(x=year,y=GHG_pgdp,colour=region_ar6_5_short)) +
  geom_line() +
  theme_bw() +
  ylab('GHG Emissions intensity\n(gCO2eq/$)') +
  theme(legend.position = "bottom",
        axis.title.x = element_blank(),
        text = element_text(size=11),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank())

p2 <- ggarrange(p2_1,p2_2,ncol=1,nrow=2)

########### Decomposition figure ###########


load('../Data/basic.RData')
decomp <- decomp_figure_countries(1990,'GHG',edgar_GHG_ar6,basic)

mylegend<-g_legend(p1)

p3 <- ggarrange(decomp$rate_plot,decomp$abs_plot,ncol=2,nrow=1)
p4 <- ggarrange(decomp$pc_plot,decomp$pgdp_plot,ncol=2,nrow=1)


plot <- ggarrange(p1 + theme(legend.position="none"),p2,ncol=2,nrow=1,widths=c(0.65,0.35))
plot <- ggarrange(plot,p3,p4,ncol=1,nrow=3,heights=c(0.3,0.35,0.35),mylegend)
plot


##########

openxlsx::addWorksheet(wb,"Fig5_ghgs_region")
openxlsx::writeData(wb, sheet = "Fig5_ghgs_region", spread(plot_data,year,value), colNames = T, rowNames = F)
openxlsx::addWorksheet(wb,"Fig5_ghgs_countries")
openxlsx::writeData(wb, sheet = "Fig5_ghgs_countries", decomp$data, colNames = T, rowNames = F)


```

``` {r benchmark_test, echo=FALSE,warning=FALSE,fig.width=8,fig.height=4,fig.path="../Results/Plots/",dev=c('png','pdf')}

# what i already have
p <- decomp$rate_plot
p +
  geom_hline(yintercept=-2.5,color="red",linetype="dashed") +
  geom_hline(yintercept=-3,color="red",linetype="dashed") +
  geom_hline(yintercept=-7.5,color="red",linetype="dashed")


```

```{r Fig9_sectors, echo=FALSE,warning=FALSE,fig.width=8,fig.height=10,fig.path="../Results/Plots/",dev=c('png','pdf')}

load('../Data/edgar_data_gwp_ar6.RData')
source("decomp_figure_sectors.R")

plot_data <- edgar_GHG_ar6  %>% 
  filter(year>1989) %>% 
  filter(year<2019) %>% 
  group_by(year,chapter,chapter_title) %>%  
  summarise(value=sum(GHG,na.rm=TRUE)/1e9) %>% 
  ungroup()

land_data <- openxlsx::read.xlsx('../Data/Land and GCB/Global_Carbon_Budget_2019v1.0.xlsx',sheet="Global Carbon Budget",rows=19:79,cols=2:4) %>% 
  select(year=Year,value="land-use.change.emissions")

#### convert from C to CO2

land_data <- land_data %>% 
  mutate(value=value*(44/12))

land_data <- land_data %>% 
  filter(year>1989) %>% 
  filter(year<2019) %>% 
  mutate(chapter=7,chapter_title="AFOLU") %>% 
  select(year,chapter_title,chapter,value)


plot_data <- rbind(plot_data,land_data)

### merge agriculture and FOLU
plot_data <- plot_data %>% 
  group_by(year,chapter,chapter_title) %>% 
  summarise(value=sum(value)) %>% 
  ungroup()

plot_data$chapter_title <- as.factor(plot_data$chapter_title)
plot_data$chapter_title <- factor(plot_data$chapter_title,levels(plot_data$chapter_title)[c(3,1,2,5,4)])

shares <- plot_data %>% 
  filter(year %in% c(1990,2000,2010,2018)) %>% 
  group_by(year) %>% 
  mutate(totals=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,chapter) %>% 
  mutate(fractions=(value/totals)*100) %>% 
  ungroup()

shares <- locate_shares(shares,"chapter",4)

line_data <- data.frame(x=c(1990,1990,2000,2000,2010,2010,2018,2018),y=c(0,60))

p1 <- plot_data %>%
  ggplot(.,aes(x=year,y=value,fill=chapter_title)) +
  geom_area(colour="#737373") +
  
  
  geom_text(data=shares,aes(x=year+0.75,y=location,label=paste(round(fractions,0),"%",sep="")),size=3.5,colour="#252525")+
  
  geom_line(inherit.aes = FALSE,data=line_data,aes(x=x,y=y,group=x),alpha=0.3,linetype="dashed") +
  
  #### text with the totals
  geom_text(data=shares %>% filter(chapter_title=="Industry"),aes(x=year,y=62,label=paste(round(totals,0),  "Gt")),size=3.5,colour="#252525")+
  
  ylab("GHG emissions (GtCO2eq/yr)") +
  
  labs(fill="Sector") +
  scale_y_continuous(breaks=c(0,10,20,30,40,50,60)) +
  scale_x_continuous(breaks=c(1990,2000,2010,2018),limits=c(1990,2019)) +
  
  big_trend_theme +
  theme(legend.position="bottom")


######## subsectors

decomp <- decomp_figure_sectors(2010,'GHG',edgar_GHG_ar6)


  
p2 <- ggarrange(decomp$rate_plot,decomp$abs_plot,ncol=1,nrow=2)

plot <- ggarrange(p1,p2,ncol=1,nrow=2,heights=c(0.4,0.6))
plot


openxlsx::addWorksheet(wb,"Fig9_sectors")
openxlsx::writeData(wb, sheet = "Fig9_sectors", spread(plot_data,year,value), colNames = T, rowNames = F)
openxlsx::addWorksheet(wb,"Fig9_subsectors")
openxlsx::writeData(wb, sheet = "Fig9_subsectors", decomp$data, colNames = T, rowNames = F)


```

```{r benchmarking, echo=FALSE,warning=FALSE,fig.width=8,fig.height=4,fig.path="../Results/Plots/",dev=c('png','pdf')}

# import scenario data
benchmark_data_raw <- read.csv("../Data/supplemetary data/Emission reduction benchmarks.csv")

benchmark_data <- benchmark_data_raw %>% 
  rename(rate=reduction_rates_2020.2050) %>% 
  filter(rate>-25) %>% 
  #filter(is.na(rate)) %>% 
  filter(aggregated_category!="Other") %>% 
  select(aggregated_category,rate)


benchmark_data2 <- benchmark_data_raw %>% 
  rename(rate=reduction_rates_2020.2040) %>% 
  filter(rate>-25) %>% 
  #filter(is.na(rate)) %>% 
  filter(aggregated_category!="Other") %>% 
  select(aggregated_category,rate)

rates <- edgar_GHG_ar6 %>% 
  filter(region_ar6_5_short!="AIR") %>% 
  filter(region_ar6_5_short!="SEA") %>% 
  group_by(country,ISO,year,region_ar6_5,region_ar6_5_short) %>% 
  summarise(GHG=sum(GHG,na.rm = TRUE)) %>% 
  ungroup() %>% 
  rename(emissions_total=GHG)


##### 1990 - 2018 (as chapter figures)
# time_start = 1990
# 
# blarg <- rates %>% 
#   filter(year>=time_start & year<2019) %>% 
#   group_by(country,year,region_ar6_5) %>% 
#   summarise(emissions_total=sum(emissions_total,na.rm=TRUE))
# 
# blarg <- blarg %>% 
#   group_by(country,region_ar6_5) %>% 
#   summarise(rate=(last(emissions_total)/first(emissions_total))^(1/(last(year)-time_start))-1) %>% 
#   ungroup() %>% 
#   mutate(rate=rate*100) %>% 
#   mutate(aggregated_category=paste0("All countries ",time_start,"-2018")) %>% 
#   select(aggregated_category,rate)
#   
# blarg <- rbind(blarg,benchmark_data)
# 
# blarg <- blarg %>% 
#   mutate(aggregated_category = as.factor(aggregated_category))
# 
# blarg$aggregated_category <- factor(blarg$aggregated_category,levels= levels(blarg$aggregated_category)[c(2,1,3,4)])
# 
# blarg %>% 
#   ggplot(.,aes(x=aggregated_category,rate)) +
#   geom_boxplot() +
#   coord_flip() +
#   ylab("Average annual GHG emissions growth rates (%)") +
#   theme(axis.title.x = element_blank())



##### regions
time_start = 2010

blarg <- rates %>% 
  filter(ISO!="COK") %>% 
  filter(ISO!="FRO") %>% 
  filter(ISO!="GRL") %>% 
  filter(ISO!="IMN") %>% 
  filter(year>=time_start & year<2019) %>% 
  group_by(country,year,region_ar6_5) %>% 
  summarise(emissions_total=sum(emissions_total,na.rm=TRUE))

blarg <- blarg %>% 
  group_by(country,region_ar6_5) %>% 
  summarise(rate=(last(emissions_total)/first(emissions_total))^(1/(last(year)-time_start))-1) %>% 
  ungroup() %>% 
  mutate(rate=rate*100) %>% 
  mutate(aggregated_category=region_ar6_5) %>% 
  select(aggregated_category,rate) %>% 
  mutate(facet="Historical (2010-2018)")
  
#blarg <- rbind(blarg,benchmark_data %>% mutate(facet="Scenarios (2020-2050)"))
blarg <- rbind(blarg,benchmark_data2 %>% mutate(facet="Scenarios (2020-2040)"))

blarg <- blarg %>% 
  mutate(aggregated_category = as.factor(aggregated_category))

blarg$aggregated_category <- factor(blarg$aggregated_category,levels= levels(blarg$aggregated_category)[c(2,3,4,5,7,1,6,8)])

blarg %>% 
  ggplot(.,aes(x=fct_rev(aggregated_category),rate,fill=aggregated_category)) +
  geom_boxplot() +
  coord_flip() +
  facet_grid(facet~.,scales="free") +
  theme_bw() +
  ylab("Average annual GHG emissions growth rates (%)") +
  theme(axis.title.y = element_blank(),
        legend.position = "none")


```

### Figure PROPOSAL: Individual gases, split by region

```{r Figx_region_gas, echo=FALSE,warning=FALSE,fig.width=8,fig.height=6,fig.path="../Results/Plots/",dev=c('png','pdf')}


# plot_data <- edgar_GHG_ar6 %>% 
#   filter(year>1989) %>% 
#   filter(year<2019) %>% 
#   filter(region_ar6_5!="Intl. Aviation") %>% 
#   filter(region_ar6_5!="Intl. Shipping") %>% 
#   group_by(year,region_ar6_5) %>% 
#   summarise_at(vars(CO2:GHG),sum,na.rm=TRUE)
# 
# plot_data <- gather(plot_data,key,value,CO2:GHG) %>% 
#   mutate(value=value/1e9)
# 
# # plot_data %>% 
# #   ggplot(.,aes(x=year,y=value,color=key)) +
# #   geom_line(size=1) +
# #   theme_bw +
# #   ylab("GHG Emissions (Gt CO2eq)") +
# #   facet_grid(key~region_ar6_5,scales="free",labeller = label_wrap_gen(width=12)) +
# #   theme(axis.title.x = element_blank(),
# #         legend.position="none",
# #         axis.title.y = element_text(margin = margin(r = 10)))
#   
# plot_data %>% 
#   ggplot(.,aes(x=year,y=value,color=key)) +
#   geom_line(size=1) +
#   theme_bw +
#   ylab("GHG Emissions (Gt CO2eq)") +
#   facet_wrap(region_ar6_5~.,scales="free",labeller = label_wrap_gen(width=20),nrow=2) +
#   theme(axis.title.x = element_blank(),
#         legend.position = c(0.8,0.2),
#         axis.title.y = element_text(margin = margin(r = 10)))
  


```

### Figure PROPOSAL: GHGs by sector, split by region

```{r Figx_region_sector, echo=FALSE,warning=FALSE,fig.width=8,fig.height=6,fig.path="../Results/Plots/",dev=c('png','pdf')}

# 
# plot_data <- edgar_GHG_ar6 %>% 
#   filter(year>1989) %>% 
#   filter(year<2019) %>% 
#   filter(region_ar6_5!="Intl. Aviation") %>% 
#   filter(region_ar6_5!="Intl. Shipping") %>% 
#   group_by(year,region_ar6_5,chapter,chapter_title) %>% 
#   summarise_at(vars(GHG),sum,na.rm=TRUE) %>% 
#   mutate(GHG=GHG/1e9)
# 
# plot_data %>% 
#   ggplot(.,aes(x=year,y=GHG,color=chapter_title)) +
#   geom_line(size=1) +
#   theme_bw +
#   ylab("GHG Emissions (Gt CO2eq)") +
#   facet_wrap(region_ar6_5~.,scales="free",labeller = label_wrap_gen(width=20),nrow=2) +
#   theme(axis.title.x = element_blank(),
#         legend.position = c(0.8,0.3),
#         axis.title.y = element_text(margin = margin(r = 10)))
  
```

``` {r write_data,include=FALSE,echo=FALSE}

openxlsx::saveWorkbook(wb,"../Results/Data/ipcc_plot_data.xlsx",overwrite=T)


```












