---
title: "International energy and emissions inequality"
output: word_document
---

```{r setup, include=FALSE}


rm(list = ls())
library(tidyverse)
library(xlsx)

load('../Data/basic.RData')

data <- read.xlsx('../Data/confidential_yannick_oswald_data.xlsx',sheetName='data') %>% 
  select(vars=country.Code.,everything())

data <- gather(data,country,value,-vars)

data <- data %>% 
  filter(vars!="country ID") %>% 
  filter(vars!="region code") %>% 
  group_by(country) %>% 
  mutate(region=nth(value,1)) %>% 
  mutate(income_category=nth(value,2)) %>% 
  mutate(pop=nth(value,3)) %>% 
  mutate(energy_use=nth(value,4)) %>% 
  select(ISO=country,everything()) %>%
  select(-vars,-value) %>% 
  distinct()

data$ISO <- gsub(".1","",data$ISO)
data$ISO <- gsub(".2","",data$ISO)
data$ISO <- gsub(".3","",data$ISO)
data$ISO <- gsub(".4","",data$ISO)
data$ISO <- gsub(".5","",data$ISO)
data$ISO <- gsub("USA.","USA",data$ISO)
data$income_category <- gsub(" ","",data$income_category)

#data <- data %>% 
 # filter(!income_category %in% c("Q1","Q2","Q3","Q4","Q5"))

data$income_category <- as.factor(data$income_category)
data$energy_use <- as.numeric(data$energy_use)

data <- left_join(data,basic %>% filter(Year==2015) %>% select(ISO,Country,RCP5),by=c("ISO"="ISO"))

### change country names
data$Country <- gsub("'","",data$Country)
data$Country <- gsub('Lao Peoples Democratic Republic','Laos',data$Country)
data$Country <- gsub('United Republic of Tanzania','Tanzania',data$Country)
levels(data$Country) <- c(levels(data$Country),'Bolivia')
data$Country[data$ISO=="BOL"] <- 'Bolivia'

### change a few regions



```




```{r energy_inequality,echo=FALSE,warning=FALSE,fig.width=8,fig.height=12,fig.path="../Results/Plots/",dev=c('png','pdf')}

data %>% 
  ggplot(.,aes(x=reorder(Country, desc(Country)),y=energy_use,color=income_category)) +
  geom_point(size=2.5) +
  coord_flip() +
  ylim(0,300) +
  theme_bw() +
  facet_grid(RCP5~.,space = 'free',scales = 'free') +
  ylab("Energy use (GJ/cap)") +
  theme(
    axis.title.y = element_blank(),
    legend.position = 'bottom'
  )


```


```{r clustering,echo=FALSE,warning=FALSE,fig.width=8,fig.height=12,fig.path="../Results/Plots/",dev=c('png','pdf')}

z <- data %>% 
  filter(income_category=="lowest"|income_category =="high"|income_category=="Q1"|income_category=="Q4") %>% 
  select(-pop) %>% 
  ungroup()

z$income_category[z$income_category=="Q1"] <- "lowest"
z$income_category[z$income_category=="Q4"] <- "high"

z$energy_use[z$ISO=="ARM"] <- NA

z <- spread(z,income_category,energy_use) %>% 
  select(ISO,Country,high,lowest) %>% 
  na.omit


blarg <- kmeans(z %>% select(-ISO,-Country),5)
cluster <- blarg$cluster
z <- cbind(z,cluster)

new_data <- left_join(data,z %>% select(ISO,cluster),by=c("ISO"="ISO"))

new_data %>% 
  ggplot(.,aes(x=reorder(Country, desc(Country)),y=energy_use,color=income_category)) +
  geom_point(size=2.5) +
  coord_flip() +
  ylim(0,500) +
  theme_bw() +
  facet_grid(cluster~.,space = 'free',scales = 'free') +
  ylab("Energy use (GJ/cap)") +
  theme(
    axis.title.y = element_blank(),
    legend.position = 'bottom'
  )

```

```{r income_ranking,echo=FALSE,warning=FALSE,fig.width=8,fig.height=12,fig.path="../Results/Plots/",dev=c('png','pdf')}

load('../Data/basic.RData')

## bring in more regional codes
codes <- read.xlsx('C:/Users/lamw/Documents/SpiderOak Hive/Work/Code/R/.Place names and codes/output/ISOcodes.xlsx',sheetName = 'ISO_master')

basic <- left_join(basic,codes %>% select(Code,WB.income),by=c("ISO"="Code")) %>%
  select(Country,ISO,Year,UN6,RCP5,IAM10,WB.income,pop_UN,everything())

basic$WB.income <- factor(basic$WB.income,levels(basic$WB.income)[c(1,4,3,2)])

# any other adjustments here
basic$UN6 <- gsub("LATIN AMERICA AND THE CARIBBEAN","LATIN AMERICA",basic$UN6)

basic <- basic %>%
  mutate(gdp_ppp_pc = gdp_ppp_WB/pop_UN) %>% 
  filter(Year==2016) %>% 
  select(ISO,gdp_ppp_pc)

basic$WB_category  <- cut(basic$gdp_ppp_pc,breaks = c(1700,4300,8600,15000,29000,150000),dig.lab=10,include.lowest=TRUE)



data <- left_join(data,basic,by=c("ISO"="ISO"))


data %>% 
  filter(!is.na(WB_category)) %>% 
  ggplot(.,aes(x=reorder(Country, desc(gdp_ppp_pc)),y=energy_use,color=income_category)) +
  geom_point(size=2.5) +
  coord_flip() +
  ylim(0,500) +
  theme_bw() +
  facet_grid(WB_category~.,space = 'free',scales = 'free') +
  ylab("Energy use (GJ/cap)") +
  theme(
    axis.title.y = element_blank(),
    legend.position = 'bottom'
  )



```