---
title: "indirect emissions"
author: "William F. Lamb"
date: "19 10 2020"
output: word_document
---

```{r setup, include=FALSE}

rm(list = ls())
library(tidyverse)
library(openxlsx)


```

```{r load_iea}

######### read IEA data and clean empty country rows

iea <- read.csv(file="../Data/IEA/2020 update/iea_scope2.csv",sep = ";")
names <- c("country","flow","var",1990:2018)
names(iea) <- names
iea <- iea %>% 
  filter(country!="COUNTRY") %>% 
  filter(row_number()!=19553:19656)

######### tidy up variables, convert to long format, change units to Gt CO2

iea <- gather(iea,year,value,`1990`:`2018`)
iea <- iea %>% 
  mutate(value=ifelse(grepl("x",value),NA,value)) %>% 
  mutate(value=as.numeric(value)) %>% 
  mutate(var=as.character(var)) %>% 
  mutate(year=as.numeric(year))

iea <- iea %>% 
  mutate(var=ifelse(grepl("Emissions by sector",var),"CO2",var)) %>% 
  mutate(var=ifelse(grepl("Emissions with electricity and heat",var),"CO2_plus_elec_heat",var)) %>% 
  filter(var=="CO2" | var=="CO2_plus_elec_heat") %>% 
  mutate(value=value*1000) %>%
  mutate(value=value/1e9)

######### save world totals for ELECHEAT sector

world_totals <- iea %>% 
  filter(country=="World") %>% 
  filter(flow=="ELECHEAT") %>% 
  filter(var=="CO2") %>% 
  select(year,world_elec_heat=value)



```
```{r allocate_ononspec, echo=FALSE}

iea <- spread(iea,var,value)
iea <- iea %>% 
  mutate(indirect_CO2 = CO2_plus_elec_heat-CO2)

# set industry and transport totals to NA
iea <- iea %>% 
  mutate(indirect_CO2=ifelse(flow=="TOTIND",NA,indirect_CO2)) %>% 
  mutate(indirect_CO2=ifelse(flow=="TOTTRANS",NA,indirect_CO2))


blarg <- iea %>% 
  filter(country=="World") %>% 
  filter(year==2018)


###### allocate ONONSPEC indirect CO2

# get the residential, commercial, agriculture/forestry and fishing CO2 for each country and year ("other_sector_CO2")

other_sectors <- iea %>%
  filter(flow %in% c("RESIDENT","COMMPUB","AGRICULT","FISHING")) %>% 
  group_by(country,year) %>% 
  summarise(other_sector_CO2=sum(CO2,na.rm=TRUE))

# get ONONSPEC indirect CO2 for each country and year

ononspec <- iea %>% 
  filter(flow=="ONONSPEC") %>% 
  group_by(country,year) %>% 
  summarise(ononspec = indirect_CO2)

# join to data

iea <- left_join(iea,other_sectors,by = c("country", "year")) 
iea <- left_join(iea,ononspec,by = c("country", "year")) 

# for residential, commercial, agriculture/forestry and fishing, calculate their fractions of CO2 relative to the total for all 4

iea <- iea %>% 
  mutate(fraction=ifelse(flow=="RESIDENT",CO2/other_sector_CO2,NA)) %>% 
  mutate(fraction=ifelse(flow=="COMMPUB",CO2/other_sector_CO2,fraction)) %>% 
  mutate(fraction=ifelse(flow=="AGRICULT",CO2/other_sector_CO2,fraction)) %>% 
  mutate(fraction=ifelse(flow=="FISHING",CO2/other_sector_CO2,fraction))

# multiply this fraction by the unallocated ONONSPEC indirect CO2

iea <- iea %>% 
  mutate(reallocated_ononspec=ifelse(flow=="RESIDENT",fraction*ononspec,NA)) %>% 
  mutate(reallocated_ononspec=ifelse(flow=="COMMPUB",fraction*ononspec,reallocated_ononspec)) %>% 
  mutate(reallocated_ononspec=ifelse(flow=="AGRICULT",fraction*ononspec,reallocated_ononspec)) %>% 
  mutate(reallocated_ononspec=ifelse(flow=="FISHING",fraction*ononspec,reallocated_ononspec))

# add the reallocated ONONSPEC indirect CO2 emissions to totals for each of the 4 sectors
# set ONONSPEC sector to 0

iea <- iea %>% 
  mutate(indirect_CO2=ifelse(!is.na(reallocated_ononspec),indirect_CO2+reallocated_ononspec,indirect_CO2)) %>% 
  mutate(indirect_CO2=ifelse(flow=="ONONSPEC",NA,indirect_CO2))

# remove vars
iea <- iea %>% 
  select(country:indirect_CO2)


# check sums - sum of indirect CO2 should equal world elecheat with a small difference from TRNONSPE

totals <- iea %>% 
  filter(country=="World") %>% 
  filter(year==2018)

```

```{r match_EDGAR, echo=FALSE}

######### match IEA sectors to (EDGAR) IPCC 2006 codes

matching <- openxlsx::read.xlsx("../Data/Codes and classifications/iea_ipcc_sector_classification.xlsx",sheet = "sectors")
matching <- matching %>% 
  select(CODE,LEVEL,ipcc.code,sector_chapter,chapter_title,description)
iea <- left_join(iea,matching %>% select(CODE,LEVEL,ipcc.code),by=c("flow"="CODE"))

######### use IPCC 2006 codes to merge IEA with AR6 sectors and subsectors

load("../Data/ipcc_sectors.RData")
iea <- left_join(iea,ipcc_sectors %>% select(-IPCC.2006),by=c("ipcc.code"="code"))


######### allocate OTHEN to "Other incl. Indirect N2O"

iea <- iea %>% 
  mutate(IPCC_AR6_chapter=ifelse(flow=="OTHEN",6,IPCC_AR6_chapter)) %>% 
  mutate(IPCC_AR6_chapter_title=ifelse(flow=="OTHEN","Energy systems",IPCC_AR6_chapter_title)) %>% 
  mutate(subsector=ifelse(flow=="OTHEN",6.6,subsector)) %>% 
  mutate(subsector_title=ifelse(flow=="OTHEN","Other incl. Indirect N2O",subsector_title))


########### trim down to sectors that we match in EDGAR (ONONSPEC and OTHEN are removed)
iea <- iea %>% 
  filter(!is.na(IPCC_AR6_chapter))

totals <- iea %>% 
  filter(country=="World") %>% 
  filter(year==2018) %>% 
  group_by(IPCC_AR6_chapter_title) %>% 
  summarise(indirect_CO2=sum(indirect_CO2))

```

```{r propagate_EDGAR_elecheat, echo=FALSE}

# calculate fraction of world elecheat for each country and sector

iea <- left_join(iea,world_totals,by="year")
iea <- iea %>% 
  mutate(indirect_fraction = indirect_CO2/world_elec_heat) %>% 
  mutate(indirect_fraction = ifelse(indirect_CO2==0,NA,indirect_fraction))

######### join EDGAR world ELECHEAT

load("../Data/edgar_data_gwp_ar6.RData")
edgar_world_elec_heat <- edgar_GHG_ar6 %>% 
  filter(year>1989) %>% 
  filter(chapter==6) %>% 
  group_by(year,chapter,sector_code,description,subsector,subsector_title) %>% 
  summarise(CO2=sum(CO2,na.rm=TRUE)/1e9) %>% 
  ungroup()

edgar_world_elec_heat <- edgar_world_elec_heat %>% 
  filter(grepl("1A1a",sector_code)) %>% 
  group_by(year) %>% 
  summarise(edgar_world_elec_heat=sum(CO2,na.rm=TRUE))


iea <- left_join(iea,edgar_world_elec_heat %>% select(year,edgar_world_elec_heat),
                         by="year")

# propagate adjusted indirect CO2
iea <- iea %>% 
  mutate(adjusted_indirect_CO2=edgar_world_elec_heat*indirect_fraction) %>% 
  filter(!is.na(adjusted_indirect_CO2))



totals <- iea %>% 
  filter(country=="World") %>% 
  filter(year==2018) %>% 
  group_by(IPCC_AR6_chapter_title) %>% 
  summarise(adjusted_indirect_CO2=sum(adjusted_indirect_CO2))

``` 


```{r match_countries_regions, echo=FALSE}

# tidy up dataframe

iea <- iea %>% 
  select(country,year,iea_code=flow,chapter=IPCC_AR6_chapter,
         chapter_title=IPCC_AR6_chapter_title,sector_code=ipcc.code,description,
         subsector,subsector_title,CO2_indirect=adjusted_indirect_CO2)


######### take the IPCC regions straight from IEA dataset

load("../Data/tsu_codes.RData")
regions_10 <- tsu_codes %>%
  select(region_ar6_10,region_ar6_5) %>%
  distinct() %>%
  mutate(include=1)

indirect_CO2_regions <- left_join(iea,regions_10,by=c("country"="region_ar6_10"))
indirect_CO2_regions <- indirect_CO2_regions %>%
  filter(include==1) %>% 
  select(-include) %>% 
  select(region_ar6_10=country,region_ar6_5,everything())


######### world

indirect_CO2_world <- iea %>% 
  filter(country=="World") %>%
  filter(year==2018)

######### match up individual countries

codes <- openxlsx::read.xlsx('C:/Users/lamw/Documents/SpiderOak Hive/Work/Code/R/.Place names and codes/output/ISOcodes.xlsx',sheet = 'alternative_names')

indirect_CO2_countries <- left_join(iea %>% mutate(country=tolower(country)),codes,by=c("country"="alternative.name"))

notjoined <- anti_join(iea %>% mutate(country=tolower(country)),codes,by=c("country"="alternative.name")) %>% 
  select(country) %>% 
  distinct()

indirect_CO2_countries <- indirect_CO2_countries %>% 
  filter(!is.na(alpha.3)) %>% 
  filter(alpha.3!="ZZZZ")

edgar_countries <- edgar_GHG_ar6 %>% 
  select(country,ISO) %>% 
  distinct()

indirect_CO2_countries <- left_join(indirect_CO2_countries %>% select(name=country,everything()),edgar_countries,by=c("alpha.3"="ISO"))

indirect_CO2_countries <- indirect_CO2_countries %>% 
  filter(!is.na(country))

removed <- indirect_CO2_countries %>% 
  filter(is.na(country)) %>% 
  select(name,country,alpha.3) %>% 
  distinct()

indirect_CO2_countries <- indirect_CO2_countries %>% 
  select(country,ISO=alpha.3,year,everything()) %>% 
  select(-name)


yy <- indirect_CO2_regions %>% 
  filter(year==2018)


```

```{r save_data, echo=FALSE}

wb <- openxlsx::createWorkbook(title = paste("ipcc_indirect_emissions_",Sys.Date()))

openxlsx::addWorksheet(wb,"10 Regions")
openxlsx::writeData(wb, sheet = "10 Regions",indirect_CO2_regions , colNames = T, rowNames = F)

openxlsx::addWorksheet(wb,"World 2018")
openxlsx::writeData(wb, sheet = "World 2018",indirect_CO2_world , colNames = T, rowNames = F)

openxlsx::addWorksheet(wb,"Countries")
openxlsx::writeData(wb, sheet = "Countries",indirect_CO2_countries , colNames = T, rowNames = F)

openxlsx::saveWorkbook(wb,paste0("../Results/Data/ipcc_indirect_emissions_",Sys.Date(),".xlsx"),overwrite=T)


``` 

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
