---
title: "Countries with declining emissions"
author: "William F. Lamb"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  word_document:
    toc: yes
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../Results") })
  
---

```{r setup,include=FALSE}

rm(list = ls())
library(tidyverse)
library(ggpubr)
library(xlsx)
library(ggplot2); theme_set(theme_bw())

load('../Data/edgar_data_gwp_ar6.RData')
load('../Data/gwps.RData')
load('../Data/basic.RData')

source("small_figures.R")

colours_sectors <- c(`AFOLU` = "#66c2a5",
                       `Buildings` = "#fc8d62",
                       `Energy systems` = "#8da0cb",
                       `Industry` = "#e78ac3",
                       `Transport` = "#a6d854")

```

### Overview


```{r decline,echo=FALSE,warning=FALSE,fig.width=8,fig.height=7,fig.path="../Results/Plots/Peak/",dev=c('png','pdf')}

data <- edgar_GHG_ar6 %>% 
  group_by(ISO,country,year,region_ar6_10) %>% 
  summarise_at(vars(CO2,CH4,N2O,Fgas,GHG),sum,na.rm=TRUE)

## filter to countries above 1m population

data <- left_join(data,basic %>% select(ISO,Year,pop_UN,gdp_ppp_WB),by=c("ISO"="ISO","year"="Year"))
data <- data %>% 
  #filter(region_ar6_10=="Europe" | region_ar6_10=="Asia-Pacific Developed" | region_ar6_10=="North America") %>% 
  group_by(country) %>% 
  mutate(include=ifelse(max(pop_UN)>1e6,1,0)) %>% 
  ungroup() %>% 
  filter(include==1) %>% 
  select(-include)

## calculate growth rates - simple time 1:time 2 method

time_start=2005

rates <- data %>% 
  filter(year>=time_start & year<2019) %>% 
  group_by(country) %>% 
  summarise(rate_CO2=(last(CO2)/first(CO2))^(1/(last(year)-time_start))-1,
            rate_GHG=(last(GHG)/first(GHG))^(1/(last(year)-time_start))-1) %>% 
  ungroup()

rates <- rates %>% 
  group_by(country) %>% 
  mutate(decline=ifelse(rate_GHG<0,1,0))

data <- left_join(data,rates,by=c("country"="country")) %>% 
  filter(decline==1)

data %>% 
  filter(year>1989) %>% 
  ggplot(.,aes(x=year,y=GHG)) +
  geom_path() +
  geom_line(data=data %>% filter(year %in% c(time_start,2018)), aes(x=year,y=GHG,colour="blue")) +
  scale_x_continuous(breaks=c(1990,2000,2010)) +
  scale_y_continuous(expand = expand_scale(mult = c(0.2, .2))) +
  facet_wrap(.~country,scales="free") +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        axis.title = element_blank()) +
  ggtitle("Countries with declining emissions 2005-2018")

```

```{r countries,echo=FALSE,warning=FALSE,fig.width=8,fig.height=6,fig.path="../Results/Plots/Peak/",dev=c('png','pdf'),results="asis"}

country_handle="United States"
time_start = 2005

country_plot <- function(country_handle,edgar_GHG_ar6,rate) {
  
  data <- edgar_GHG_ar6 %>%
    filter(year>1989) %>% 
    filter(country==country_handle) %>% 
    group_by(country,year,chapter,chapter_title) %>% 
    summarise_at(vars(GHG),sum,na.rm=TRUE) %>% 
    mutate(GHG=GHG/1e7) %>% 
    ungroup() %>% 
    mutate(chapter_title=as.factor(chapter_title))
  
  sector_rates <- data %>% 
    filter(year %in% c(time_start,2018)) %>% 
    group_by(country,chapter,chapter_title) %>% 
    mutate(rate=((last(GHG)/first(GHG))^(1/(last(year)-first(year)))-1)*100) %>% 
    filter(year==2018) 
  
  sector_rates <- sector_rates %>% 
    arrange(desc(chapter_title)) %>% 
    mutate(location=GHG/2) %>% 
    group_by(country) %>% 
    mutate(GHG=cumsum(GHG))
  
  z = 5
  for (i in 2:z) {
    sector_rates$location[i] = sector_rates$location[i] + sector_rates$GHG[i-1]
  }
    
  sector_rates <- sector_rates %>%  
    select(-year,-GHG)
  
  data <- left_join(data,sector_rates, by = c("country", "chapter", "chapter_title"))
  
  p1 <- data %>%
    filter(year>1989) %>% 
    ggplot(.,aes(x=year,y=GHG,fill=chapter_title)) +
    geom_area(colour="#737373") +
    geom_text(data = data %>% filter(year==2018),
              aes(x=year+1,y=location,colour=chapter_title,label=paste0(chapter_title," [",ifelse(rate>0,"+",""),round(rate,1),"%]")),hjust=0,) +
    geom_vline(xintercept=c(time_start,2018),alpha=0.3,linetype="dashed") +
    scale_fill_brewer(palette = "Set2") +
    scale_colour_brewer(palette = "Set2") +
    scale_x_continuous(limits = c(1990,2026)) +
    ylab("GHG Emissions (MtCO2eq)") + 
    theme(axis.title.x = element_blank(),
          legend.position = "none") +
    ggtitle(paste0(country_handle," - ",rate,"% decline since ",time_start))
  
  data <- edgar_GHG_ar6 %>% 
    filter(country==country_handle) %>% 
    group_by(country,year,chapter_title,subsector,subsector_title) %>% 
    summarise_at(vars(GHG),sum,na.rm=TRUE) %>% 
    mutate(GHG=GHG/1e7)
  
  subsector_rates <- data %>% 
    filter(year %in% c(2000,2018)) %>% 
    group_by(country,subsector,subsector_title) %>% 
    mutate(rate=((last(GHG)/first(GHG))^(1/(last(year)-first(year)))-1)*100) %>% 
    filter(year==2018)
  
  data <- data %>% 
    filter(year %in% c(2000,2018)) %>% 
    group_by(country,subsector_title) %>% 
    mutate(difference=last(GHG)-first(GHG)) %>% 
    mutate(rate_sector=((last(GHG)/first(GHG))^(1/(last(year)-first(year)))-1)*100)
  
  total_GHG <- data %>% filter(year==2018) %>% group_by(country) %>% summarise(GHG=sum(GHG))
  
  data <- data %>% 
    filter(year==2018) %>% 
    mutate(filter=(abs(difference)/total_GHG$GHG)*100)
  
  p2 <- data %>% 
    filter(filter>=0.25) %>% 
    ggplot(.,aes(x=reorder(subsector_title,desc(difference)),y=difference,fill=chapter_title)) +
    geom_text(aes(x=reorder(subsector_title,desc(difference)),y=difference,label=paste0(ifelse(rate_sector>0,"+",""),round(rate_sector,1),"%"),hjust = ifelse(difference >= 0, -0.1, 1.1)),size=3,colour="#737373") +
    geom_bar(stat='identity',colour="#737373") +
    scale_y_continuous(expand = expand_scale(mult = c(0.15, .15))) +
    scale_fill_manual(values= colours_sectors) +
    ylab(paste0("GHG Emissions change in major sectors, ",time_start,"-2018 (MtCO2eq)")) +
    xlab('') +
    coord_flip() +
    theme(legend.position="none")
  
  p <- ggarrange(p1,p2,nrow=2)
  
  return(list("plot"=p,"data"=data))
}


for (i in 1:length(rates$country[rates$decline==1])) {
#for (i in 1:2) {
 
  country_handle = rates$country[rates$decline==1][i]
  rate = round(abs(rates$rate_GHG[rates$decline==1][i]*100),1)
  
  p <- country_plot(country_handle,edgar_GHG_ar6,rate)
  cat("  \n### ",country_handle,"  \n")
  print(p$plot)
  cat("  \n")
  
}




```
```{r save_data,echo=FALSE,warning=FALSE}

output <- data %>% 
  filter(year %in% c(time_start,2017)) %>% 
  group_by(country) %>% 
  summarise(rate_POP=(last(pop_UN)/first(pop_UN))^(1/(last(year)-time_start))-1,
    rate_GDP=(last(gdp_ppp_WB)/first(gdp_ppp_WB))^(1/(last(year)-time_start))-1) %>% 
  ungroup()

output <- left_join(data,output,by = "country")
output <- output %>% 
  group_by(country) %>% 
  fill(gdp_ppp_WB)

output <- output %>% 
  filter(year==2018) %>% 
  select(-year,-decline)



wb <- openxlsx::createWorkbook(title = paste("decarbonising_countries",Sys.Date()))
openxlsx::addWorksheet(wb,"data")
openxlsx::writeData(wb, sheet = "data", output, colNames = T, rowNames = F)
openxlsx::saveWorkbook(wb,paste0("../Results/Data/decarbonising_countries_",Sys.Date(),".xlsx"),overwrite=T)

```



```{r decline_zero,include=FALSE,warning=FALSE,fig.width=8,fig.height=7,fig.path="../Results/Plots/Peak/",dev=c('png','pdf')}

# data %>% ggplot(.,aes(x=year,y=GHG)) +
#   geom_rect(data = data %>% filter(year==2018),aes(fill = rate_GHG),xmin = -Inf,xmax = Inf,
#             ymin = -Inf,ymax = Inf,alpha = 0.3) +
#   geom_path() +
#   scale_x_continuous(breaks=c(1970,1990,2010)) +
#   scale_y_continuous(limits = c(0,NA)) +
#   facet_wrap(.~country,scales="free") +
#   theme(axis.text.y = element_blank(),
#         axis.ticks.y = element_blank(),
#         legend.position = c(0.4,0.05),
#         legend.title = element_blank(),
#         axis.title = element_blank()) +
#   ggtitle("GHG emissions trends in developed countries, scales starting at zero")

```


```{r sectors,include=FALSE,warning=FALSE,fig.width=8,fig.height=7,fig.path="../Results/Plots/Peak/",dev=c('png','pdf')}

# sectors <- right_join(edgar_GHG_ar6,rates,by=c("country"="country"))
# 
# sectors <- sectors %>% 
#   filter(rate_CO2=="decline") %>% 
#   filter(year %in% c(1970,1975,1980,1985,1990,1995,2000,2005,2010,2015,2018)) %>% 
#   group_by(country,year,chapter_title) %>% 
#   summarise_at(vars(CO2),sum,na.rm=TRUE) %>% 
#   ungroup() %>% 
#   mutate(year=as.factor(year))
# 
# sectors %>% ggplot(.,aes(x=year,y=CO2,fill=chapter_title)) +
#   geom_bar(stat='identity') +
#   facet_grid(country~chapter_title,scales="free") +
#   theme(legend.position="none",
#         axis.title.x = element_blank(),
#         axis.text.y = element_blank()) +
#   ylab("GHG emissions tCO2eq/year") +
#   ggtitle("GHG emissions in developed countries by sector")

```


